### DISCUSSION TITLE
How to get a create an environment that doesn't install with the default environment?

### DISCUSSION THREAD

**Discussion by matthewfeickert** [prefix-dev/pixi#1149] [Q&A] [answered]
While Issue https://github.com/prefix-dev/pixi/issues/1067 and PR https://github.com/prefix-dev/pixi/pull/1092 are addressing this with the addition of `no-default-feature`, currently, with `pixi` `0.18.0`, how would you install an environment where there is a directly conflicting dependency with the `default` environment?

```
$ pixi --version
pixi 0.18.0
```

with `pixi.toml` of

```toml
[project]
name = "columnar-analysis-benchmarks"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
coffea = "==2024.4.0"

[feature.ab-stable.dependencies]
python = "3.11.*"
coffea = "==2023.12.0"

[environments]
ab-stable = {features = ["ab-stable"], solve-group = "ab-stable"}
```

as this fails on `pixi install` and `pixi install --environment ab-stable` with

```
  × failed to solve the conda requirements of 'ab-stable' 'linux-64'
  ╰─▶ Cannot solve the request because of: The following packages are incompatible
      ├─ coffea ==2024.4.0 can be installed with any of the following options:
      │  └─ coffea 2024.4.0
      └─ coffea ==2023.12.0 cannot be installed because there are no viable options:
         └─ coffea 2023.12.0, which conflicts with the versions reported above.`
```

I want to have multiple environments with different versions to be able to debug a script across multiple environments with different installed versions, e.g.:

```
$ pixi run --environment ab-stable python failing_example.py
```

**Comment by matthewfeickert** [comment, marked as answer]
I think the answer as of `pixi` `v0.18.0` is "you don't" and you instead construct multiple environments that work with a very minimal "default" environment like the following:

```toml
[project]
name = "columnar-analysis-benchmarks"
version = "0.1.0"
description = "Add a short description here"
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"

[feature.ab-stable.dependencies]
coffea = "==2023.12.0"

[feature.ab-dev.dependencies]
coffea = "==2024.4.0"

[environments]
ab-stable = ["ab-stable"]
ab-dev = ["ab-dev"]
```

**Reply by ruben-arts** [reply]
Correct. We actually didn't have an example of this case yet. But the logic dictates the behavior like this. I could think of a situation where you would like to make it "overwrite" the dependencies based on definitions. This  however requires the developer to know to overwrite behavior. So not sure if it is worth it to replace this behavior. 

One tip:
You can redifine the `default` environments.
```toml
[environments]
default = ["ab-stable"]
ab-dev = ["ab-dev"]
```
This would create the same ux as your initial example

**Reply by matthewfeickert** [reply]
I'm not sure off the top of my head when this was added, but in `pixi` `v0.41.4` there is now the concept of [non default environments](https://pixi.sh/v0.41.4/tutorials/multi_environment/#non-default-environments) where you explicitly indicate that 

> the environment not [have] the default feature, and only the features you specify.

In the [`[environments]` table](https://pixi.sh/v0.41.4/reference/pixi_manifest/#the-environments-table) you can indicate this with setting the `no-default-feature` field to `true`

```toml
[environments]
example = {features = ["example"], no-default-feature = true}
```
