### DISCUSSION TITLE
Feature/optional dependencies should be pinned in `pixi.toml`

### DISCUSSION THREAD

**Discussion by redeboer** [prefix-dev/pixi#1223] [Ideas]
Imagine the following setup:

```shell
pixi init
pixi add 'python==3.11.*'
pixi add mypy --feature dev
```

```toml
[project]
name = "pixi-test"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"

[feature.dev.dependencies]
mypy = ">=0.812,<1.10"
```

Similar to `Cargo.lock`, I expect the exact `mypy` version to be listed in `pixi.toml` as well, but it isn't:
```shell
grep mypy pixi.lock
```

Is this a design choice? For instance, (in PyPI lingo) is `pixi.lock` considered to be a list of [requirements](https://pip.pypa.io/en/stable/user_guide/#requirements-files) or a list of [constraints](https://pip.pypa.io/en/stable/user_guide/#constraints-files)?

**Comment by bollwyvl** [comment]
In my understanding, a feature won't impact the lockfile until it is explicitly composed into an environment:

```toml
[environments]
dev = {features = ["dev"]}
```
