### DISCUSSION TITLE
How to use [activation] with [tasks]?

### DISCUSSION THREAD

**Discussion by matthewfeickert** [prefix-dev/pixi#1323] [Q&A] [answered]
A colleague of mine has a (org internal repo, sorry) `pixi.toml` of the following

```toml
[project]
name = "Run3ModelGen"
version = "0.1.1"
description = "Add a short description here"
authors = ["My colleague <their email>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]

build = """
cmake -S source -B build && \
cmake \
    --build build \
    --clean-first \
    --parallel 4
"""

genModels = """
. build/setup.sh && \
mkdir run && \
cd run && \
genModels.py
"""

[target.linux-64.tasks]
# Use nproc as available
build = """
cmake -S source -B build && \
cmake \
    --build build \
    --clean-first \
    --parallel "$(nproc --ignore=1)"
"""

[dependencies]
python = "3.11.*"
gfortran = ">=13.2.0,<13.3"
cmake = ">=3.29.2,<3.30"
numpy = ">=1.26.4,<1.27"
pyyaml = ">=6.0.1,<6.1"
make = ">=4.3,<5"
which = ">=2.21,<3"

[target.linux-64.dependencies]
gcc = ">=13.2.0,<13.3"
cxx-compiler = ">=1.0.0,<1.1"

[pypi-dependencies]
pyslha = ">=3.2.6"
uproot = ">=5.3.3"
```

However, after running

```console
$ pixi run build
```

to build the unpackaged C++ dependencies acquired via Git, `pixi run genModels` fails with:

```
$ pixi run genModels 
✨ Pixi task (genModels in default): . build/setup.sh && mkdir run && cd run && genModels.py

.: command not found

Available tasks:
	build
	genModels
```

as the shell that `pixi run` uses isn't one that understands `.` as a source command(?).

`pixi` [does support activation scripts](https://pixi.sh/latest/features/multi_platform_configuration/#activation) with `[activation]`, but how would one write the TOML to specify an activation script for a specific task in an environment?

**Comment by ruben-arts** [comment, marked as answer]
Currently this is not possible. The latest release does support setting environment variables per task:
```toml
[tasks]
run = { cmd="python run.py $ARGUMENT", env={ ARGUMENT="value" }}
```
But that might only marginally help. 

The other solution would be to run a shell in the `pixi task` e.g.:
```toml
[tasks]
hello = "bash -c 'source env.sh && echo $HELLO'"
```
```sh
# env.sh file
export HELLO="Hello, World!"
```
This can obviously go wrong, but you could make these tasks per target to make them a little more safe.

**Reply by matthewfeickert** [reply]
Thanks @ruben-arts.

> The other solution would be to run a shell in the `pixi task`

I think this is probably the best way forward for the time being (in `pixi` `v0.21.0`).

> Currently this is not possible

Are there any plans to implement something like this in the future? Or is this not a goal for the `pixi task` runners in general?

**Reply by ruben-arts** [reply]
I could see support for that coming to the tasks yes, and it shouldn't be to hard as we already do the activation anyway.

**Reply by tacaswell** [reply]
I have a very similar problem, but I need to pass different env depending on the platform (in my case setting different `CC` and `CXX` on windows) so hard coding the env is not enough.

**Reply by matthewfeickert** [reply]
@ruben-arts is this in any way connected to the limitations of the [`deno` shell](https://pixi.sh/v0.39.5/features/advanced_tasks/#our-task-runner-deno_task_shell) currently used, and might be affected by https://github.com/prefix-dev/shell in the future? Or is this unrelated and would required additional new features in `pixi`?

**Reply by ruben-arts** [reply]
This is on pixi's side, this constantly gets rained down by other features. Would definitely be open for a design discussion and get the feature contributed by the community to get this in sooner!

**Reply by lucascolley** [reply]
@matthewfeickert would you mind opening an issue for this if it is still of interest? Besides that, I think we can close this discussion.

**Reply by tacaswell** [reply]
I created the issue.

**Reply by kratsg** [reply]
@tacaswell can you link the issue? I ran into a similar problem where if one wants to use `pydot` and `graphviz` -- one needs to run `dot -c` to set up the environment first.

EDIT: it seems

```toml
[feature.dev.activation]
scripts = ["setup.sh"]
```

works as presumed :)

**Reply by matthewfeickert** [reply]
Use of the `activation` table with `scripts` is how I recommend that Pixi projects with environmental secrets (e.g. API keys) use them. You can create a `.env` file that contains the secret

```bash
# .env
export SECRET="your-key-here"
```

and then have your `setup.sh` file contain

```bash
#!/usr/bin/env bash

. .env
```

and then define their use in the Pixi manifest

```toml
[activation]
# Load secrets into shell environment
scripts = ["setup.sh"]
```
