### DISCUSSION TITLE
How to set different dependencies based on os version?

### DISCUSSION THREAD

**Discussion by gzm55** [prefix-dev/pixi#1349] [Q&A]
Like `[target.linux-64.dependencies]` table, can we set different  dependencies based on the detected virtual package versions? for example set special version for `linux = "2.6.32"`

**Comment by ruben-arts** [comment]
I've been brainstorming about this as well, in my case for `__cuda` but the same issue holds. 

If we build a `[target.cfg('linux=2.6.32').dependencies]`, what needs to happen in the solver is that we build a complete new environment. So in terms of solving and required system resources this might not really help. 

The power would be auto selecting a certain environment for the specialized target. So pixi shouln't just use the available default env with the current platform but have a `get_best_target(current_platform, available_virtual_packages)` function to figure out the most specialized environment.

**Reply by gzm55** [reply]
> The power would be auto selecting a certain environment for the specialized target.

Can we auto enable some `feature`s based on the virtual packages? We can put this kind of features into all envs including `default`. Also a flag is needed to exclude those features.

**Reply by ruben-arts** [reply]
The features are locked in environments but we could think of a better way to decide which is the "default" environment for your platform. e.g.:
```toml
[environments]
cuda = { features = ["cuda12"], default-if = { cuda = "12.2" } }
cuda_old = { features = ["cuda11"], default-if = { cuda = "11" } }
```
> [!NOTE] 
> This is just a brain dump, not a design proposal.

**Reply by gzm55** [reply]
what if both `default-if` clauses are evaluated to true for two environments? one is cuda = 12.2, another is glibc = 2.12

**Reply by ruben-arts** [reply]
We have this interactive ambiguity message, that we could reuse:
```
pixi/examples/multi-machine
➜ pixi run train 
? The task 'train' can be run in multiple environments.

Please select an environment to run the task in: ›
❯ default
  cuda
```

**Reply by gzm55** [reply]
then we could probably have to make a matrix of envs for virtual packages.

it's better to let the conditional check in a more composable level. if `feature` is not suitable, how about a `if` field for each dependency?

```toml
[dependencies]
pytorch-cpu = { version = "~=1.1", channel = "pytorch", if: { cuda: "...", linux: "..." } }
```
