### DISCUSSION TITLE
Canonical way to call complex `pip` commands.

### DISCUSSION THREAD

**Discussion by DamianB-BitFlipper** [prefix-dev/pixi#1474] [Q&A]
I am installing [unsloth](https://github.com/unslothai/unsloth?tab=readme-ov-file#-installation-instructions) in a pixi environment. The installation instructions involve two more complicated calls to `pip`. What I am currently doing is `pixi add pip` and then calling these `pip` commands as written. I'd like them to be a part of the `pixi.toml` to make a self-contained environment file.

Here are the `pip` commands:
`pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"`
`pip install --no-deps trl peft accelerate bitsandbytes`

**Comment by ruben-arts** [comment]
Sorry for missing this discussion.

This worked for me:
```toml
[project]
channels = ["https://fast.prefix.dev/conda-forge"]
name = "unsloth"
platforms = ["linux-64"]

[dependencies]
python = ">=3.12.5,<4"
trl = "*"
peft = "*"
accelerate = "*"
bitsandbytes = "*"
datasets = ">=2.16.4"

[pypi-dependencies]
unsloth = { git = "https://github.com/unslothai/unsloth.git", extras = ["colab-new"] }
```
