### DISCUSSION TITLE
what would equivalent of this conda in pyproject.toml or cli

### DISCUSSION THREAD

**Discussion by pvbhanuteja** [prefix-dev/pixi#1664] [Q&A]
As heading as 

conda install pytorch torchvision torchaudio cpuonly -c pytorch

how would the above translate into pyproject.toml or cli? There are a lot of GPU examples but not for CPU.

**Comment by ruben-arts** [comment]
The equivalent would be:
```
pixi init --pyproject torch-example && cd torch-example
pixi project channel add pytorch
pixi add pytorch::pytorch pytorch::torchvision pytorch::torchaudio pytorch::cpuonly
```

Resulting in (after removing not required fields):
```toml
[project]
name = "torch-test"
requires-python = ">= 3.11"

[tool.pixi.project]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
pytorch = { version = ">=2.4.0,<3", channel = "pytorch" }
torchvision = { version = ">=0.19.0,<0.20", channel = "pytorch" }
torchaudio = { version = ">=2.4.0,<3", channel = "pytorch" }
cpuonly = { version = ">=2.0,<3", channel = "pytorch" }

```


> [!NOTE]  
> We define the `pytorch` channel per dependency, this is the advised way! 
> Do you want to avoid that, then switch around the channels:
> ```toml
> channels = [ "pytorch", "conda-forge"]
> ```
> Notice that now more packages are pulled from the `pytorch` channel, which is most likely not what you want!!
> More documentation about channel priority found here: https://pixi.sh/latest/advanced/channel_priority/#channel-priority
