### DISCUSSION TITLE
What is the `pixi` equilvalent to `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu`?

### DISCUSSION THREAD

**Discussion by asmith26** [prefix-dev/pixi#1714] [Q&A] [answered]
Hi, I'm trying to install a CPU version of (py)torch using the following command, but I can't seem to get `pixi` to install `torch` from https://download.pytorch.org/whl/cpu.

What is the `pixi` equilvalent to the following (I'm using a pyproject.toml file)?

```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
```

Many thanks for any help!

**Comment by asmith26** [comment, marked as answer]
I've got it working:

### Option 1 (easier)

Following https://pixi.sh/v0.22.0/reference/configuration/#the-pypi-options-table, add to `pyproject.toml`:

```toml
[tool.pixi.pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]
```

### Option 2 (more work)

Following https://pixi.sh/v0.22.0/reference/configuration/#pypi-dependencies, pass in the appropriate URL (within `pyproject.toml`, e.g.

```toml
torch = { url = "https://download.pytorch.org/whl/cpu/torch-2.4.0%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=78dbf5f2789933a7ea2dabeead4daa44679b1e0d8eb35ddb7071c8ab7b181eb3" }
```

--- 

Thanks again for an amazing lib!

**Reply by yor-b** [reply]
After editing the toml, how do we tell pixi to update the environment by installing them, what's the command? just pixi install, or something else?

**Reply by baszalmstra** [reply]
Almost all commands will update the lockfile. pixi lock is the explicit one.

**Comment by m0n203** [comment]
I am using this way:


**pixi.toml**
```toml
[pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cpu" }
```

but it's no way to do this w/ `pixi add --pypi`, have to edit toml manually.

**Comment by Norlandz** [comment]
Pytorch Installation - Pixi by prefix.dev
https://pixi.sh/dev/python/pytorch/

I just follow the official docs :

```toml
[system-requirements]
cuda = "12.0"

[dependencies]
# pytorch-gpu = ">=2.5.1,<2.8"
pytorch-gpu = "*"
cuda-version = "12.6.*"
```

Then `pixi i`
Then `pixi add torchvision`

More:
```toml
[workspace]
channels = ["conda-forge", "pytorch"]
name = "build-llm-demo"
platforms = ["win-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.11.*"
pandas = "<=2.1.4"
pydantic-settings = ">=2.9.1,<3"
ruff = ">=0.12.0,<0.13"
pyright = ">=1.1.402,<2"
pytest = ">=8.4.1,<9"
# pytorch-gpu = ">=2.5.1,<2.8"
pytorch-gpu = "*"
cuda-version = "12.6.*"
ipykernel = ">=6.29.5,<7"
pixi-pycharm = ">=0.0.8,<0.0.9"
ipywidgets = ">=8.1.7,<9"
transformers = ">=4.13,<4.38"
huggingface_hub = ">=0.33.1,<0.34"
matplotlib = ">=3.10.3,<4"
itables = ">=2.4.2,<3"
tiktoken = ">=0.9.0,<0.10"
jupyterlab = ">=4.4.4,<5"
pypandoc = ">=1.15,<2"
pandoc = ">=3.7.0.2,<4"
jupytext = ">=1.17.2,<2"
torchvision = ">=0.22.0,<0.23"


[pypi-dependencies]
fastapi = { version = ">=0.115.13, <0.116", extras = ["standard"] }
uvicorn = { version = ">=0.34.3, <0.35", extras = ["standard"] }
gunicorn = ">=23.0.0, <24"
build-llm-learn = { path = ".", editable = true }
tensorflow = ">=2.18.0, <3"
bpemb = ">=0.3.6,<0.4"
```

**Comment by Norlandz** [comment]
There is another way from pypi: 

Pytorch Installation - Pixi by prefix.dev
https://pixi.sh/dev/python/pytorch/#pytorch-index

```toml
[pypi-dependencies]
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu124" }
```

(doesnt seem like need `cuda` as a package or something..)

Full code:
```toml
[workspace]
authors = ["norlz <norlz@gitkra.com>"]
channels = ["conda-forge"]
name = "iopaint-exe"
platforms = ["win-64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"

[pypi-dependencies]
iopaint = "==1.5.3"
torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu124" }
```
