### DISCUSSION TITLE
why does libc=2.12 resolve to  sysroot_linux-64 == 2.17 ?

### DISCUSSION THREAD

**Discussion by gzm55** [prefix-dev/pixi#1818] [General]
```toml
[system-requirements]
linux = "2.6"
libc = { family="glibc", version="2.12" }
```

this will resolve to sysroot_linux-64 == 2.17, and introduce some new glibc symbols after linking.
