### DISCUSSION TITLE
platform specific tasks and system-requirements same solve group

### DISCUSSION THREAD

**Discussion by geoHeil** [prefix-dev/pixi#1828] [Q&A]
How can I run platform-specific tasks?

```bash
pixi run create_environment

```

```
✨ Pixi task (create_environment in research-cpu): pixi install -e mlx
  × The platform you are running on should at least have the virtual package __cuda on version 12, build_string: 0
```

```toml
[environments]
mlx = {features = ["mlx"], solve-group = "default"}
cuda = {features = ["cuda"], solve-group = "default"}


[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12" }


[project]
name = "foo"
platforms = ["linux-64",  "osx-arm64"]
channels = ["conda-forge", "pytorch"]


[feature.mlx.tasks]
create_environment = {cmd = "pixi install -e mlx"}
```

However, a `pixi install -e research-cpu` will install fine. This works in this particular case, but fails in the generic task runner case due to not being able to execute the dependencies outside of the pixi enabled shell.

When looking at https://github.com/prefix-dev/pixi/blob/main/examples/multi-machine/pixi.toml and modifying it slightly and choosing separate solve groups - it works

```toml
[environments]
mlx = {features = ["mlx"], solve-group = "default"}
cuda = {features = ["cuda"], solve-group = "cuda"}


[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12" }


[project]
name = "foo"
platforms = ["linux-64",  "osx-arm64"]
channels = ["conda-forge", "pytorch"]


[feature.mlx.tasks]
create_environment = {cmd = "pixi install -e mlx"}
```

But if I want to ensure that (except for the cuda stuff) the same dependencies are used is there any chance I can get this to work  in the same groups?

**Comment by geoHeil** [comment]
My real project is a bit different:

```
pixi install
  × Unable to solve pypi dependencies for the research-cuda environment because no compatible python interpreter can be installed for the current platform
     ╭─[174:13]
 173 │ [feature.research-cuda]
 174 │ platforms = ["linux-64"]
     ·             ──────┬─────
     ·                   ╰── feature 'research-cuda' does not support 'osx-arm64'
platforms = ["linux-64", "win-64", "osx-arm64"]
     ·             ─────────────────┬─────────────────
     ·                              ╰── even though the projects does include support for 'osx-arm64'
```

I indeed do not WANT to support osx for this feature. How can I disable osx support for good for that feature? Why is the platforms directive limiting to linux (see below) not working as expected?

This is why

```
[feature.research-cuda]
platforms = ["linux-64"]
```

are set.

- When choosing the same solve group --> install works, but task runs fail
- When choosing different solve groups installation fails with the aforementioned error -

**Reply by ruben-arts** [reply]
You can't use `solve-groups` and `pypi-dependencies` when the different environments can't be installed on the machine your solving on. This is because we need to install the `conda` part of the environment before we can solve the `pypi-dependencies` but with the `platforms` you specify that the environment can not be installed on that platform. So cannot solve it.

**Reply by geoHeil** [reply]
What do you think the suggested way forward is? Use different solve groups. No pinning of system dependencies (seems to work so far)

Separate pixi file for each env? (I really would want to avoid it.

Also I didn`t specify any pip pipy-dependencies sections - where are these coming from (in the more complex example yes perhaps) but in the one above not - and still, I was running into the same error

**Reply by ruben-arts** [reply]
```toml
[project]
name = "foo"
# Default feature/environment work on both systems
platforms = ["linux-64",  "osx-arm64"]
channels = ["conda-forge"]

[feature.linux]
# Overwrite platforms
platforms = ["linux-64"]
# Overwrite channels
channels = ["conda-forge", "pytorch"]
# Linux feature requires cuda, so it can not be installed on osx.
system-requirements.cuda = "12"

[feature.macos]
# Overwrite platforms
platforms = ["osx-arm64"]

[environments]
linux = ["linux"]
macos = ["macos"]
```

This works as the two environments don't need to be installed for solving and don't interfere with solve groups. 

- Adding the same `solve-group` to both environments will fail as you then try to solve the complete dependency set for both.
- Adding `pypi-dependencies` will not work as you can't install all environments on all systems. Which doesn't allow you to solve. 

This is the issue related to solving your issues:
- https://github.com/prefix-dev/pixi/issues/1051
- https://github.com/prefix-dev/pixi/issues/1046

And It would be good to check out: https://github.com/prefix-dev/pixi/issues/1295

**Reply by geoHeil** [reply]
But why is my:

```toml
[feature.cuda]
platforms = ["linux-64"]
```
override not working?

it looks to me exactly the same as yours:

```toml
[feature.linux]
# Overwrite platforms
platforms = ["linux-64"]
```

**Reply by geoHeil** [reply]
Thanks for the links - at least for me it looks like setting:

```toml
[tool.pixi.feature.research-cuda.system-requirements]
cuda = "12"
```

can be a suitable workaround
