### DISCUSSION TITLE
Abillity to split pixi.toml into multiple files

### DISCUSSION THREAD

**Discussion by jleibs** [prefix-dev/pixi#1898] [Ideas]
### Problem description

We have a large, and growing pixi.toml file

It has grown to the point where some kind of hierarchical file-based organization would be helpful.

There are clearly different ways to partition: by function such as task vs dependency, by environment, by project sub-directory, including dependencies and tasks related to a given part of the code-base.

However, at a minimum just a way to include other files so create a pixi.toml that is a concatenation of all the included files might help bring a little bit of organization to things.

**Comment by niemiaszek** [comment]
Interesting. I really appreciate the possibility to keep all my env-related stuff in one file instead of having multiple environment.yml's like I did with conda before. Moreover, possibility of bundling Pixi into pyproject.yml is also nice for python-only projects.

Would be interesting to see work on such a large project

**Comment by bollwyvl** [comment]
Yes, lovely stuff, and could potentially help reduce duplication in matrix use cases, and enable monorepos and skeleton-based tools to get spun up on `pixi` more quickly.

As long as there is a way to get a single inspectable file back _out_, fully realized, things are pretty ok. Otherwise, behold the nightmare that is GitHub actions `uses` or, worse still, the GitLab pipeline spaghetti: can't know until you try, and have already spun up 20 containers!

> concatenation

Yep, TOML is quite resilient to `cat`. I've explored not actually checking in `pixi.toml` and having a wrapper script which _doesn't_ need `pixi`... cleaned up a bit, my "run"-focused `pxr`:

```bash
#!/usr/bin/env bash
cat pixi.base.toml src/*/pixi.partial.toml > pixi.toml

set -eux
for task in "$@"; do
    pixi run $task
done
```

_Writing_ those files can be a bit hard to reason about, however, as all those paths need to be `pixi.toml`-relative.

> include

As with the `inputs`/`outputs` feature, `task` could provide some inspiration with its top-level  [`includes`](https://taskfile.dev/usage/#including-other-taskfiles) which can be a simple path string or a rich object. 

Typographically, this could be adaptable here, assuming a reserved namespace delimiter, e.g. `:`:

```toml
[project]
includes.docs = "docs/pixi.toml"
includes.atest = { manifest = "atest/pixi.toml", features = ["deps-atest"] }

[project.includes.ff]
manifest = "atest/pixi.toml"
features = ["tasks-atest"]
env = { BROWSER = "firefox" }

[project.includes.cr]
manifest = "atest/pixi.toml"
features = ["tasks-atest"]
env = { BROWSER="chromium" }

[tasks.all]
depends_on = ["docs:build", "ff:robot", "cr:robot"]
inputs = [
  "build/docs/.buildinfo", 
  "build/reports/robot/chromium", 
  "build/reports/robot/firefox",
]

[environments]
docs = ["docs:deps-docs", "docs:tasks-docs"]
atest = ["atest:deps-atest", "ff:tasks-atest", "cr:tasks-atest"]
```

Dangerously close to going down the spaghetti route of "post-install hooks": if an `include` could be declared as coming from an environment, all of a sudden partial `pixi` workflows could be packaged like proper software:

```toml
[project.includes.ex]
manifest = { environment = "default", path = "share/pixi/tasks/example.com/pixi.toml" }
env = { EX_PROJECT_NAME="my-project" }

[feature.baseline.dependencies]
example-com-pixi-tasks = "2024.04.*"
```

Having been down this road, it gets pretty hairy if a child wants to reference its parent files, features, tasks, etc. This could either be _banned_ (which would limit the overall functionality) or would require some more syntax to make an includable partial contract more explicit and self-documenting, e.g.

```toml
[partial]
parent = "root"

# just use JSON Schema: don't get fancy
[partial.env.EX_PROJECT_REPO]
description = "the location of repo"

[partial.env.EX_PROJECT_NAME]
description = "a lovely project name according to your friendly example.com company policies"
pattern = "[a-z][a-z/d\\-]+"
```
