### DISCUSSION TITLE
pip install works - what is failing for pixi/uv

### DISCUSSION THREAD

**Discussion by geoHeil** [prefix-dev/pixi#1924] [Q&A] [answered]
```toml

[dependencies]
python = "3.11"
pip = ">=24.2"

[environments]
example = { features = ["example"], solve-group = "example" }

[feature.example.dependencies]


[feature.example.pypi-dependencies]
dagster = ">=1.8,<1.9"


[project]
name = "baz"
version = "1.0.0"
description = "bar"
authors = [
  "foo",
]
platforms = ["linux-64", "osx-arm64"]
channels = ["conda-forge"]
```

fails with 

```
pixi install
  × failed to solve the pypi requirements of 'example' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because dagster>=1.8.0,<=1.8.2 depends on typing-extensions>=4.4.0,<5
      and typing-extensions==72.2.0, we can conclude that
      dagster>=1.8.0,<=1.8.2 cannot be used.
      And because only the following versions of dagster are available:
          dagster<=1.8.0
          dagster==1.8.1
          dagster==1.8.2
          dagster==1.8.3
      we can conclude that dagster>=1.8.0,<1.8.3 cannot be used.
      And because dagster==1.8.3 was yanked (reason: Determined that this
      version of Dagster resulted in errors when trying to launch runs that
      target individual asset partitions) and you require dagster>=1.8, we can
      conclude that your requirements are unsatisfiable.
```

adding

```
typing-extensions = ">=4.4.0,<5"
```

results in 

```
pixi install
  ⠂ default:linux-64     [00:00:00] resolving conda
  ⠂ example:linux-64     [00:00:00] resolving conda                               × failed to solve the pypi requirements of 'example' 'osx-arm64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because you require typing-extensions>=4.4.0,<5 and typing-
      extensions==72.2.0, we can conclude that your requirements are
      unsatisfiable.
```

how can this be fixed?

Install via pip works - why does UV fail?
How can it be that a single (solo) dependency fails to resolve?
