### DISCUSSION TITLE
How tell `pixi` to use different `pypi-options` for different environments?

### DISCUSSION THREAD

**Discussion by asmith26** [prefix-dev/pixi#1949] [Q&A] [answered]
Hi there,

I'm trying to install different pytorch dependencies depending on my computing environment (i.e. CPU or GPU). Following my answer at https://github.com/prefix-dev/pixi/discussions/1714#discussioncomment-10317535, I'm trying:

```toml
[project]
name = "my_project"
requires-python = ">=3.12"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = ">=3.12"

[tool.pixi.feature.cpu]
pypi-options = { extra-index-urls = ["https://download.pytorch.org/whl/cpu"] }
pypi-dependencies = { "torch" = "*", "torchvision" = "*"}

[tool.pixi.feature.gpu]
system-requirements = {cuda = "12.4"}
pypi-options = { extra-index-urls = ["https://download.pytorch.org/whl/cu124"] }
pypi-dependencies = { "torch" = "*", "torchvision" = "*"}

[tool.pixi.environments]
default = {features = [], solve-group = "default"}
cpu = {features = ["cpu"], solve-group = "default"}
gpu = {features = ["gpu"], solve-group = "default"}
```

But when I look at `pixi.lock` I see:

```lock
  gpu:
    channels:
    - url: https://conda.anaconda.org/conda-forge/
    indexes:
    - https://pypi.org/simple
    - https://download.pytorch.org/whl/cpu
    - https://download.pytorch.org/whl/cu124
```

Any help great appreciated. Thanks!

**Comment by tdejager** [comment]
Oh hi! I missed this sorry, but the `pypi-options` are also combined over `solve-groups` there is not really a way around that currently. So to only use the indices for the environments, your only option now is to exclude the solve-groups.

**Reply by asmith26** [reply, marked as answer]
Many thanks for your help and info @tdejager. Can confirm this works for me:

```toml
# pyproject.toml  -  pypi

[project]
name = "my_project"
requires-python = ">=3.12"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = ">=3.12"

[tool.pixi.feature.cpu]
pypi-options = { extra-index-urls = ["https://download.pytorch.org/whl/cpu"] }
pypi-dependencies = { "torch" = "*", "torchvision" = "*"}

[tool.pixi.feature.gpu]
system-requirements = {cuda = "12.2"}
pypi-options = { extra-index-urls = ["https://download.pytorch.org/whl/cu124"] }
pypi-dependencies = { "torch" = "*", "torchvision" = "*"}

[tool.pixi.environments]
cpu = ["cpu"]
gpu = ["gpu"]
```

also (interestingly/strangely I did have to use `requires-python = ">= 3.11"` for this conda version):

```toml
# pyproject.toml  -  conda

[project]
name = "my_project"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "name", email = "email@email.com"}]
requires-python = ">= 3.11"

[tool.pixi]
project = {channels = ["conda-forge"], platforms = ["linux-64"]}
dependencies = {python = ">=3.11"}

[tool.pixi.feature.cpu]
channels = ["pytorch"]
dependencies = {"pytorch" = "*", "torchvision" = "*", "cpuonly" = "*"}

[tool.pixi.feature.gpu]
channels = ["pytorch", "nvidia"]
dependencies = {"pytorch" = "*", "torchvision" = "*", "pytorch-cuda" = "12.4"}

[tool.pixi.environments]
cpu = ["cpu"]
gpu = ["gpu"]
```

Then running the following works as expected:

```bash
$ pixi install && pixi install -e cpu && pixi install -e gpu

$ pixi run python -c "import torch; print(torch.cuda.is_available())"
...
ModuleNotFoundError: No module named 'torch'

$ pixi run -e cpu python -c "import torch; print(torch.cuda.is_available())"
False

$ pixi run -e gpu python -c "import torch; print(torch.cuda.is_available())"
True
```
