### DISCUSSION TITLE
Install multiple [editable] packages from `src/<packageN>`?

### DISCUSSION THREAD

**Discussion by jmuchovej** [prefix-dev/pixi#1998] [Q&A] [answered]
👋 is it possible to have two packages, which are editable, installed via `tools.pixi.pypi-dependencies`?
```
src
├── package1
│  └── __init__.py
└── package2
   └── __init__.py
```

essentially, if i have a `pyproject.toml` like the following:
```toml
[project]
name = "package1"
requires-python = ">=3.12"
version = "0.1.0"

[tool.pixi.pypi-dependencies]
package1 = { path = ".", editable = true }
package2 = { path = ".", editable = true }
```

i only end up with `package1` installed after doing `pixi install`. so i'm curious if it's possible to install (and how so) multiple packages like this?

my use-case is essentially – i'm replicating some research code which i want to freeze (since they just used a flat file structure, which i don't want to). so i've forked their code and aimed to repackage it into `package2`, so i could import it within `package1` and anywhere else i might need it.

if i update my `pyproject.toml` by removing `editable = true` on the `package2 = ...` line, then i get an error stating "package metadata name `package1` does not match the given name `package2`.

i'm not entirely sure how much of this is a pixi issue vs python toolchain, but i figured someone here would know better than i do. 😅

**Comment by ruben-arts** [comment, marked as answer]
I think you need to specify your build system to use the [src-layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/)
```
.
├── pixi.lock
├── pyproject.toml
└── src
    ├── package1
    │   └── __init__.py
    └── package2
        └── __init__.py

```
`pyproject.toml`:
```toml
[project]
name = "package_name"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
package_name = { path = ".", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["src/package1", "src/package2"]
```

```
❯ pixi run python
Python 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:36:51) [GCC 12.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import package1
>>> package1.package1()
package1
>>> import package2
>>> package2.package2()
package2
>>> exit()
```

**Reply by jmuchovej** [reply]
~~thanks! so, this is definitely on the right track – you do need the last set of lines in your `pyproject.toml`; **critically**, though, the `package_name` _cannot overlap with either of `src/package1` and `src/package2`_. (i didn't specify that there was an overlap, but this is the last bit of information i needed for this approach to work.)~~

```toml
[tool.hatch.build.targets.wheel]
packages = ["src/package1", "src/package2"]
```

(turns out the above solution works – my issue also due to `project.name = research-project` while the key in `tool.pixi.pypi-depdencies.research_project = ...` – `project.name` needed to be `research_project`, and the overlapping names caused no issues!)
