### DISCUSSION TITLE
pixi and micromamba install different builds of the same package

### DISCUSSION THREAD

**Discussion by Yura52** [prefix-dev/pixi#2199] [Q&A] [answered]
Hi! Namely, this:

```
pixi init a
cd a
pixi add pytorch
```

results in `pytorch=2.4.0=cpu_mkl_py312h31352b0_101`. While this:

```
micromamba env create -n b python=3.12.6 pytorch
```

results in `pytorch=2.4.0=cuda120_py312h26b3cf7_301`. Is this behavior expected? Can I somehow tell Pixi to follow `conda`/`mamba`/`micromamba` when choosing builds?

I tested the above on `linux-64` with `pixi=0.31.0` and `micromamba=1.5.9`.

P.S. Also, I am curious which of the two builds is actually better/faster?

**Comment by baszalmstra** [comment, marked as answer]
Did you add the [`cuda` system requirement](https://pixi.sh/latest/features/system_requirements/#using-cuda-in-pixi)?

**Reply by ruben-arts** [reply]
This does fix it:
```toml
[project]
channels = ["conda-forge"]
name = "a"
platforms = ["linux-64"]

[system-requirements]
cuda = "12.1" # <<<

[dependencies]
pytorch = ">=2.4.0,<3"
```

```
> pixi list --no-install
....
pytorch               2.4.0       cuda120_py312h26b3cf7_301  24.6 MiB   conda  pytorch-2.4.0-cuda120_py312h26b3cf7_301.conda
...
```
