### DISCUSSION TITLE
Managing dependencies in Python 3.13 environment

### DISCUSSION THREAD

**Discussion by hoxbro** [prefix-dev/pixi#2267] [Ideas]
Note: First asked on [Discord](https://discord.com/channels/1082332781146800168/1289943383607087144).

Could it be possible to add a way only to add a dependency to an environment based on another dependency/feature? With the upcoming release of Python 3.13 and some packages still needing to support it, writing features in the `pixi.toml` becomes a bit awkward. There are different ways to tackle it, but nothing feels great.

1) I create multiple features with the same dependencies and comment out those not yet supporting Python 3.13.
2) I split the features up into supported/not supported dependencies, and add both to all environments except the Python 3.13 ones.
3) I wait until every dependency in the feature supports Python 3.13 before I add it to the environment. 
4) I'm overlooking something obvious.

Option 1 and 2 add many temporary configurations, which first need to be added and removed at some point. Option 3 is also less than ideal if 90% of the dependencies support Python 3.13.

Maybe a dependency could have a way to be ignored if another feature is also set in the environment; an example is given below. This will then install numba in the test-312 environment but not in the test-313 environment. In my case, it is not possible to add numba to the py312 feature as it is also used elsewhere where it should be removed from numba. 

``` toml
[environments]
test-core = ["py312"]
test-312 = ["py312", "test"]
test-313 = ["py313", "test"]

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.test.dependencies]
numba = { version = "*", ignore_with_features = ["py313"]} 
```
*) `ignore_with_features` is a suboptimal name.
