### DISCUSSION TITLE
Can you have both `pixi.toml` (for system deps and non Python requirements) and `pyproject.toml` (for Python package requirements) in a project

### DISCUSSION THREAD

**Discussion by Robinlovelace** [prefix-dev/pixi#2382] [Q&A]
Basically as the title suggests. Context: working with @wangzhao0217 and others on teaching materials that will use R and Python. If the Python deps can be in a pyproject.toml file that is called from the higher level pixi.toml file that could make the project more modular and useful for people who don't care about installing R. Is that possible though?

Here's our repo for reference (see PR where we're managing Python deps in CI, would be good if a single pixi.toml could handle deps in one place): https://github.com/ITSLeeds/TDStests/pull/22

**Comment by ruben-arts** [comment]
It's not entirely clear to me what you are requesting, but you can have both yes. 

You can also just use a `pyproject.toml` and create a seperate environment that doesn't use the "default" parts of the `pyproject.toml` 

You can also let `pixi` handle your ci setup: https://github.com/marketplace/actions/setup-pixi which can then do the setup of a `ci` environment with exactly everything you want. instead of these multiple `setup-xxx`'s which allowes you to test the CI environment locally.

**Reply by Robinlovelace** [reply]
Just to be clear: if you do 

```bash
pixi install 
```

in a project with both `pixi.toml` and `pyproject.toml` config files, will pixi 

a) Install the system deps definied in the former

b) then install the Python pkgs defined in the latter

?

Is there a way to do something like

```
[python-pkgs]
  [pyproject = "path-to-pyproject.toml"]
```

Hope this makes sense, apologies if I've asked something non-sensical, learning as I go.

**Reply by ruben-arts** [reply]
Ah you might want to checkout the `[pypi-dependencies]`: https://pixi.sh/latest/reference/project_configuration/#path

You can do in a `pixi.toml`:
```toml
[pypi-dependencies]
# This will look for a package called `minimal-project` in the folder `minimal-project`.
# If it is a Python package it will find a way to install it.
minimal-project = { path = "./minimal-project", editable = true}
```
This doesn't import packages it just installs a python package for you that can be path based and editable. Which includes installing the dependencies.

---

If you are looking to simply import the `pyproject.toml`, and you don't have an actual Python package. I would motivate you to use the `pyproject.toml` directly or skip it completely. 

For example this is a `pyproject.toml` which can be used by `pip` and `pixi`:
```toml
[project]
name = "pixi-py"
# Setup your python here
requires-python = ">= 3.11"
# Whatever pypi dependencies you need.
dependencies = ["pypi-packages"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
jupyter = "*"
# etc..
```

Which is equivalent to this `pixi.toml`:
```toml
[project]
name = "pixi-py"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

# Put the pypi dependencies here instead of `[project.dependencies]`
[pypi-dependencies]
pypi-packages = "*"
# etc...

[dependencies]
python = ">=3.11"
jupyter = "*"
# etc...
```
