### DISCUSSION TITLE
Option to Set Default Package Type for pyproject.toml Dependencies (PyPI vs Conda)

### DISCUSSION THREAD

**Discussion by gitkief** [prefix-dev/pixi#2550] [Ideas]
Pixi [supports both][1] the `pyproject.toml` and `pixi.toml` files for configuring Python projects. This flexibility is particularly useful if you want to fall back on Python's native tooling. When using the `pyproject.toml`, the listed `dependencies` are treated as [PyPI dependencies][2] by Pixi. 

This behavior surprised me since Pixi describes itself as "[Pixi](https://github.com/prefix-dev/pixi) is a fast software package manager built on top of the existing conda ecosystem." Given this description, I would have expected PyPI packages to serve as a fallback option rather than the primary one. 

According to the documentation, the currently recommended approach to ensure Pixi installs conda dependencies instead is to explicitly list the dependencies in the `[tool.pixi.dependencies]` section again. For example:

```toml
[project]
name = "my_project"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.dependencies]
numpy = "*"
pandas = "*"
matplotlib = "*"
```

This approach may not be ideal for projects with a significant number of dependencies, as it introduces additional boilerplate. If this option doesn’t already exist (and apologies if I’ve overlooked it), I wonder if it might be a good idea to allow users to set a default package type or specify a rule such as, "handle all packages as conda dependencies except for the following ones...".  

[1]: https://pixi.sh/dev/advanced/pyproject_toml/#pyprojecttoml-in-pixi
[2]: https://pixi.sh/dev/advanced/pyproject_toml/#dependency-section
