### DISCUSSION TITLE
Ruff and mypy usage

### DISCUSSION THREAD

**Discussion by laguill** [prefix-dev/pixi#2594] [Q&A]
Hello,
How do you integrate ruff and mypy in your project ?

Do you create dev feature ?
For now I added ruff and mypy directly in my project

For sharing or collaboration I am not sure that the "correct " way ...

What do you suggest do you have some exemple ?

Thanks for your help

**Comment by ruben-arts** [comment]
Hey @laguill,

A `dev` feature might be the best option indeed!

```toml
[project]
name = "project"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[feature.dev.dependencies]
ruff = "*"
mypy = "1.13"

[dependencies]
python = ">=3.12, <3.13"
matplotlib = "*"
numpy = "*"

[feature.test.dependencies]
pytest = "*"

[environments]
 # Extend the default environment with multiple features
default = { features = [ "dev", "test", ], solve-group = "default" }
# Have only the default dependencies and the added test dependencies.
test = { features = ["test"], solve-group = "default" }
```

Results in this `pixi info`:
```
....
Environments
------------
       Environment: default
          Features: dev, test, default
       Solve group: default
          Channels: https://prefix.dev/conda-forge
  Dependency count: 6
      Dependencies: ruff, mypy, pytest, python, matplotlib, numpy
  Target platforms: win-64, linux-64, osx-arm64, osx-64

       Environment: test
          Features: test, default
       Solve group: default
          Channels: https://prefix.dev/conda-forge
  Dependency count: 4
      Dependencies: pytest, python, matplotlib, numpy
  Target platforms: osx-64, win-64, osx-arm64, linux-64
  ```

Note that for `pyproject.toml` there is also `dependency-groups` which allow you to rewrite this same project in a `pyproject.toml` as:
```toml
[project]
name = "project"
requires-python = ">=3.12, <3.13"
dependencies = ["matplotlib", "numpy"]

[dependency-groups]
dev = ["ruff", "mypy==1.13"]
test = ["pytest"]

[tool.pixi.project]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tool.pixi.environments]
 # Extend the default environment with multiple features
default = { features = [ "dev", "test", ], solve-group = "default" }
# Have only the default dependencies and the added test dependencies.
test = { features = ["test"], solve-group = "default" }
```
