### DISCUSSION TITLE
GitHub Action to update pixi.lock in a sub-directory

### DISCUSSION THREAD

**Discussion by SheldonWBM** [prefix-dev/pixi#2603] [Q&A] [answered]
Hi,
I am setting up a GitHub Action to update the lock file, similar to dependabot.
I am following these instructions: https://pixi.sh/latest/advanced/updates_github_actions/

It fails at creating a pull request; `diff.md` does not exist. 

```
jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false
      - name: Update lockfiles
        working-directory: my/sub/dir
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: diff.md
          branch: update-pixi
          base: main
          labels: pixi
          delete-branch: true
          path: my/sub/dir
          add-paths: pixi.lock
```
I have tried `body-path: my/sub/dir/diff.md`, but `working-directory` does not work in "Create pull request."

![image](https://github.com/user-attachments/assets/e33402a6-2042-4db4-bfa2-7013df907693)

**Comment by pavelzw** [comment]
diff.md is also in your subdirectory

**Reply by SheldonWBM** [reply]
Yes, `working-directory: my/sub/dir` for the step `Update lockfiles`.
I assume that when `diff.md` is blank (no changes), it does not fail with the error "does not exist".

**Comment by SheldonWBM** [comment, marked as answer]
Solved issue. While I did this before and merged it into `main`, it might have used the old action when re-running:
```
jobs:
  pixi-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false
      - name: Update lockfiles
        working-directory: my/sub/dir
        run: |
          set -o pipefail
          pixi update --json | pixi exec pixi-diff-to-markdown >> diff.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pixi lockfile
          title: Update pixi lockfile
          body-path: my/sub/dir/diff.md
          branch: update-pixi
          base: main
          labels: pixi
          delete-branch: true
          add-paths: my/sub/dir/pixi.lock
```
