### DISCUSSION TITLE
Empty pixi environment

### DISCUSSION THREAD

**Discussion by akhmerov** [prefix-dev/pixi#2662] [Ideas]
I am using pixi as a simple caching tool to run tasks in CI. For one of the tasks I use an alpine-based docker image with inkscape (linuxserver/inkscape) because that one isn't available on conda. Since this is alpine, glibc is not available, however I also don't need to install any packages in the environment that runs the task.

So far this works, with the relevant part of the configuration looking as follows:
```toml
[feature.empty.tasks]
svgtopdf = { cmd = "bash -c 'for f in *.svg; do inkscape -o ${f%.*}.pdf $f; done'", inputs = [ "figures/*.svg" ], outputs = [ "figures/*.pdf" ], cwd = "figures" }

[feature.empty.dependencies]

[environments]
default = { solve-group = "default" }
empty = { features = ["empty"], no-default-feature = true }

[feature.empty.system-requirements]
libc = { family = "unix", version = "0" }
```

Note that this requires an ugly hack: specifyin `unix` virtual package as a placeholder for libc. This doesn't cause any problems because the task doesn't use libc, but I'm wondering if it is possible to implement this cleaner. Does anyone have an idea?
