### DISCUSSION TITLE
optional cuda system dependency

### DISCUSSION THREAD

**Discussion by geoHeil** [prefix-dev/pixi#2746] [Q&A] [answered]
my pyproject.toml looks like

```toml
[project]
name = "chemxtract"
version = "1.0.0"
description = "foo"
authors = [{ name = "bar", email = "baz" }]
requires-python = "==3.13"

[tool.pixi.project]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64", "linux-aarch64"]
channels = ["pytorch", "conda-forge", "bioconda", "anaconda"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]

img2txt = { features = [
  "img2txt",
  "img2txt_base",
], solve-group = "img2txt",  no-default-feature = true }
img2txt-cuda = { features = [
  "img2txt_base",
  "img2txt-cuda",
], solve-group = "img2txt",  no-default-feature = true }

[tool.pixi.feature.img2txt_base.dependencies]
python = "~=3.12.0"

[tool.pixi.feature.img2txt_base.pypi-dependencies]
layoutparser = { version = "==0.3.4", extras = ["layoutmodels", "ocr"] }
easyocr = "~=1.7.2"

[tool.pixi.feature.img2txt.dependencies]
[tool.pixi.feature.img2txt.pypi-dependencies]
paddlepaddle = "~=2.6.2"

[tool.pixi.feature.img2txt-cuda]
platforms = ["win-64", "linux-64"]
system-requirements = { cuda = "12" }

[tool.pixi.feature.img2txt-cuda.target.linux-64.dependencies]
cuda-version = { version = ">=12.0,<=12.6" }

[tool.pixi.feature.img2txt-cuda.target.linux-64.pypi-dependencies]
paddlepaddle-gpu = "~=2.6.2"
```

A `pixi install` works and is properly resolved. A `pixi shell -e img2txt` fails with `  × The platform you are running on should at least have the virtual package __cuda on version 12, build_string: 0` even tough the feature was instantiated without `cuda`.

what is wrong?
