### DISCUSSION TITLE
Pixi resolves unused optional dependencies

### DISCUSSION THREAD

**Discussion by rmorshea** [prefix-dev/pixi#2803] [Q&A]
I'm working on converting a project from Poetry to Pixi that depends on a Python package that has platform specific [optional dependencies](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies). It appears that Pixi resolves all dependencies of Python packages if they match `pixi.project.platforms`, even if the optional dependencies are never required by a project.

This is a problem because some platform-specific Python packages may implement `setup.py` files which build steps that error if executed from an unsupported platform. In my particular case, Pixi is trying to build [systemd-python](https://github.com/systemd/python-systemd) when on OSX which errors complaining that linux-specific `libsystemd-*` dependencies are missing. I can fix the issue by removing `linux-64` from the list of platforms.

I've been unable to reproduce this issue with a minimal example where I create a minimal project with `systemd-python` as an optional dependency, build it, and then try and install it in another project that doesn't use the optional dependency.

```toml
# in parent pyproject.toml
[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[project]
name = "parent"
version = "0.0.1"
dependencies = ["child@file:///Users/ryanmorshead/Repositories/public/pixi-issue/child-project/dist/child-0.0.1.tar.gz"]

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"


# in child pyproject.toml
[project]
name = "child"
version = "0.0.1"

[project.optional-dependencies]
optional = ['systemd-python==235']

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"
```

The fact I'm unable to reproduce this might suggest there an issue with my package's metadata, but I've been unable to figure out why Pixi thinks it needs to install systemd-python. I've tried to make the installation process as verbose as possible (`-vvv`) but I didn't see any logs that hinted at this info - only that it did so because it was resolving dependencies for the `linux-64` platform.
