### DISCUSSION TITLE
Installation of local package in a specified location

### DISCUSSION THREAD

**Discussion by b4rlw** [prefix-dev/pixi#283] [Q&A] [answered]
Poetry has a section like this:
```toml
[tool.poetry]
packages = [{include = "my_package", from = "src"}]
```
so that a local package in a particular location can be installed when running `poetry install`.

Does Pixi have some analogous functionality, or are there any plans to introduce it?

Thanks so much for building this awesome project for the Conda ecosystem!

**Comment by wolfv** [comment, marked as answer]
Hi @b4rlw indeed, we have plans for something like this. 

Our idea is that it will look like:

```toml
mypkg = { git = "https://github.com/prefix-dev/pixi", rev = "main" }
otherpkg = { path = "../local/package" }
oreven = { package = "../oreven.conda" }
```

We will first finish the package building (#12) and then the others should be relatively straight-forward :)
