### DISCUSSION TITLE
How pixi deal with multi-language?

### DISCUSSION THREAD

**Discussion by asuper0** [prefix-dev/pixi#295] [General]
Hi, I wonder how it works wiff multi-language in one project. I find nothing about the language field in the `pixi.toml` file. So would it cache multiple dependency packages for every language, or just keep one for each language?

This work is pretty cool, thanks!

**Comment by ruben-arts** [comment]
He @asuper0, 

We're building environments using conda packages. This means we are not limited by a language as you can build anything into a conda package. 

Currently pixi is very useful to install Python, C++ and R packages but its not limited to those languages. Pixi itself is a rust project but we also use pixi to start development on it and there are more examples like Nodejs, Ruby, Zig, etc. In those cases you use pixi to install the language itself and their own package managers like `cargo` and `npm` which can use the pixi environment. 

Hope that explains it!

Example of a multi-language pixi project:

```toml
[project]
name = "multilanguage"
version = "0.1.0"
description = "An pixi project that has multiple languages available."
authors = ["Ruben Arts <ruben@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
rust = "1.71.1.*"
python = "3.11.4.*"
zig = "0.9.1.*"
nodejs = "20.5.1.*"
ruby = "3.2.2.*"

```
