### DISCUSSION TITLE
Fail to resolve a package

### DISCUSSION THREAD

**Discussion by noamgot** [prefix-dev/pixi#3023] [Q&A]
[Orignally asked on discord]

I need to install a package called "alpha-shape". It's an internal package within my organization. I don't think the problem I describe here is a channel issue, as I managed to install many other internal packages from the channel where this package is stored. 

I tried installing it with version>=1 in a clean pixi project and got an error:
![image](https://github.com/user-attachments/assets/cd91e867-e165-40e0-9f00-081ecf743cb0)

Without the version constraint, I managed to install it with version 0.0.10 (I must use version >=1 though).

I ran pixi add with -vvv , here are the relevant logs:
![image](https://github.com/user-attachments/assets/411c3d4f-f66d-402c-aaa6-533b64500813)

Installing this package with a regular mamba create command works properly:
```
mamba create -n dummy "alpha-shape>=1" --dry-run
```
If that helps, here are the results of `pixi info alpha-shape`:
![image](https://github.com/user-attachments/assets/83d72987-4005-4175-8cbf-28bedacec69a)

What could be the issue here? I don't even know where to start... thanks

**Comment by ruben-arts** [comment]
Could you check the `conda-meta/alpha-shape-....json` file in the folder of the `mamba` environment?

It feels like this should contain a `constraints` list. Which would explain the pixi result. e.g. something like this:
```
{
...
  "constrains": [
    "alpha-shape 1010.6.*",
  ],
  ```
  Could you share this file?

**Reply by noamgot** [reply]
sure, here it is 

```yaml
{
  "build": "0",
  "build_number": 0,
  "channel": "https://***/noarch",
  "constrains": [
    "alpha-shape 9.9.9999"
  ],
  "depends": [
    "matplotlib",
    "numpy",
    "scipy"
  ],
  "extracted_package_dir": "$HOME/.cache/conda/alpha-shape-1.0.4-0",
  "features": "",
  "files": [
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/INSTALLER",
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/METADATA",
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/RECORD",
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/REQUESTED",
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/WHEEL",
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/direct_url.json",
    "lib/python3.10/site-packages/alpha_shape-1.0.4.dist-info/top_level.txt",
    "lib/python3.10/site-packages/alpha_shape/__init__.py",
    "lib/python3.10/site-packages/alpha_shape/alpha_shape.py",
    "lib/python3.10/site-packages/alpha_shape/__pycache__/__init__.cpython-310.pyc",
    "lib/python3.10/site-packages/alpha_shape/__pycache__/alpha_shape.cpython-310.pyc"
  ],
  "fn": "alpha-shape-1.0.4-0.tar.bz2",
  "license": "",
  "link": {
    "source": "$HOME/.cache/conda/alpha-shape-1.0.4-0",
    "type": 1
  },
  "md5": "2adc4d7922e535db9ce14b2c86e93b57",
  "name": "alpha-shape",
  "noarch": "python",
  "package_tarball_full_path": "$HOME/.cache/conda/alpha-shape-1.0.4-0.tar.bz2",
  "package_type": "noarch_python",
  "paths_data": {
    "paths": [
      {
        "_path": "lib/python3.10/site-packages/alpha_shape/__pycache__/__init__.cpython-310.pyc",
        "path_type": "pyc_file"
      },
      {
        "_path": "lib/python3.10/site-packages/alpha_shape/__pycache__/alpha_shape.cpython-310.pyc",
        "path_type": "pyc_file"
      }
    ],
    "paths_version": 1
  },
  "requested_spec": "None",
  "sha256": "2a6374dc7da76208d217cddf07f6ffb6ef514d66d57e186d521f6d652d7ea45c",
  "size": 9663,
  "subdir": "noarch",
  "timestamp": 1692165672000,
  "track_features": "",
  "url": "https://***/noarch/alpha-shape-1.0.4-0.tar.bz2",
  "version": "1.0.4"
}%      
```

indeed, there's a `constraints` section with `alpha-shape` itself. I don't understand how it works with mamba but not with pixi...
