### DISCUSSION TITLE
Import error after installing a github package using pixi

### DISCUSSION THREAD

**Discussion by xinge-ji** [prefix-dev/pixi#3053] [Q&A]
Hi there,

I am trying to install a package from my GitHub repository in my Python project using `pixi`, but I am encountering an issue when trying to import the package.

When I install the package using the following `pip` command, it works as expected:

```bash
pip install git+https://github.com/xinge-ji/dolphinscheduler-sdk-python-4.0.4.git@4.0.4
```

I then added the dependency to my `pyproject.toml` like this:

```toml
[tool.pixi.pypi-dependencies]
apache-dolphinscheduler = { git = "https://github.com/xinge-ji/dolphinscheduler-sdk-python-4.0.4.git", tag = "4.0.4" }
```

The package installs correctly when I use `pixi install` to manage the dependencies. However, when I activate the Python environment by running:

```bash
pixi r python
```

and try importing the module that I wrote:

```python
from pydolphinscheduler.tasks.seatunnel import SeaTunnel
```

I get the following error:

```bash
ModuleNotFoundError: No module named 'pydolphinscheduler.tasks.seatunnel'
```

This import works fine when I use the `pip` method, but I encounter the issue when using `pixi`.

However, the module from the original pypi `apache/dolphinscheduler-sdk-python` such as 

```python
from pydolphinscheduler.tasks.sql import Sql
```

It works fine in `pixi` environment as well.

Could anyone suggest what might be causing this issue or how I can resolve it? 

Thanks in advance!

**Comment by ruben-arts** [comment]
Hey I tried your example with this configuration:
```toml
[project]
channels = ["https://prefix.dev/conda-forge"]
name = "dolphin"
platforms = ["osx-arm64"]

[dependencies]
python = ">=3.13.1,<3.14"
setuptools = ">=75.8.0,<76"

[pypi-dependencies]
apache-dolphinscheduler = { git = "https://github.com/xinge-ji/dolphinscheduler-sdk-python-4.0.4.git", tag = "4.0.4" }

[tasks]
import = "python -c 'from pydolphinscheduler.tasks.seatunnel import SeaTunnel; from pydolphinscheduler.tasks.sql import Sql; print(SeaTunnel, Sql)'"
```

Which gave me this output:
```shell
pixi run import
✨ Pixi task (import): python -c 'from pydolphinscheduler.tasks.seatunnel import SeaTunnel; from pydolphinscheduler.tasks.sql import Sql; print(SeaTunnel, Sql)'
Auth token is default token, highly recommend add a token in production, especially you deploy in public network.
/Users/rubenarts/envs/dolphin/.pixi/envs/default/lib/python3.13/site-packages/pydolphinscheduler/java_gateway.py:324: UserWarning: Using unmatched version of pydolphinscheduler (version 4.0.4) and Java gateway (version unknown) may cause errors. We strongly recommend you to find the matched version (check: https://pypi.org/project/apache-dolphinscheduler)
  gateway = GatewayEntryPoint()
<class 'pydolphinscheduler.tasks.seatunnel.SeaTunnel'> <class 'pydolphinscheduler.tasks.sql.Sql'>
```

Could you try again or share your full manifest?
