### DISCUSSION TITLE
pip works - pixi fails to resolve for magic-pdf

### DISCUSSION THREAD

**Discussion by geoHeil** [prefix-dev/pixi#3217] [Q&A] [answered]
Using pip like:

```pyproject.toml
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "xx", email = "yy" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = ["linux-64", "win-64", "linux-aarch64", "osx-arm64"]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
ocr-mineru = { features = [
  "ocr-mineru",
  
], solve-group = "ocr-mineru", no-default-feature = true }

[tool.pixi.feature.ocr-mineru.dependencies]
python = "~=3.10.0"
pip = "*"
```

Then executing:

```bash
pixi update
pixi shell -e ocr-mineru
pip install -U "magic-pdf[full]" --extra-index-url https://wheels.myhloli.com
```

works fine.

However, a pure pixi appraoch like:

```toml
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "xx", email = "yy" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = ["linux-64", "win-64", "linux-aarch64", "osx-arm64"]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
ocr-mineru = { features = [
  "ocr-mineru",
  
], solve-group = "ocr-mineru", no-default-feature = true }

[tool.pixi.feature.ocr-mineru.dependencies]
python = "~=3.10.0"
pip = "*"

[tool.pixi.feature.ocr-mineru.pypi-dependencies]
magic-pdf = { version = ">1,<2", extras = ["full"] }

```

given a config `./.pixi/config.toml` file like the one below which specifies the extra index:

```
[pypi-config]
extra-index-urls = ["https://wheels.myhloli.com"]
```

fails with:

```
pixi update
Error:
  × failed to solve the pypi requirements of 'ocr-mineru' 'osx-arm64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because there is no version of doclayout-yolo==0.0.2 and magic-pdf[full]==1.0.1 depends on doclayout-yolo==0.0.2, we can conclude that magic-pdf[full]==1.0.1 cannot be used.
      And because only the following versions of magic-pdf[full] are available:
          magic-pdf[full]<1
          magic-pdf[full]==1.0.1
          magic-pdf[full]==1.1.0
      we can conclude that magic-pdf[full]>1,<1.1.0 cannot be used. (1)

      Because there is no version of doclayout-yolo==0.0.2b1 and magic-pdf[full]==1.1.0 depends on doclayout-yolo==0.0.2b1, we can conclude that magic-pdf[full]==1.1.0 cannot be
      used.
      And because we know from (1) that magic-pdf[full]>1,<1.1.0 cannot be used, we can conclude that magic-pdf[full]>1 cannot be used.
      And because you require magic-pdf[full]>1, we can conclude that your requirements are unsatisfiable.

      hint: `doclayout-yolo` was requested with a pre-release marker (e.g., doclayout-yolo==0.0.2b1), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

how can this be fixed?

**Comment by nichmor** [comment]
hey @geoHeil !

what is the result if you will use this version specifier `magic-pdf = { version = "*", extras = ["full"] }`?

could you also please do a `pip freeze` in first approach?

thanks!

**Reply by nichmor** [reply]
ah! could you also please use
```
[tool.pixi.feature.ocr-mineru.pypi-options]
```

table instead of the config one?

**Reply by geoHeil** [reply]
The result is:

```
The package `magic-pdf==0.6.1` does not have an extra named `full` 
```
is the result for a version of *. But it resolves. However, to a totally outdated version.

**Reply by geoHeil** [reply]
Adding

```
[tool.pixi.feature.ocr-mineru.pypi-options]
extra-index-urls = ["https://wheels.myhloli.com"]
```

is using:

```
  ~ P magic-pdf                0.6.1               ->  0.8.1
```

still not at all the 1.1.0 from pip https://pypi.org/project/magic-pdf/

**Reply by geoHeil** [reply]
The output of freeze looks like:

```bash
pip freeze

absl-py==2.1.0
accelerate==1.4.0
aiohappyeyeballs==2.4.6
aiohttp==3.11.13
aiosignal==1.3.2
albucore==0.0.23
albumentations==1.4.24
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.8.0
astor==0.8.1
async-timeout==5.0.1
attrdict==2.0.1
attrs==25.1.0
babel==2.17.0
bce-python-sdk==0.9.29
beautifulsoup4==4.13.3
black==25.1.0
blinker==1.9.0
boto3==1.37.1
botocore==1.37.1
braceexpand==0.1.7
Brotli==1.1.0
cachetools==5.5.2
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.4.1
click==8.1.8
cloudpickle==3.1.1
coloredlogs==15.0.1
colorlog==6.9.0
contourpy==1.3.1
cryptography==44.0.1
cssselect==1.2.0
cssutils==2.11.1
cycler==0.12.1
Cython==3.0.12
datasets==3.3.2
decorator==5.2.1
detectron2==0.6
dill==0.3.8
distro==1.9.0
doclayout_yolo==0.0.2b1
einops==0.8.1
et_xmlfile==2.0.0
evaluate==0.4.3
exceptiongroup==1.2.2
fairscale==0.4.13
fast-langdetect==0.2.5
fasttext-predict==0.9.2.4
filelock==3.17.0
fire==0.7.0
Flask==3.1.0
flask-babel==4.0.0
flatbuffers==25.2.10
fonttools==4.56.0
frozenlist==1.5.0
fsspec==2024.12.0
ftfy==6.3.1
future==1.0.0
fvcore==0.1.5.post20221221
grpcio==1.70.0
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
huggingface-hub==0.29.1
humanfriendly==10.0
hydra-core==1.3.2
idna==3.10
imageio==2.37.0
imgaug==0.4.0
iopath==0.1.9
itsdangerous==2.2.0
Jinja2==3.1.5
jiter==0.8.2
jmespath==1.0.1
joblib==1.4.2
kiwisolver==1.4.8
lazy_loader==0.4
lmdb==1.6.2
loguru==0.7.3
lxml==5.3.1
magic-pdf==1.1.0
Markdown==3.7
MarkupSafe==3.0.2
matplotlib==3.10.0
more-itertools==10.6.0
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.16
mypy-extensions==1.0.0
networkx==3.4.2
numpy==1.26.4
omegaconf==2.3.0
onnxruntime==1.20.1
openai==1.64.0
opencv-contrib-python==4.6.0.66
opencv-python==4.6.0.66
opencv-python-headless==4.11.0.86
openpyxl==3.1.5
opt-einsum==3.3.0
packaging==24.2
paddleocr==2.7.3
paddlepaddle==2.6.1
pandas==2.2.3
pathspec==0.12.1
pdf2docx==0.5.8
pdfminer.six==20231228
pillow==11.1.0
platformdirs==4.3.6
portalocker==3.1.1
premailer==3.10.0
propcache==0.3.0
protobuf==5.29.3
psutil==7.0.0
py-cpuinfo==9.0.0
pyarrow==19.0.1
pyclipper==1.3.0.post6
pycocotools==2.0.8
pycparser==2.22
pycryptodome==3.21.0
pydantic==2.10.6
pydantic_core==2.27.2
PyMuPDF==1.24.14
pyparsing==3.2.1
python-dateutil==2.9.0.post0
python-docx==1.1.2
pytz==2025.1
PyYAML==6.0.2
rapid-table==1.0.3
RapidFuzz==3.12.1
rapidocr-onnxruntime==1.4.4
rapidocr-paddle==1.4.5
rarfile==4.2
regex==2024.11.6
requests==2.32.3
robust-downloader==0.0.2
s3transfer==0.11.2
safetensors==0.5.3
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.15.2
seaborn==0.13.2
shapely==2.0.7
simsimd==6.2.1
six==1.17.0
sniffio==1.3.1
soupsieve==2.6
stringzilla==3.12.0
struct-eqtable==0.3.2
sympy==1.13.3
tabulate==0.9.0
tensorboard==2.19.0
tensorboard-data-server==0.7.2
termcolor==2.5.0
thop==0.1.1.post2209072238
threadpoolctl==3.5.0
tifffile==2025.2.18
timm==0.9.16
tokenizers==0.19.1
tomli==2.2.1
torch==2.3.1
torchvision==0.18.1
tqdm==4.67.1
transformers==4.42.4
typing_extensions==4.12.2
tzdata==2025.1
ultralytics==8.3.80
ultralytics-thop==2.0.14
unimernet==0.2.3
urllib3==2.3.0
visualdl==2.5.3
Wand==0.6.13
wcwidth==0.2.13
webdataset==0.2.111
Werkzeug==3.1.3
xxhash==3.5.0
yacs==0.1.8
yarl==1.18.3

```

**Reply by geoHeil** [reply]
Looking at https://pypi.org/project/doclayout-yolo/#history it looks like 0.0.2 is not even available on pip - and pixi refuses - correctly. 

Am I understanding this correctly?

Why does pip still resolve ==0.0.2 is not 0.0.2b?

**Reply by nichmor** [reply]
could you add `doclayout_yolo = { version = ">=0.0.2b1" }` in your `pypi-dependencies`?

I've tried this pixi.toml and I was able to solve it

```
[project]
name = "foo"
version = "1.0.0"
description = "bar"
# authors = [{ name = "xx", email = "yy" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = ["osx-arm64"]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
ocr-mineru = { features = [
  "ocr-mineru",
  
], solve-group = "ocr-mineru", no-default-feature = true }

[tool.pixi.feature.ocr-mineru.dependencies]
python = "~=3.10.0"
pip = "*"

[tool.pixi.feature.ocr-mineru.pypi-dependencies]
magic-pdf = { version = ">1.0.0 ,<2", extras = ["full"] }
doclayout_yolo = { version = ">=0.0.2b1" }

[tool.pixi.feature.ocr-mineru.pypi-options]
extra-index-urls = ["https://wheels.myhloli.com"]

```

**Reply by geoHeil** [reply]
Why does:

```
doclayout_yolo = { version = ">=0.0.2,<0.1" }
```

fail but 

```
doclayout_yolo = { version = ">=0.0.2b1,<0.1" }
```

work?

**Reply by nichmor** [reply, marked as answer]
it is related to selecting pre-release versions during the solve. by default UV allows pre-release versions if all versions of a package are pre-release, or if the package has an explicit pre-release marker in its version requirements. 

so in this case we are using an explicit version selector to trigger this behaviour.

it is configurable in UV https://docs.astral.sh/uv/reference/settings/#prerelease


but we don't allow this configuration yet: https://github.com/prefix-dev/pixi/issues/1291#issuecomment-2310189570


also cross-related with this: https://github.com/prefix-dev/pixi/issues/1357

**Reply by geoHeil** [reply]
Thanks! This is already a big step forward. May I add a related follow-up question to finalize this discussion: Enabling the GPU support.


The GPU version sits here: https://paddle-whl.bj.bcebos.com/stable/cu123/paddlepaddle-gpu/paddlepaddle_gpu-3.0.0rc1-cp310-cp310-linux_x86_64.whl

A:

```
pixi shell -e ocr-mineru-gpu
python -m pip install paddlepaddle-gpu==3.0.0rc1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/
```

installs nicely and freezes to:

```
❯ pip freeze
alembic==1.13.1
annotated-types==0.6.0
anyio==4.8.0
astor==0.8.1
awscli==1.29.57
boto3==1.34.41
certifi==2024.12.14
click==8.1.7
colorama==0.4.4
coloredlogs==14.0
croniter==2.0.1
decorator==5.1.1
distro==1.8.0
docstring-parser==0.15
docutils==0.16
exceptiongroup==1.2.2
fsspec==2024.2.0
github3.py==4.0.1
greenlet==3.0.3
grpcio-health-checking==1.60.1
h11==0.14.0
httpcore==1.0.7
httpx==0.28.1
humanfriendly==10.0
idna==3.10
Jinja2==3.1.3
jmespath==1.0.1
Mako==1.3.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
networkx==3.4.2
numpy==2.2.1
nvidia-cublas-cu12==12.3.4.1
nvidia-cuda-cupti-cu12==12.3.101
nvidia-cuda-nvrtc-cu12==12.3.107
nvidia-cuda-runtime-cu12==12.3.101
nvidia-cudnn-cu12==9.1.1.17
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.4.127
opt-einsum==3.3.0
paddlepaddle-gpu==3.0.0rc1
pendulum==3.0.0
pex==2.1.163
pillow==11.1.0
protobuf==4.25.2
psycopg2-binary==2.9.9
pyasn1==0.5.0
pydantic_core==2.16.2
Pygments==2.16.1
PyJWT==2.8.0
python-dateutil==2.8.2
python-dotenv==1.0.1
pytz==2024.1
PyYAML==6.0.1
rich==13.6.0
rsa==4.7.2
shell_gpt==0.9.4
shellingham==1.5.4
six==1.16.0
sniffio==1.3.1
SQLAlchemy==2.0.27
structlog==24.1.0
tabulate==0.9.0
time-machine==2.13.0
tomli==2.0.1
toposort==1.10
typer==0.9.0
typing_extensions==4.8.0
tzdata==2024.1
universal_pathlib==0.2.0
uritemplate==4.1.1
urllib3==1.26.16
watchdog==4.0.0
wcwidth==0.2.13
```

```
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "xx", email = "yy" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = [ "linux-64"]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
ocr-mineru-gpu = { features = [
  "ocr-mineru-gpu",
  
], solve-group = "ocr-mineru-gpu", no-default-feature = true }

[tool.pixi.feature.ocr-mineru-gpu.pypi-options]
no-build-isolation = ["magic-pdf"]

[tool.pixi.feature.ocr-mineru-gpu]
platforms = [ "linux-64" ]
[tool.pixi.feature.ocr-mineru-gpu.dependencies]
python = "~=3.10.0"
pip = "*"
```

when trying via pixi:

```
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "xx", email = "yy" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = [ "linux-64"]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
ocr-mineru-gpu = { features = [
  "ocr-mineru-gpu",
  
], solve-group = "ocr-mineru-gpu", no-default-feature = true }

[tool.pixi.feature.ocr-mineru-gpu.pypi-options]
no-build-isolation = ["magic-pdf"]

[tool.pixi.feature.ocr-mineru-gpu]
platforms = [ "linux-64" ]
[tool.pixi.feature.ocr-mineru-gpu.dependencies]
python = "~=3.10.0"
pip = "*"

[tool.pixi.feature.ocr-mineru-gpu.pypi-dependencies]
#magic-pdf = { version = ">=1.2.0 ,<2", extras = ["full"] }
doclayout_yolo = { version = ">=0.0.2b1,<0.1" }
paddlepaddle-gpu = { version = ">=3.0.0rc1", index = "https://www.paddlepaddle.org.cn/packages/stable/cu123/" }
```

almost works.

However, when enabling:

```
magic-pdf = { version = ">=1.2.0 ,<2", extras = ["full"] }
```

the error is:

```
failed to solve the pypi requirements of 'ocr-mineru-gpu' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because there is no version of paddlepaddle{sys_platform == 'linux'}==3.0.0b1 and magic-pdf[full]>=1.0.1,<=1.1.0 depends on paddlepaddle{sys_platform == 'linux'}==3.0.0b1, we can conclude that magic-pdf[full]>=1.0.1,<=1.1.0 cannot be used.
      And because only the following versions of magic-pdf[full] are available:
          magic-pdf[full]<1.0.0
          magic-pdf[full]==1.0.1
          magic-pdf[full]==1.1.0
          magic-pdf[full]==1.2.0
      we can conclude that magic-pdf[full]>1.0.0,<1.1.0 cannot be used. (1)
      
      Because there is no version of paddlepaddle{sys_platform == 'linux'}==3.0.0b1 and magic-pdf[full]==1.1.0 depends on paddlepaddle{sys_platform == 'linux'}==3.0.0b1, we can conclude that magic-pdf[full]==1.1.0 cannot be used.
      And because we know from (1) that magic-pdf[full]>1.0.0,<1.1.0 cannot be used, we can conclude that magic-pdf[full]>1.0.0,<1.2.0 cannot be used. (2)
      
      Because there is no version of paddlepaddle{sys_platform == 'darwin' or sys_platform == 'linux'}==3.0.0rc1 and magic-pdf[full]==1.2.0 depends on paddlepaddle{sys_platform == 'darwin' or sys_platform == 'linux'}==3.0.0rc1, we can conclude that magic-pdf[full]==1.2.0 cannot be
      used.
      And because we know from (2) that magic-pdf[full]>1.0.0,<1.2.0 cannot be used, we can conclude that magic-pdf[full]>1.0.0 cannot be used.
      And because you require magic-pdf[full]>1.0.0, we can conclude that your requirements are unsatisfiable.
      
      hint: `paddlepaddle` was requested with a pre-release marker (e.g., paddlepaddle==3.0.0b1), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

**Reply by geoHeil** [reply]
## one more observation

I want to use python 3.12

Changes:

```toml
python = "~=3.12.0"
```

and

```toml
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", rev = "9604f5995cc628619f0e4fd913453b4d7d61db3f" }
torch = { version = ">=2.2.0,<2.7", index = "https://download.pytorch.org/whl/cpu" }
```

and


```toml
[tool.pixi.feature.ocr-mineru.pypi-options]
extra-index-urls = ["https://wheels.myhloli.com"]
no-build-isolation = ["detectron2"]
```

```toml
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "xx", email = "yy" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = ["osx-arm64", "linux-64", "linux-aarch64" ]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
ocr-mineru = { features = [
  "ocr-mineru",
], solve-group = "ocr-mineru", no-default-feature = true }

ocr-mineru-gpu = { features = [
  "ocr-mineru-gpu",
], solve-group = "ocr-mineru-gpu", no-default-feature = true }

[tool.pixi.feature.ocr-mineru.pypi-options]
extra-index-urls = ["https://wheels.myhloli.com"]
no-build-isolation = ["detectron2"]

[tool.pixi.feature.ocr-mineru]
# notice no windows
platforms = ["osx-arm64", "linux-64", "linux-aarch64" ]
[tool.pixi.feature.ocr-mineru.dependencies]
# TODO: get 3.12 to work.
python = "~=3.12.0"
pip = "*"

[tool.pixi.feature.ocr-mineru.pypi-dependencies]
magic-pdf = { version = ">1.0.0 ,<2", extras = ["full"] }
doclayout_yolo = { version = ">=0.0.2b1,<0.1" }
detectron2 = { git = "https://github.com/facebookresearch/detectron2.git", rev = "9604f5995cc628619f0e4fd913453b4d7d61db3f" }
# TODO set up GPU version
# https://download.pytorch.org/whl/cpu
# https://download.pytorch.org/whl/cu126
#torch = { version = ">=2.6.0,<2.7", index = "https://download.pytorch.org/whl/cpu" }
#torchvision = { version = ">=0.21.0,<0.22", index = "https://download.pytorch.org/whl/cpu" }
torch = { version = ">=2.2.0,<2.7", index = "https://download.pytorch.org/whl/cpu" }
paddlepaddle = { version = ">=3.0.0rc1,<3.1", index = "https://www.paddlepaddle.org.cn/packages/stable/cpu/" }


[tool.pixi.feature.ocr-mineru-gpu.pypi-options]
extra-index-urls = ["https://wheels.myhloli.com"]

[tool.pixi.feature.ocr-mineru-gpu]
# just need osx for convenient resolution
platforms = ["osx-arm64", "linux-64" ]
[tool.pixi.feature.ocr-mineru-gpu.dependencies]
python = "~=3.10.0"

[tool.pixi.feature.ocr-mineru-gpu.pypi-dependencies]
# TODO: fix GPUs to work: https://github.com/prefix-dev/pixi/discussions/3217#discussioncomment-12338215
# magic-pdf = { version = ">1.0.0 ,<2", extras = ["full"] }
doclayout_yolo = { version = ">=0.0.2b1,<0.1" }
[feature.research-basics.target.linux-64.dependencies]
paddlepaddle = { version = ">=3.0.0rc1,<3.1", index = "https://www.paddlepaddle.org.cn/packages/stable/cu123/" }
```

## observation

- osx resolves just fine
- linux  fails with:

```
Error: 
  × failed to solve the pypi requirements of 'ocr-mineru' 'linux-aarch64'
  ├─▶ Failed to build `detectron2 @ git+https://github.com/facebookresearch/detectron2.git@9604f5995cc628619f0e4fd913453b4d7d61db3f`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.prepare_metadata_for_build_wheel` failed (exit status: 1)
      
      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/data/raid5/data/heiler/foo/.pixi/envs/ocr-mineru/lib/python3.12/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/data/raid5/data/heiler/foo/.pixi/envs/ocr-mineru/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/data/raid5/data/heiler/foo/.pixi/envs/ocr-mineru/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      ModuleNotFoundError: No module named 'torch'
      
      hint: This error likely indicates that `detectron2 @ git+https://github.com/facebookresearch/detectron2.git@9604f5995cc628619f0e4fd913453b4d7d61db3f` depends on `torch`, but
      doesn't declare it as a build dependency. If `detectron2 @ git+https://github.com/facebookresearch/detectron2.git@9604f5995cc628619f0e4fd913453b4d7d61db3f` is a first-party
      package, consider adding `torch` to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.
```

is this a bug?
