### DISCUSSION TITLE
Is there a command equivalent to "pip install -e ." for pixi?

### DISCUSSION THREAD

**Discussion by hanruiyao163** [prefix-dev/pixi#3292] [General]
Is there a command equivalent to "pip install -e ." for pixi?

**Comment by hanruiyao163** [comment]
and  what is the equivalent command to “pip install "sglang[all]>=0.4.3.post4" --find-links https://flashinfer.ai/whl/cu124/torch2.5/flashinfer-python”

**Comment by ruben-arts** [comment]
You can add an editable package with:
```toml
# [tool.pixi.pypi-dependencies] in pyproject.toml
[pypi-dependencies]
package = {path = ".", editable = true}
```

and the find-links can be added with:
```toml
# [tool.pixi.project.pypi-options] in pyproject.toml
[project.pypi-options]
find-links = [{ url = "https://flashinfer.ai/whl/cu124/torch2.5/flashinfer-python"]
```
