### DISCUSSION TITLE
Equivalent of conda entry points in `pixi.toml` when using `pixi build`

### DISCUSSION THREAD

**Discussion by EugenePlanteurCS** [prefix-dev/pixi#3424] [Q&A]
Hello, I'm working on converting a project from conda to pixi. Everything works out so far, but we want to still be able to build a conda package, that way users can choose either to `conda install` or clone the repo and run `pixi install`. This project is only supposed to be used as a CLI tool, using entry points. When using pixi, we can just convert them to pixi tasks, but what about when building a conda package ? 

Let's take a simple example project:

```
my_project
├── src
│   └── main.py
├── .gitignore
├── pixi.toml
└── meta.yaml
```

For example,  `meta.yaml` could contain:

```yaml
package:
  name: my_package
  version: 0.1.0

source:
  git_url: https://github.com/my_package
  git_rev: main

build:
    entry_points:
      - start = src.main:main
# ...
```
We can run `conda build meta.yaml` to build the corresponding conda package. Once installed in an evironment, one can use `start` to execute the `main.py` file.

The equivalent `pixi.toml` could look like this:
```toml
[project]
channels = ["conda-forge", "https://prefix.dev/pixi-build-backends"]
description = "Add a short description here"
name = "my_package"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[package]
name = "iota2_develop"
version = "20250325"

[package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }

[tasks]
"start" = "python $PIXI_PROJECT_ROOT/src/main.py"
# ...
```
In this case, we can then use `pixi run start` when installing it with `pixi install`. But if we use `pixi build` and install this package in a separate conda environment, there isn't really a "clean" way to call `main.py`. The easiest method would be to clone the project and run `python my_project/src/main.py`. I tried using the solution from [this discussion](https://github.com/prefix-dev/pixi/discussions/2392), but I get the following error:

```
Error:   × Unexpected keys, expected only 'name', 'version', 'description', 'authors', 'channels', 'channel-priority', 'platforms', 'license', 'license-file', 'readme', 'homepage', 'repository',  'documentation', 'conda-pypi-map', 'pypi-options', 's3-options', 'preview', 'target', 'build-variants'
    ╭─[.../my_project/pixi.toml:70:10]
 69 │ 
 70 │ [project.scripts]
    ·          ───┬───
    ·             ╰── 'scripts' was not expected here
 71 │ pkg_cli = "src.main:main"
    ╰────
  help: Did you mean 'description'?
```
So I'm guessing this section is only available for `project.toml` files, and not `pixi.toml` ? In any case, is there a "clean" way to implement entry points in the `pixi.toml`, when using `pixi build` ? I understand that `pixi build` is still heavily in development, so maybe this is something that will be added later?

Thanks !
