### DISCUSSION TITLE
How to debug code from pixi tasks?

### DISCUSSION THREAD

**Discussion by 0xorial** [prefix-dev/pixi#3554] [Q&A]
Hi! Perhaps I am missing something obvious, but is there a way to use debugpy for tasks definded in pixi.toml? It is quite convenient to define common project tasks there, and it would be convenient to debug them without having to copy-paste them somewhere else (I am using vscode)

**Comment by ruben-arts** [comment]
With a little argument and jinja magic you can do this now:
```toml
[tasks.test]
cmd = "{{'debugpy --listen 5678 --wait-for-client' if debugpy=='-d' or debugpy=='--debug' else 'python'}} main.py"
args = [{arg = "debugpy", default = ""}]
```

This example allows you to add `-d` or `--debug` to use `debugpy` instead of `python`. 

Tip, you can play with minijinja templates (the task command) in https://mitsuhiko.github.io/minijinja-playground/
