### DISCUSSION TITLE
Using `pixi build` with hatch-vcs

### DISCUSSION THREAD

**Discussion by ollyhensby** [prefix-dev/pixi#3827] [General]
My project is setup to use hatch-vcs:

```toml
[tool.hatch.version]
source = "vcs"
raw-options = { root = "../.." }
```

This gets the version from the git tags.

I want to use `pixi build` to build my package using hatch-vcs but I am struggling to get it to work. Currently, you have to explicitly define the version in the pixi.toml.

Any help with this is much appreciated!
