### DISCUSSION TITLE
pixi is unable to add a pypi dependency with features for specific platforms

### DISCUSSION THREAD

**Discussion by kratsg** [prefix-dev/pixi#3855] [Q&A]
```toml
[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "scipp-pixels-module-qc-monitoring"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[feature.rpi]
platforms = ["linux-aarch64"]

[feature.rpi.dependencies]
python = ">=3.7,<3.11"

[feature.daq]
platforms = ["linux-64"]

[feature.daq.dependencies]
python = ">=3.7,<3.11"

[environments.rpi]
features = ["rpi"]

[environments.daq]
features = ["daq"]
```

and then running

```
$ pixi add --pypi -f rpi 'adafruit-circuitpython-bitbangio==1.3.0'
Error:   × Unable to solve pypi dependencies for the rpi environment because no compatible python interpreter can be installed for the current
  │ platform
  help: Try converting your [pypi-dependencies] to conda [dependencies]
```

just does not work. In fact, running anything like

```
$ pixi add --pypi -f rpi numpy
Error:   × Unable to solve pypi dependencies for the rpi environment because no compatible python interpreter can be installed for the current
  │ platform
  help: Try converting your [pypi-dependencies] to conda [dependencies]
```

also does not work. This seems to be limited to just `--pypi` flag added which does not seem to let `pixi` resolve things properly.

**Comment by kratsg** [comment]
This version works

```toml
[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "scipp-pixels-module-qc-monitoring"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.7,<3.11"

[pypi-dependencies]
adafruit-circuitpython-bitbangio = "==1.3.0"
```

but it seems I will need to have separate `pixi` configurations for two different features.

**Comment by matthewfeickert** [comment]
@kratsg You can define platform specific targets for each feature:

```toml
[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "scipp-pixels-module-qc-monitoring"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[feature.rpi.target.linux-aarch64.dependencies]
python = ">=3.7,<3.11"

[feature.daq.target.linux-64.dependencies]
python = ">=3.7,<3.11"

[environments.rpi]
features = ["rpi"]

[environments.daq]
features = ["daq"]
```

This manifest solves and on my `linux-64` machine correctly gives me

```console
$ pixi list --environment rpi  # Has environment locked but correctly doesn't install as wrong platform
Error:   × ✘ No packages found in 'rpi' environment for 'linux-64' platform.

$ pixi list --environment rpi --platform linux-aarch64  # Specifying the target platform allows to show what would be installed if I was on that platform machine
Environment: rpi
Package                Version    Build               Size       Kind   Source
_openmp_mutex          4.5        2_gnu               23.2 KiB   conda  https://conda.anaconda.org/conda-forge/
bzip2                  1.0.8      h68df207_7          185.4 KiB  conda  https://conda.anaconda.org/conda-forge/
ca-certificates        2025.4.26  hbd8a1cb_0          148.7 KiB  conda  https://conda.anaconda.org/conda-forge/
ld_impl_linux-aarch64  2.43       h80caac9_4          682.7 KiB  conda  https://conda.anaconda.org/conda-forge/
libexpat               2.7.0      h5ad3122_0          71.4 KiB   conda  https://conda.anaconda.org/conda-forge/
libffi                 3.4.6      he21f813_1          54.5 KiB   conda  https://conda.anaconda.org/conda-forge/
libgcc                 15.1.0     he277a41_2          504.6 KiB  conda  https://conda.anaconda.org/conda-forge/
libgcc-ng              15.1.0     he9431aa_2          34 KiB     conda  https://conda.anaconda.org/conda-forge/
libgomp                15.1.0     he277a41_2          445.4 KiB  conda  https://conda.anaconda.org/conda-forge/
liblzma                5.8.1      h86ecc28_1          122 KiB    conda  https://conda.anaconda.org/conda-forge/
libnsl                 2.0.1      h31becfc_0          33.7 KiB   conda  https://conda.anaconda.org/conda-forge/
libsqlite              3.49.2     h5eb1b54_0          893.8 KiB  conda  https://conda.anaconda.org/conda-forge/
libuuid                2.38.1     hb4cce97_0          34.9 KiB   conda  https://conda.anaconda.org/conda-forge/
libxcrypt              4.4.36     h31becfc_1          111.6 KiB  conda  https://conda.anaconda.org/conda-forge/
libzlib                1.3.1      h86ecc28_2          65.1 KiB   conda  https://conda.anaconda.org/conda-forge/
ncurses                6.5        ha32ae93_3          904.3 KiB  conda  https://conda.anaconda.org/conda-forge/
openssl                3.5.0      hd08dc88_1          3.5 MiB    conda  https://conda.anaconda.org/conda-forge/
python                 3.10.17    h256493d_0_cpython  12.4 MiB   conda  https://conda.anaconda.org/conda-forge/
readline               8.2        h8382b9d_2          285 KiB    conda  https://conda.anaconda.org/conda-forge/
tk                     8.6.13     h194ca79_0          3.2 MiB    conda  https://conda.anaconda.org/conda-forge/
tzdata                 2025b      h78e105d_0          120.1 KiB  conda  https://conda.anaconda.org/conda-forge/
$ pixi list --environment daq  # environment and my machine's platform match and so is installed
Environment: daq
Package           Version    Build               Size       Kind   Source
_libgcc_mutex     0.1        conda_forge         2.5 KiB    conda  https://conda.anaconda.org/conda-forge/
_openmp_mutex     4.5        2_gnu               23.1 KiB   conda  https://conda.anaconda.org/conda-forge/
bzip2             1.0.8      h4bc722e_7          246.9 KiB  conda  https://conda.anaconda.org/conda-forge/
ca-certificates   2025.4.26  hbd8a1cb_0          148.7 KiB  conda  https://conda.anaconda.org/conda-forge/
ld_impl_linux-64  2.43       h712a8e2_4          655.5 KiB  conda  https://conda.anaconda.org/conda-forge/
libexpat          2.7.0      h5888daf_0          72.7 KiB   conda  https://conda.anaconda.org/conda-forge/
libffi            3.4.6      h2dba641_1          56.1 KiB   conda  https://conda.anaconda.org/conda-forge/
libgcc            15.1.0     h767d61c_2          809.7 KiB  conda  https://conda.anaconda.org/conda-forge/
libgcc-ng         15.1.0     h69a702a_2          33.8 KiB   conda  https://conda.anaconda.org/conda-forge/
libgomp           15.1.0     h767d61c_2          442 KiB    conda  https://conda.anaconda.org/conda-forge/
liblzma           5.8.1      hb9d3cd8_1          110.2 KiB  conda  https://conda.anaconda.org/conda-forge/
libnsl            2.0.1      hd590300_0          32.6 KiB   conda  https://conda.anaconda.org/conda-forge/
libsqlite         3.49.2     hee588c1_0          894.8 KiB  conda  https://conda.anaconda.org/conda-forge/
libuuid           2.38.1     h0b41bf4_0          32.8 KiB   conda  https://conda.anaconda.org/conda-forge/
libxcrypt         4.4.36     hd590300_1          98 KiB     conda  https://conda.anaconda.org/conda-forge/
libzlib           1.3.1      hb9d3cd8_2          59.5 KiB   conda  https://conda.anaconda.org/conda-forge/
ncurses           6.5        h2d0b736_3          870.7 KiB  conda  https://conda.anaconda.org/conda-forge/
openssl           3.5.0      h7b32b05_1          3 MiB      conda  https://conda.anaconda.org/conda-forge/
python            3.10.17    hd6af730_0_cpython  23.9 MiB   conda  https://conda.anaconda.org/conda-forge/
readline          8.2        h8c095d6_2          275.9 KiB  conda  https://conda.anaconda.org/conda-forge/
tk                8.6.13     noxft_h4845f30_101  3.2 MiB    conda  https://conda.anaconda.org/conda-forge/
tzdata            2025b      h78e105d_0          120.1 KiB  conda  https://conda.anaconda.org/conda-forge/
```

**Reply by matthewfeickert** [reply]
@kratsg to be more useful, here's a working manifest for the example you showed me earlier today that uses [`adafruit-circuitpython-bitbangio`](https://pypi.org/project/adafruit-circuitpython-bitbangio/) and [`RPi.GPIO`](https://pypi.org/project/RPi.GPIO/)

```toml
[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "scipp-pixels-module-qc-monitoring"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.7,<3.11"

[feature.rpi.target.linux-aarch64.pypi-dependencies]
adafruit-circuitpython-bitbangio = "==1.3.0"
rpi-gpio = "==0.7.1"

[feature.daq.target.linux-64.dependencies]
# This actually isn't needed, but just keeping it in so that daq isn't empty
python = ">=3.7,<3.11"

[environments.rpi]
features = ["rpi"]

[environments.daq]
features = ["daq"]
```

**Reply by kratsg** [reply]
@But this seems to allow for `linux-64` with the `rpi` target when I want to restrict the platforms. So this isn't really equivalent.

**Reply by kratsg** [reply]
Also not sure how you get to that, when the toml above was created using pixi's command line. So I somehow got into a situation that it broke itself on some level, or just was unable to proceed further, when at first glance, the original `toml` file seems ok? Is there a reason dependencies has to be defined at the level of target, rather than using platforms?

**Reply by matthewfeickert** [reply]
> but this seems to allow for `linux-64` with the `rpi` target when I want to restrict the platforms. So this isn't really equivalent.

@kratsg Can you explain in more detail what you mean? The only thing that https://github.com/prefix-dev/pixi/discussions/3855#discussioncomment-13288806 would do (differently than https://github.com/prefix-dev/pixi/discussions/3855#discussioncomment-13288561) is allow for Python to exist in the `rpi` feature and that's it. You could get back to the 

```console
$ pixi list --environment rpi --platform linux-64
Error:   × ✘ No packages found in 'rpi' environment for 'linux-64' platform.
```

behavior easily be just not defining Python in the default feature/environment.

Can you explain what behavior you want to have happen?

> Also not sure how you get to that, when the toml above was created using pixi's command line. So I somehow got into a situation that it broke itself on some level, or just was unable to proceed further, when at first glance, the original `toml` file seems ok?

I don't think I understand what this means. Can you elaborate? 

> Is there a reason dependencies has to be defined at the level of target, rather than using platforms?

The distinction here seems artificial, given that the [`target` table is a table of target platforms](https://pixi.sh/latest/reference/pixi_manifest/#the-target-table) with possible sub-tables. However, that's a good question and I'm not quite sure.

I would agree that

```toml
[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "scipp-pixels-module-qc-monitoring"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.7,<3.11"

[feature.rpi]
platforms = ["linux-aarch64"]

[feature.rpi.pypi-dependencies]
adafruit-circuitpython-bitbangio = "==1.3.0"
rpi-gpio = "==0.7.1"

[feature.daq]
platforms = ["linux-64"]

[feature.daq.dependencies]
python = ">=3.7,<3.11"

[environments.rpi]
features = ["rpi"]

[environments.daq]
features = ["daq"]
```

seems like it should be a valid manifest and equivalent to the one I gave in https://github.com/prefix-dev/pixi/discussions/3855#discussioncomment-13288806 but it fails with

```console
$ pixi lock
Error:   × Unable to solve pypi dependencies for the rpi environment because no compatible python interpreter can be installed for the current platform
  help: Try converting your [pypi-dependencies] to conda [dependencies]

```

so I agree that _this_ seems like it should be a bug (that I'd suggest you raise an Issue for) given the current (`v0.47.0`) [docs on the `feature` table](https://pixi.sh/v0.47.0/reference/pixi_manifest/#the-feature-table).
