### DISCUSSION TITLE
How to get instantiated dependencies with versions with `pixi add` for a feature when an environment hasn't been created yet?

### DISCUSSION THREAD

**Discussion by matthewfeickert** [prefix-dev/pixi#3944] [Q&A] [answered]
Is it possible from the `pixi` command line to add a dependency to a feature to an environment and get a solved environment with constraints if the environment doesn't exist yet without rerunning the `pixi add` command? This question is somewhat artificial as you can write a Pixi manifest by hand that achieves this, but I'm trying to do this all from the command line as this has come up in teaching Pixi where students find the Pixi CLI a useful tool for navigating the Pixi manifest.

I'm going to do this all from the command line as this is how students I'm teaching do most things. To demonstrate the question I'm going to show in steps: command line actions, their output, and the effect on a Pixi manifest.

First, let's make a Pixi workspace.

```console
$ pixi init example
✔ Created /tmp/example/pixi.toml
$ cd example
```

Let's add `pytorch-cpu` to a `cpu` feature.

```console
$ pixi add --feature cpu pytorch-cpu
✔ Added pytorch-cpu
Added these only for feature: cpu
```

```toml
[workspace]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.cpu.dependencies]
pytorch-cpu = "*"
```

Here we see that `pytorch-cpu` doesn't have any instantiated versions yet, as it exists only in a feature but not in an environment where it can actually be installed. Now that a `cpu` feature exists we can create an environment (as you can't create a non-empty environment from the command line without providing features)

```console
$ pixi workspace environment add --feature cpu cpu
✔ Added environment cpu
```

```toml
[workspace]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.cpu.dependencies]
pytorch-cpu = "*"

[environments]
cpu = ["cpu"]
```

If we now rerun the command to add `pytorch-cpu` to the `cpu` feature then, as the feature now has an environment, the solve will result in realized conditions and a solved environment

```console
$ pixi add --feature cpu pytorch-cpu
✔ Added pytorch-cpu >=1.6.0,<2
Added these only for feature: cpu
```

```toml
[workspace]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.cpu.dependencies]
pytorch-cpu = ">=1.6.0,<2"

[environments]
cpu = ["cpu"]
```

Is it possible to reach this without having to rerun the `add` command?

```console
$ pixi init example
$ cd example
$ pixi add --feature cpu pytorch-cpu
$ pixi workspace environment add --feature cpu cpu
$ pixi add --feature cpu pytorch-cpu
```

We can't just flip the order, as that results in errors.

**Comment by matthewfeickert** [comment, marked as answer]
@Hofer-Julian points out in Discord that [`pixi upgrade`](https://pixi.sh/latest/reference/cli/pixi/upgrade/) does this.

Example:

```console
$ pixi init example
$ cd example
$ pixi add --feature cpu pytorch-cpu
$ pixi workspace environment add --feature cpu cpu
$ pixi upgrade --feature cpu pytorch-cpu
```

resolves as

```toml
[workspace]
channels = ["conda-forge"]
name = "example"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.cpu.dependencies]
pytorch-cpu = ">=1.6.0,<2"

[environments]
cpu = ["cpu"]
```

Calling `upgrade` at the end seems slightly unintuitive, but I guess that's force things to be resolved by asking it to upgrade given that `pixi upgrade`

https://github.com/prefix-dev/pixi/blob/104461262e47a70cf76a9d1ff0604666c01465a3/docs/reference/cli/pixi/upgrade.md?plain=1#L5

Though I'm not sure why it ends up with different version bounds then the `add` approach.
