### DISCUSSION TITLE
Whats the best practices in Task(cache or download file)

### DISCUSSION THREAD

**Discussion by baka-gourd** [prefix-dev/pixi#3982] [Q&A]
for example
```toml
[tasks.download-jdk]
cmd = "wget --output-document=OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.7%2B6/OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz"
outputs = ["OpenJDK21U-jdk_x64_linux_hotspot_21.0.7_6.tar.gz"]
```

The task has cache function, but this does not seem to work properly.

If the output already exists, it will not be skipped because the file already exists in a new environment where the task has never been run before, but will be downloaded again. At the same time, if the file is removed, it does not seem to be able to detect that the file has been removed, resulting in the file not actually being downloaded.

Does anyone have any better ideas?
