### DISCUSSION TITLE
How to use pixi inside scripts or Dockerfiles

### DISCUSSION THREAD

**Discussion by bcm0** [prefix-dev/pixi#690] [Q&A] [answered]
Hey, using conda or pixi inside a Dockerfile or bash script is still too hard.
Can I download pixi, create a pixi environment and activate it in a single bash script?
This is an important use case and it should be easy.

How to avoid repeating `pixi run` over and over inside a Dockerfile or bash script?

> You cannot globally activate a shell like you can with mamba/micromamba. 
https://github.com/prefix-dev/pixi/discussions/303

Pixi can make important improvements to conda in terms of usability
https://github.com/conda/conda/issues/7980
https://github.com/conda/conda/issues/13002

**Comment by ruben-arts** [comment, marked as answer]
He @bcm0,

If I understand correctly you are looking for `pixi shell-hook` which is a command that will ship with the next release. (or you try the main branch right now)

This would allow you to get the actual bash script to activate an environment directly. 

```
$ pixi init test && cd test

$ pixi add python

$ pixi shell-hook > hook.sh

# Now you can remove pixi completely

$ source hook.sh

$ python
# now you will run the pixi installed python from your "test" project
>>> 
```

**Reply by bcm0** [reply]
Your solution works well, thank you. Can I undo `source hook.sh`?

**Reply by ruben-arts** [reply]
Great!

> Can I undo source hook.sh?

No we're currently not supporting that, for that workflow you can use the `pixi shell` which deactivates when you run `exit`.

**Comment by pavelzw** [comment]
I'm currently using this docker configuration with pixi. It includes synced prod/test environments which makes sure that you are actually testing against the same versions that you use in production.
(works with the newest pixi version from `main` / the one after `v0.13.0`)

The two-step docker image ensures that _only_ the actual environment and not pixi is in the production image. This saves a couple of MB when shipping.

```toml
[project]
name = "pixi-proj"
description = "pixi proj"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64"]

[dependencies]
python = ">=3.8"

[host-dependencies]
pip = "*"

[feature.test.dependencies]
pytest = ">=6"
[feature.test.tasks]
test = "pytest"

[feature.build.dependencies]
build = "*"
hatchling = "*"
[feature.build.tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
build-wheel = "python -m build --no-isolation ."

[feature.prod.tasks]
postinstall-production = "pip install --no-deps --disable-pip-version-check dist/pixi_proj-*.whl"

[environments]
# TODO: solve-group default + prod https://github.com/prefix-dev/pixi/issues/769
default = ["test", "build"]
build = ["build"]
prod = ["prod"]
```

```docker
FROM ubuntu:22.04 AS build
# TODO: FROM ghcr.io/prefix-dev/pixi:0.13.0 AS build
RUN apt update && apt install -y curl git
RUN curl -Ls "https://github.com/prefix-dev/pixi/releases/latest/download/pixi-$(uname -m)-unknown-linux-musl" \
    -o /usr/local/bin/pixi \
    && chmod +x /usr/local/bin/pixi

COPY . /app
WORKDIR /app
RUN pixi run -e build build-wheel
RUN pixi install -e prod
RUN pixi run -e prod postinstall-production
RUN pixi shell-hook -e prod > /shell-hook
# https://github.com/prefix-dev/pixi/issues/781
RUN echo "my-app" > /shell-hook

FROM ubuntu:22.04 AS production
COPY --from=build /app/.pixi/envs/prod /app/.pixi/envs/prod
COPY --from=build /shell-hook /shell-hook
WORKDIR /app
ENTRYPOINT ["/bin/sh", "/shell-hook"]
```
