### ISSUE TITLE
Separate pixi from rattler config in global configuration file

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1014]
```toml
# shared config for pixi and rattler-build
default_channels = ["conda-forge", "my-channel"]
[mirrors]
# ...

# pixi-only
[pixi]
use_ps1 = false

# rattler-build-only
[rattler-build]
# TBD
```
