### ISSUE TITLE
`run` keeps recreating the lock file

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#103]
The following project keeps recreating the lockfile on every `run`.

```toml
[project]
name = "recipe-model"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[commands]
generate = "python model.py"

[dependencies]
pydantic = "1.10.9.*"
ruff = "0.0.271.*"
black = "23.3.0.*"
```
