### ISSUE TITLE
0.17.0: `pixi list` doesn't work with projects that don't contain python

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1032]
```toml
[project]
name = "test-project"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[dependencies]
lucky-commit = "*"
```

```shell
❯ pixi install
✔ Project in /private/tmp/testpixi is ready to use!
/tmp/testpix 
❯ pixi list
  × could not resolve pypi dependencies because no python interpreter is added to the dependencies of the project.
  │ Make sure to add a python interpreter to the [dependencies] section of the pixi.toml, or run:
  │ 
  │     pixi add python
```

Would be nice to get a hotfix for this as projects using setup-pixi and no python now have red CI since setup-pixi runs `pixi list`.
