### ISSUE TITLE
`pixi install` installs all environment in multi env setting when pypi-dependency with `path` is used

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1046]
```toml
[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.9"
polars = ">=0.14.24,<0.21"

[pypi-dependencies]
test = {path = "."}

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
py39 = ["py39"]
py310 = ["py310"]
py311 = ["py311"]
py312 = ["py312"]
```

```
❯ rm -rf .pixi && oixi install
# ...
❯ ls .pixi/envs
default/ py310/   py311/   py312/   py39/
```

**Comment by baszalmstra** [comment]
I assume this always happens, regardless of the type of requirement. This is expected behavior because all environments have pypi-dependencies (inherited from the default feature). To be able to solve these pypi environments we need to install a python interpreter, this is done by first only installing the conda packages into their target prefixes.

**Comment by pavelzw** [comment]
Hmm, i guess this makes sense... But i still don't like this behavior as this will fill up your drive quite fast if you have a large number of environments that you want to test against 😅 
In [polarify](https://github.com/quantco/polarify) this totals to `3.6 GB` being used while the default environment (which is used in 99% of local development use cases) is only `309 MB` large.

**Comment by pavelzw** [comment]
Do you have envisioned another approach to get rid of `pixi run postinstall` that doesn't require all envs being installed?

**Comment by baszalmstra** [comment]
Ah I see your use case. The problem is that to determine the dependencies of your path based project we need python to execute the build backend. Since you have environments with different python versions, the only way to reliably  lock this is to invoke python. 

The only thing I can think of is that we dont need all conda dependencies to run python. However, some of them might be used by the build backend so its also not really clear which dependencies we can skip during this step..

**Comment by pavelzw** [comment]
> we need python to execute the build backend

it's probably not possible to let the pypi dependencies be evaluated by pixi because the build backend could theoretically do arbitrary stuff?
At least in polarify, the `pyproject.toml` doesn't contain anything that's not already in `pixi.toml`.

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
# ...
dependencies = [
    "polars >=0.14.24,<0.21",
]
```

Not sure what other shenanigans hatchling supports.
