### ISSUE TITLE
pypi path dependencies with illegal arguments in `pixi.toml` don't raise an error

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1065]
```toml
[pypi-dependencies]
my-package = {path = ".", this-key-doesnt-exist=false}
```

Pixi silently ignores `this-key-doesn't-exist`.
