### ISSUE TITLE
pixi add <channel>::<requirement> does not record the channel in pixi.toml

### ISSUE THREAD

**Issue by sapetnioc** [prefix-dev/pixi#1068]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Failing code:
```shell
mkdir /tmp/test
cd /tmp/test
pixi init -c pytorch -c conda-forge
pixi add 'conda-forge::libjpeg-turbo>=3.0.0'
pixi add 'rattler-build>=0.13'
```
Working code:
```shell
mkdir /tmp/test2
cd /tmp/test2
pixi init -c pytorch -c conda-forge
pixi add 'conda-forge::libjpeg-turbo>=3.0.0' 'rattler-build>=0.13'
```

### Issue description

The sample code is failing because the specification of a channel with `pixi add` do not record the channel in `pixi.toml`. The command
```shell
pixi add 'conda-forge::libjpeg-turbo>=3.0.0'
```
adds this in `pixi.toml`:
```toml
[dependencies]
libjpeg-turbo = ">=3.0.0"
```

### Expected behavior

Using `pixi add 'conda-forge::libjpeg-turbo>=3.0.0'` should produce the following dependency:

```toml
[dependencies]
libjpeg-turbo = { channel="conda-forge", version=">=3.0.0" }
```
