### ISSUE TITLE
Make pixi use build-backend dependencies from conda packages instead of uv build isolated variants

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1088]
### Problem description

https://github.com/prefix-dev/pixi/pull/1084#issuecomment-2027053618

In corporate environments, you might not have access to pypi but only a conda server.
It would be cool if pixi was able to lock the used build backends in the lockfile and use it from conda and not pypi when specifying source dependencies in `pypi-dependencies`.

In general, I think it would be beneficial to lock the used build-backends for reproducibility.

**Comment by pavelzw** [comment]
If we can't influence this, could we maybe get a `no-build-isolation` flag?

```toml
[pypi-dependencies]
my-package = {path = ".", editable = true, no-build-isolation = true}

[dependencies]
setuptools = "*"
setuptools-scm = "*"
```
