### ISSUE TITLE
Avoid having to specify the name twice when using pyproject.toml

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#1090]
### Problem description

With the new pyproject file format. When looking at an example:

```toml
[project]
name = "flask-hello-world-pyproject"
version = "0.1.0"
description = "Example how to get started with flask in a pixi environment."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["flask==2.*"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
name = "flask-hello-world-pyproject"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.tasks]
start = "python -m flask run --port=5050"
```

I think we should allow having the name in `[project]` section only, instead of having to specify it twice. Or is there some technicality that I'm missing :)?
