### ISSUE TITLE
custom pypi index

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1094]
### Problem description

I use self-hosted pypi within the company, and `uv` can set the pypi index through environment variables.

```bash
export UV_INDEX_URL=xxxx
export UV_EXTRA_INDEX_URL=xxxx
```

Since pixi uses uv to install pip-related packages, I hope this can be supported.

**Comment by olivier-lacroix** [comment]
We would need create that struct to pass it to uv

pub struct IndexLocations {
    index: Option<IndexUrl>,
    extra_index: Vec<IndexUrl>,
    flat_index: Vec<FlatIndexLocation>,
    no_index: bool,
}

@tdejager , what would be your preference in terms of TOML configuration? a `pypi-index-location` table?

**Comment by zen-xu** [comment]
I think `pypi-options` would be more suitable.

**Comment by gzm55** [comment]
does this related with #906?

**Comment by baszalmstra** [comment]
Also related: https://github.com/prefix-dev/pixi/issues/588

**Comment by vigneshmanick** [comment]
also related to #1058

**Comment by tdejager** [comment]
@olivier-lacroix @gzm55 @zen-xu @vigneshmanick  Would it be fine to have this on the level of project similar to channels?

**Comment by vigneshmanick** [comment]
I am fine with the project level definition, but it would also be good if it can be defined **per** package similar to how the conda dependencies are mentioned in the current [documentation ](https://pixi.sh/latest/configuration/#dependencies). 

```toml
[dependencies]
vtk-osmesa = { version = "~=9.3", channel = "conda-forge" }
```

similar way for pypi should be

```toml
[pypi-dependencies]
vtk-osmesa = { version = "~=9.3", extra-index-url= "wheels.vtk.org" }
```

**Comment by gzm55** [comment]
> @olivier-lacroix @gzm55 @zen-xu @vigneshmanick Would it be fine to have this on the level of project similar to channels?

LGTM. both index-url and extra index-urls need to be set separately.

**Comment by tdejager** [comment]
> I am fine with the project level definition, but it would also be good if it can be defined **per** package similar to how the conda dependencies are mentioned in the current [documentation ](https://pixi.sh/latest/configuration/#dependencies).
> 
> ```toml
> [dependencies]
> vtk-osmesa = { version = "~=9.3", channel = "conda-forge" }
> ```
> 
> similar way for pypi should be
> 
> ```toml
> [pypi-dependencies]
> vtk-osmesa = { version = "~=9.3", extra-index-url= "wheels.vtk.org" }
> ```

That would be awesome I agree, I'm afraid that's technically more difficult because `uv` does not support such fine-grained selection (yet). We could do it on a feature level, like only use an extra-index-url for a specific feature.

**Comment by olivier-lacroix** [comment]
@tdejager project/ feature level settings mirroring the UV struct would be sufficient yes.

**Comment by zachcp** [comment]
Thank you @tdejager . Looking forward to this.   ( its the primary blocker for uptake in my company. )

**Comment by tdejager** [comment]
I'm now just thinking, all of these optional

```toml
[project]
...
[pypi-options]
# When not used, will use uv default which is just pypi
primary-index = "pypi.org/simple"
extra-indices = ["foo", "bar"]
flat-indices = ["path/to/index"]
```
@ruben-arts and others in-thread WDYT?
