### ISSUE TITLE
Add "commands"/"scripts"

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#11]
Just like with npm, add a section in a project manifest that lists several shortcut commands. E.g.

```toml
[project]
name = "myproject"

[commands]
test = "pytest ."
```

Invoking the command

```shell
pax run test
```

will execute the command `pytest .` in the environment.
