### ISSUE TITLE
pixi install stuck on some conda channels: e.g. rapidsai-nightly

### ISSUE THREAD

**Issue by j-bac** [prefix-dev/pixi#1107]
### Problem description

pixi install works for rapidsai channel but rapidsai-nightly hangs forever for linux-64

```
[project]
name = "test"
channels = ["rapidsai-nightly"]
platforms = ["linux-64"]

[system-requirements]
linux="4.18"
```

**Comment by wolfv** [comment]
That's quite weird - can you share what you are trying to install?

**Comment by j-bac** [comment]
rapids 24.04 which is needed for cuda=12.2 support ([https://docs.rapids.ai/install](https://docs.rapids.ai/install))

**Comment by ruben-arts** [comment]
I've dove into this, as this is not a usual setup but it is pretty interesting!

Based of the nightly build of `rapids` came to this conclusion for a `pixi.toml`:
```toml
[project]
name = "test"
channels = [ "rapidsai",  "rapidsai-nightly", "dask/label/dev", "pytorch", "nvidia", "conda-forge",]
platforms = ["linux-64"]

[system-requirements]
linux="4.18"
cuda = "12.2"

[dependencies]
rapids = {version = "*", channel = "rapidsai-nightly"}
```

But I see `pixi` reads `24.06` as `24.6`. I know @baszalmstra has spend significant time on this, so maybe he knows a way around this. 

Summary:
- Specify the need for `cuda` in the `[system-requirements]`
- Use all required channels, as there is no such thing yet as depending on other channels (Which would be really cool)
- Specify the required channel for a special build if you don't want to get everything from that channel and put the nightly channel after the main channel to avoid using the nightly packages for all available dependencies.

**Comment by j-bac** [comment]
Thanks, really appreciate the quick help! Indeed solves the weird problem of hanging forever on my side as well. It now fails for incompatibility error

**Comment by ruben-arts** [comment]
Yeah I'm not finding the right combination of packages to get from which channel. As most of our users have "conda-forge" and possibly one extra channels this isn't hard to debug but this case is pretty hard without knowning the background. 

Do you have the knowledge of which packages should come from which channels?

**Comment by j-bac** [comment]
This is what is printed when installing through conda
[conda_print.txt](https://github.com/prefix-dev/pixi/files/14849300/conda_print.txt)

**Comment by ruben-arts** [comment]
```toml
[project]
name = "test"
channels = [ "rapidsai-nightly",   "conda-forge" ]
platforms = ["linux-64"]

[system-requirements]
linux="4.18"
cuda = "12.2"

[dependencies]
rapids = {version = "24.04.*", channel = "rapidsai-nightly"}
python = "3.10.*"
cuda-version = "12.2.*"
cupy = {version = "13.0.*", channel = "conda-forge"}
ucx = {version = "1.15.*", channel = "conda-forge"}
datashader ={ version = "0.16.*", channel = "conda-forge"}
libcublas = {version = "12.*", channel = "conda-forge"}
nccl = {version = "2.20.*", channel = "conda-forge"}
```
With that conda example I could install it with these dependencies. The "problem" is that we hold a strict priority for the channels which you can only overwrite by specifying from which channel you want your dependencies. 

Do you know why rapids has such a larges set of the same packages as conda-forge?
