### ISSUE TITLE
Allow for the creation of a seperate pypi build environment

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#1110]
### Problem description

Currently we solve and install all environments that require a pypi solve as you need the correct python version to do the pypi solving. This also requires the rest of that environment to install as you might need some of the tools in order to build some `sdists`. This is a cool feature until you don't need all of the complete environments and you are downloading them for no reason. 

Imagine this project:
```toml
[project]
name = "bla"
platforms = ["linux-64"]
channels = ["conda-forge"]

[dependencies]
tensorflow = "*"

[pypi-dependencies]
ruff = "*"

[feature.py39.dependencies]
python = "3.9.*"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[environments]
py39 = ["py39"]
py310 = ["py310"]
py311 = ["py311"]
```
 All of these environments would be installed. That means you need to download 3 different version of `tensorflow` to be able to solve for `ruff`. Which on a slow internet connection could take minutes. 
 
 The ability to define a separate pypi build env would solve the slow installation problem here.
