### ISSUE TITLE
Expose UV `NoBuildIsolation` in some way

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#1124]
### Problem description

UV, like pip has the concept of `NoBuildIsolation` where it doesn't create a `venv` for building and it does not install requirements, these need to be installed.

Exposing this allows us to use conda dependencies for building.

The question mainly is how we want to expose this, @pavelzw suggested: https://github.com/prefix-dev/pixi/issues/1088#issuecomment-2027250661

```toml
[pypi-dependencies]
my-package = {path = ".", editable = true, no-build-isolation = true}

[dependencies]
setuptools = "*"
setuptools-scm = "*"
```

Because this is somwhat a global setting in UV to support it in this way we would need to create two seperate `BuildDispatch`'s to support this and two seperate `DistributionDatabase`s, and select which one to use somehow.

The easiest approach is to use a global `project` setting and then this is enabled for every **sdist** and every **editable**. This is quite brittle though, because if you use another sdist you might need to manually update your dependencies (to account for new build dependencies), as uv will no longer handle this.
