### ISSUE TITLE
Incorrect behaviour with `pixi add --feature --pypi`

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1133]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add --feature test --pypi ruff
pixi add --feature test ruff
```

### Issue description

the commands above will result in the following changes to `pixi.toml`

```toml
[feature.test.dependencies]
ruff = ">=0.3.5,<0.4"

[pypi-dependencies] # <- Incorrect since this is the wrong feature
ruff = "*"  
```
Adding a pypi dependency via cli places it incorrectly into the `default` feature instead of the specified feature. The same works correctly when adding without the `--pypi` argument. 

Also the version strings are different between the pypi and conda-forge variant. While the conda forge variant has the version range in the specification (`">=0.3.5,<0.4"`) the pypi variant has no modifier and is set to   `"*" ` 

NOTE: Adding the dependency manually by editing the `pixi.toml` file works correctly.

### Expected behavior

````toml
[feature.test.pypi-dependencies]
ruff = ">=0.3.5,<0.4"  

[feature.test.dependencies]
ruff = ">=0.3.5,<0.4"
````
