### ISSUE TITLE
Solve group but don't force the same version for specific dependencies / support hierarchical environment specifications

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1138]
### Problem description

In Deep Learning, you sometimes have the use case that you want to test dependencies using solve groups but want to support both cpu and gpu configurations.
Since there is a `pytorch=2.1.12=cuda...` and a `pytorch=2.1.12=cpu...` package, this is not possible with solve-groups at the moment.

```toml
[project]
name = "dl-project"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
pytorch = "2.1.2"

[feature.gpu.system-requirements]
cuda = "12.1"
[feature.gpu.dependencies]
pytorch = {build = "cuda*"}

[feature.cpu]
platforms = ["linux-64", "osx-arm64"]
[feature.cpu.dependencies]
pytorch = {build = "cpu*"}

[feature.dev.dependencies]
pytest = "*"
ruff = "*"

[environments]
dev-cpu = {features = ["cpu", "dev", "test"], solve-group = "cpu"}
prod-cpu = {features = ["cpu"], solve-group = "cpu"}

dev-gpu = {features = ["gpu", "dev", "test"], solve-group = "gpu"}
prod-gpu = {features = ["gpu"], solve-group = "gpu"}
```

This example has the problem that the GPU environments might behave differently than the CPU environments.
Therefore, we would like them to be in the same solve-group. This will fail unfortunately, because in one env, `pytorch 2.1.12 *cpu` is requested and in the other, `pytorch 2.1.12 *cuda` is requested.

One solution I could think of would be the following:

```toml
[solve-groups.prod]
ignore-dependencies = ["pytorch"]

[environments]
dev-cpu = {features = ["cpu", "dev", "test"], solve-group = "prod"}
prod-cpu = {features = ["cpu"], solve-group = "prod"}

dev-gpu = {features = ["gpu", "dev", "test"], solve-group = "prod"}
prod-gpu = {features = ["gpu"], solve-group = "prod"}
```

Which forces everything to be in the same solve-group except for `pytorch`.
I'm not 100% sure if this would be easily implementable with the current "put every requirement into one superset" approach, though.

WDYT? Do you have better ideas?
I think solving this would be a great improvement for deep learners.

**Comment by pavelzw** [comment]
Might be slightly related to this discussion https://github.com/prefix-dev/pixi/pull/584#discussion_r1433812282

**Comment by baszalmstra** [comment]
We could also experiment with tightly integrating multiple dependend environments in the solver perhaps. 🤔 

We could also use that when solving multiple platforms..

**Comment by pavelzw** [comment]
Environments depending on each other could solve the issue like this:

```toml
[environments]
_prod = {features = [], solve-group = "prod"}
_dev = {features = ["dev", "test"], solve-group = "prod"}

dev-cpu = {features = ["cpu", "dev", "test"], constraints = "_dev"}
prod-cpu = {features = ["cpu"], constraints = "_prod"}

dev-gpu = {features = ["gpu", "dev", "test"], constraints = "_dev"}
prod-gpu = {features = ["gpu"], constraints = "_prod"}
```

or

```toml
[environments]
_prod = {features = [], solve-group = "prod"}
_dev = {features = ["dev", "test"], solve-group = "prod"}

dev-cpu = {features = ["cpu"], depends-on = "_dev"}
prod-cpu = {features = ["cpu"], depends-on = "_prod"}

dev-gpu = {features = ["gpu"], depends-on = "_dev"}
prod-gpu = {features = ["gpu"], depends-on = "_prod"}
```
