### ISSUE TITLE
Unexpected behavior of missing/changed task `inputs`and `outputs`

### ISSUE THREAD

**Issue by bollwyvl** [prefix-dev/pixi#1139]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
# pixi.toml
[project]
name = "foo"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
sqlite = "*"

[tasks.preflight]
inputs = ["pixi.toml"]
outputs = ["build/preflight.txt", "build/preflight.txt"]
cmd = """
    mkdir -p build
    && cd build
    && echo "$(date) preflight" > preflight.txt
    && echo "$(date) preflight extra" > preflight-extra.txt
    """

[tasks.build]
inputs = ["build/preflight.txt"]
outputs = ["build/built.txt"]
cwd = "build"
cmd = """
    cat preflight.txt > built.txt
    && sleep 1
    && echo "$(date) built" >> built.txt
    """

[tasks.test]
inputs = ["build/built.txt"]
outputs = ["build/test.txt"]
cwd = "build"
cmd = """
    rm -f test.txt
    && cat built.txt > test.txt
    && sleep 1
    && echo "$(date) tested" >> test.txt
    """

[tasks.clean]
cmd = ["rm", "-rf", "build"]


### Issue description

The above graph works for the manual "happy path":

```bash 
$> pixi run preflight && pixi run build && pixi run test
✨ Pixi task (default):     rm -f build/preflight.txt
        && mkdir -p build
        && cd build
        && touch preflight.txt preflight-extra.txt

✨ Pixi task (default):     rm -f built.txt
        && cat preflight.txt > built.txt

✨ Pixi task (default): cat built.txt > test.txt
```

But fails in unexpected ways with most other invocations:

```bash
$> pixi run clean && pixi run test
✨ Pixi task (default): rm -rf build
✨ Pixi task (default): cat built.txt > test.txt
  × invalid working directory 'build'
```

> would have expected the same amount of work as as above

### Expected behavior

I guess my mental model of `inputs` and `outputs` is something like, given the
above graph:

```mermaid
flowchart LR
pixi.toml -- inputs --> preflight -- outputs --> preflight.txt & preflight-extra.txt
preflight.txt -- inputs --> build -- outputs --> built.txt
built.txt -- inputs --> test -- outputs --> test.txt
```

> aside: `pixi task list --status --files --markdown >> $GITHUB_STEP_SUMMARY` would be _amazing_

Where deleting a _file_ would either mark a _task_ as directly invalidated (❌) 
or indeterminate (❓), since the parent state is unknown:

| _file_                |   _task_    |         |        |         |
| --------------------- | :---------: | :-----: | :----: | :-----: |
|                       | `preflight` | `build` | `test` | `clean` |
| `pixi.toml`           |     ❌      |   ❓    |   ❓   |         |
| `preflight.txt`       |     ❌      |   ❌    |   ❓   |         |
| `preflight-extra.txt` |     ❌      |   ❓    |   ❓   |         |
| `built.txt`           |             |   ❌    |   ❌   |         |
| `test.txt`            |             |         |   ❌   |         |

Running a goal task would first ensure all of the parent tasks were valid, and not even bother checking e.g. `cwd`.

I also see `depends_on` is a thing, but _requires_ double-encoding of both a concrete file name _and_ a semantic name feels very unsatisfying.

**Comment by bollwyvl** [comment]
Oh, and got a bit wrapped around the form input: thanks for `pixi`, and congrats on the recent big feature releases! :heart_eyes_cat:

**Comment by ruben-arts** [comment]
He @bollwyvl, very nice issue report!

I think there is a misunderstanding of the feature of `inputs` and `outputs`. I'm not sure if it is the naming or the documentation but they're not used for task graph generation. Only the `depends_on` will create a graph. The `inputs` and `outputs` are only used to define caching for the task. 

```toml
[tasks.build]
inputs = ["build/preflight.txt"]
outputs = ["build/built.txt"]
cwd = "build"
cmd = """
    cat preflight.txt > built.txt
    && sleep 1
    && echo "$(date) built" >> built.txt
    """
depends_on = ["preflight"] # <<<

[tasks.test]
inputs = ["build/built.txt"]
outputs = ["build/test.txt"]
cwd = "build"
cmd = """
    rm -f test.txt
    && cat built.txt > test.txt
    && sleep 1
    && echo "$(date) tested" >> test.txt
    """
depends_on = ["build"] # <<<
```
Adding these two depends on creates the required graph.

Ps. I like the idea to generate mermaid graphs from the task definitions. :star_struck:
