### ISSUE TITLE
Pre/Post install commands to run

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1146]
### Pre/Post install scripts to run

When creating an environment i would like to be able to execute some tasks pre and post install (`pixi install`) .

For example,  consider the following project 

```toml
[project]
name = "project-name"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "*"
nodejs = "*"
```

Now after this projct is created and installed, it requires additional nodejs dependencies which can only be installed via `npm` command.  e.g `npm install sax` and before installation via npm the contents of a folder should have clean git history

This could be achieved by using the `tasks` section by using fixed keywords for `depends_on`.  For example,  `pre-install` and `post-install`

```toml
[tasks]
cleanup = {cmd= "git clean -xdff", depends_on="pre-install", cwd="npm_proj"}
npm-deps= { cmd="npm install sax", depends_on="post-install", cwd="npm_proj"}

```

The same will also work when the tasks are defined on a feature level

```toml
[feature.node.tasks]
cleanup = {cmd= "git clean -xdff", depends_on="pre-install", cwd="npm_proj"}
npm-deps= { cmd="npm install sax", depends_on="post-install", cwd="npm_proj"}

[environments]
node= ["node"]
```
