### ISSUE TITLE
Allow (or always) ignore checksum for editable dependencies

### ISSUE THREAD

**Issue by garymm** [prefix-dev/pixi#1151]
### Problem description

Here's my repo structure:
```
repo/
.
├── pixi.toml
├── non-python-code
└── foo-python-code
```

And in my pixi.toml I have:
```toml
[pypi-dependencies]
foo-python-code = { path = "./foo-python-code", editable = true }
```

This works fine, except everytime that I update any python code, I have to update `pixi.lock` because the checksum changes.

It seems like ignoring the checksum is now the default behavior for some cases (https://github.com/prefix-dev/pixi/issues/1083), so it seems natural for it to be extended to all editable dependencies.
