### ISSUE TITLE
cxx-compiler not activated properly on Windows due to mounted folder

### ISSUE THREAD

**Issue by beenje** [prefix-dev/pixi#1162]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I haven't managed to compile a C++ project on Windows with pixi.
I have Visual Studio 2019 build tools installed.

Tested with the `cpp-sdl` example from pixi repo: https://github.com/prefix-dev/pixi/tree/main/examples/cpp-sdl

```toml
[project]
name = "sdl_example"
version = "0.1.0"
description = "Showcases how to create a simple C++ executable with Pixi"
authors = ["Bas Zalmstra <bas@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks.start]
# Start the built executable
cmd = ".build/bin/sdl_example"
depends_on = ["build"]

[dependencies]
sdl2 = "2.26.5.*"

[feature.build.dependencies]
cmake = "3.26.4.*"
cxx-compiler = "1.5.2.*"
ninja = "1.11.1.*"

[feature.build.tasks.configure]
# Configures CMake
cmd = [
    "cmake",
    # Use the cross-platform Ninja generator
    "-GNinja",
    # The source is in the root directory
    "-S.",
    # We wanna build in the .build directory
    "-B.build",
]
inputs = ["CMakeLists.txt"]
outputs = [".build/CMakeFiles/"]

# Build the executable but make sure CMake is configured first.
[feature.build.tasks.build]
cmd = ["cmake", "--build", ".build"]
depends_on = ["configure"]
inputs = [
    "CMakeLists.txt",
    "src/*"
]
outputs = [
    ".build/bin/sdl_example"
]

[environments]
build = ["build"]
```

### Issue description

pixi can't find the compiler.

```shell
Z:\Windows\pixi\examples\cpp-sdl>pixi run configure
Pixi task (build): cmake -GNinja -S. -B.build
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
```

```shell
Z:\Windows\pixi\examples\cpp-sdl>pixi info
      Pixi version: 0.19.0
          Platform: win-64
  Virtual packages: __win=0=0
                  : __archspec=1=x86_64_v4
         Cache dir: C:\Users\beenj\AppData\Local\rattler/cache
      Auth storage: C:\Users\beenj\.rattler\credentials.json

Project
------------
           Version: 0.1.0
     Manifest file: Z:\Windows\pixi\examples\cpp-sdl\pixi.toml
  Config locations:
      Last updated: 11-04-2024 08:09:26

Environments
------------
       Environment: default
          Features: default
          Channels: conda-forge
  Dependency count: 1
      Dependencies: sdl2
  Target platforms: linux-64, win-64, osx-64, osx-arm64
             Tasks: start

       Environment: build
          Features: build, default
          Channels: conda-forge
  Dependency count: 4
      Dependencies: cmake, cxx-compiler, ninja, sdl2
  Target platforms: osx-64, osx-arm64, linux-64, win-64
             Tasks: start, configure, build
```

### Expected behavior

When running the same command in a conda env, compilation works without issue:

```shell
 C:\Users\beenj>mamba create -y -n cpp-sdl sdl2="2.26.5.*" cmake="3.26.4.*" cxx-compiler="1.5.2.*" ninja="1.11.1.*"
 C:\Users\beenj>mamba activate cpp-sdl
(cpp-sdl) Z:\Windows\pixi\examples\cpp-sdl>cmake -GNinja -S. -Bbuild
-- The C compiler identification is MSVC 19.29.30148.0
-- The CXX compiler identification is MSVC 19.29.30148.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (5.4s)
-- Generating done (0.1s)
-- Build files have been written to: Z:/Windows/pixi/examples/cpp-sdl/build
```

`mamba activate` is setting many variables via `<env>/etc/conda/activate.d/vs2019_compiler_vars.bat`.

```shell
CC=cl.exe
CMAKE_ARGS=-DCMAKE_BUILD_TYPE=Release
CMAKE_GEN=Visual Studio 16 2019
CMAKE_GENERATOR=Visual Studio 16 2019
CMAKE_GENERATOR_PLATFORM=x64
CMAKE_GENERATOR_TOOLSET=v142
CMAKE_PLAT=x64
ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
Framework40Version=v4.0
FrameworkDir64=C:\Windows\Microsoft.NET\Framework64\
FrameworkDir=C:\Windows\Microsoft.NET\Framework64\
FrameworkVersion64=v4.0.30319
FrameworkVersion=v4.0.30319
USE_NEW_CMAKE_GEN_SYNTAX=1
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
VCIDEInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\
VCToolsInstallDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\
VCToolsRedistDir=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Redist\MSVC\14.29.30133\
VCToolsVersion=14.29.30133
VCVARSBAT=64
VS160COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\
VSCMD_ARG_HOST_ARCH=x64
VSCMD_ARG_TGT_ARCH=x64
VSCMD_ARG_VCVARS_VER=14.29
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_winsdk=10.0.19041.0
VSCMD_VER=16.11.25
VSINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\
VS_MAJOR=16
VS_VERSION=16.0
VS_YEAR=2019
VisualStudioVersion=16.0
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0
WindowsSDKLibVersion=10.0.19041.0\
WindowsSDKVer=10.0.19041.0
WindowsSDKVersion=10.0.19041.0\
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
```

I don't see any of those variables when running `pixi shell -e build`.
