### ISSUE TITLE
pixi install -e default not working

### ISSUE THREAD

**Issue by PaulKMueller** [prefix-dev/pixi#1170]
```bash
pixi install -e default
  × unknown environment 'default'
```

The explicit installation of the default environment does not work.
This is relevant e.g. in the context of installing multiple environments in CI including the default.
```yaml
  - name: Set up pixi
    uses: prefix-dev/setup-pixi@19b5e6071f70a82d3c5741d7b3f98a71d192eb20
    with:
      environments: default py312
```

Is this intended?
