### ISSUE TITLE
`requires-python` version from pyproject.toml not being considered as a dependency

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1175]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dummyproj"
version = "0.1"
requires-python = ">=3.11"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.system-requirements]
linux = "3.10.0"

[tool.pixi.dependencies]
pip = ">=24.0,<25"
requests = ">=2.31.0,<2.32"
numpy = ">=1.26.4,<1.27"
matplotlib = ">=3.8.4,<3.9"

[tool.pixi.pypi-dependencies]
dummyproj = { path = ".", editable = true }
```

### Issue description

When the `tool.pixi.dependencies` section does not contain python as a dependency it resorts to the latest python version that is available after solving.  In the above example it solves to python 3.12

### Expected behavior

Use the `requires-python` version value in the `pyproject.toml` (in this case `3.11`)
