### ISSUE TITLE
Issues when both `pyproject.toml` and `pixi.toml` are present

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1182]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi.toml
```toml

[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[system-requirements]
linux = "3.10.0"

[dependencies]
python = ">=3.11"
pip = "*"

[tasks]
task1= "echo hi from pixi"

```

pyproject.toml

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "test"
version = "0.1"
requires-python = ">=3.11"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.system-requirements]
linux = "3.10.0"

[tool.pixi.dependencies]
pip = ">=24.0,<25"

[tool.pixi.pypi-dependencies]
test= { path = ".", editable = true }

[tool.pixi.tasks]
task1= "echo hi from pyproject"


```

### Issue description

Some issues that i noticed when moving from `pixi.toml` to `pyproject.toml`

- The `pixi init` command only adds the `tool.pixi.project` section (atleast in my case), it would be more convenient if all the sections from the existing `pixi.toml` are moved to `pyproject.toml` and the existing `pixi.toml` file either renamed(`pixi.toml_bkup`)/deleted . This is more explicit and easier for users.
- If both a `pixi.toml` and `pyproject.toml` are present then the tasks in `pixi.toml` have precedence over the ones in `pyproject.toml`  .
- if the `pixi.toml` is incomplete then running `pixi install` or other related commands errors out e.g if `name` key is missing in the `pixi.toml` the following errror is displayed even though the `pyproject.toml` is valid

  ```shell
   pixi install
    × Missing field `name`
  ```

### Expected behavior

1. `pyproject.toml` should take precedence 
2. warnings/errors shown when both are present and there is overlap in defintions between them
