### ISSUE TITLE
Lifecycle hooks

### ISSUE THREAD

**Issue by adamblake** [prefix-dev/pixi#1183]
### Problem description

There was a brief proposal regarding lifecycle hooks in #524 but that issue was framed around Python dependencies. With the addition of the new `pypi-dependencies` the issue was more or less discarded. However there are other common use-cases for lifecycle hooks, especially when using pixi to setup development environments. Here's an example that will probably look familiar:

```toml
[dependencies]
pre-commit = ">=3.7.0,<3.8"

[tasks]
postinstall = "pre-commit install"
```

Love this project, and always looking forward to the new features. The `pypi-dependencies` addition has seriously made life easier!

**Comment by adamblake** [comment]
I also just saw that this is mentioned as one of the requests in #1128

**Comment by tdejager** [comment]
I was thinking about this a bit, do you think that instead of like a 'postinstall' we can create a trigger that uses the hash of a file to automatically trigger a task after a or a number of tasks.

Think of having both a Python project that uses npm as well. You could make a "trigger" that triggers when the package.json changes after an install or maybe any other task.

Might be more powerful than a postinstall.

**Comment by adamblake** [comment]
I think that it could a good addition to the idea. It definitely would make this a more complex feature to implement though. If it went that way I would think it could be some kind of configurable trigger, e.g.

```toml
[tasks]
list-files = "ls -lah"
reset = "chartpress --reset"

[triggers]
post-install = ["list-files"]

[file-triggers]
"pixi.toml" = ["reset", "list-files"]
```

**Comment by ruben-arts** [comment]
What about adding it to the task definition:
```toml
[tasks]
install-npm = { cmd = "npm install", trigger = "post-install", inputs = ["package.json", "src/javascript/*.js" }
```
Where those triggers are predefined names that pixi looks for when it runs the install. These could be extended with more triggers, but I would like to add them based on use-case/on-request. 

This would allow you to do something similar to the life cycle scripts from [npm](https://docs.npmjs.com/cli/v10/using-npm/scripts) but without predefined names for the tasks.

**Comment by pavelzw** [comment]
Actually, the `postinstall` problem is not quite solved for me yet (because adding `pypi-dependencies` introduces more complexity into conda-only projects). Maybe just making postinstall a lifecycle script could solve this issue for me.

**Comment by bollwyvl** [comment]
Having now tried a few different `pixi` things: it seems like the `task` primitive is probably enough for just about everything, where `lock` and `install` are just hidden, special cases... making them even _more_ special (or introducing _more_ special tasks) would likely complicate things further.

I've ended up with a pattern like this for a monorepo where i can't use `pixi`/`uv`-managed editable installs:

```toml
[feature.pip.tasks.install-editable]
inputs = ["pyproject.toml", "contrib/*/pyproject.toml", "editable.txt"]
outputs = ["build/pip-freeze/$PIXI_ENVIRONMENT_NAME.txt"]
cmd = """
  rm -f build/pip-freeze/$PIXI_ENVIRONMENT_NAME.txt
  && python -m pip install -vv --no-deps --no-build-isolation --ignore-installed -r editable.txt
  && mkdir -p build/pip-freeze
  && pip freeze > build/pip-freeze/$PIXI_ENVIRONMENT_NAME.txt"""
```

... and then have any downstream tasks `depends_on: ["install-editable"]`, with an `input` of the `pip freeze` output. This ensures if some packaging-related thing changes (e.g. `entry_points`), the env in question will be brought up-to-date before trying to test it.

This still gets a little annoying further down the line when the `-e` argument isn't enough to fully specify the required intermediate environments... indeed, consider a fan-in reporting use case which still needs an editable install:

```toml
[feature.docs.tasks.report]
depends_on = [
  "install-editable", # where the current -e will be right
  {task="test", environment="some-env"},
  {task="test", environment="some-other-env"},
]
inputs = [
  "build/pip-freeze/$PIXI_ENVIRONMENT_NAME.txt", 
  "build/reports/some-env.txt", 
  "build/reports/some-other-env.txt"
]
```

Running `pixi run report` should then end up running `install-editable` (up to) three times, each time in a different env (which it may have also created). If the cache data is right, these might have been on entirely separate machines in CI. 

Alternately, as the task name regex is luckily already quite tight, a separator could be introduced:

```toml
depends_on = ["install-editable", "some-env::test", "some-other-env::test"]
```

Of course, if `inputs`/`outputs` _already_ defined the task-task relationship, and only one task was permitted to `outputs` a particular file, there would be no need for duplicating or specifying `depends_on` at all (see #1139).
