### ISSUE TITLE
Pixi updates python without being asked

### ISSUE THREAD

**Issue by liquidcarbon** [prefix-dev/pixi#1193]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

From empty folder with minimal `pyproject.toml`
Windows shown here, same on Linux.

```
[project]
name = "test"
description = "Minimal pyproject.toml with minimal [tool.pixi] section."

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]
```

```
PS C:\Users\a\py> pixi add python=3.11
✔ Added python=3.11
PS C:\Users\a\py> pixi run python -VV
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:40:50) [MSC v.1937 64 bit (AMD64)]


PS C:\Users\a\py> pixi add numpy
✔ Added numpy
PS C:\Users\a\py> pixi run python -VV
Python 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:42:31) [MSC v.1937 64 bit (AMD64)]
```

Final `pyproject.toml` becomes:

```
[project]
name = "test"
description = "Minimal pyproject.toml with minimal [tool.pixi] section."

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.dependencies]
python = "3.11.*"
numpy = ">=1.26.4,<1.27"
```

### Issue description

Pixi updates python to latest without being asked to do so

### Expected behavior

Keep python what it was

**Comment by tdejager** [comment]
Yes, I can definitely reproduce, even with the following toml:

```toml
[project]
name = "test"
description = "Minimal pyproject.toml with minimal [tool.pixi] section."

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.dependencies]
python = ">=3.11,<3.12"
numpy = ">=1.26.4,<1.27"
```

and just running `pixi install` I get a `3.12` version.

Adding a `requires-python = "<3.12"`, seems to constrain python again. I haven't investigated but, I think it's adding a default when the `requires-python` is missing that overwrites the explicit dependency. @olivier-lacroix might be interesting for you as well :)
