### ISSUE TITLE
Undefined symbol for `pyarrow`

### ISSUE THREAD

**Issue by mjkanji** [prefix-dev/pixi#1194]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

My `pixi.toml` is shown below.

<details><summary>pixi.toml</summary>

```toml
[project]
name = "easyknock_analytics"
version = "0.1.0"
description = "Add a short description here"
authors = ["Muhammad Jarir Kanji <mjkanji@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
dbt_run = { cmd = "dbt run" }

[dependencies]
python = ">=3.10,<3.11"
pip = "*"
pre-commit = "*"
pytz = "*"
pandas = ">=2.2.2,<2.3"

[pypi-dependencies]
dbt-core = { version = ">=1.7, <1.8" }
dbt-redshift = "*"
sqlfluff = "*"
sqlfluff-templater-dbt = "*"
dbt-coves = "*"

[feature.dev.dependencies]


[environments]
dev = { features = ["dev"], solve-group = "dev" }
prod = { features = [], solve-group = "dev" }
```
</details> 

Then, simply do:

```shell
pixi run python
> import pyarrow
```

### Issue description

This results in an `undefined symbol` error for Arrow:

```
ImportError: .pixi/envs/default/lib/python3.10/site-packages/pyarrow/libarrow_python.so: undefined symbol: _ZNK5arrow8DataType18ComputeFingerprintB5cxx11Ev
```

### Expected behavior

That Pyarrow should be installed properly.
