### ISSUE TITLE
👷‍♀ Add the ability to "build" a conda package

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#12]
_This probably requires some extra experimentation._

As a building block, we should add the ability to build a conda package from a project. If we can always construct a conda package from a pixi project we can enable source builds pretty easily by building any source package into a conda package first.

I envision a command called 

```
pixi build
```

that (on success) constructs a new package archive containing the build output of the project. Building the project simply calls the "build" command/script (https://github.com/prefix-dev/pax/issues/11) and passes in an environment variable or replaces something in the "build" command/script (with minijinja or whatever). The responsibility of outputting the correct build files is left up to the user.

I don't know how to handle creating buildstrings, multiple outputs, binary/text patching, etc. Probably have to investigate that a little more.

**Comment by rahuldave** [comment]
Does this not need the ability to add a dev-dependencies section? Or is that already doable?

**Comment by ruben-arts** [comment]
@rahuldave we took some first steps. So you can define build and host dependencies, but that all gets installed right now.

**Comment by pavelzw** [comment]
@rahuldave In the newest pixi release you can do something like this to separate `run` and `dev`-dependencies.

```toml
[dependencies]
# run dependencies

[host-dependencies]
# ...

[build-dependencies]
# ...

[feature.dev.dependencies]
...

[environments]
default = ["dev"]
```
