### ISSUE TITLE
Add flag to `pixi add` for adding PyPI packages to `optional-dependencies` instead of features

### ISSUE THREAD

**Issue by redeboer** [prefix-dev/pixi#1221]
### Problem description

First of all, thanks a lot for pixi! Following this project with interest :)

Since https://github.com/prefix-dev/pixi/issues/1062, PyPI dependencies listed under [`project.optional-dependencies`](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies) are interpreted as features. That's great, because the extra dependencies can also be 'understood' by `pip` itself, so that people can also use e.g. `venv` if they want.

I experience two drawbacks in the workflow now:
- Adding more dependencies to a specific `optional-dependencies` identifier can only be done by manually editing `pyproject.toml`.

  <details><summary>Example</summary>
  
  A Python project with one default dependency and an optional dependency section called `dev`:
  ```toml
  [project]
  name = "pixi-pypi-test"
  version = "0.0.1"
  dependencies = ["sympy"]
  
  [project.optional-dependencies]
  dev = ["pre-commit"]
  
  [tool.pixi.project]
  channels = ["conda-forge"]
  platforms = ["linux-64"]
  
  [tool.pixi.dependencies]
  python = "3.11.*"
  ```

  Now run
  
  ```shell
  pixi add mypy --feature dev --pypi
  ```
  
  This creates a new feature table for `dev` instead of adding `mypy` to the `dev` package list.
  
  ```toml
  [tool.pixi.feature.dev.pypi-dependencies]
  mypy = "*"
  ```

  </details>

- Each optional dependency identifier needs to have a corresponding environment defined ([right?](https://pixi.sh/v0.19.1/advanced/pyproject_toml/#optional-dependencies)). This is neatly done by `pixi init` if `pyproject.toml` has a `project.optional-dependencies` table.
  Do I understand correctly that after the project has been initialized, the only way to add more feature dependencies is to manually edit `pyproject.toml` and taking care to define environments for each additional optional dependency identifier?

### Proposed solution

Adding an `--optional-dependency` flag to `pixi add --feature ...`, which adds the PyPI package to the `project.optional-dependencies` table instead of creating a new feature table.

Something tells me this is not the cleanest solution, so open to suggestions 😅
