### ISSUE TITLE
User credentials request is not visible from commandline

### ISSUE THREAD

**Issue by carschandler** [prefix-dev/pixi#1227]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I'd prefer not to paste my company's Bitbucket repo URL here, but basically use a `pypy-dependencies` entry with some `{ git = "https://repo.mycompany.com" }` spec that will require username + password authentication and then
```shell
pixi install
```

For example, this is my (redacted) `pyproject.toml`:
```toml pyproject.toml
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "my_project"
version = "0.0.1"
authors = [
  { name="Cars Chandler", email="92899389+carschandler@users.noreply.github.com" },
]
description = "N/A"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://repo.mycompanyname.com/users/myusername/repos/my_project"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
my_project = { path = ".", editable = true }
my_lib = { git = "https://repo.mycompanyname.com/users/myusername/repos/my_lib.git" }

[tool.pixi.dependencies]
python = ">=3.12"
dash = "*"
dill = "*"
netcdf4 = "*"
numpy = "*"
pandas = "*"
pandas-stubs = "*"
plotly = "*"
pyarrow = "*" # required for upcoming pandas 3.0
python-kaleido = "*" # for plotly figure image exports
scipy = "*"
xarray = "*"

[tool.pixi.feature.dev.dependencies]
ipython = "*"
icecream = "*"
matplotlib = "*"

[tool.pixi.environments]
dev = ["dev"]
```

### Issue description

My company has some custom SSL certificate that I have to use and it typically prompts me at the terminal with a `Username:` followed by a `Password:` input field. The loading bar graphics of `pixi` prevent me from ever seeing these fields. They are still there, and when I enter my username and password blindly, the authentication does succeed, but it would be nice if there were a way to pause those bars while the authentication requests show. I'm aware that `pixi auth` is intended to make this a non-issue, and while it isn't working for me, I think it would still be nice to show the credentials requests to users who either aren't aware of `pixi auth`, aren't able to use it successfully, or just prefer not to.

### Expected behavior

Loading bars show, then are removed once a credential request is printed to stdout, then they resume after credentials are collected.

**Comment by ruben-arts** [comment]
We currently don't expect interaction with the installer/solver during `pixi install` so we would have to support that. Put it on the backlog. @wolfv your generally good at these issue, could you drop your thoughts on the matter?

**Comment by carschandler** [comment]
That's certainly a fair assumption and it's not a common use case at all so I understand. If only my company would set up SSH on their Bitbucket 🤧.

**Comment by wolfv** [comment]
@carschandler do you have some way of reproducing the behavior with a publicly accessible endpoint? That would help :)

Do I need to manually add a SSL certificate in some way that it asks for a password/

**Comment by carschandler** [comment]
@wolfv I've been thinking of the best way to go about this... I will try to find a public example that presents this behavior. Apologies I didn't have it in the original post!

**Comment by carschandler** [comment]
@wolfv okay, I found a simple way. Just use a private GitHub repo (doesn't actually have to be a Python package) and use the https link to it. You can `git clone` this link to see what the desired behavior would show, and if you use this snippet in a `pixi.toml`, then it will show what I'm talking about.
```toml
[pypi-dependencies]
my_library = { git = "https://github.com/user/my_library.git" }
```
Everything will go fine, and eventually it will hang on the `cloning https://github.com/user/my_library.git` step since the credential request has actually been printed, but was just instantly covered by the loading bars (I think). You can type in your username blindly, hit enter, and paste in a personal access token, and you'll authenticate successfully.
