### ISSUE TITLE
Better error message for missing local channel

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/pixi#1255]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "resnet"
version = "0.1.0"
description = "Add a short description here"
authors = ["Nichita Morcotilo <nmorkotilo@gmail.com>"]
channels = ["../local", "conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
pytorch = "*"

```

### Issue description

Having defined a local channel in `channels = ["../local", "conda-forge"]`
will show following error:

<img width="488" alt="Screenshot 2024-04-22 at 19 13 54" src="https://github.com/prefix-dev/pixi/assets/25200469/d098acbe-ced7-4766-b053-36081c028673">

### Expected behavior

As a user I would like to see more friendly error message indicating what channel pixi can't find
