### ISSUE TITLE
pixi install works with pixi.toml but not pyproject.toml

### ISSUE THREAD

**Issue by j-bac** [prefix-dev/pixi#1264]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi install works with pixi.toml but not pyproject.toml

pixi.toml
```toml
[project]
name = "test"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux="4.18"

[dependencies]
python = "3.10.*"
geos = ">=3.12.1,<3.13"
setuptools = ">=69.5.1,<69.6"

[pypi-dependencies]
spatialdata = "*"
spatialdata-io = "*"
```

pyproject.toml
```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "test"
version = "0.0.1"

[tool.pixi.system-requirements]
linux="4.18"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
python = "3.10.*"
geos = ">=3.12.1,<3.13"
setuptools = ">=69.5.1,<69.6"

[tool.pixi.pypi-dependencies]
spatialdata = "*"
spatialdata-io = "*"
```

### Issue description

With pixi.toml, pixi install works fine. With pyproject.toml, it fails with error:
``` 
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ Failed to build: pygeos==0.14
```

### Expected behavior

Successful install using pyproject.toml
