### ISSUE TITLE
Lock files for global environments

### ISSUE THREAD

**Issue by kxmh42** [prefix-dev/pixi#1280]
### Problem description

Pixi environments inside projects can be deleted at any time and regenerated using `pixi.lock`. However, it looks like it's not the case for global environments. If I delete `$PIXI_HOME/envs`, I have no way of recreating exact versions of the installed tools and their dependencies, is that right?

The particular scenario I'm looking at is saving space in my home folder by moving `$PIXI_HOME/envs` to a partition that has larger quota, but doesn't get backed up. And if `$PIXI_HOME/envs` is lost, I would like to recreate it in its exact state.

My suggestion would be to save lock files for global environments somewhere in `$XDG_STATE_HOME/pixi` / `~/.local/state/pixi`.

**Comment by ruben-arts** [comment]
Currently the global environments are simple "non project" installs of a conda environment. So we don't save any information apart form the environment itself. 

I unfortunately can't find the discussion but we've been talking about a configuration file for the global environments. E.g.:
```yaml
envs:
  - name: bat
    channels:
      - conda-forge
    dependencies:
      - bat

  - name: ripgrep
    channels:
      - conda-forge
    dependencies:
      - ripgrep

  - name: some_pytorch_package
    channels:
      - conda-forge
      - pytorch
    dependencies:
      - some_pytorch_package
      - pytorch==2.3.1
```
This way you could easily track your global environments and even better recreate them on a new machine. These might then be extended with lock files per env to accommodate your request. 

p.s. Not sure if we want to do this in YAML but my brain wrote it like that. Just take this as an example.
