### ISSUE TITLE
Mismatched virtual package error when using official Docker image

### ISSUE THREAD

**Issue by mjkanji** [prefix-dev/pixi#1293]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I'm trying to use the [official Pixi Docker image](https://github.com/prefix-dev/pixi-docker) for my GitLab CI pipeline, but I'm running into the same error as #346.

Since I'm using the official Docker image, I'm not sure why the version of Linux is not up-to-date.

Here are my config files:

<details><summary>.gitlab-ci.yml</summary>

```yml
stages:
  - test

precommit-checks:
  stage: test
  image: ghcr.io/prefix-dev/pixi
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
    GIT_FETCH_EXTRA_FLAGS: $CI_DEFAULT_BRANCH --prune
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  before_script:
    # Install git because the Pixi container doesn't have it
    - apt update && apt install -y --no-install-recommends git

  script:
    - pixi --version
    - pixi install
    - pixi run pre-commit --version
    # Run pre-commit hooks only on the files that are different compared to the default (master) branch.
    - pixi run pre-commit run --from-ref origin/$CI_DEFAULT_BRANCH --to-ref $CI_COMMIT_SHORT_SHA
  allow_failure: true # Allow the job to fail without blocking downstream stages
```

</details> 

<details><summary>pixi.toml</summary>

```toml
[project]
name = "my_project"
version = "0.1.0"
description = "Add a short description here"
authors = ["Muhammad Jarir Kanji <hello@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
dbt_run = { cmd = "dbt run" }

[dependencies]
python = ">=3.10,<3.11"
pip = "*"
pre-commit = "*"
pytz = "*"
pandas = ">=2.2.2,<2.3"
# Needed by dbt-coves
pyarrow = "*"
# Needed by dbt-coves
sqlalchemy = "*"

[pypi-dependencies]
dbt-core = { version = ">=1.7, <1.8" }
dbt-redshift = "*"
sqlfluff = "*"
sqlfluff-templater-dbt = "*"
dbt-coves = "*"

[feature.dev.dependencies]


[environments]
dev = { features = ["dev"], solve-group = "dev" }
prod = { features = [], solve-group = "dev" }
```

</details> 

And here's the error I'm getting in the CI job:

```shell
$ pixi --version
pixi 0.20.1
$ pixi install
Project in /xx/xx/xx/xx is ready to use!
$ pixi run pre-commit --version
  × The current system has a mismatching virtual package. The project requires
  │ '__linux' to be at least version '5.10' but the system has version
  │ '5.4.109'
```

### Issue description

As described above.

### Expected behavior

That the official Docker container has the correct system requirements.
