### ISSUE TITLE
Add support for injecting dotenv environment variables into tasks 

### ISSUE THREAD

**Issue by croth1** [prefix-dev/pixi#1330]
### Problem description

pixi tasks nicely support environment variables. Being able to inject environment variables from a `.env` file could make it easy for injecting host-specific environment variables into `pixi run <task-name>` without having to manually source the .env file first.

I will leave this here for voting. It's a nice-to-have for me - maybe somebody else would also find this useful for their workflow?

**Comment by bollwyvl** [comment]
I've been using generated `.env`'s as `outputs` to isolate/generate settings in the absence of a solid matrix mechanism. 

If `.env` is supported, seems like it would need a fair amount of specificity to handle the breadth of ways it is used, ideally providing a way to compose in a predictable order with other configuration:

```toml
[tasks.build]
cmd = "whatever"
env = {FOO="bar"}
env-file = ".env"
# or
env-file = [".env", ".env.dev"]
# and maybe
depends-on = [
  { task="preflight", environment="build", env={FOO="$FOO"}, env-file=[".env.another"] }
]
```
