### ISSUE TITLE
Weird lock after 0.21

### ISSUE THREAD

**Issue by Hoxbro** [prefix-dev/pixi#1331]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

``` shell
pixi install
cat pixi.lock | grep datashader
```

``` shell
      - conda: https://conda.anaconda.org/pyviz/label/dev/noarch/datashader-0.16.1-py_0.tar.bz2
      - conda: https://conda.anaconda.org/rapidsai/noarch/datashader-0.13.1a-py_0.tar.bz2
  name: datashader
  url: https://conda.anaconda.org/rapidsai/noarch/datashader-0.13.1a-py_0.tar.bz2
  name: datashader
  url: https://conda.anaconda.org/pyviz/label/dev/noarch/datashader-0.16.1-py_0.tar.bz2

```

```toml
[project]
name = "holoviews"
channels = ["pyviz/label/dev", "conda-forge"]
platforms = ["linux-64"]

[environments]
test = ["test"]
test-gpu = ["test", "test-gpu"]

[feature.test.dependencies]
python = "3.11.*"
datashader = ">=0.11.1"

[feature.test-gpu]
channels = ["pyviz/label/dev", "rapidsai", "conda-forge"]

[feature.test-gpu.dependencies]
cuda-version = "12.2.*"

```

### Issue description

After upgrading to 0.21, my channel priorities seem messed up when combining features. 

### Expected behavior

I would expect both environments to have datashader 0.16.1 installed from the `pyviz/label/dev`
