### ISSUE TITLE
Why are not all environments created on `pixi install`?

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1333]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dummyproj"
version = "0.1"
requires-python = "==3.11.*"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[tool.pixi.system-requirements]
linux = "3.10.0"

[tool.pixi.dependencies]
pip = ">=24.0,<25"
requests = ">=2.31.0,<2.32"
numpy = ">=1.26.4,<1.27"
pandas = ">=2.2.2,<2.3"
matplotlib = ">=3.8.4,<3.9"
pydantic = ">=2.7.0,<2.8"

[tool.pixi.feature.lint.dependencies]
ruff = ">=0.3.4,<0.4"

[tool.pixi.feature.lint.tasks]
lint = "ruff check ."

[tool.pixi.tasks]
plot = "python -m dummyproj.plot"
task1 = "echo hi from pyproject"

[tool.pixi.environments]
lint = {features = ["lint"], no-default-feature = true}
```

### Issue description

In the above example, i used the new feature in the v0.21 `no-default-feature` and after running the following command `rm -f pixi.lock && pixi install`,  the `lint` env is not present in the `.pixi/envs` folder.

What am i doing wrong?

### Expected behavior

both `default` and `lint` envs are present and usable.

**Comment by vigneshmanick** [comment]
Thanks for the info. This was not clear to me, now running `pixi run lint` does what you mentioned and the `lint` env is now **there**. I have a further point regarding this. When running `pixi run lint` for the first time i got the following error

```
pixi run lint
✨ Pixi task (lint-code in lint): ruff check --fix . && ruff format .
  × The current system has a mismatching virtual package. The project requires '__linux' to be at least version '5.10' but the system has version
  │ '3.10.0'
```

I guess the `no-default-feature` ignores everything from the `default` ? would be good if there is a fine grained filter avaialble, `platforms`,  `system-requirements `,  etc.  so that i don't have to redefine the fields.

maybe 

```toml
[no-default-feature]
include = [ "platforms", "system-requirements" ]
```
