### ISSUE TITLE
disable conda-pypi mapping for some or all channels

### ISSUE THREAD

**Issue by gzm55** [prefix-dev/pixi#1342]
### Problem description

can we disable the mapping feature for some channels or all channels?

**Comment by gzm55** [comment]
packages from pypi and conda may be compiled with different flags, such as tensorflow, can we depends on the pypi one. Second, when enable mapping, the resolving and installing progress of the tensorflow with mapping is very very slow, in the mean while, pip install takes less then one minutes.

**Comment by tdejager** [comment]
Sure, but if you add tensorflow to `pypi-dependencies` it should that one right? I mean you cannot have the conda package and the pypi package at the same time.

**Comment by tdejager** [comment]
Would also be great if you could share your `pixi.toml` or `pyproject.toml` here :)

**Comment by gzm55** [comment]
> Would also be great if you could share your `pixi.toml` or `pyproject.toml` here :)

```toml
[project]
name = "tf"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]
# conda-pypi-map = { "conda-forge" = "empty.json" } # force disable mapping

[tasks]

[dependencies]
python = "3.8.*"
nomkl = ">=1.0,<2"

[system-requirements]
linux = "2.6.32" # centos 6
libc = "2.12"

[pypi-options]
index-url = "https://corp.com/pypi/simple" # a pypi mirror

[pypi-dependencies]
tensorflow = { version = ">=2.2, <2.3" }
grpcio = { version = "<1.47" }
h5py = { version = "<3.8" }
```
