### ISSUE TITLE
pixi add arize-phoenix fails due to dependency conflict, where as plain pip install arize-phoenix works.

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [prefix-dev/pixi#1345]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Here is my `pixi.toml` file:

```toml
[project]
name = "bla_bla"
version = "0.1.0"
description = "Add a short description here"
authors = ["Damian Barabonkov <damianb@alum.mit.edu>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
black = "*"
jupyterlab = "*"
notebook = "*"
pandas = "*"
pre-commit = "*"
pyarrow = "*"
python = "3.11.*"
pyright = "*"
pip = ">=24.0,<25"

[pypi-dependencies]
openai = "*"
dspy-ai = ">=2.4.9"
arize-phoenix = "*"
```

Version: pixi 0.21.0

### Issue description

I first thought that this was an issue with the library `arize-phoenix`, however after seeing that `pip install` works, that leads me to think that this is a pixi issue.

I have a pixi environment set up as above. Doing `pixi add arize-phoenix` or `pixi add --pypi arize-phoenix` leads to a dependency conflict. However, if I do `pixi add pip` and then `pip install arize-phoenix`, it works out just fine.

Here is the `arize-phoenix` repo: https://github.com/Arize-ai/phoenix

### Expected behavior

The installation works like `pip install` does.
