### ISSUE TITLE
Starting from pixi-0.21.0 `pixi task list` will fail if system-requirements do not comply, but without saying so

### ISSUE THREAD

**Issue by anjos** [prefix-dev/pixi#1347]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

In an empty directory, create `pixi.toml` with the following contents:

```toml
[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "7.0.0"

[tasks]
task1 = "echo task1"
task2 = "echo task2"
```

Start a container for the target platform (N.B.: I'm on a macOS with Apple Silicon machine), such that `pixi info` reports a value smaller than the `system-requirements` set above:

```shell
$ docker run --platform linux/amd64 -v $PWD:/work --rm -ti ghcr.io/prefix-dev/pixi:0.21.0 /bin/bash
$ cd work
$ pixi task list
No tasks found
```

(N.B.: Same holds for 0.21.1).

If you lower the system-requirements, then the task list works again.

If you execute the same on 0.20.1, you get, however:

```shell
$ docker run --platform linux/amd64 -v $PWD:/work --rm -ti ghcr.io/prefix-dev/pixi:0.20.1 /bin/bash
$ cd work
$ pixi task list
* task1
* task2
```

### Issue description

N/A

### Expected behavior

I'm not sure what to expect, however, it would be great to get a message that is more consistent with the actual problem than `No tasks found`.
