### ISSUE TITLE
UV cache error in read-only filesystems.

### ISSUE THREAD

**Issue by tobiasraabe** [prefix-dev/pixi#1387]
### Checks

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
docker build -t repro .
docker run --rm -p 8080:8080 --read-only repro
```

The full example is zipped up here: [pixi-repro.zip](https://github.com/prefix-dev/pixi/files/15306100/pixi-repro.zip)

### Issue description

Hi! First of all thanks for the amazing software!

I want to run a FastAPI app in a Docker container with a read-only filesystem. #1363 fixed an issue where pixi tried to write to the filesystem although it could simply use the existing environment.

Now that the issue is fixed, another issue has surfaced. pixi attempts to create a uv cache which fails since the filesystem is read-only.

![image](https://github.com/prefix-dev/pixi/assets/22533006/f6cd518a-6970-4cb0-897d-ffd9ae8123be)

I also have another issue unrelated to this one. Feel free to ignore it.

I am not able to shut down the Docker container with CTRL+C when I am using pixi in `CMD`. It is possible if I do not use `pixi run` and use the raw `CMD [".pixi/envs/default/bin/uvicorn", "main:app", "--port", "8080", "--host", "0.0.0.0"]` instead. If it is indeed an issue, I could create another ticket for you.

### Expected behavior

The service should run in Docker container.

Visiting http://localhost:8080/docs should display the swagger page of the app.

**Comment by tdejager** [comment]
Hmmm, so uv has a `--no-cache` option but that still creates a temporary file. I suppose that would not work either right?

**Comment by tdejager** [comment]
Ok, so thinking about this a bit more it is a bit of a hard one.

So by default we run an install for pypi and for conda because you might have changed the prefix in the mean time. Although in this case you know you didn't because it's in a docker. There is the `--no-install` flag that ensures no installation happens, *but* because you have pypi-dependencies in form of an editable you **need** a conda prefix to build the dependency. Which is fine in the installation part of the `Dockerfile`.

Normally this does not matter much because even though it runs an installation it does nothing because the prefix is up-to date. But because you have a read-only filesystem, it fails on the uv cache invocation.

A solution could be that we check if we have a `--no-install` and a `--locked`, we would need to add this to `run`, and we could forego the pypi installation.

**Comment by tdejager** [comment]
In the mean-time if we first add `--no-install` to run you could make do with:

```toml
[project]
name = "pixi-repro"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64"]

# We use dependencies from conda to use it to build the wheel
[tool.pixi.feature.build.dependencies]
build = "*"

[tool.pixi.feature.build.tasks]
# Create a wheel for installation
build-wheel = "python -m build --no-isolation --wheel ."
# Install into the production environment
postinstall = {cmd = "pip install --no-deps --disable-pip-version-check dist/pixi_repro-*.whl", depends_on = ["build-wheel"]}

[tool.pixi.tasks]
serve = { cmd = "uvicorn main:app --port 8080 --host 0.0.0.0" }
postinstall = "pip install ."

[tool.pixi.dependencies]
pip = "*"
fastapi = ">=0.111.0,<0.112"

[tool.pixi.environments]
build = ["build"]
```

Dockerfile:
```
FROM ghcr.io/prefix-dev/pixi:0.22.0

WORKDIR /app

COPY pyproject.toml .
COPY main.py .
COPY pixi.lock .

RUN pixi install
RUN pixi r -e build postinstall

ENV PIXI_FROZEN=true
ENV UV_NO_CACHE=1

EXPOSE 8080

CMD ["pixi", "run", "-v", "serve"]
```
