### ISSUE TITLE
Can't install pypi package when version contains special character like `+`

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#1418]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi version: 0.22.0

pixi.toml
```toml
[project]
name = "test-install"
channels = ["conda-forge"]
platforms = ["win-64"]

[pypi-options]
index-url = "https://pypi.org/simple"
find-links = [{ url = "https://download.pytorch.org/whl/torch_stable.html" }]

[dependencies]
python = "*"

[pypi-dependencies]
torch = "==2.3.0+cu121"
```

```pwsh
> pixi install
⠠ updating pypi packages in 'default'
thread 'main' panicked at src\install_pypi.rs:175:21:
package = torch, url = https://download.pytorch.org/whl/cu121/torch-2.3.0%2Bcu121-cp312-cp312-win_amd64.whl => could not convert to dist filename
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Issue description

I did not meet this problem when I use uv. I think these specical charachters in url encoding causes this problem.

https://github.com/prefix-dev/pixi/blob/95176bcc10ba93c9249c478b31de832216c1312d/src/install_pypi.rs#L175

In this line, the `filename_raw` variable is `torch-2.3.0%2Bcu121-cp312-cp312-win_amd64.whl` .

If I use `filename_raw.replace("%2B", "+").as_str()` as input, pytorch will be installed successfully.

### Expected behavior

Support to install pypi packages with special characters.

**Comment by RaphaelMelanconAtBentley** [comment]
Having the same issue, thanks for being proactive on these!

**Comment by tdejager** [comment]
I think the uv upgrade should have fixed this issue as well, I've added a test to main that does not fail anymore :) I'll close and we can re-open if the issue persist. Note it's still in main, will be integrated with the next release.

**Comment by Glatzel** [comment]
> I think the uv upgrade should have fixed this issue as well, I've added a test to main that does not fail anymore :) I'll close and we can re-open if the issue persist. Note it's still in main, will be integrated with the next release.

Build with the main branch and test with my sample pixi.toml above, but get this error. I also check the lock file, url and version look correct.

```
- kind: pypi
  name: torch
  version: 2.3.0+cu121
  url: https://download.pytorch.org/whl/cu121/torch-2.3.0%2Bcu121-cp312-cp312-win_amd64.whl
  requires_dist:
  - filelock
  - typing-extensions>=4.8.0
  - sympy
  - networkx
  - jinja2
  - fsspec
  - nvidia-cuda-nvrtc-cu12==12.1.105 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cuda-runtime-cu12==12.1.105 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cuda-cupti-cu12==12.1.105 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cudnn-cu12==8.9.2.26 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cublas-cu12==12.1.3.1 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cufft-cu12==11.0.2.54 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-curand-cu12==10.3.2.106 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cusolver-cu12==11.4.5.107 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-cusparse-cu12==12.1.0.106 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-nccl-cu12==2.20.5 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - nvidia-nvtx-cu12==12.1.105 ; platform_system == 'Linux' and platform_machine == 'x86_64'
  - triton==2.3.0 ; platform_system == 'Linux' and platform_machine == 'x86_64' and python_version < '3.12'
  - mkl<=2021.4.0,>=2021.1.1 ; platform_system == 'Windows'
  - opt-einsum>=3.3 ; extra == 'opt-einsum'
  - optree>=0.9.1 ; extra == 'optree'
  requires_python: '>=3.8.0'
```

```pwsh
× error updating pypi prefix
  ├─▶ Failed to download distributions
  ├─▶ Failed to fetch wheel: torch==2.3.0+cu121
  ├─▶ Failed to extract archive
  ╰─▶ Unsupported archive type: torch-2.3.0%2Bcu121-cp312-cp312-win_amd64.whl
```
