### ISSUE TITLE
pixi should help user with missing project channel

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/pixi#1452]
### Problem description

```toml
[project]
name = "torchaudio"
channels = ["conda-forge"]

[tasks]

[dependencies]
captum = {version="*", channel="pytorch"}
```
While trying to install this small example, we will have following error:

```
(default) graf@Nichitas-MacBook-Pro torchaudio % pixi install
  × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: The following packages are incompatible
      └─ captum * cannot be installed because there are no viable options:
         └─ captum 0.4.1 | 0.4.1 | 0.5.0 | 0.6.0 is excluded because candidate not in requested channel: 'pytorch'
```

I think pixi should help user in this case and hint that pytorch should be added in project channels.
