### ISSUE TITLE
`pixi install` / `pixi run` doesn't handle multiple concurrent invocations very well

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1482]
In our pre-commit configuration, we use something like

```yml
exclude: (^env/|.pixi/)
repos:
  - repo: local
    hooks:
      # prettier
      - id: prettier
        name: prettier
        entry: pixi run -e lint prettier --write --list-different --ignore-unknown
        language: system
        types: [text]
        files: \.(md|yml|yaml)$
      # pre-commit-hooks
      - id: trailing-whitespace-fixer
        name: trailing-whitespace-fixer
        entry: pixi run -e lint trailing-whitespace-fixer
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: pixi run -e lint end-of-file-fixer
        language: system
        types: [text]
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: pixi run -e lint check-merge-conflict --assume-in-merge
        language: system
        types: [text]
      # typos
      - id: typos
        name: typos
        entry: pixi run -e lint typos --force-exclude
        language: system
        types: [text]
        require_serial: true
      # cargo fmt and clippy
      - id: cargo-fmt
        name: cargo-fmt
        entry: pixi run -e default cargo fmt --
        language: system
        require_serial: false
        types: [rust]
      - id: cargo-clippy
        name: cargo-clippy
        entry: pixi run -e default cargo clippy --all-targets --all-features --workspace -- -D warnings
        pass_filenames: false
        language: system
        require_serial: false
        types: [rust]
      # taplo
      - id: taplo
        name: taplo
        entry: pixi run -e lint taplo format
        language: system
        types: [toml]
```

since it is a bad idea to let pre-commit manage lint dependencies when you have a proper package manager who can do that as well in a `lint` environment.

When running `pre-commit run -a`, it invokes a lot of `pixi run ...` processes that all try to install the environment if it doesn't exist.
This then leads to warnings/errors like this:

![image](https://github.com/prefix-dev/pixi/assets/29506042/b134aae7-ffaf-4e28-af6a-2a00d3743b90)

To be fair, how our pre-commit config looks is a bit hacky but I think pixi could write a lock file to `.pixi` to prevent parallel access.

---

Also, sort-of related, i'm not sure why I see a `updating environment 'default'` here since the `default` environment should already be installed:

![image](https://github.com/prefix-dev/pixi/assets/29506042/e97b056c-3943-4049-b472-98a107f9c8db)

Any ideas why this is the case?

**Comment by pavelzw** [comment]
a workaround for this is to add the following at the beginning of your `.pre-commit-config.yaml`:

```yml
      # ensure pixi environments are up to date
      # workaround for https://github.com/prefix-dev/pixi/issues/1482
      - id: pixi-install
        name: pixi-install
        entry: pixi install -e default -e lint
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
```

**Comment by baszalmstra** [comment]
I wonder if this is still an issue!

**Comment by lucascolley** [comment]
> I wonder if this is still an issue!

looks like @Hofer-Julian hit this at https://github.com/prefix-dev/rattler-build/pull/2387.

**Comment by Hofer-Julian** [comment]
Yeah, I hit this all the time when using lefthook with parallel enabled

**Comment by pavelzw** [comment]
we are now just using something like this in lefthook:

```yml
templates:
  run: run --as-is --quiet --no-progress
no_auto_install: true
pre-commit:
  fail_on_changes: always
  jobs:
    - name: pixi-install
      run: pixi install
    - group:
        parallel: true
        jobs:
          - name: ruff-check
            glob: "*.{py,pyi}"
            run: pixi {run} ruff check --fix --exit-non-zero-on-fix --force-exclude
          # ...
```

with an initial install and then follow-up `--as-is`, it seems to be relatively stable

**Comment by lucascolley** [comment]
FWIW I haven't had problems with the naïve parallel approach on either this repo or array-api-extra. Not sure what the failure modes are, but possibly there is something linux-specific?

**Comment by baszalmstra** [comment]
Im working on a PR to ensure that parallel installations do not happen.

**Comment by crusaderky** [comment]
> Yeah, I hit this all the time when using lefthook with parallel enabled

I've rigged lefthook to call the tools directly to solve this problem.
This way the pixi environment is initialised before starting lefthook and doesn't change halfway through.

```toml
# pixi.toml
[feature.lint.dependencies]
lefthook = "*"
ruff = "*"
mypy = "*"
# ...

[feature.lint.tasks]
install-git-hooks = { cmd = "lefthook install", description = "Install pre-commit hooks" }
update-dprint = { cmd = "dprint config update", description = "Update dprint plugins" }
lint = { cmd = "lefthook run pre-commit --all-files --force", description = "Run all linters" }

[environments]
lint = ["lint"]
```

```yaml
#lefthook.yml
pre-commit:
  parallel: true
  jobs:
    - name: ruff
      group:
        piped: true
        jobs:
          - name: ruff format
            run: ruff format
          - name: ruff check
            run: ruff check --fix --show-fixes
    - run: mypy
    # ...
```
