### ISSUE TITLE
CUDA virtual package is not detected on when using brew version of pixi

### ISSUE THREAD

**Issue by tfriedel** [prefix-dev/pixi#1484]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi --version:
0.23.0

pixi.toml:
```toml
[project]
name = "PyTorch"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
cuda = "12"

[dependencies]
python = "3.10.*"
pytorch-gpu = ">=2.1.2,<2.2"
```

```shell
brew install pixi
pixi install
pixi shell
```

output:
```
  × The platform you are running on should at least have the virtual package __cuda on version 12, build_string: 0
```  

If instead of using the brew version of pixi I install it like this:
```
PIXI_VERSION=v0.23.0 curl -fsSL https://pixi.sh/install.sh | bash
```

I don't have this issue.

### Issue description

I suspect pixi looks for some conda libraries in brew, instead of systemwide.
I'm not sure if this is necessary. I think the conda toolkit is installed with conda, so it should work even if some of this cuda stuff is missing both systemwide and in brew. 

### Expected behavior

It shouldn't print an error message, when brew version of pixi is used and you should also not be required to install cuda libraries for brew.
