### ISSUE TITLE
`pixi project version` doesn't work correctly in `pyproject.toml`

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#1496]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

# condition1
```toml
[project]
name = "demo1"
requires-python = ">=3.10"
version = "1.0.0"
authors = [{ name = "Glatzel" }]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]
```
If run `pixi project version get`. Nothing happens.
If run `pixi project version minor`. It shows `No version found in manifest.`

# condition2
```toml
[project]
name = "demo2"
requires-python = ">=3.10"
dynamic = ["version"]
authors = [{ name = "Glatzel" }]

[tool.pixi.project]
version="1.0.0"
channels = ["conda-forge"]
platforms = ["win-64"]
```
In this condition, `pixi project version get` works, it returns `1.0.0`.
Then, if I run `pixi project version minor`, the `pyproject.toml` will add `version="1.1.0"` to `project`. In this toml, run `pixi project version get`, it still returns `1.0.0` rather than `1.1.0`.

```toml
# after running `pixi project version minor`
[project]
name = "demo2"
requires-python = ">=3.10"
dynamic = ["version"]
authors = [{ name = "Glatzel" }]
version = "1.1.0"

[tool.pixi.project]
version="1.0.0"
channels = ["conda-forge"]
platforms = ["win-64"]
```

### Issue description

1. In `pyproject.toml`, `version` should be in either project table or tool.pixi.project table. Like the toml files above.
2. `pixi project version xxx` should be able to detect version in project table.
3. major/minor/patch command should only modify version in its original location, not to add new line.

### Expected behavior

`pixi project version` commmand works correctly for `pyproject.toml`
