### ISSUE TITLE
`pixi add` is really slow in some scenarios

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1506]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "glum"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[build-dependencies]
c-compiler = "*"
cxx-compiler = "*"
cython = "*"
setuptools-scm = ">=8.1"

[host-dependencies]
python = ">=3.9"
pip = "*"

[dependencies]
numexpr = "*"
pandas = ">=1.1"
tabmat = ">=4.0.0"
scikit-learn = ">=0.23"
scipy = "*"
tqdm = "*"
formulaic = "*"
pyarrow = "*"

[feature.no-tabmat.dependencies]
numexpr = "*"
pandas = ">=1.1"
scikit-learn = ">=0.23"
scipy = "*"
tqdm = "*"
formulaic = "*"
pyarrow = "*"

[feature.test.dependencies]
statsmodels = "*"
pytest = "*"
pytest-xdist = "*"
git_root = "*"
click = "*"
attrs = "*"
psutil = "*"
mypy = "*"

[feature.dev.dependencies]
ipdb = "*"
ipython = "*"
line_profiler = "*"
memory_profiler = "*"
ipykernel = "*"

[feature.lint.dependencies]
pre-commit = "*"
cython-lint = "*"
ruff = "*"

[feature.docs.dependencies]
jinja2 = "*"
jupyterlab = "*"
jupytext = "*"
make = "*"
matplotlib-base = "*"
nbclassic = ">=0.2.8"
nbsphinx = ">=0.8.3"
sphinx = ">=3.5.3"
sphinx_rtd_theme = "*"
sphinxcontrib-apidoc = "*"
sphinxext-altair = "*"

[feature.tutorial.dependencies]
jupyterlab = "*"
altair = "*"
openml = "*"
dask-ml = ">=2022.5.27"
shapely = "*"
libpysal = "*"

[feature.benchmark.dependencies]
h2o-py = "*"
openjdk = "*"
[feature.benchmark.target.win-64.dependencies]
blas = "=*=*mkl"
[feature.benchmark.target.linux-64.dependencies]
blas = "=*=*mkl"

[feature.build-tabmat.dependencies]
c-compiler = "*"
cxx-compiler = "*"
cython = "!=3.0.4"
setuptools-scm = "*"
make = "*"
mako = "*"
xsimd = "<11|>12.1"
pip = "*"
[feature.build-tabmat.target.unix.dependencies]
jemalloc-local = "*"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.oldies.dependencies]
python = "3.9.*"
pandas = "1.2.*"
scikit-learn = "0.24.*"
tabmat = "4.0.*"
scipy = "1.7.*"
formulaic = "0.6.*"

[environments]
default = ["dev", "test"]
docs = ["docs", "tutorial"]
benchmark = ["benchmark"]
py39 = ["py39", "test"]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
oldies = ["oldies", "test"]
lint = { features = ["lint"], no-default-feature = true}
nightly = ["py312", "build-tabmat", "test"]
glum-tabmat = { features = ["no-tabmat", "build-tabmat", "dev", "test"], no-default-feature = true}
```

[pixi.lock.txt](https://github.com/user-attachments/files/15821360/pixi.lock.txt)

```
$ pixi add python
<takes 90s until it prints anything>
updating lockfile ...
-> total 140s
```

### Issue description

We want to adopt pixi in https://github.com/Quantco/glum.
When playing around with it, we noticed, that `pixi add polars` takes a _long_ time to finish.

What I noticed is that most of this time is spent while pixi doesn't print anything and pixi also doesn't do any parallel work.
Only once the `updating lock-file` was printed, pixi used all cores on my machine.

Here a recording of what's happening:

https://github.com/prefix-dev/pixi/assets/29506042/0702e828-3b1e-4bf9-bce6-2205de39761f

https://github.com/prefix-dev/pixi/assets/29506042/2f8291d6-e56b-4fff-a840-c47a75a6c764

Do you know what's happening in the first part and why it is so slow?
