### ISSUE TITLE
`pixi update` not updating dependency but `pixi add ` does

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1514]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "myproj"
version = "0.0.1"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]


[tool.pixi.system-requirements]
linux = "3.10.0"

[tool.pixi.pypi-dependencies]
myproj = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
pydantic = ">=2.6.4,<2.7"
numpy = ">=1.26.4,<1.27"
pandas = ">=2.2.2,<2.3"

```

### Issue description

running `pixi update pydantic` doesn't update the dependency  but running `pixi add pydantic` updates it to `pydantic = ">=2.7.4,<2.8"`

### Expected behavior

`pixi update` / `pixi update <dependency>` should update it to the latest version that can be supported after solving
