### ISSUE TITLE
pixi add --pypi adds your dependencies inline as opposed to on its own line (even if you've explicitly formatted your list as a multi-line list)

### ISSUE THREAD

**Issue by kszlim** [prefix-dev/pixi#1515]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "project"
version = "0.1.0"
description = "my project"
authors = []
requires-python = "< 3.12"
dependencies = [
    "panel"
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]
```

```shell
pixi add --pypi flask
```

output:
```toml
[project]
name = "project"
version = "0.1.0"
description = "my project"
authors = []
requires-python = "< 3.12"
dependencies = [
    "panel"
, "flask"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]
```

### Issue description

It would be nice for it to respect existing formatting, though that might be finnicky. Maybe the real solution is to format the toml on file on edits using a known good toml formatted?

### Expected behavior

```toml
[project]
name = "project"
version = "0.1.0"
description = "my project"
authors = []
requires-python = "< 3.12"
dependencies = [
    "panel",
    "flask"
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]
```
