### ISSUE TITLE
Might want to prevent naming an environment `solve-group-envs`

### ISSUE THREAD

**Issue by RaphaelMelanconAtBentley** [prefix-dev/pixi#1525]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pixi.toml example:

```toml
[project]
name = "Solve groups"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "~=3.11"

[feature.pytest.pypi-dependencies]
pytest = "*"

[feature.cpu]
channels = ["conda-forge", "pytorch"]
[feature.cpu.dependencies]
pytorch = { version = "~=2.3.0", channel = "pytorch" }
cpuonly = { version = "*", channel = "pytorch" }


[environments]
solve-group-envs = { features = ["general", "pytest"], solve-group = "my_group" }
cpu-only = { features = ["cpu"], solve-group = "my_group" }
cpu = { features = ["general", "cpu"], solve-group = "my_group" }
```

### Issue description

It's possible to name an environment `solve-group-envs`, which clashes with the solve groups feature a could yield weird results.

Here's is the resulting .pixi,

![image](https://github.com/prefix-dev/pixi/assets/98826280/4af73499-67ec-48cf-9cf1-f81906137e17)

### Expected behavior

Pixi should detect this and it should result in an invalid pixi.toml.
