### ISSUE TITLE
pixi.lock file is not stable

### ISSUE THREAD

**Issue by kdheepak** [prefix-dev/pixi#1535]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I have an issue when using `pixi` where the `pixi.lock` file changes even without any changes to the `pyproject.toml`. This happens in an internal project and I'm not able to share the exact code where this occurred. I copied over the parts of the `pyproject.toml` into a MWE repo but I'm currently not able to reproduce it as part of this separate test repo. 

Here's where I'm attempting to reproduce the issue:

https://github.com/kdheepak/pixi-test/blob/main/pyproject.toml

```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pixi-test"
requires-python = ">=3.11"
dependencies = [
  "pyomo",
  "matplotlib",
  "numpy",
  "pandas",
  "plotly",
  "colour",
  "altair",
  "psutil",
  "networkx",
  "highspy",
]
authors = [
  { name = "model", email = "email@email.com" }
]
readme = "README.md"
license = {file = "LICENSE"}
dynamic = ["version"]

[project.optional-dependencies]
test = ["pytest"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.pypi-dependencies]
pixi_test = { path = ".", editable = true }

[tool.pixi.dependencies]
ipython = ">=8.25.0,<8.26"
python = ">=3.12.4,<3.13"
jupyter = ">=1.0.0,<1.1"
jupyterlab = ">=4.2.2,<4.3"
pixi-kernel = ">=0.3.0,<0.4"

[tool.pixi.feature.test.tasks]
test = "pytest"

[tool.setuptools]
packages = ["pixi_test"]

# Environments
[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
```

Here's an example of different sections of the diff:

<img width="1512" alt="image" src="https://github.com/prefix-dev/pixi/assets/1813121/7b4ae631-a597-4fe7-8446-eeb9dfcb119e">

<img width="1512" alt="image" src="https://github.com/prefix-dev/pixi/assets/1813121/ae6ab650-8ca6-4136-9bb6-bf6ca1cb95e7">

It appears to be sections of the file moved around. In this case, the only change I made was to the `.envrc` file where I removed `watch pixi.lock`.

Maybe the `pixi.lock` file should be sorted before being written to disk?

### Issue description

If I'm able to reproduce it here:

https://github.com/kdheepak/pixi-test/blob/main/pyproject.toml

I'll link to the exact commit diff. The problem seems to happen randomly and intermittently.

### Expected behavior

I would like the `pixi.lock` file to not change unless there's changes to the `pyproject.toml` file.
