### ISSUE TITLE
`pixi task list` panics if any feature has non-compatible platforms

### ISSUE THREAD

**Issue by hoxbro** [prefix-dev/pixi#1547]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi task list
pixi task list -e test-unit
```
``` toml
[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
install = 'python -m pip install --no-deps --disable-pip-version-check -e .'

[environments]
test-gpu = ["test-gpu"]
test-unit = ["test-unit"]

[feature.test-unit.tasks]
test-unit = "echo test-unit"

[feature.test-gpu]
# platforms = ["linux-64"]   # Works if on Linux
platforms = ["win-64"]   # Fails if on Linux

[feature.test-gpu.tasks]
test-gpu = "echo test-gpu"
```

### Issue description

`pixi task list` fails if any feature has non-compatible platforms. Currently, it panics:

![image](https://github.com/prefix-dev/pixi/assets/19758978/4e89a462-8ed3-4c81-8229-fb77549e9bc5)

### Expected behavior

Either hide non-compatible platforms task or show them with a message they are not available on the users platform
