### ISSUE TITLE
`system-requirements` ignored when using `no-default-feature = true`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#1549]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "my-project"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.18.0"

[dependencies]
python = "*"

[feature.lint.dependencies]
ruff = "*"

[environments]
lint = { features = ["lint"], no-default-feature = true }
```

### Issue description

When running `pixi run -e lint ruff --version`, i get the error 

```
The current system has a mismatching virtual package. The project requires '__linux' to be at least version '5.10' but the system has version '4.18.0'
```

### Expected behavior

IMO it would be more sensible if `system-requirements` would be included in the default feature similar to `channels` and `platforms`.

WDYT?

**Comment by pavelzw** [comment]
Although, with packages Like cuda this light be Not as clear… lets keep the behavior as is

**Comment by noamgot** [comment]
I just realized that the problem I mentioned in #346 ( https://github.com/prefix-dev/pixi/issues/346#issuecomment-2561086221 ) occurs due to my environment having `no-default-feature = true`, but I don't understand why does it make sense?

**Comment by ruben-arts** [comment]
@noamgot all tables are part of the "default" feature if they are not specified specifically. e.g. `[system-requirements]` could be read as `[feature.default.system-requirements]`

I've improved the debugablity of the system requirements by adding them to `pixi info` in #2753. I hope that helps

**Comment by noamgot** [comment]
@ruben-arts I now understand this technically, but shouldn't some tables be "project-global"? 

In my vase, I set `no-default-feature = true` for a lint environment, as I wanted to exclude the package dependencies, which are irrelevant for linting.  Obviously, I want to keep it that way, but then I'll have to set the `system-requirements` for every feature (that relates to no-default-feature environment). Is there a best practice to handle this?

**Comment by noamgot** [comment]
UPDATE: as a workaround I did the following:

```toml

[tool.pixi.feature.sysreq.system-requirements]
linux = "4.15"

[tool.pixi.environments]
default = { features = ["sysreq", "test", "dev"], solve-group = "default" }
test = { features = ["sysreq", "test"], solve-group = "default" }
prod = { features = ["sysreq", "prod"], solve-group = "default" }
lint = { features = ["sysreq", "lint"], no-default-feature = true }
docs = { features = ["sysreq", "docs"], no-default-feature = true }
```
This way I define the system-requirements just once, and it's available for all environments (that was enough for my case)
