### ISSUE TITLE
Support "nested pixi dependencies" (for git dependencies)

### ISSUE THREAD

**Issue by Zaubeerer** [prefix-dev/pixi#1569]
## Problem

I have a package B, with the following `pyproject.toml`:

```toml
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "core"
version = "0.0.1"
description = "core package"
requires-python = ">=3.9, <3.11"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
package_a = { git = "ssh://git@github.com/package_a.git", rev = "asdfasdfasfd" }
core = { path = ".", editable = true }
```

It installs the git dependency `package_a`, which itself has the following `pyproject.toml`: 

```toml
[project]
name = "package_a"
version = "0.1.0"
description = "Add a short description here"
requires-python = "< 3.11"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tool.pixi.pypi-dependencies]
vpp_optimization = { path = ".", editable = true }
ortools = "*"


[tool.pixi.tasks]

[tool.pixi.dependencies]
pip = ">=24.0,<25"
pytest = ">=8.2.2,<8.3"
python-dotenv = "*"
```

However, it seems like `ortools` and `python-dotenv` are not installed in the environment created with `package_b` that installs `package_a` as dependency.

The `package_a` dependencies are only installed in the environment created when running `pixi install` in `package_a` directly.

I just created a minimal reproducible example as screenshot:

![image](https://github.com/prefix-dev/pixi/assets/60844432/f0487213-e2f2-4eb5-a3ca-0d0f77b1d46f)

## Current workarounds

1. "pip dependencies"
- OK, another way would be to add the dependencies as `dependencies=[]` in normal `pyproject.toml` format, not leveraging pixi. In that case, the dependencies would be superseded by the pixi dependencies if additionally added in the `[pypi.dependencies]`, but only, when installing the `pyproject.toml` directly, not as dependency.
2. "setting all dependencies in the top level pixi `pyproject.toml`"
- This is not very clean, but does the job and avoids pip related dependency resolution problems.
3. publishing the packages to 

## Proposed solution

It would be great if one can just reference the respective git revision as dependency and pixi resolves the packages iteratively based on the pixi dependencies.

**Comment by ruben-arts** [comment]
This is a really high value idea indeed, we previously tempt to refer to this feature as "workspaces" which in theory do exactly this but then from a path instead of a git dependency. 

Here is my reply to the discussion (from already some time ago) https://github.com/prefix-dev/pixi/discussions/387#discussioncomment-7253056

What we might already implement more quickly instead of the full building logic mentioned in the discussion is the retrieval of the dependencies from a source dependency, like we can for `pypi-dependencies` without building it first. Currently you can only depend on a `conda` or `pypi` project and  a `pixi` project is neither but rather a combination.

_This comment solves nothing, just giving some background information._

**Comment by atancoder** [comment]
I'm running into this same issue when looking to migrate our python codebase to use Pixi. In our case, we're utilizing a local path instead of a git path
```
[tool.pixi.pypi-dependencies]
package_a = { path = "../package_a", editable= true}
```

When trying to create an environment for package b, package a's dependencies (e.g ortools) in the `tool.pixi.pypi-dependencies` table don't get installed. However, if you instead, put package a's dependencies under the main `dependencies`, then it does get installed. I assume pixi doesn't resolve dependencies recursively? 

Is the solution to just abandon `tool.pixi.pypi-dependencies` and put everything under dependencies? Although one challenge we have is that we have nested local editable dependencies. e.g in pkg a, we can have also have a dependency on another local pkg
```
[tool.pixi.pypi-dependencies]
package_d = { path = "../package_d", editable= true}
```

And AFAIK, you can't quite put this into the normal dependencies format in editable mode?
e.g
```
dependences = ["package_d @ file://../package_d]
```

**Comment by ruben-arts** [comment]
We're working on the `pixi build` feature, linked to this milestone: https://github.com/prefix-dev/pixi/issues/1654

It's currently moving so fast it's hard to make a good overview, we're also still making breaking changed in the format. So please give us some more time. Beginning next year we'll have a usable preview and we like to get alot of feedback on it. I'll do a bigger announcement on our channels. 

To get a sneak peak you could look at some of our examples that work with the workspace logic:
- https://github.com/prefix-dev/pixi/blob/main/examples/rich_example/pyproject.toml#L36
- https://github.com/prefix-dev/pixi/blob/main/examples/cpp-sdl/pixi.toml

**Comment by ccharp** [comment]
> To get a sneak peak you could look at some of our examples that work with the workspace logic:
    https://github.com/prefix-dev/pixi/blob/main/examples/rich_example/pyproject.toml#L36

I get 404. 

Any updates on this or anything I can do to help push it along?

**Comment by lucascolley** [comment]
https://github.com/prefix-dev/pixi/tree/main/examples/pixi-build/recursive-run-dependencies should serve as a sneak-peek relevant to this issue (for nested source deps).

We are building up a testsuite at e.g. https://github.com/prefix-dev/pixi-build-testsuite/pull/9, the scope of which goes past this issue but you may also be interested in that repo if you are looking for `pixi build` examples.

> anything I can do to help push it along?

I would say we are still not quite ready for it, but soon it would be useful for you to try it out on the workspaces in which you are interested and let us know what does/doesn't work. Maybe after the next Pixi and `pixi-build-backends` releases would be a good time. You could follow along my testing at https://github.com/rgommers/pixi-dev-scipystack/pull/20 and emulate it for your workspaces as it develops.

Maybe someone else on the team can think of other ways you could help, though!

**Comment by ccharp** [comment]
Thanks for the quick reply, @lucascolley. So far Pixi has been head and shoulders above Poetry, which I've migrated from, and this is the final feature my team needs.

> I would say we are still not quite ready for it, but soon it would be useful for you to try it out on the workspaces in which you are interested and let us know what does/doesn't work.

I'm happy to put it through some user testing when it's ready! I'll stay subscribed to this thread.

**Comment by baszalmstra** [comment]
It took some time but we just released the new build protocol. We are maintaining a rolling distribution of the build backends on the `pixi-build-backends` channel and a stable one on `conda-forge`. For the time being you have to use the `pixi-build-backends `channel to install the build backends. You can do this with:

```toml
[package.build]
backend = { name = "pixi-build-python", version = "0.*" }
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
```

With this you can build python packages directly into conda packages (including transitive dependencies) which can be consumed by pixi itself.
