### ISSUE TITLE
Editable package not available from subfolders

### ISSUE THREAD

**Issue by pietrolesci** [prefix-dev/pixi#1622]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Folder structure
```shell
├── pixi.lock
├── pyproject.toml
├── README.md
├── scripts
│   └── ...
└── src
    ├── __init__.py
    ├──...
    ├── src.egg-info
```

pyproject.toml
```toml
[project]
  authors = [ { name = "<name>", email = "<email>" } ]
  dependencies = [
    "bitsandbytes>=0.43.1,<0.44",
    "colorlog>=6.8.2,<6.9",
    "datasets>=2.20.0,<2.21",
    "einops>=0.8.0,<0.9",
    "hf-transfer>=0.1.6,<0.2",
    "huggingface-hub>=0.23.4,<0.24",
    "hydra-colorlog>=1.2.0,<1.3",
    "hydra-core>=1.3.2,<1.4",
    "hydra-joblib-launcher>=1.2.0,<1.3",
    "hydra-submitit-launcher>=1.2.0,<1.3",
    "ipykernel>=6.29.5,<6.30",
    "ipywidgets>=8.1.3,<8.2",
    "lightning>=2.3.3,<2.4",
    "nvitop>=1.3.2,<1.4",
    "omegaconf>=2.3.0,<2.4",
    "pandas>=2.2.2,<2.3",
    "plotnine>=0.13.6,<0.14",
    "polars>=1.1.0,<1.2",
    "ruff>=0.5.2,<0.6",
    "safetensors>=0.4.3,<0.5",
    "srsly>=2.4.8,<2.5",
    "tensorboard>=2.17.0,<2.18",
    "torch>=2.3.1,<2.4",
    "torchmetrics>=1.4.0.post0,<1.4.1",
    "transformers>=4.42.4,<4.43",
  ]
  description = "Add a short description here"
  name = "src"
  requires-python = ">=3.10,<3.11"
  version = "0.1.0"

[build-system]
  build-backend = "setuptools.build_meta"
  requires      = [ "setuptools" ]

[tool.pixi.project]
  channels  = [ "conda-forge" ]
  platforms = [ "linux-64" ]

[tool.pixi.pypi-dependencies]
  src       = { path = ".", editable = true }
```

Once installed, the error is reproducible by simply

```shell
cd scripts
pixi shell
python
>>> import src
```

**version: pixi 0.25.0**

### Issue description

`ModuleNotFoundError: No module named 'src'`

Whenever I try to access the src module while not in the root forder---e.g., `root/scripts`---the `src` module cannot be found. Is this expected?

I am trying to move away from a conda+poetry workflow and did not have this issue. For example, in poetry by specifying the `src` among the packages 

```toml
[build-system]
requires      = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name        = "src"
version     = "0.1.0"
description = "memorisation"
authors     = [ "Pietro Lesci <pietrolesci@outlook.com>" ]
license     = "Apache-2.0"
readme      = "README.md"
packages    = [ { include = "src" } ] 
```

I can find it from anywhere in my system once the correct conda environment is activated.

### Expected behavior

Once the pixi shell is activated, the src package should be visible from any folder under the root

**Comment by olivier-lacroix** [comment]
Hi @pietrolesci I don't think your project name (and editable dependency name) should be `src`, but rather, the name of the folder where your pyproject.toml is located.

**Comment by pietrolesci** [comment]
Hi @olivier-lacroix, since the package's name is arbitrary, does it matter? Can this be the cause?

I am following the [doc](https://pixi.sh/latest/tutorials/python/#lets-get-started) and being consistent with the flat-layout

**Comment by olivier-lacroix** [comment]
I would not use src as package name for a flat layout. Given the alternative is … the src layout 😀.

**Comment by olivier-lacroix** [comment]
The package name to refer to in your pyproject.toml is actually the name of the folder _containing_ the pyproject.toml.

For a flat layout, you should typically have :
```
my-package-name
├── pixi.lock
├── pyproject.toml
├── README.md
├── scripts
│   └── ...
└── my_package_name
    ├── __init__.py
    ├──...
```

In which case your pyproject.toml will contain

```toml
[project]
  name = "my-package-name"

...

[tool.pixi.pypi-dependencies]
  my-package-name = { path = ".", editable = true }
```

Notice the use of '-' in the root folder, for the package name, versus the use of '_' for the inner folder, for the module import name. I know, this can be confusing :-).

I noticed the current pixi documentation does not differentiate between the two. I have created a PR to fix it https://github.com/prefix-dev/pixi/pulls
