### ISSUE TITLE
problem with editable pypi packages and solve-groups

### ISSUE THREAD

**Issue by kcajf** [prefix-dev/pixi#1632]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Folder structure:
```
tree -h .
.
├── [ 4.0K]  my_python_proj
│   ├── [ 4.0K]  mylib
│   │   └── [    1]  __init__.py
│   └── [  155]  setup.py
├── [  16K]  pixi.lock
└── [  422]  pixi.toml
```

`pixi.toml`:
```toml
[project]
name = "proj"
version = "0.1.0"
channels = [ "conda-forge" ]
platforms = ["linux-64"]

[tasks]

[system-requirements]
linux = "4.18"

[dependencies]
python = "3.11.*"

[feature.my-feature.pypi-dependencies]
seagull = { path = "./my_python_proj", editable = true }

[environments]
env1 = { features = ["my-feature"], solve-group = "test-group" }
env2 = { features = ["my-feature"], solve-group = "test-group" }
```

`__init__.py` is empty

`setup.py` contains:
```python
import setuptools

setuptools.setup(
    name="my_python_proj",
    version="0.0.0",
    packages=setuptools.find_packages(),
    install_requires=[],
)
```

To reproduce:
```
pixi --version
pixi 0.25.0

pixi run --environment env1 python -c 'import mylib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'mylib'
```

If you change the solve-groups to be different (e.g. change one of them to `test-group-2`), `import mylib` will work.

### Issue description

It seems that when you use solve-groups and editabled pypi packages, sometimes the packages don't end up getting included in the solve.

### Expected behavior

it should be possible to import these packages
