### ISSUE TITLE
Feature design proposal/prototype: `pixi build` 

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#1654]
As https://github.com/prefix-dev/pixi/discussions/793 didn't give us enough discussion to finalize a design that fit our ideas, so we've started an ultra simple prototype. This issue is to share the status and hopefully fetch more input from our contributors. 

### The goal:
- Allow pixi to call build tools to build packages for distribution.
- Allow pixi projects to depend on pixi project, which invokes build to build the dependency on the spot.

### Out of scope
- We're not looking at mixed `conda` and `pypi` projects. 

### The `build` section in the manifest file
```toml
# Users can define multiple build backend
[build.conda]
# These requirements are installed in a pixi specific build environment.
# This tool is going to do the actual build.
requires = { pixi-build-python = "3.12" } 
# A pixi task to run the build. Uses the normal `pixi task` workflow.
# Including depends-on, inputs, outputs, etc.
task = { cmd = "pixi-build-conda", ..., inputs = ["*.py"] }

# We allow extra metadata in a `tool` section. 
# This enables build-tool specific configuration to be stored.
[tool.pixi-build-python]
build = "noarch"
```

### The `build` command
```pixi build conda```
- Pixi will create an build environment where it installs the required tool.
- Pixi will run the `build.conda.task` in that environment.
- The build tool will do _its_ thing, and notify pixi with the result.

### The build tool.
We want users to not get locked in by our build backend for which tools they can use to build packages. 
Building a backend should be simple and straight forward, with a small communication layer between pixi and the tool.
But most logic should happen in the build tool.

- The build tool reads directly from the pixi manifest. (e.g. `[tool.pixi-build-python]`)
- The build tool invokes the actual build. e.g. using or other backend tools e.g. `rattler-build`.

### Related work
- Refactor pixi into crates:
   - #1656: Extract manifest into a crate for possible reuse
   - #1661
   - #1662 
   - #1678 
   - #1700
   - #1684
   - #1699
   - #1712
   - #1717
   - #1718
   - #1722
   - #1723
   - #1725
   - #1736
   - #1741
- #1653: Add `[build]` section to pixi manifest.
- #1728
