### ISSUE TITLE
`pixi run` swallows CLI flags

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#167]
```toml
[...]
[commands]
test = "pytest"

[dependencies]
python = "*"
pytest = "*"
[...]
```

```bash
❯ pixi run python --version
Python 3.11.4
❯ pixi run pytest --version
pytest 7.4.0
❯ pixi run test --version
[starting pytest]
```

I understand that we don't want to support command line flags for commands (similar to pnpm, I don't know about cargo) since we could execute arbitrary shell things in there. But then we should print out a warning that this is not supported.
