### ISSUE TITLE
cannot download package

### ISSUE THREAD

**Issue by brian316** [prefix-dev/pixi#1676]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.


### Reproducible example

pyproject.toml file
```toml
[project]
name = "project"
version = "0.1.0"
description = "test"
authors = []
requires-python = ">=3.9"

[tool.pixi.pypi-dependencies]
pytoda = { git = "https://github.com/PaccMann/paccmann_datasets@0.2.5#egg=pytoda"}

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["bmfm_inference_service"]
```


### Issue description

error:
```shell
pixi install
  ⠙ default:linux-64     [00:00:00] resolving guacamol==0.5.5                                                                                                                                                                                                                  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ├─▶ Failed to download and build `pytoda @ git+https://github.com/PaccMann/paccmann_datasets/@0.2.5#egg=pytoda`
  ├─▶ Git operation failed
  ├─▶ failed to fetch into: /home/dev/.cache/rattler/cache/uv-cache/git-v0/db/d06a38293fe867f4
  ╰─▶ process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/PaccMann/paccmann_datasets/@0.2.5#egg=pytoda' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)
      --- stderr
      remote: Not Found
      fatal: repository 'https://github.com/PaccMann/paccmann_datasets/@0.2.5#egg=pytoda/' not found
```

I used to be able to install this, but now i cant plus a few other packages. i can install the package without the tags at the end but i need them.

### Expected behavior

pytoda installed

**Comment by brian316** [comment]
downgrading pixi to `pixi 0.24.2` from `0.26.1` fixes my issue....

**Comment by ruben-arts** [comment]
Hi @brian316, thats very unfortuanate.

I assume this has to do with the update to the latest `uv` in `pixi` which might have altered this behavior. 
As a workaround you could use the `tag = "0.2.5"` in the toml file which did work for me:
```toml
[project]
name = "project"
version = "0.1.0"
description = "test"
authors = []
requires-python = ">=3.9"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]


[tool.pixi.pypi-dependencies]
pytoda = { git = "https://github.com/PaccMann/paccmann_datasets", tag = "0.2.5" }

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["bmfm_inference_service"]
```
