### ISSUE TITLE
Add support for global configuration

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#172]
It would be nice to support a global configuration file (for example `$XDG_CONFIG_HOME/pixi/pixirc`) in which you can specify channel aliases.

Like this, one would be able to support channel mirrors and it's possible not to ship credentials for custom channels in `pixi.toml`.

Some thoughts:

```yml
# all channels are by default "https://path-to-custom-quetz-server/get/<channel-name>"
channel-alias: https://path-to-custom-quetz-server/get

custom-channels:
  - conda-forge:
      http://custom-conda-forge-mirror
  - cf-staging:
      https://conda.anaconda.org/cf-staging
```

This would allow pixi to be used in locked down systems that don't allow `conda-forge` without modifying the `pixi.toml`.
