### ISSUE TITLE
PyPI dependencies raise error when falling back from osx-arm64 to osx-64

### ISSUE THREAD

**Issue by ekiefl** [prefix-dev/pixi#1750]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

This is the pixi.toml. It is a stripped down version of the "multiple machines from one project" example in the [multi-environment docs](https://pixi.sh/latest/features/multi_environment/#real-world-example-use-cases)

```toml
[project]
name = "my-ml-project"
description = "A project that does ML stuff"
authors = ["Your Name <your.name@gmail.com>"]
channels = ["conda-forge", "pytorch"]
# All platforms that are supported by the project as the features will take the intersection of the platforms defined there.
platforms = ["win-64", "linux-64", "osx-64"]

[dependencies]
python = "3.11.*"

[pypi-dependencies]
matplotlib-base = ">=3.8.2,<3.9"

[feature.cuda]
platforms = ["win-64", "linux-64"]
channels = ["nvidia", {channel = "pytorch", priority = -1}]
system-requirements = {cuda = "12.1"}

[feature.cuda.dependencies]
pytorch-cuda = {version = "12.1.*", channel = "pytorch"}

[feature.cpu]
platforms = ["win-64", "linux-64", "osx-64"]

[environments]
cuda = ["cuda"]
default = ["cpu"]
``` 

On a osx-arm64 machine, I get the following error:

```bash
▶▶ pixi install
 WARN osx-arm64 (Apple Silicon) is not supported by the pixi.toml, falling back to osx-64 (emulated with Rosetta)
  × Unable to solve pypi dependencies for the cuda environment because no compatible python interpreter can be installed for the current platform
   ╭─[7:13]
 6 │ # All platforms that are supported by the project as the features will take the intersection of the platforms defined there.
 7 │ platforms = ["win-64", "linux-64", "osx-64"]
   ·             ────────────────┬───────────────
   ·                             ╰── even though the projects does include support for 'osx-arm64'
 8 │
   ╰────
    ╭─[18:13]
 17 │ [feature.cuda]
 18 │ platforms = ["win-64", "linux-64"]
    ·             ───────────┬──────────
    ·                        ╰── feature 'cuda' does not support 'osx-arm64'
 19 │ channels = ["nvidia", {channel = "pytorch", priority = -1}]
    ╰────
  help: Try converting your [pypi-dependencies] to conda [dependencies]
```

If you move the matplotlib-base dependency into `dependencies`, it works.

### Issue description

I believe this issue is related to https://github.com/prefix-dev/pixi/issues/1404

Basically, on macOS, I have dependencies that don't have support for osx-arm64, which is what pixi determines my platform to be. So I have to fallback to osx-64 by dropping support for osx-arm64, which according to this warning is emulated via Rosetta:

```
 WARN osx-arm64 (Apple Silicon) is not supported by the pixi.toml, falling back to osx-64 (emulated with Rosetta)
```

This works well, except for cases like the MRE above. I think that this is a bug, because although the warning says that we're falling back to osx-64, the platform is still being treated as osx-arm64 during the pypi dependency resolution, which subsequently raises pixi errors.

### Expected behavior

One should be able to add pypi dependencies when emulating osx-64.
