### ISSUE TITLE
Have the ability to `source` `.sh` files to setup an environment.

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#176]
After building a workspace with `colcon` I want to be able to source the `setup.sh` before running any commands or starting the shell. I want to be able to define that in the `pixi.toml` so I dont have to do it manually. These scripts are often placed somewhere relative to where the build command is run, so there needs to be a way to specify the paths relative to the `pixi.toml`

So a possible idea to define those scripts would be:
```toml
# Used for the normal `run` and `shell`
[activation]
script = ["path/to/setup.sh", "path/to/other/setup.sh"]

activation.script = "path/to/setup.sh"

# Specific activation files for the commands
[commands]
controller = {cmd = "ros2 run turtlesim_controller controller" activation="install/setup.sh"}
echo_vel = "ros2 topic echo /cmd_vel" # doesn't need the colcon workspace 
```
