### ISSUE TITLE
failed to solve OSX platform path requirements while installing on linux

### ISSUE THREAD

**Issue by oxinabox** [prefix-dev/pixi#1788]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

This example uses [cplex community edition](https://www.ibm.com/account/reg/us-en/signup?formid=urx-20028)
but you could substitute anything with `setup.py` that is separately installed locally
where that setup.py file ends up at a different location depending on the OS.
I want this same pixi.toml to work for myself on linux, and my colleagues on OSX

pixi.toml:
```toml
[project]
name = "test"
version = "0.1.0"
platforms = ["osx-arm64", "linux-64"]
channels = ["conda-forge"]

[dependencies]
python = "3.9.*"

[target.osx-arm64.pypi-dependencies]
cplex = { path = "/applications/cplex_studio2211/cplex/python/3.9/arm64_osx" }

[target.linux-64.pypi-dependencies]
cplex = { path = "/opt/ibm/ilog/cplex_studio_community2211/cplex/python/3.9/x86-64_linux/"}
```

Here is the error i get

```shell
❯ pixi install                                              
  × failed to solve the pypi requirements of 'default' 'osx-arm64'
  ├─▶ error while canonicalizing /Applications/CPLEX_Studio2211/cplex/python/3.9/arm64_osx
  ╰─▶ No such file or directory (os error 2)
```

### Issue description

It seems like it is trying to resolve the OS dependency even though I am on linux.

### Expected behavior

This should just work,
and should install on linux using the path given.

**Comment by ruben-arts** [comment]
This is by design, in this case unfortunately. We solve the complete manifest for every machine at once to make sure that the project you define works on all platforms you want it too. 

I can see how that workflow doesn't align with yours.  Would you mind me changing this issue into a feature request for the behavior you need?

**Comment by oxinabox** [comment]
I thought that might be the case.
I think in general that is pretty hard if you allow local paths.
(Since you can't control what someone is doing on those paths)

> Would you mind me changing this issue into a feature request for the behavior you need?

Go ahead.

**Comment by oxinabox** [comment]
As a workaround I have made a shell script that creates a symlink to the platform dependent path,
and then got rid of the `[platform...]` lines and just put
```toml
[pypi-dependencies]
cplex = { path = "./cplex/" }
```
