### ISSUE TITLE
pyproject dependency env markers not work

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#1801]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
authors = [{ name = "ZhengYu, Xu", email = "zen-xu@outlook.com" }]
description = "Add a short description here"
name = "playground"
requires-python = ">=3.7,<3.12"
version = "0.1.0"
dependencies = [
    'pyarrow >=11.0.0; python_version >= "3.7" and python_version < "3.8"',
    'pyarrow ==16.1.0; python_version >= "3.8" and python_version < "3.12"',
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py37.dependencies]
python = "3.7.*"

[tool.pixi.tasks]

[tool.pixi.environments]
default = { features = ["py311"], solve-group = "py311" }
py311 = { features = ["py311"], solve-group = "py311" }
py37 = { features = ["py37"], solve-group = "py37" }
```

### Issue description

I am installing different versions of pyarrow by restricting the python_version, but it seems that pixi fail to resolve it.

<img width="1769" alt="image" src="https://github.com/user-attachments/assets/c6d424d7-4a39-440a-8c7f-08066c128eb6">

### Expected behavior

Correctly resolve the dependencies.
