### ISSUE TITLE
pixi shell not writing temp file

### ISSUE THREAD

**Issue by funnell** [prefix-dev/pixi#1811]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi shell
 source "/tmp/tfunnell/pixi_env_VQv.fish"
Error starting shell: No such file or directory (os error 2)
```

```toml
[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "sv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
linux = "4.18.0"

[dependencies]
python = ">=3.12.5,<4"
r-base = ">=4.4.1,<5"
```

### Issue description

pixi shell expects a file in my tmp directory, but the tmp directory is empty.
I'm using pixi 0.27.1

### Expected behavior

pixi shell should not produce the above error.
