### ISSUE TITLE
Support 'publish' like what poetry does

### ISSUE THREAD

**Issue by raceychan** [prefix-dev/pixi#1841]
### Problem description

This feature should be very similar to what poetry has right now. By typing 'pixi publish', user should be able to upload their package to pypi or similar organizations.

**Comment by ruben-arts** [comment]
We're currently working on `pixi build` which would be the first step towards a `publish`.

**Comment by tdejager** [comment]
Do note that as a small workaround you can use pixi tasks for this. 

E.g something like:
```toml
#... rest of toml
[tool.pixi.feature.publish.dependencies]
# For building wheel using hatch
hatch = "*"
# Uploading package
twine = "*"


[tool.pixi.environments]
# Use this env for publishing:
publish = { features = ["publish"] }

# This has tasks for building and uploading
# to custom GCP instance
[tool.pixi.feature.publish.tasks]
# Build into a wheel using hatch
build = { cmd = "hatch build", inputs = ["say_hi/*"], outputs = ["dist/*"] }
# Upload to custom GCP registry using twine
publish = { cmd = "twine upload --skip-existing dist/*", depends-on = [
  "build",
] }
```
