### ISSUE TITLE
Task env variables on win-64

### ISSUE THREAD

**Issue by eightysteele** [prefix-dev/pixi#1843]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
# pyproject.toml

[tool.pixi.tasks.echo]
cmd = "echo $HELLO"
env = { HELLO = "world?" }

[tool.pixi.target.win-64.tasks.echo-win]
cmd = "echo $HELLO_WIN"
env = { HELLO_WIN = "world?" }
```

Then from powershell:

```powershell
pixi run echo
Pixi task (echo in default): echo $HELLO
glob: no matches found 'C:\Users\eighty\b3d/world?'

pixi run echo-win
Pixi task (echo-win in default): echo $HELLO_WIN
glob: no matches found 'C:\Users\eighty\b3d/world?'
```

Note that this works:

```powershell
$env:HELLO="world!"
pixi run echo
Pixi task (echo in default): echo $HELLO
world!

$env:HELLO_WIN="windows world!"
pixi run echo-win
Pixi task (echo-win in default): echo $HELLO_WIN
windows world!
```

### Issue description

Default `env` variables in a task are not recognized on `win-64`.

### Expected behavior

I would expect default env variables in a task to be recognized on `win-64`. :)

**Comment by eightysteele** [comment]
If relevant, we're using `hatchling`:

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
```

With:

```shell
λ pixi --version
pixi 0.27.1
```

**Comment by baszalmstra** [comment]
The reason this happens is because `?` is recognized as a glob pattern by deno task shell which is the shell interpreter used by pixi. I think this is also not unique to windows or powershell.

You environment variable `HELLO` is replaced with its value in the task command. So 

```
echo $HELLO
```

becomes

```
echo world?
```

The question mark in this case will be interpreted as a glob string which will result in the error you are seeing:

```
glob: no matches found 'C:\Users\eighty\b3d/world?'
```

When you do 

```
$env:HELLO="world!"
```

you override the `HELLO` environment variable and instead you use an exclamation mark instead of question mark which is not a glob character. Thats why it works. If you would instead use `$env:HELLO="foobar?"` you would see a similar issue.

To work around this issue you can escape the contents of the variable, e.g.:

```toml
[tool.pixi.tasks.echo]
cmd = "echo \"$HELLO\""
env = { HELLO = "world?" }
```

Which results in:

```
❯ pixi run echo
✨ Pixi task (echo): echo "$HELLO"
world?
```
