### ISSUE TITLE
Allow alternative cross platform shells to be used instead of `deno`

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1844]
### Problem description

1. Can `nushell` be provided/integrated as an alternative to the deno shell? or is it not allowed due to license?
2. how about specify the shell to use (as a configuration in the pixi.toml/pyproject.toml) and `pixi` uses that shell if it's available in `PATH`/installed in system and use it? e.g , powershell and nushell both are avialble for linux, windows and mac  so the commands here would truly be cross platform and also come with a broad user based compared to `deno`
3. This will also give a huge boost to writing complex tasks and increase flexiblity for those authoring them.

**Comment by Hofer-Julian** [comment]
Hey @vigneshmanick!

We are aware of the limitations of deno task shell. `nushell` would be an option, but for now it is too unstable and probably also a bit too big to ship with pixi.

We could allow that your shell is one of you conda dependencies, if we can't manage to integrate a small, cross-platform shell into pixi.

**Comment by baszalmstra** [comment]
You can already do this!

```toml
[project]
channels = ["conda-forge"]
name = "nu"
platforms = ["win-64"]

[tasks]
hash = "nu -c 'http get https://google.com | hash sha256'"

[dependencies]
nushell = ">=0.96.1,<0.97"
```

```
❯ pixi run hash
✨ Pixi task (hash): nu -c 'http get https://google.com | hash sha256'
69eb2456069f51ebd98a41c01750cccdb52e39791334dea197dfc83c7d99b7de
```

It would be nice if you can just add `interpreter = "nu"` to your task though! Would you be able to open a PR?
