### ISSUE TITLE
Changing the rev of a pypi dependency causes a git error

### ISSUE THREAD

**Issue by Mozartenhimer** [prefix-dev/pixi#1870]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Since this involves updating a pixi.toml,  I have an original.toml and an updated.toml The only difference is the commit hash.
On version pixi 0.27.1.
repo.sh This script is the operations to reproduce.
```bash
set -ex
pixi clean cache --pypi
pixi --version
cp original.toml pixi.toml
pixi install 
rm -f pixi.toml
cp updated.toml pixi.toml
pixi install
```

orignal.toml
```toml
[project]
name = "min-rep"
version = "0.1.0"
channels = [
  "conda-forge",
]


platforms = ["linux-64"]
[dependencies]
python = ">=3.11"

[pypi-dependencies]
requests = { git = "https://github.com/psf/requests.git", rev = "877892e67e22e25bd3cb0dec780bf45c0e67026e" }
```
updated.toml
```toml
[project]
name = "min-rep"
version = "0.1.0"
channels = [
  "conda-forge",
]


platforms = ["linux-64"]
[dependencies]
python = ">=3.11"

[pypi-dependencies]
requests = { git = "https://github.com/psf/requests.git", rev = "a3ce6f007597f14029e6b6f54676c34196aa050e" }
```

### Issue description

When changing the rev of a pypi git project, you get a git error of.
```
▶ Failed to download and build `requests @ git+https://github.com/psf/requests.git@a3ce6f007597f14029e6b6f54676c34196aa050e`
  ├─▶ Git operation failed
  ╰─▶ process didn't exit successfully: `git reset --hard a3ce6f007597f14029e6b6f54676c34196aa050e` (exit status: 128)
      --- stderr
      fatal: Could not parse object 'a3ce6f007597f14029e6b6f54676c34196aa050e'.
 `
```
It looks like pixi thinks it's cached, but the commit is not actually cached.

Clearing the cache can work around this problem.

### Expected behavior

I expect the environment to install.
