### ISSUE TITLE
`pixi add pip` results in wrong matchspec and fails during install

### ISSUE THREAD

**Issue by vigneshmanick** [prefix-dev/pixi#1878]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init --format pyproject  test-proj
cd test-proj
pixi add pip
pixi install
# Errors out because the versions of pip is not right
```

```toml
[project]
dependencies = []
name = "test-proj"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
test-proj = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
pip = ">=24.2,<24.1"

```

### Issue description

Not sure if it's just with my machine or genreally the case , i just tested with a dummy project just to be sure and can reproduce it.

Pixi add seems to mix up the min and max versions of the added dependencies and fails install as a result. Currently i am facing this with just adding `pip` as  a dependency.

### Expected behavior

should be 

```toml
[tool.pixi.dependencies]
pip = ">=24.1,<24.2"
```

NOTE: I have set `pinning-strategy` to `minor`

Edit: I am pretty sure this has to do with the pinning-strategy set to minor, when it's set to semver, the issue doesn't occur since the upper bounds are much higher.
