### ISSUE TITLE
Feature: Retrieve dependencies in chained pixi projects

### ISSUE THREAD

**Issue by julian-belina** [prefix-dev/pixi#1886]
### Problem description

Hello,

It would be nice to be able to include the dependencies specified in the pyproject.toml of an old project in a new project. So that all the dependencies from the old and new projects are also available in the environment of the new project.

My old pixi project
```toml
[project]
authors = [{name = "julian-belina", email = "56728940+julian-belina@users.noreply.github.com"}]
dependencies = []
description = "Add a short description here"
name = "my_old_project"
requires-python = ">= 3.10"
version = "0.1.0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.dependencies]
python = { version = ">=3.10", channel = "conda-forge" }

[tool.pixi.pypi-dependencies]
pandas="*"
```

My New pixi project

```toml
[project]
name = "my_new_project"
authors = [{name = "julian-belina", email = "56728940+julian-belina@users.noreply.github.com"}]
dependencies = []
description = "Add a short description here"
name = "my_new_project"
requires-python = ">= 3.10"
version = "1.3.0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.dependencies]
python = { version = ">=3.10", channel = "conda-forge" }
gdal="*"

[tool.pixi.pypi-dependencies]
ethos_penalps = { path = "./my_old_project", editable = true }
pyaml="*"
```

So that the environment of the new project would contain pandas, gdal, pyaml and python.

Also I would like to thank the the developers of this project. It seems very promising to ease the struggle with Python installations.
