### ISSUE TITLE
Adding target specific run commands

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#192]
While working on the `llama.cpp` project to get it working as an example for pixi: https://github.com/tdejager/llama.cpp

I ran into the issue that different platforms need the different build commands, e.g OSX can use Metal while other platforms cannot. We have target dependencies per platform: https://github.com/prefix-dev/pixi/blob/main/docs/getting_started.md#dependencies-per-platform. But I think it would be useful to have run tasks per platform as well. Note we've recently renamed `command` to `task` in the main branch.

So something along the lines of 

```toml
[tasks]
build = "make"
run = {cmd = "./build/bin/exe", depends_on = ["build"]}

[target.osx64.tasks]
build = "make METAL=ON"

[target.osx64-arm.tasks]
build = "make METAL=ON"
```

In this case we are using a different build command for the platform types, but `run` is shared across platforms. The depends should select the platform specific one. WDYT?
