### ISSUE TITLE
Using platform remove clears all platforms

### ISSUE THREAD

**Issue by Ahajha** [prefix-dev/pixi#1920]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "bug"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
python = ">=3.9,<3.13"
```

```shell
pixi project platform remove linux-aarch64
```

### Issue description

The above removes all platforms instead of just the one specified.

### Expected behavior

I would expect the above example to only remove linux-aarch64, however it instead removes all platforms. (This isn't specific to linux-aarch64, it does it with any of the platforms).

Additionally, I would expect `target.<platform>.<section>` sections to be removed, otherwise as-is the project file is broken. This can be repro'd with the following:
```toml
[project]
name = "bug"
channels = ["conda-forge"]
platforms = []

[target.linux-64.dependencies]
python = ">=3.9,<3.13"

[target.linux-aarch64.dependencies]
python = ">=3.9,<3.13"

[target.osx-arm64.dependencies]
python = ">=3.9,<3.13"
```
