### ISSUE TITLE
Add ability to run only for the target platform

### ISSUE THREAD

**Issue by Ahajha** [prefix-dev/pixi#1921]
### Problem description

Suppose I have a project where one or more platforms is known to be broken:
```toml
[project]
name = "feature"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]
tests = "python3 --version"

[target.linux-64.dependencies]
python = ">=3.9,<3.13"

[target.linux-aarch64.dependencies]
python = ">=3.9,<3.13"

[target.osx-arm64.dependencies]
python = ">=4.0" ### Hopefully this is always broken :)
```
It would be convenient to be able to only validate the current platform. There are a few use cases for this:
1. Providing a temporary escape hatch for development, perhaps someone only wants to focus on one platform but cannot do so because of dependency resolution issues on another platform.
2. Testing local packages, in this case the other platform's packages are simply not available. This could be worked around with `pixi project platform remove`ing the other platforms, but as far as I can tell that does not work properly, see #1920.
