### ISSUE TITLE
Add support to use different `pypi-options` for different environments

### ISSUE THREAD

**Issue by asmith26** [prefix-dev/pixi#1956]
### Problem description

I was reading the [Multi Environment docs](https://pixi.sh/latest/features/multi_environment/#feature-environment-set-definitions), and it appears in that list that configuring multiple `pypi-options` is not available for different environments.

Would be useful to have this features (related: https://github.com/prefix-dev/pixi/discussions/1949).
Thanks!

**Comment by asmith26** [comment]
In fact, it looks like using this might be broken for conda dependecies too (unless I'm doing something wrong?):

```toml
# pyproject.toml

[project]
name = "project"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "name", email = "email@email.com"}]
requires-python = ">= 3.12"

[tool.pixi]
project = {channels = ["conda-forge"], platforms = ["linux-64"]}
dependencies = {python = ">=3.12"}

[tool.pixi.feature.cpu]
channels = ["pytorch"]
dependencies = {"pytorch" = "*", "torchvision" = "*", "cpuonly" = "*"}

[tool.pixi.feature.gpu]
channels = ["pytorch", "nvidia"]
dependencies = {"pytorch" = "*", "torchvision" = "*", "pytorch-cuda" = "12.4"}

[tool.pixi.environments]
default = {features = [], solve-group = "default"}
cpu = {features = ["cpu"], solve-group = "default"}
gpu = {features = ["gpu"], solve-group = "default"}
```

and then I see in pixi.lock e.g.:

```lock
version: 5
environments:
  cpu:
    channels:
    - url: https://conda.anaconda.org/conda-forge/
    - url: https://conda.anaconda.org/pytorch/
    - url: https://conda.anaconda.org/nvidia/
    packages:
...
```
