### ISSUE TITLE
conda-pypi-map misleading error, issues with numpy

### ISSUE THREAD

**Issue by niemiaszek** [prefix-dev/pixi#1988]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
channels = ["https://fast.prefix.dev/conda-forge"]
description = "Add a short description here"
name = "mapping-test"
platforms = ["linux-64"]
version = "0.1.0"
conda-pypi-map = {"pytorch" = "local_mapping.json" }


[tasks]

[dependencies]

[feature.pytorch]
channels = ["https://fast.prefix.dev/conda-forge", "pytorch"]

[feature.pytorch.dependencies]
pytorch = {version="*", channel="pytorch"}
torchvision = {version="*", channel="pytorch"}
torchaudio = {version="*", channel="pytorch"}
cpuonly = {version="*", channel="pytorch"}

[feature.pytorch.pypi-dependencies]
pyannote-audio = "*"

[environments]
pytorch = ["pytorch"]
```

Please note that local mapping is default mapping with appended `"torchaudio":"torchaudio"`, even tho it's not that important for this example.

### Issue description

Resolving this env on newest pixi gives an error (?)   "× Defined conda-pypi-map channel: pytorch is missing from the channels, which are: https://fast.prefix.dev/conda-forge/". It made me think that something changed with mapping. Previously there were a different warning for this case, when mapped channel was not present in default env. I tried moving conda-pypi-map to feature specification, but it's illegal.

Switching to 0.27.1 I got an actual error:
```
× failed to solve the pypi requirements of 'pytorch' 'linux-64'
  ├─▶ Failed to build: `numba==0.51.2`
  ├─▶ Failed to install requirements from build-system.requires (install)
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: numpy==2.1.1
  ├─▶ Failed to extract archive
  ╰─▶ Unsupported archive type: numpy
```
It might be related to #1966 

Attached env only solves when `numpy="<2.0"` is added for me. On my other env I had silent failure for some `pixi add`, which was not really adding anything and I had to add it manually to `.toml`.

### Expected behavior

Pixi resolves and installs env sucessfully or at least gives informative error.
