### ISSUE TITLE
Import conda-based environment with pip (requirements.txt) dependencies

### ISSUE THREAD

**Issue by pierrepo** [prefix-dev/pixi#1993]
### Problem description

This feature request is related to issue #1410 

Currently, it is possible to create a new Pixi environment based on a Conda YAML file:

```bash
pixi init --import environment.yml
```

This command works nicely if the environment contains both conda and pip dependencies, for instance: 

```yml
name: test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - matplotlib
  - pip:
    - watermark
```

However, it does not work if pip dependencies are in an external file, for example:

`environment.yml`

```yml
name: test
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - pip
  - pandas
  - matplotlib
  - pip:
    - -r requirements.txt
```

`requirements.txt`

```
watermark
```

```bash
$ pixi init --import environment.yml 
  × Can't parse '-r requirements.txt' as pypi dependency
  ╰─▶ Expected package name starting with an alphanumeric character, found `-`
      -r requirements.txt
      ^
```

**Feature request**: could we please import conda YAML file with pip dependencies listed in an external file?
