### ISSUE TITLE
Publish unpublished crates to crates.io

### ISSUE THREAD

**Issue by corneliusroemer** [prefix-dev/pixi#2002]
### Problem description

I noticed that in the "install from source" guide you mention that one can't cargo install pixi from crates.io because of reliance on unpublished crates.

It might be nice to publish those unpublished crates to crates.io

Are these crates you developed or dependencies? Which ones are they?

> The reason for this is that we depend on some unpublished crates which disallows us to publish to crates.io.

**Comment by corneliusroemer** [comment]
It looks like it's possibly only the astral-sh UV crates that aren't on cargo. 

Stuff like that:

```toml
distribution-filename = { git = "https://github.com/astral-sh/uv", tag = "0.4.0" }
distribution-types = { git = "https://github.com/astral-sh/uv", tag = "0.4.0" }
```
