### ISSUE TITLE
Failure to resolve rerun-skd dependency unless I duplicated it in [tool.pixi.dependencies]

### ISSUE THREAD

**Issue by blooop** [prefix-dev/pixi#2020]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

in this repo:
https://github.com/blooop/rerun_minimal/tree/feature/more_minimal

which contains a pyproject.toml where I try to add rerun-sdk as a dependency. when I try to install

```toml
[project]
name = "rerun_ex"
version = "0.1.0"
description = "using pixi to manage a rerun based project"
authors = [{name = "Austin Gregg-Smith", email = "blooop@gmail.com"}]
requires-python = ">=3.10"

dependencies = ["rerun-sdk"]

##uncommenting these lines enables pixi to run, but this does not feel correct as its duplicating the rerun-sdk dependency
# [tool.pixi.dependencies]
# rerun-sdk = ">=0.18.2"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.tasks]
demo = "python3 rerun_ex.py"
```

Attempting to install:

```shell
$pixi install
```

outputs:
``` shell
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because only the following versions of rerun-sdk are available:
          rerun-sdk==0.2.0
          rerun-sdk>=0.3.0,<=0.5.0
          rerun-sdk>=0.5.1,<=0.8.0
          rerun-sdk>=0.8.1,<=0.8.2
          rerun-sdk==0.9.0
          rerun-sdk==0.9.1
          rerun-sdk==0.10.0
          rerun-sdk==0.10.1
          rerun-sdk==0.11.0
          rerun-sdk==0.12.0
          rerun-sdk==0.12.1
          rerun-sdk==0.13.0
          rerun-sdk>=0.14.0,<=0.14.1
          rerun-sdk==0.15.0
          rerun-sdk==0.15.1
          rerun-sdk==0.16.0
          rerun-sdk==0.16.1
          rerun-sdk==0.17.0
          rerun-sdk==0.18.0
          rerun-sdk>=0.18.1
      and all of:
          rerun-sdk==0.2.0
          rerun-sdk>=0.3.0,<=0.5.0
          rerun-sdk>=0.5.1,<=0.8.0
          rerun-sdk>=0.8.1,<=0.8.2
          rerun-sdk==0.9.0
          rerun-sdk==0.9.1
          rerun-sdk==0.10.0
          rerun-sdk==0.10.1
          rerun-sdk==0.11.0
          rerun-sdk==0.12.0
          rerun-sdk==0.12.1
          rerun-sdk==0.13.0
          rerun-sdk>=0.14.0,<=0.14.1
          rerun-sdk==0.15.0
          rerun-sdk==0.15.1
          rerun-sdk==0.16.0
          rerun-sdk==0.16.1
          rerun-sdk==0.17.0
          rerun-sdk==0.18.0
          rerun-sdk>=0.18.1
      have no wheels with a matching platform tag, we can conclude that all of:
          rerun-sdk<0.3.0
          rerun-sdk>0.5.0,<0.5.1
          rerun-sdk>0.8.0,<0.8.1
          rerun-sdk>0.8.2,<0.9.0
          rerun-sdk>0.9.0,<0.9.1
          rerun-sdk>0.9.1,<0.10.0
          rerun-sdk>0.10.0,<0.10.1
          rerun-sdk>0.10.1,<0.11.0
          rerun-sdk>0.11.0,<0.12.0
          rerun-sdk>0.12.0,<0.12.1
          rerun-sdk>0.12.1,<0.13.0
          rerun-sdk>0.13.0,<0.14.0
          rerun-sdk>0.14.1,<0.15.0
          rerun-sdk>0.15.0,<0.15.1
          rerun-sdk>0.15.1,<0.16.0
          rerun-sdk>0.16.0,<0.16.1
          rerun-sdk>0.16.1,<0.17.0
          rerun-sdk>0.17.0,<0.18.0
          rerun-sdk>0.18.0,<0.18.1
       cannot be used.
      And because you require rerun-sdk, we can conclude that your requirements are unsatisfiable.
      
      hint: Pre-releases are available for rerun-sdk in the requested range (e.g., 0.18.1rc1), but pre-releases
      weren't enabled (try: `--prerelease=allow`)

```

### Issue description

Uncommenting the [tool.pixi.dependencies] fixes the problem, but the workaround seems wrong as I should not need to specify the same dependency twice.

I made an issue on the discord where I was told it did look like a bug and to make an issues:

https://discord.com/channels/1082332781146800168/1281636597611233340

### Expected behavior

pixi install should install rerun-sdk without errors and without duplicating the dependency in [tool.pixi.dependencies]

**Comment by tdejager** [comment]
Thanks for the issue, this is again a case of mismatching system-requirements:

This works

```toml
[project]
name = "rerun_ex"
version = "0.1.0"
description = "using pixi to manage a rerun based project"
authors = [{name = "Austin Gregg-Smith", email = "blooop@gmail.com"}]
requires-python = ">=3.10"

dependencies = ["rerun-sdk"]

##uncommenting these lines enables pixi to run, but this does not feel correct as its duplicating the rerun-sdk dependency
# [tool.pixi.dependencies]
# rerun-sdk = ">=0.18.2"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.system-requirements]
libc = { family="glibc", version="2.31" }

[tool.pixi.tasks]
demo = "python3 rerun_ex.py"
```
