### ISSUE TITLE
`pixi shell` should only pull the requested environment, not all environments.

### ISSUE THREAD

**Issue by sebastian-sz** [prefix-dev/pixi#2114]
### Problem description

TL;DR `pixi shell` pulls ALL environments, even when only the default is requested.

I'm rolling a Pytorch CPU / GPU project. `linux-64` uses GPU and CPU, everything else is CPU. Please find the `pyproject.toml` below:
```toml
[project]
authors = [{name = "Sebastian Sz", email = "***@***.com"}]
dependencies = ["jaxtyping>=0.2.34,<0.3"]
description = "Add a short description here"
name = "torch-proj"
requires-python = ">= 3.9, <3.13"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[tool.pixi.dependencies]
pytorch = {version = "2.4.1", channel = "pytorch"}
torchvision = {version = "0.19.1", channel = "pytorch" }

[tool.pixi.pypi-dependencies]
torch-proj = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.environments]
cuda = ["cuda"]

# CUDA setup
[tool.pixi.feature.cuda]
platforms = ["linux-64"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "conda-forge", "pytorch"]

[tool.pixi.feature.cuda.dependencies]
pytorch-cuda = {version = "12.4.*", channel = "pytorch"}
```

The issue is: when running `pixi shell` on Linux, the `cuda` environment gets downloaded and installed, even though I did not request cuda. This is kinda bloaty, e.g. when I want to run CI on Linux on the CPU there is no reason to pull the Nvidia's packages (which are quite heavy).

Ideally, we would pull cuda only when requested, e.g:  
`pixi shell` <- downloads CPU only packages
`pixi shell -e cuda` <- downloads CUDA only packages

Rather then have everything possible downloaded, regardless of the environment.

Pixi version: `0.30.0`
