### ISSUE TITLE
Use correct span in error

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#2119]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
channels = []
name = "test"
platforms = []

[environments]
default = ["bla"]
```
Will result in the following error on `pixi run start`
```
  × the feature 'bla' is not defined in the project manifest
   ╭─[pixi.toml:1:1]
 1 │ [project]
   · ▲
   · ╰── unknown feature 'bla'
 2 │ channels = []
```
This should be pointing at the `"bla"` in the environment table.

### Issue description

This has to do with the usage of our `PixiSpanned` which is not used for the sequence implementation of the environments.

### Expected behavior

The error label pointing to the `"bla"` in the `default = ["bla"]`
