### ISSUE TITLE
Environment directory is not locked when environments are populated

### ISSUE THREAD

**Issue by vlad-ivanov-name** [prefix-dev/pixi#2133]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "requirements-3.10.13"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
python = "==3.10.13"
pip-tools = ">=7.3.0,<7.4"
```

```shell
pixi update
pixi run --frozen --manifest-path pixi.toml echo | pixi run --frozen --manifest-path pixi.toml cat
```

### Issue description

This is a follow-up to https://github.com/prefix-dev/pixi/issues/1004 -- even though it was closed, the issue is still there. I've simplified reproduction steps, and tested that it's still present with the latest release.

The command fails with:

```
  ⠁ installing packages  [00:00:00] [━━──────────────────]     2/24 libffi                                                                                                     × failed to link libffi-3.4.2-h3422bc3_5.tar.bz2
  ├─▶ failed to link 'share/man/man3/ffi_prep_cif_var.3'
```

### Expected behavior

Environment dir is locked for the update.

Relevant code: https://github.com/conda/rattler/blob/40803042b829346ed7522f797d70fd4da20fc12e/crates/rattler_repodata_gateway/src/utils/flock.rs#L204
