### ISSUE TITLE
Resolve can be slow for specific packages

### ISSUE THREAD

**Issue by fecet** [prefix-dev/pixi#2134]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```yaml
name: default
channels:
- conda-forge
- nodefaults
dependencies:
- cmake *
- compilers *
- gcc ==11.4
- pyspark *
```
save this as `environment.yml`, then solve it with
```
pixi init --import environment.yml
pixi project export conda-explicit-spec . -vvvv
```

### Issue description

Solve takes a long time (90s on my machine), as a comparsion, `conda-lock` takes 55s

### Expected behavior

The solve should not be that slow, or at least as fast as `conda-lock`
