### ISSUE TITLE
Questions about multi-environment, and potentially a feature request.

### ISSUE THREAD

**Issue by raceychan** [prefix-dev/pixi#2159]
### Problem description

I am a bit confused about how pixi multi-environment works, assume i have three environments default, dev, test
```toml
[tool.pixi.environments]
default = {solve-group = "default"}
test = {features = ["test"], solve-group = "default"}
dev = {features = ["dev"], solve-group = "test"}

[tool.pixi.dependencies]
redis-py = ">=5.0.1"
[tool.pixi.feature.test.dependencies]
pytest = ">=8.3.0"
[tool.pixi.feature.dev.dependencies]
alembic = ">=1.13.3,<2"
```

my question:
1. Do these three environments share a same python interpreter?
2. If i do
```bash
pixi install -e dev 
```  
will redis-py be installed? will pytest be installed? or both?

#### Desired feature

I am trying to use pixi inside docker container. 
To reduce image size, I would like to have only the default dependencies installed, but not the ones of test or dev.
Here is my dockerfile
```dockerfile
FROM alpine:3.12 AS python-base

FROM python-base as builder-base

# Install pixi
RUN curl -fsSL https://pixi.sh/install.sh | bash
ENV PIXI_HOME="/root/.pixi"
ENV PATH="$PIXI_HOME/bin:${PATH}"

# Set the working directory in the Docker image
WORKDIR /app

# Pip uses pyproject.toml to install dependencies
COPY pyproject.toml ./

# Install dependencies using pixi
RUN pixi install -e default
```

right now, I am not sure if 
```dockerfile
RUN pixi install -e default
```
only installs the default dependencies.
