### ISSUE TITLE
Install R package from Github

### ISSUE THREAD

**Issue by roaldarbol** [prefix-dev/pixi#2187]
### Problem description

It would be great to be able to install an R package from Github. I seem to recall that it would need a new parser of the `DESCRIPTION` file, but that that shouldn't be the most difficult thing in the world (if I remember correctly @wolfv).

**Comment by wolfv** [comment]
We're working on `pixi build` and this would be possible once we have it. When we have it, we would implement a build backend for R packages and pixi should do everything else automagically :)

**Comment by roaldarbol** [comment]
That sounds great! Do you have any idea about time horizon?

**Comment by ruben-arts** [comment]
`pixi build` is under heavy construction. I'm planning to show off an initial version at the end of this month, then we'll probably also start excepting contributor PR's on it. So extending it with a R build backend would then be a next step.

**Comment by roaldarbol** [comment]
Hey guys! Is there any progress on `pixi build` that would be of interest to R package building? Or do you think we could try prioritizing it soonish? :-)

**Comment by baszalmstra** [comment]
This is an example that shows how this works now (@wolfv build the R backend). 

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
preview = ["pixi-build"]

# ---------------------------------------------------------------------------
# Package: what we're building. The source is fetched from GitHub and handed
# to the pixi-build-r backend, which reads the upstream DESCRIPTION file for
# metadata and dependencies.
# ---------------------------------------------------------------------------
[package]
name = "r-highr"
version = "0.9"

[package.build.source]
git = "https://github.com/yihui/highr.git"
tag = "v0.9"

[package.build.backend]
name = "pixi-build-r"
version = "*"
channels = [
  # The R backend is not officially released which is why you need this. 
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

# ---------------------------------------------------------------------------
# Dependencies: r-base for the runtime, and a path-dependency on the package
# we just declared so the workspace installs the freshly built conda package.
# ---------------------------------------------------------------------------
[dependencies]
r-base = ">=4.3,<5"
r-highr = { path = "." }

# ---------------------------------------------------------------------------
# Tasks: smoke-test that the package built from GitHub is importable.
# ---------------------------------------------------------------------------
[tasks]
check = "Rscript -e 'library(highr); cat(as.character(packageVersion(\"highr\")), \"\\n\")'"
```

Im going to close this issues. If you run into issues with the backend, feel free to file issues here!
