### ISSUE TITLE
Pixi stuck during pixi resolving conda

### ISSUE THREAD

**Issue by amirhosseindavoody** [prefix-dev/pixi#2190]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi shell
```

### Issue description

pixi seems to be stock when trying to resolve the environment for the following dependencies:

``` toml

[system-requirements]
libc = {family = "glibc", version = "2.22"}
linux = "4.12.14"

[dependencies]
polars = ">=1.8.2,<2"
pyarrow = ">=17.0.0,<18"
python = "3.9.*"
```

I am using pixi version 0.30.0

### Expected behavior

Resolve the environment and instantiate the shell.
