### ISSUE TITLE
Package uninstalled when switching between pypi/conda

### ISSUE THREAD

**Issue by jxu10** [prefix-dev/pixi#2203]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I made 2 `pixi.toml` to easily switch between them (`cp` vs editing lines).

`pixi.pypi.toml`:
```toml
[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12"
# pytest = "8.3.3"

[pypi-dependencies]
pytest = "8.3.3"
```

`pixi.conda.toml`:
```toml
[project]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12"
pytest = "8.3.3"

[pypi-dependencies]
# pytest = "8.3.3"
```

Sequence of commands:

```shell
rm -rf .pixi pixi.lock

cp pixi.pypi.toml pixi.toml
pixi install
# ✔ The default environment has been installed.
# pixi.lock has pytest from pypi
ls .pixi/envs/default/lib/python3.12/site-packages
# README.txt                 iniconfig-2.0.0.dist-info/ pluggy/                    pytest/
# _pytest/                   packaging/                 pluggy-1.5.0.dist-info/    pytest-8.3.3.dist-info/
# iniconfig/                 packaging-24.1.dist-info/  py.py

cp pixi.conda.toml pixi.toml
pixi install
# ✔ The default environment has been installed.
# pixi.lock does not have pytest
ls .pixi/envs/default/lib/python3.12/site-packages
# README.txt

pixi install
# ✔ The default environment has been installed.
# pixi.lock has pytest from conda
ls .pixi/envs/default/lib/python3.12/site-packages
# README.txt                      iniconfig/                      py.py
# _pytest/                        iniconfig-2.0.0.dist-info/      pytest/
# colorama/                       packaging/                      pytest-8.3.3.dist-info/
# colorama-0.4.6.dist-info/       packaging-24.1.dist-info/       tomli/
# exceptiongroup/                 pluggy/                         tomli-2.0.2.dist-info/
# exceptiongroup-1.2.2.dist-info/ pluggy-1.5.0.dist-info/
```

### Issue description

When switching a package from pypi to conda, `pixi install` succeeds but sometimes removes the pypi package without adding the conda package, leaving no package installed. Running `pixi install` a second time will usually add the conda package.

### Expected behavior

`pixi install` should install all packages from `pixi.toml` on the first try, instead of needing multiple `pixi install` to finish installing everything.
