### ISSUE TITLE
osx pixi install fails to generate lockfile

### ISSUE THREAD

**Issue by geoHeil** [prefix-dev/pixi#2204]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

sometimes (not in all cases but sometimes)

```toml
platforms = ["linux-64", "osx-arm64", "linux-aarch64"]
```

fails silently for

```shell
pixi install
```

and the lockfile is never created

### Issue description

Strange - for 0.30 pixi (and also some versions before) I have (sometimes not fully clear when/why) the issue that on linux everything works fine. But on osx  pixi install stops like here updating lock-file  

```
 [00:00:01] [────────────────────────────────────────]    0/41
  ⠤ default:linux-aarch6400:00:01] resolving conda
  ⠤ ci-tools:osx-arm64   [00:00:01] resolving conda
  ⠤ ci-tools:linux-aarch6400:00:01] resolving conda
```

and never generates a lockfile vs. on linux it works exactly like expected

### Expected behavior

The lockfile should also be created on osx.

> WORKAROUND: I just removed the `"linux-aarch64"` platform - now this issue seems to not show up anymore for me

**Comment by ruben-arts** [comment]
Hi @geoHeil, does it just stop or gives it an error? Also could you try running with `-vvv` so we can see the last messages from the debug output and share a minimal reproducible example, as i can solve for all these platforms and it will result in a lockfile.

**Comment by geoHeil** [comment]
I just upgraded to 0.31 it fails again


```
updating lock-file   [00:00:00] [━━──────────────────────────────────────]    2/41
  ⠚ default:osx-arm64    [00:00:00] extracting pypi packages
  ⠚ default:win-64       [00:00:00] loading repodata
  ⠚ default:linux-64     [00:00:00] parsing repodata
```

for a toml of

```toml
[dependencies]
python = "3.11"
pip = ">=24.2"

[environments]
ci-tools = { features = ["ci-basics"], solve-group = "ci" }
shared-library = { features = ["shared-library"], solve-group = "default" }
codelocation-foo = { features = [
  "codelocation-foo",
  "shared-library",
  "shared",
], solve-group = "default" }
codelocation-bar = { features = [
  "codelocation-bar",
  "shared-library",
  "shared",
], solve-group = "default" }
ci-validation = { features = [
  "ci-basics",
  "codelocation-bar",
  "codelocation-foo",
  "shared-library",
  "shared",
], solve-group = "default" }
dagster-webserver = { features = [
  "dagster-webserver",
  "dagster-basics",
], solve-group = "default" }
dagster-daemon = { features = [
  "dagster-daemon",
  "dagster-basics",
], solve-group = "default" }

[feature.ci-basics.dependencies]
yamllint = ">=1.35.1,<2"
taplo = ">=0.9.3,<0.10"
pytest = ">=8.3.3,<9"
pytest-mock = ">=3.14.0,<4"
pytest-cov = ">=5.0.0,<6"
nbqa = "~=1.9.0"
pyright = "~=1.1.382.post0"

[feature.ci-basics.pypi-dependencies]
moto = "~=5.0.14"

[feature.dagster-basics.dependencies]
grpcio = "*"
grpcio-tools = "*"
protobuf = ">=4,<5" # dagster currently only works with protobuf 4

[feature.dagster-basics.pypi-dependencies]
dagster = ">=1.8.7,<1.9"
dagster-postgres = ">=0.24.7,<0.25"

[feature.dagster-daemon.pypi-dependencies]
dagster-docker = ">=0.24.7,<0.25"

[feature.dagster-webserver.pypi-dependencies]
dagster-webserver = ">=1.8.7,<1.9"
dagster-docker = ">=0.24.7,<0.25"

[feature.shared-library.dependencies]
[feature.shared-library.pypi-dependencies]

[feature.shared.dependencies]
[feature.shared.pypi-dependencies]

[feature.codelocation-foo.dependencies]
[feature.codelocation-foo.pypi-dependencies]

[feature.codelocation-bar.dependencies]
[feature.codelocation-bar.pypi-dependencies]

[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = ["Gbaz"]
platforms = ["linux-64", "osx-arm64", "win-64"]
channels = ["conda-forge"]



```

this fails to generate the lockfile on osx m2 but works flawlessly on linux
