### ISSUE TITLE
Support for `--no-deps` in `pypi-dependencies`

### ISSUE THREAD

**Issue by SultanOrazbayev** [prefix-dev/pixi#2208]
### Problem description

Hello, I started experimenting with `pixi` and one feature that seems to be missing for Python development is the ability to replicate the command:

```shell
pip install --no-deps -e .
```

My understanding the syntax could look like this (in `pyproject.toml`):

```toml
[tool.pixi.pypi-dependencies]
mypackage = { path = ".", editable = true, no_deps = false }
```

Or perhaps like this:

```toml
[tool.pixi.pypi-dependencies]
mypackage = { path = ".", editable = true, dependencies = false }
```

If this feature is already available, it might not be well-documented.
