### ISSUE TITLE
Add support for `dev-dependencies` in `[tool.uv]` table

### ISSUE THREAD

**Issue by redeboer** [prefix-dev/pixi#2211]
### Problem description

If I understand correctly, Pixi manages Python dependencies with `uv`. Since `uv` v0.4, there is now support for defining [`dev-dependencies`](https://docs.astral.sh/uv/reference/settings/#dev-dependencies). Would it be possible to install these as well into the Pixi environment?

---

The use case is to list Python dependencies for the developer environment without exposing them downstream. A common way is to do this with [optional dependencies](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-optional-dependencies), like `dev` or `test`, but these are exposed to PyPI (and therefore also appear downstream in lock files).

There is unfortunately no official standard yet for defining developer dependencies through `pyproject.toml`. Long-term, this can hopefully be with dependency groups (see **[PEP&nbsp;735](https://peps.python.org/pep-0735/)**), but until then it would be good to support upcoming standards like `tool.uv.dev-dependencies`.

**Comment by ruben-arts** [comment]
In pixi there is already a more defined way to specify multiple environments in a project.

We use `features` and `environments`

e.g.
```toml
[tool.pixi.feature.dev]
pypi-dependencies = { pytest = "*"}
dependencies = { python = "3.10.*" }

[tool.pixi.environments]
dev = ["dev"]
```

This would allow you to run `pixi run --environments(-e) dev pytest` or `pixi shell --environment(-e) dev`.
Which would create a seperate dev environment.

What I often do is make the "dev" environment the default environment.
```toml
[tool.pixi.environments]
default= ["dev"]
```
So that on my local work machine `pixi run` will always run in the "dev" environment. And ci could use the defined environments.

For more information checkout: https://pixi.sh/latest/features/multi_environment/#multi-environment-support
