### ISSUE TITLE
Pin Python version with `.python-version` file

### ISSUE THREAD

**Issue by redeboer** [prefix-dev/pixi#2212]
### Problem description

Many Python package managers can pin the Python version with a `.python-version` file, see e.g. `uv` [here](https://docs.astral.sh/uv/guides/projects/#python-version). Would it be possible to pin the Python version in the Pixi environment with such a `.python-version` (or even [`.python-versions`](https://docs.astral.sh/uv/concepts/python-versions/#project-python-versions)) file?

- `pyproject.toml`
  ```toml
  [project]
  name = "test-pixi"
  version = "0.1.0"
  
  [tool.pixi.project]
  channels = ["conda-forge"]
  platforms = ["linux-64"]
  
  [tool.pixi.dependencies]
  python = "*"
  ```

- `.python-version`
  ```
  3.10
  ```

- Current behavior:
  ```shell
  $ pixi run python --version
  Python 3.12.7
  ```

**Comment by redeboer** [comment]
This issue possibly touches on #2211. Depending on how deeply `uv` is integrated into Pixi, it can in theory now also be used to [bootstrap Python itself](https://docs.astral.sh/uv/concepts/python-versions).

Personally, the way I use Pixi is as an environment manager around Python projects that require other non-Python dependencies. Ideally, the Python part of those projects can be fully defined in Python standards and then Pixi provides the rest of the (non-Python) tools.

**Comment by olivier-lacroix** [comment]
@redeboer , is this a standard? I thought the preferred way was to use `requires-python` in pyproject.toml?

pixi will interpret that property correctly.

**Comment by redeboer** [comment]
No, `requires-python` is included in the built distribution and [signals the minimum version of Python](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires) you need to run the package you publish. A `.python-version` file pins the version of the developer environment around your package without exposing it downstream.

But there is indeed no official Python standard for this. As far as I can see, it comes from `pyenv` and was adopted by `uv`.

**Comment by tdejager** [comment]
So we'll probably never use the bootstrapping python feature of uv, those are pre-built statically linked python binaries. The python we get is taken from conda-forge a behavior we are not changing soon. I could see the use-case for the `.python-version` file, let's leave this issue open and please leave a comment or thumbs up if you want to see this happening :)

cc @ruben-arts

**Comment by olivier-lacroix** [comment]
@redeboer it seems using an upper bound to 'pin' python is also an accepted (but discouraged) use case. The warning made seems to be more about the concept of pinning python itself, rather than the use of the `requires-python` field for it.

**Comment by rgommers** [comment]
I think the right answer here is to use the regular way of declaring non-python dependencies in `pyproject.toml` (or `pixi.toml`), rather than a special file to control the `python` version. E.g., adapted from https://pixi.sh/latest/advanced/pyproject_toml/#dependency-section:
```toml
[project]
name = "my_project"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
]

[tool.pixi.dependencies]
python = "3.11"  # `python` is a regular conda package, so control its version as normal
numpy = "*"
```

`uv` & co may need a special file because there is no way to express this in standardized Python packaging metadata, but Conda is more general so special-casing `python` in the UX is not desirable.



> No, `requires-python` is included in the built distribution and [signals the minimum version of Python](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#python-requires) you need to run the package you publish.

This is correct. What's written in https://pixi.sh/latest/advanced/pyproject_toml/#python-dependency isn't wrong though, it's just incomplete. If an explicit `python` is given in `[tool.pixi.dependencies]`, that should supersede the implicit requirement that's otherwise derived from `requires-python`.
