### ISSUE TITLE
`mlflow` and `streamlit` take up a lot more memory when added as feature dependencies as opposed to `pypi-dependencies`

### ISSUE THREAD

**Issue by AvishekMondalQC** [prefix-dev/pixi#2214]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name="test-project"
channels=["conda-forge"]
platforms=["linux-64"]
conda-pypi-map={}

[system-requirements]
libc = "2.26"

[feature.dev.dependencies]
python = "3.11"
setuptools = "70.0.0"
pip = "24.0.*"
streamlit = "1.35.0"
mlflow = "2.13.1"

[environments]
default = ["dev"]
```

With the above `pixi.toml` file, when I run `pixi install` and monitor memory usage using `htop`, I see that RAM goes beyond 5GB. But when I run `pixi install` using the following `pixi.toml` file and monitor RAM using `htop`, it does not exceed 2GB

```toml
[project]
name="test-project"
channels=["conda-forge"]
platforms=["linux-64"]
conda-pypi-map={}

[system-requirements]
libc = "2.26"

[feature.dev.dependencies]
python = "3.11"
setuptools = "70.0.0"
pip = "24.0.*"
# streamlit = "1.35.0"
# mlflow = "2.13.1"

[feature.dev.pypi-dependencies]
streamlit = "==1.35.0"
mlflow = "==2.13.1"

[environments]
default = ["dev"]
```

### Issue description

I do not understand why there is such a discrepancy in memory usage when downloading the same packages from conda vs when getting if from pypi. How would I go about tracking the source of the discrepancy? 

Additionally, is it possible to specify the maximum amount of memory or number of workers the `pixi install` process uses?

### Expected behavior

I would expect the memory usage of `pixi install` to be roughly the same for both `pixi.toml` files.
