### ISSUE TITLE
Allow pypi dependencies in global envs

### ISSUE THREAD

**Issue by hadim** [prefix-dev/pixi#2261]
### Problem description

The global feature is really great and complements perfectly the project-based approach IMO. I know it's not fully released yet, but I wanted to check whether you are planning to support pypi dependencies in global envs?

One of the use cases is, for example, using a global tool either from its released version but also from its dev version at the same time. Something like:

```toml
[envs.smithy]
channels = ["conda-forge"]
dependencies = { conda-smithy = "*" }
exposed = { conda-smithy = "conda-smithy" }

[envs.smithy-dev]
channels = ["conda-forge"]
pypi-dependencies = { conda-smithy = "https://github.com/conda-forge/conda-smithy/archive/refs/heads/main.zip" }
exposed = { conda-smithy-dev = "conda-smithy" }
```
