### ISSUE TITLE
pixi runs tasks in default environment instead of activated environment from `pixi shell`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#2299]
```toml
[project]
name = "my-project"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.9"
polars = ">=0.14.24,<0.21"

[tasks]
test = "echo $PIXI_ENVIRONMENT_NAME"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"

[environments]
py39 = ["py39"]
py310 = ["py310"]
```

Actual:

```bash
# with pixi 0.32.2 and 0.33.0
$ pixi shell -e py39
$ pixi run test
default
```

Expected

```bash
# with pixi 0.31.0
$ pixi shell -e py39
$ pixi run test
py39
```
