### ISSUE TITLE
Pixi tries to resolve the packages for the different platform

### ISSUE THREAD

**Issue by skayred** [prefix-dev/pixi#2353]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "win-test"
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]

[host-dependencies]
python = "<=3.11"

[target.linux-64.dependencies]
numpy = {version = ">=1.26.2,<2"}

[target.win-64.dependencies]
python = "==3.10.11"

[pypi-dependencies]
jsonargparse = { version = "*", extras = ["signatures"] }

[target.win-64.pypi-dependencies]
pypiwin32 = "==223"
pywin32 = "==306"
pywin32-ctypes = "==0.2.2"

[feature.build-win.pypi-dependencies]
pyinstaller = "==6.10.0"
pyinstaller-hooks-contrib = "==2024.9"
setuptools = ">=68,<70"
pefile = "<2024.8.26"
psutil = "==5.9.6"

[environments]
default = {features = [], solve-group = "default"}
build-win = {features = ["build-win"], solve-group="default"}
```

### Issue description

Hello,

I am trying to reorganize the Python application using Pixi, and faced an issue when trying to install the bundle that contains Windows-specific packages on Linux. With the TOML file I have provided, if I run it on the Ubuntu machine, I receive the following error:

```
pixi install --all
  ⠚ default:linux-64     [00:00:00] resolving pypi dependencies
  × failed to solve the pypi requirements of 'default' 'win-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because pywin32==306 has no wheels with a matching Python implementation tag and you require pywin32==306, we can conclude that your requirements are unsatisfiable.
```

Same command works on the Windows machine, and if I copy the `pixi.lock` to the Ubuntu machine, both `pixi install --frozen` and `pixi install --all` work fine.

### Expected behavior

Installation should not fail on both platforms even without the lock-file
