### ISSUE TITLE
rapidsai package cannot be installed as per prefix-dev channel instructions

### ISSUE THREAD

**Issue by naondo88** [prefix-dev/pixi#2357]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
nano pixi.toml  # Manually add "rapidsai" to channels list in addition to default "conda-forge".
pixi add cuml==24.10.0
```

This generates the error message:
```
  × failed to solve the conda requirements of 'default' 'linux-64'
  ╰─▶ Cannot solve the request because of: The following packages are incompatible
      └─ cuml >=24.10.0 cannot be installed because there are no viable options:
         └─ cuml 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 would require
            └─ raft-dask 24.10.*, which cannot be installed because there are no viable options:
               └─ raft-dask 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 would require
                  └─ rmm 24.10.*, which cannot be installed because there are no viable options:
                     └─ rmm 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 | 24.10.0 is excluded because due to strict channel priority not using this option from: 'https://conda.anaconda.org/rapidsai/'
```

### Issue description

I am working on a project where I need to use the cuML library from the rapidsai channel.  According to [the prefix.dev channel info on installing rapidsai::cuml](https://prefix.dev/channels/rapidsai/packages/cuml), the most recent version is 24.10.0 and works with python 3.11 and greater.  NOTE:  I am working with Ubuntu 22.04 over WSL2 on Windows 11 with the latest `pixi --version  # Shows 0.34.0`.

If I try installing from a fresh `pixi init`, adding rapidsai to the channels, and then running `pixi add cuml`, it installs python 3.7 and some ancient version of cuml, which is curious but also not helpful.

I tried a lot of other things to get pixi to install this (treating it as a pip install and following the pip install instructions, trying out different versions, etc).  This whole package seems to be bricked in this channel after 0.6, but the prefix.dev documentation shows this as an installable package version for linux-64 platform, but neither it nor dozens of versions older than it is actually installable with pixi.

### Expected behavior

It should install the version described in the prefix.dev channel description.

**Comment by ruben-arts** [comment]
Hi @naondo88, 

This has to do with the channel priority logic. You can turn this off by running with `channel-priority = "disabled"` to avoid pixi ignoring the dependencies if they come from a different channel then the one with the highest priority. 

This worked for me:
```toml
[project]
channels = ["conda-forge", "rapidsai"]
channel-priority = "disabled"
name = "test-cuml"
platforms = ["linux-64"]

[dependencies]
cuml = "==24.10.0"
```

It better to stripout the dependencies and define which channel you want to get them from e.g.:
```toml
[project]
channels = ["conda-forge", "rapidsai"]
name = "test-cuml"
platforms = ["linux-64"]

[dependencies]
cuml = {version = "==24.10.0", channel = "rapidsai" }
cudf = {version = "==24.10.01", channel = "rapidsai" }
# ... etc.
```
But that takes some manual labor
