### ISSUE TITLE
pixi did not install specified commit of pypi git dependency

### ISSUE THREAD

**Issue by ericphanson** [prefix-dev/pixi#2358]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

I'm sorry, I don't have a reproducible example since the code is not open source

### Issue description

pixi 0.34.0

I have a pyproject with:
```toml
[tool.pixi.pypi-dependencies]
library = { git = "https://github.com/user/library.git", rev = "2f33247a11ac3d72e7d943b1500fd5df0e285b27" }
```
and when I install it, my pixi lock file correctly has
```yaml
- kind: pypi
  name: library
  version: 15.7.5.dev14
  url: git+https://github.com/user/library.git@2f33247a11ac3d72e7d943b1500fd5df0e285b27
```
However, the installed code is not that of commit `2f33247a11ac3d72e7d943b1500fd5df0e285b27`! It is an older version.

I believe the order was:
- I previously used an older commit on the same version 15.7.5.dev14 of my library with my pixi environment
- I updated my library's branch and updated the commit in my pixi pyproject
- I did `pixi install` (or possibly just `pixi run`) and checked the lockfile was updated to reflect my new commit
- I ran my code expecting to use the new code, but instead got the old code

I believe pixi is caching based on the version number, which doesn't seem appropriate if all I have specified in my pyproject is the commit and if the commit is in the lockfile.

### Expected behavior

If a dependency is specified by a commit sha, pixi should ensure it uses that specific commit sha.
