### ISSUE TITLE
Global activation env vars ignored when platform-specific ones are provided

### ISSUE THREAD

**Issue by hameerabbasi** [prefix-dev/pixi#2383]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
authors = ["Hameer Abbasi <2190658+hameerabbasi@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "sparse"
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[feature.finch.activation.env]
SPARSE_BACKEND = "Finch"

# Change this to your platform
[feature.finch.target.osx-arm64.activation.env]
PYTHONFAULTHANDLER = "${HOME}/faulthandler.log"

[feature.mlir.activation.env]
SPARSE_BACKEND = "MLIR"

[environments]
finch-dev = {features = ["finch"], no-default-feature = true}
mlir-dev = {features = ["mlir"], no-default-feature = true}
```

```shell
❯ pixi run -e finch-dev 'echo $SPARSE_BACKEND'

❯ pixi run -e mlir-dev 'echo $SPARSE_BACKEND'
MLIR
❯ pixi run -e finch-dev 'echo $PYTHONFAULTHANDLER'
/Users/habbasi/faulthandler.log
```

### Issue description

If both platform-agnostic and platform-specific env vars are provided, the platform-agnostic ones are ignored entirely.

### Expected behavior

Global env vars should be overridable by platform-specific ones, but platform-agnostic ones should take precedence if present.
