### ISSUE TITLE
Question about tasks & environments

### ISSUE THREAD

**Issue by ernimd** [prefix-dev/pixi#2389]
I am writing CI pipeline to test with multiple versions of `python` and would like to have a single line to call in CI config. I've achieved that with the below config and running `pixi run test-all`. But tbh looks ugly and repetitive. 

Is there a better way of doing this ? Or there is potential for a new feature ?  

```yaml
[tool.pixi.feature.python39]
dependencies = { python = "3.9.*" }
tasks = { test39 = "pytest" }

[tool.pixi.feature.python310]
dependencies = { python = "3.10.*" }
tasks = { test310 = "pytest" }

[tool.pixi.feature.python311]
dependencies = { python = "3.11.*" }
tasks = { test311 = "pytest" }

[tool.pixi.tasks]
test-all = { depends_on = ["test311", "test310", "test39"] }
```

**Comment by olivier-lacroix** [comment]
That’s the best way to do it afaik. Matrix based approaches have been suggested as alternatives https://github.com/prefix-dev/pixi/issues/2236

**Comment by jjjermiah** [comment]
I use a similar setup and let the GHA CI matrix handle distribution:

The following setup runs my unit tests on the product of python versions [py310, py311, py312] and GHA machines [ubuntu-latest, macos-latest, macos-14] so 9 individual jobs 

1. runs in parallel
2. individual fail is a lot easier to debug 
3. adding another python version is pretty straightforward// 

```
[tool.pixi.environments]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]

############################################## python ###############################################

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"
[tool.pixi.feature.py311.dependencies]
python = "3.11.*"
[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

############################################## TEST ################################################

[tool.pixi.feature.test.dependencies]
pytest = "*"

[tool.pixi.feature.test.tasks.test]
cmd = "pytest -s -v tests/"
```

```yaml
jobs:
  ################################################################################################
  # Unit-Tests: Run unit tests using pytest
  ################################################################################################
  Unit-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14] # , windows-latest removed for now
        env: ["py310", "py311", "py312"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ${{ matrix.env }}
          pixi-version: v0.33.0

      - name: Run pytest
        run: |
          pixi run -e ${{ matrix.env }} test
```

**Comment by bollwyvl** [comment]
Right: I don't think we've seen a way to create a factor for envs, so those have to be manually constructed (though, as relatively simple `toml`, this _could_ be pretty automated). 

Tasks can be a bit more flexible, with pixi-in-pixi:

```toml
[tasks]
test = "pytest"
test-39 = "pixi r -e py39 test"
test-313 = "pixi r -e py313 test"
test-all = {depends-on = ["test-39", "test-313"]}
```

In [github](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#example-using-an-output-to-define-two-matrices), it's possible to use dynamic JSON generated in one step/job to build up the inputs to the `matrix` of another step (e.g. `pixi run build-ci-matrix`, then `fromJSON`) so there is a single source of truth in `pixi.toml`. Similar approaches work in gitlab, which can generate entire pipelines.
