### ISSUE TITLE
Support for optional dependencies

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#239]
I want to build a library and want to do unit tests with different python versions. 
In my `pixi.toml`, I have `"python" = ">= 3.9"` but i want to do a matrix GitHub Action where the python version is pinned to `3.9`, `3.10` and `3.11`.

If pixi supported something like build matrices or additional constraints, I could test multiple constraint sets without needing to do `pixi add python=${{ matrix.PYTHON_VERSION }}`.

I would imagine something like this for example:

```toml
[dependencies]
"python" = ">= 3.9"
"scikit-learn" = ">=1.1.0"

[target.custom.py39.dependencies]
python = "3.9"

[target.custom.py310.dependencies]
python = "3.10"

[target.custom.sklearn-130.dependencies]
"scikit-learn" = "1.3.0"
```

```bash
# install default stuff
$ pixi install
# install with custom constraints
$ pixi install --with py310 --with sklearn-130
```

I would suggest not solving these additional requirements beforehand but only solving at runtime if specified with `--with` since this could lead to a combinatorical explosion if too many additional dependencies are specified. (Or maybe providing the user with an option if they want to store the additional dependencies in the lock file or not)

**Comment by baszalmstra** [comment]
I have been thinking about this a lot but haven't figured out a nice way to do this. 

Essentially I want to always be able to create an environment from a lock-file (if it exists). This should include optional dependencies. This is important because, without it, it still leaves users (read not-the-authors) open to complex dependency issues.

Having the `--with` syntax is really nice but like you said this could lead to a combinatorial explosion of dependency sets. 

With rust you have `--features` which is very similar. The difference is that Rust features can only *add* dependencies, they don't have an impact on the "base" set of dependencies (I think). Rust also suffers a lot less from dependency conflicts because you can have "local" dependencies. This wouldn't work for your case because you cant install both `python 3.9` and `python 3.10`. Different python versions will also probably have a huge impact on the rest of the selected dependencies.

We could also looking into creating a proper build matrix and see how long it takes to solve. There are also definitely some performance improvements we can do for the solving subsequent requests much faster.

Perhaps the easiest way (a build matrix) could work? Ill have to try.

**Comment by pavelzw** [comment]
But what about features that exclude each other? For example when you want to test different python versions or your support for different pydantic versions?

**Comment by baszalmstra** [comment]
So Im just spitballing here but you could create a matrix for that similar to `conda-build-config.yaml` or Github actions:

```yaml
python:
  - 3.9
  - 3.10
  - 3.11
pydantic:
  - 1.0
  - 2.0
exclude:
  - python: 3.9
    pydantic: 2.0
```

Or whatever.
