### ISSUE TITLE
Simplify exposing local binaries globally

### ISSUE THREAD

**Issue by certik** [prefix-dev/pixi#2406]
### Goal

I want to build a 3rd party project locally and expose the binary into my `~/bin` directory. I am on Windows (but I think the issue applies to all platforms).

### Workarounds

Here is what I do today, which works, but is too manual, I would like pixi to automate many of these steps.

Let's take `ledger` (https://github.com/ledger/ledger). I add manual `pixi.toml`: https://github.com/certik/ledger/blob/9e9d599eb63935129056399c2e524448ac38785c/pixi.toml:
```toml
[project]
authors = ["Ondřej Čertík <ondrej@certik.us>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ledger"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
build = "cmake -GNinja -B build -DBoost_USE_STATIC_LIBS=OFF -DBUILD_LIBRARY=off . && cmake --build build -j 8"
run = "build/ledger.exe"
install = "cp build/ledger.exe .pixi/envs/default/Library/bin/"

[dependencies]
cmake = ">=3.30.5,<4"
boost = "1.72.*"
gmp = ">=6.3.0,<7"
mpfr = ">=4.2.1,<5"
```
I build it, which creates a binary in `build/ledger.exe`:
```console
$ pixi r build
```
If I do `pixi r run` then the binary works, however there are two issues:
* I didn't figure out how to pass arguments to it (is there a way?)
* The binary does not work standalone, because it requires some boost `.dll` libraries from `.pixi/envs/default/Library/bin/`.
So I copy `build/ledger.exe` into the bin directory, so that it lives next to the `.dll` files:
```console
$ pixi r install
```
Now the `ledger.exe` works out of the box. Next step is to create a `.bat` script in `~/bin` (since Windows doesn't seem to allow symlinks), so I create `~/bin/ledger.bat`:
```cmd
@echo off
C:\Users\ondrejcertik\repos\ledger\.pixi\envs\default\Library\bin\ledger.exe %*
```

Now when I start a new `shell`, I can just type `ledger` and everything just works (I have `~/bin` in my `$PATH`).

### Feature Requests

1. I would like `pixi` to automate the `install = "cp build/ledger.exe .pixi/envs/default/Library/bin/"` part. For example, I can just `cmake install` into some prefix as part of some task. However modifying the `default` environment manually is probably not the right approach?
2. I would like `pixi` to automatically create the "symlink" (`.bat` file) above to expose the binary.

Pixi can almost do this with `pixi global`, it puts these binaries as `.bat` files into `~/.pixi/bin` which I have in my path. However it seems to only work with existing conda packages, not my current project. So if the `global` feature could be extended to just work for a local project, as well as ensuring the binary lives with the `.dll` libraries in the same directory, then that would fix everything.

**Comment by Hofer-Julian** [comment]
Yes, as soon as `pixi build` is out we plan to add this functionality

**Comment by ruben-arts** [comment]
Hey @certik, 

> I didn't figure out how to pass arguments to it (is there a way?)

All words after `pixi run` will be forwarded to the run shell. So `pixi run YOUR_TASK this-is-appended-to-your-task`. 
We don't have a way yet to do this between depending tasks.

**Comment by seowalex** [comment]
@ruben-arts I have a slight problem with `pixi run`, in that the underlying `deno_task_shell` does some unexpected escaping.

A minimum repro:

```bash
$ echo "'test'"
'test'
$ pixi run echo "'test'"
test
```

**Comment by ruben-arts** [comment]
@seowalex, I've tried to find a way around this. But it seems to be a design decision within `deno_task_shell` to do it this way. Could you give a use case where this creates a problem? If you have one it's good to start a new issue as it is not related to this issue.

**Comment by wolfv** [comment]
Hi @certik did you already give `pixi-build` a try? I think it should be quite straightforward to wrap your project with a pixi-build definition like so:

```toml
[workspace]
authors = ["Ondřej Čertík <ondrej@certik.us>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ledger"
platforms = ["win-64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
ledger = { path = "." }

[package]
name = "ledger"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-cmake"
version = "0.1.*"
extra-args = ["-DBoost_USE_STATIC_LIBS=OFF", "-DBUILD_LIBRARY=off"]

[package.host-dependencies]
boost = "1.72.*"
gmp = ">=6.3.0,<7"
mpfr = ">=4.2.1,<5"
```

With this definition, you can install this package into the workspace itself (`ledger = { path = "." }`.

You can also install it from git or path into any other project / workspace or you can globally install it (e.g. `pixi global install --path ledger/`) to expose the `ledger` binary everywhere.

**Comment by wolfv** [comment]
Note: the main downside vs your approach is that we run the `install` step to put the binary into the right folder, while you are currently looking to run the "in-tree" built package.

**Comment by certik** [comment]
I can confirm that with this [pixi.toml](https://github.com/certik/ledger/blob/644d389e8ff848ef99ed4323f01882fcfe420b5d/pixi.toml):
```toml
[workspace]
authors = ["Ondřej Čertík <ondrej@certik.us>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ledger"
#platforms = ["win-64", "osx-arm64"]
platforms = ["win-64"]
version = "3.3.2"
preview = ["pixi-build"]

[dependencies]
ledger = { path = "." }

[package]
name = "ledger"
version = "3.3.2"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = ["-DBoost_USE_STATIC_LIBS=OFF", "-DBUILD_LIBRARY=off"]

[package.host-dependencies]
boost = "1.72.*"
gmp = ">=6.3.0,<7"
mpfr = ">=4.2.1,<5"

[package.run-dependencies]
boost = "1.72.*"
```
The following works:
```console
pixi build
pixi global install --path ledger-3.3.2-h9352c13_0.conda
```

And it exposes the local binary globally. I think this workflow fixes the issue fully in a clean way.
