### ISSUE TITLE
pixi global list fails when empty global environment is present

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/pixi#2413]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[envs.some_dev]
channels = ["conda-forge"]
dependencies = {}
exposed = {}
```

### Issue description

If an empty environment is present in pixi global manifest as in the example

it will make `pixi global list` fail with the following error:
`× No package records found in /Users/graf/.pixi/envs/some_dev/conda-meta`

### Expected behavior

I think we should not allow such (empty) environment declaration in manifest.
