### ISSUE TITLE
Unable to install environment that lists cuda-specific features when on macOS

### ISSUE THREAD

**Issue by ericmjl** [prefix-dev/pixi#2443]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pyproject.toml` file:

```toml
[project]
name = "pixi-cuda-environment"
version = "0.1.0"
description = "Add a short description here"
authors = [{name = "Eric Ma", email = "my-email@gmail.com"}]
requires-python = ">= 3.11"
dependencies = ["pandas"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

# Feature Definitions
[tool.pixi.feature.cuda]
platforms = ["linux-64"]
system-requirements = {cuda = "12"}

[tool.pixi.feature.cuda.dependencies]
jaxlib = { version = "*", build = "*cuda12*" }

# Environments
[tool.pixi.environments]
cuda = ["cuda"]
```

When running `pixi install`, I get this error:

```bash
❯ pixi install
  × Unable to solve pypi dependencies for the cuda environment because no compatible python interpreter can be installed for the current
  │ platform
    ╭─[15:13]
 14 │ channels = ["conda-forge"]
 15 │ platforms = ["osx-arm64", "linux-64"]
    ·             ────────────┬────────────
    ·                         ╰── even though the projects does include support for 'osx-arm64'
 16 │ 
 17 │ 
 18 │ [tool.pixi.tasks]
 19 │ test = "pytest"
 20 │ 
 21 │ [tool.pixi.dependencies]
 22 │ ruff = ">=0.5.5,<0.6"
 23 │ pytest = ">=8.3.2,<8.4"
 24 │ ipython = ">=8.26.0,<9"
 25 │ jax = ">=0.4.28"
 26 │ pytest-cov = ">=5.0.0,<6"
 27 │ 
 28 │ # Feature Definitions
 29 │ [tool.pixi.feature.cuda]
 30 │ platforms = ["linux-64"]
    ·             ──────┬─────
    ·                   ╰── feature 'cuda' does not support 'osx-arm64'
 31 │ system-requirements = {cuda = "12"}
    ╰────
  help: Try converting your [pypi-dependencies] to conda [dependencies]
```

### Issue description

It appears that I cannot install environments when I specify my pyproject.toml as above.

My goal is to support both osx-arm64 and linux-64 environments, and I want the CUDA environment to be installed only on linux-64. An additional requirement is that my project is also a distributable Python package, and I need to be able to specify dependencies in the `project.dependencies` section rather than `tool.pixi.dependencies` section, so that when others `pip`-install the package they can also pull in the necessary dependencies.

### Expected behavior

Based on my mental model, pixi should have just proceeded with the install. After all, I have defined the `cuda` feature to be linux-64 only!
