### ISSUE TITLE
Cannot solve environemnt

### ISSUE THREAD

**Issue by ernimd** [prefix-dev/pixi#2455]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "mypkg"
requires-python = ">=3.9,<3.12"
dynamic = ["version"]
dependencies = [
    "py-wake>=2.6.5,<3",
    "jupyterlab>=4.2.5,<5",
    "pydoe3>=1.0.4,<2",
    "pydoe2>=1.3.0,<2",
    "tensorflow>=2.13.1,<3",
    "shapely>=2.0.6,<3",
    "openmdao<=3.26",
    "matplotlib>=3.7.5,<4",
    "numpy>=1.24.3,<2",
    "numpy-financial>=1.0.0,<2",
    "scipy>=1.10.1,<2",
    "scikit-learn>=1.3.2,<2",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"] # TODO: add macOS

[tool.pixi.dependencies]
pyoptsparse = ">=2.11.3,<3"
pytest-xdist = ">=3.6.1,<4"
pytest = ">=8.3.3,<9"
pycodestyle = ">=2.12.1,<3"
pytest-cov = ">=5.0.0,<6"
sphinx = ">=7.4.7,<8"
sphinx_rtd_theme = ">=3.0.1,<4"
mock = ">=5.1.0,<6"
autopep8 = ">=2.3.1,<3"
git = ">=2.47.0,<3"
pre-commit = ">=4.0.1,<5"
pip = ">=24.3.1,<25"
make = ">=4.4.1,<5"
pandoc = ">=3.5,<4"
pypandoc = ">=1.14,<2"
nbsphinx = ">=0.9.5,<0.10"
nbconvert = ">=7.16.4,<8"

[tool.pixi.pypi-dependencies]
hatch = "*"
hatchling = ">=1.26"
```

Install gives:

```sh
$ pixi install
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because hatchling==1.26.1 depends on packaging>=24.2 and
      packaging==24.1, we can conclude that hatchling==1.26.1 cannot
      be used. (1)
      
      Because hatchling==1.26.0 was yanked (reason: Incompatible
      with currently released Hatch) and only the following versions
      of hatchling are available:
          hatchling<=1.26.0
          hatchling==1.26.1
      we can conclude that hatchling>=1.26.0,<1.26.1 cannot be used.
      And because we know from (1) that hatchling==1.26.1 cannot be
      used, we can conclude that hatchling>=1.26.0 cannot be used.
      And because you require hatchling>=1.26, we can conclude that
      your requirements are unsatisfiable.
```

### Issue description

Not sure if that's pixi problem or related to the latest `hatchling = ">=1.26"` release. They fixed a problem in the new version, but cannot add it to environment...

### Expected behavior

Resolution of environment

**Comment by ruben-arts** [comment]
You can try adding `packaging = ">24.2"` to the `[tool.pixi.dependencies]` and because it now got `24.1` from the conda dependencies. 

```
pixi add "packaging>24.2"
```

**Comment by ernimd** [comment]
if I comment out the hatch dep and do `pixi add "packaging>24.2"` it does not obey this and simply adds `packaging = ">=24.1,<25"`

**Comment by ruben-arts** [comment]
Oh I see, conda-forge doesn't support `packaging > 24.1` yet. This mostlikely will be solved in a short time: https://github.com/conda-forge/packaging-feedstock/pull/31

**Comment by ernimd** [comment]
How come putting this under pypi deps, doesn't get resolved? 

```toml
packaging = ">=24.2"
hatch = ">=1.13.0,<2"
hatchling = ">=1.26"
```

Because all of these are available there...
