### ISSUE TITLE
pixi doesn't install specified commit of pypi git dependency

### ISSUE THREAD

**Issue by beenje** [prefix-dev/pixi#2456]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

This is with pixi 0.35.0.

Considering the following `pixi.toml`:

```toml
[project]
channels = ["conda-forge"]
name = "test-pixi"
platforms = ["osx-arm64", "linux-64"]

[tasks]
check = "grep orphan .pixi/envs/default/lib/python3.12/site-packages/sphinx_tags/__init__.py"

[dependencies]
python = "3.12.*"
pip = ">=24.3.1,<25"
sphinx = "*"

[pypi-dependencies]
# sphinx-tags = { git = "https://github.com/beenje/sphinx-tags.git", rev = "490f40f" }
sphinx-tags = "==0.4"
```

If I run `pixi run check`, I get the expected output (only one line with `orphan`).

```shell
$ pixi run check
✨ Pixi task (check): grep orphan .pixi/envs/default/lib/python3.12/site-packages/sphinx_tags/__init__.py
        content.append(":orphan:")
```

I now replace the `sphinx-tags` version with a specific commit (the line `orphan: true` was added in this commit).

```toml
[pypi-dependencies]
sphinx-tags = { git = "https://github.com/beenje/sphinx-tags.git", rev = "490f40f" }
```

```shell
$ rm -rf .pixi/ pixi.lock
$ pixi run check
✨ Pixi task (check): grep orphan .pixi/envs/default/lib/python3.12/site-packages/sphinx_tags/__init__.py
        content.append(":orphan:")
```

The old version is still installed despite the proper version in `pixi.lock`:

```
$ grep sphinx-tags pixi.lock
      - pypi: git+https://github.com/beenje/sphinx-tags.git@490f40f0042792ca410c249e195f29c96e33b25b
      - pypi: git+https://github.com/beenje/sphinx-tags.git@490f40f0042792ca410c249e195f29c96e33b25b
  name: sphinx-tags
  url: git+https://github.com/beenje/sphinx-tags.git@490f40f0042792ca410c249e195f29c96e33b25b
```

If I remove rattler cache, I get the proper version installed:

```shell
$ rm -rf .pixi /root/.cache/rattler/cache
$ pixi run check
✨ Pixi task (check): grep orphan .pixi/envs/default/lib/python3.12/site-packages/sphinx_tags/__init__.py
        content.append("orphan: true")
        content.append(":orphan:")
```

### Issue description

I believe the issue is the same as what was reported in https://github.com/prefix-dev/pixi/issues/2358, but closed by the author who couldn't reproduce.

There seems to be a cache issue preventing the specified git version to be installed, when another version was installed previously.

### Expected behavior

Removing the cache shouldn't be needed to install a specific git version of a package.
