### ISSUE TITLE
Running a task from a given environment within pixi shell of another environment

### ISSUE THREAD

**Issue by maurosilber** [prefix-dev/pixi#2468]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Here is a simple `pixi.toml` to reproduce this issue:

```toml
[project]
name = "tasks_from_env"
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[feature.A.tasks]
echo_A = "echo hello from A"

[feature.B.tasks]
echo_B = "echo hello from B"

[environments]
a = ["A"]
b = ["B"]
```

And a series of commands and their outputs with `pixi == 0.35`:

```shell
❯ pixi run

Available tasks:
	echo_A
	echo_B

❯ pixi shell -e a

❯ pixi run

Available tasks:
	echo_A

❯ pixi run echo_B
echo_B: command not found

Available tasks:
	echo_A

❯ pixi run -e b echo_B
✨ Pixi task (echo_B in b): echo hello from B
hello from B
```

### Issue description

This might not be a bug, but I cannot run a task from a given environment without explicitly adding `-e <env>` if I'm within the shell of another environment. In my project, I have `lint` environment with a `lint` task that I used to run with `pixi run lint`, since it is the only environment defining a task with that name. But the Python extension in VSCode activates another environment automatically in its terminal. Maybe I should just prevent the VSCode extension from activating an environment in the terminal.

### Expected behavior

```shell
❯ pixi shell -e a

❯ pixi run

Available tasks:
	echo_A
        echo_B
```

**Comment by ruben-arts** [comment]
This now works, if you run `pixi run -e env-name` it will always use that environment

**Comment by maurosilber** [comment]
That already worked at the time of the issue. I was asking whether pixi can "autofill" the `-e env-name`, as it does when running `pixi run <task>` outside a pixi shell (if that task is defined for a single environment).

Without activating any environment: `pixi run echo_A` == `pixi run -e A echo_A`
Activating B (`pixi shell -e B`), `pixi run -e A echo_A` works, but `pixi run echo_A` does not.

It is also an issue with cross-environment dependencies:
```toml
[feature.A.tasks.echo_A]
cmd = "echo hello from A"
depends-on = ["echo_B"]
# depends-on = [{ task = "echo_B", environment = "b" }]

[feature.B.tasks]
echo_B = "echo hello from B"

[environments]
a = ["A"]
b = ["B"]
```

- `pixi run echo_A` ✅
- `pixi run -e A echo_A` ❌
- `pixi shell -e A` and then `pixi run echo_A` ❌

But it works if the dependency is specified with an explicit environment (the commented line).
