### ISSUE TITLE
`pixi upgrade` may modify the location of a package in a `pyproject.toml` manifest

### ISSUE THREAD

**Issue by olivier-lacroix** [prefix-dev/pixi#2470]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

With the following pyproject.toml
```toml

[project]
authors = [{name = "Olivier Lacroix", email = "olivier.lacroix@m4x.org"}]
dependencies = []
description = "Add a short description here"
name = "test-upgrade"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
test_upgrade = { path = ".", editable = true }
polars = "==0.*"
```

running `pixi upgrade` yields

```toml
[project]
authors = [{name = "Olivier Lacroix", email = "olivier.lacroix@m4x.org"}]
dependencies = ["polars>=1.13.0,<2"]
description = "Add a short description here"
name = "test-upgrade"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
test_upgrade = { path = ".", editable = true }

[tool.pixi.dependencies]
python = ">=3.13.0,<3.14"
```

### Issue description

Running `pixi upgrade`:

- removed `polars` from `[tool.pixi.pypi-dependencies]` and added it to the `[project.dependencies]` array
- added `python` to the `[tool.pixi.dependencies]` table.

### Expected behavior

Running `pixi upgrade`:

- should keep `polars` under `[tool.pixi.pypi-dependencies]`
- should most likely not add python as an explicit dependency under `[tool.pixi.pypi-dependencies]` ?
