### ISSUE TITLE
Do not add PyCharm to default package dependencies

### ISSUE THREAD

**Issue by plainerman** [prefix-dev/pixi#2484]
### Problem description

In the pixi documentation it says that you have run 
```
pixi add pixi-pycharm
```
to get PyCharm support up and running. I am a bit surprised that this is installed for the whole pyproject and not an optional dependency.

I was wondering if it is possible to achieve the same via some optional / dev dependencies? I think it would make more sense because these dependencies shouldn't be required by e..g, a production environment.

Any ideas on how to do it and if we should update the docs to reflect this?

Thank you!

**Comment by ruben-arts** [comment]
Hey @plainerman, pixi has a really powerful feature we call [multi environment](https://pixi.sh/latest/features/multi_environment/). 

Here is an example for your use-case
```toml
[project]
name = "multi-env"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["numpy"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.feature.lint.dependencies]
ruff =  "*"

[tool.pixi.feature.dev.dependencies]
pixi-pycharm = "*"

[tool.pixi.environments]
# The production environment is the default feature set.
# Adding a solve group to make sure the same versions are used in the `default` and `prod` environments.
prod = { solve-group = "main" }

# Setup the default environment to include the dev features.
# By using `default` instead of `dev` you'll not have to specify the `--environment` flag when running `pixi run`.
default = { features = ["dev"], solve-group = "main" }

# The lint environment is doesn't need the default feature set but only the `lint` feature 
# and thus can also be excluded from the solve group.
lint = { features = ["lint"], no-default-feature = true }
```

Now you as a user can run `pixi shell` which will start the `default` environment. In production you then just run `pixi run -e prod COMMAND` and the minimal `prod` environment is installed.

I hope this helps! 

ps. some pointers, `project.optional-dependencies` in a pyproject.toml are interpreted as `feature`s so for the pypi dependencies you could also use that to make the file more reusable outside of `pixi`.
