### ISSUE TITLE
Leave out development package out of lock file

### ISSUE THREAD

**Issue by ernimd** [prefix-dev/pixi#2512]
### Problem description

I'm using `pixi` as primary package manager for development of Python packages. It's nice to get an editable installation out of the box, once the environment is set up, thus I add this in a `pyproject.toml`:

```toml
[tool.pixi.pypi-dependencies]
awesome_pkg = { path = ".", editable = true }
```

One thing that's annoying about this, that lock file gets updated with every single commit (at least in my versioning setup, where each commit is marked with post: `w.y.z.postx`). Would be nice to have an option to leave this package out of lock file, so `pixi.lock` doesn't have to be committed to a repo every single commit. Something along the lines:

```toml
[tool.pixi.pypi-dependencies]
awesome_pkg = { path = ".", editable = true, lock = false }
```

Or there is another way to achieve this ? 

Thanks !
