### ISSUE TITLE
Unhelpful error messages on solve conflict between PyPI and Conda dependencies

### ISSUE THREAD

**Issue by ghost** [prefix-dev/pixi#2543]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "boundaries"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.12"

[pypi-dependencies]
topfarm = ">=2.4.1, <3"
```

If I run

```sh
pixi add pandas
```

I get:
```sh
(boundaries) ernie@andromeda:~/Downloads/boundaries$ pixi add pandas
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because topfarm==2.4.1 depends on numpy>=1.24.3,<2 and numpy==2.1.3, we can
      conclude that topfarm==2.4.1 cannot be used.
      And because only topfarm<=2.4.1 is available and you require
      topfarm>=2.4.1, we can conclude that your requirements are unsatisfiable.

  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because topfarm==2.4.1 depends on numpy>=1.24.3,<2 and numpy==2.1.3, we can
      conclude that topfarm==2.4.1 cannot be used.
      And because only topfarm<=2.4.1 is available and you require
      topfarm>=2.4.1, we can conclude that your requirements are unsatisfiable.
```

### Issue description

Weird behaviour with `numpy` dependency;

Manually adding `pandas = "<2.0"` to dependencies solves the issue : )

### Expected behavior

I would expect `pixi` to pick up an older version of `pandas` with some lower requirement of `numpy` to match the `topfarm` asking it to be below `2.0`...
