### ISSUE TITLE
Bug in resolving PyPI deps?

### ISSUE THREAD

**Issue by anabiman** [prefix-dev/pixi#2554]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

command:

```shell
pixi install
```

pyproject.toml:

```toml
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
description = "descr"
name = "my-proj"
requires-python = ">= 3"
version = "0.0.0"
readme = "README.md"
dependencies = ["tensorflow"] 

[tool.pixi.project]
channels = ["conda-forge"]
platforms = [
  "linux-64",
]

[tool.pixi.pypi-dependencies]
my_proj = { path = ".", editable = true }

```

yields

```shell
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because only the following versions of tensorflow are available:
 ...
have no wheels with a matching Python ABI tag and you require tensorflow, we can conclude that your requirements are unsatisfiable.
      
hint: Pre-releases are available for tensorflow in the requested range (e.g., 2.18.0rc2), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

### Issue description

Running pixi v0.3.7.0.

### Expected behavior

Tensorflow is pip installable.
