### ISSUE TITLE
Installing a wheel file: Wheel version does not match filename

### ISSUE THREAD

**Issue by alllexx88** [prefix-dev/pixi#2572]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.12"

[pypi-dependencies]
vllm = { url = "https://vllm-wheels.s3.us-west-2.amazonaws.com/33f460b17a54acb3b6cc0b03f4a17876cff5eafd/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl" }
```

`vllm` wheel URL is taken from `vllm` docs: https://docs.vllm.ai/en/latest/getting_started/installation.html

### Issue description

`pixi install` on an x86 Linux machine causes:
```
⠂ updating pypi packages in 'default'                                                                                                                                                                                                 thread 'main' panicked at /home/runner/work/pixi/pixi/src/install_pypi.rs:973:14:
called `Result::unwrap()` on an `Err` value: Failed to install: vllm-1.0.0.dev0-cp38-abi3-manylinux1_x86_64.whl (vllm==1.0.0.dev0 (from https://vllm-wheels.s3.us-west-2.amazonaws.com/33f460b17a54acb3b6cc0b03f4a17876cff5eafd/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl))

Caused by:
    Wheel version does not match filename: 0.6.3.dev28+g33f460b1.d20240927 != 1.0.0.dev0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Simply renaming a file to `vllm-0.6.3.dev28+g33f460b1.d20240927-cp38-abi3-manylinux1_x86_64.whl` from `vllm-1.0.0.dev0-cp38-abi3-manylinux1_x86_64.whl` would help, but I don't have a control over the URL. Also, `pip` installs such wheels just fine.

### Expected behavior

The wheel should be installed. Either accept it silently as `pip` does, or, as a more secure solution, support providing the expeted version in the URI (like `pixi add 'vllm:0.6.3.dev28+g33f460b1.d20240927 @ https://vllm-wheels.s3.us-west-2.amazonaws.com/33f460b17a54acb3b6cc0b03f4a17876cff5eafd/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl'`).

Also, in the toml, `version` key is currently not supported together with `url`, something like:
```toml
vllm = { version = "==0.6.3.dev28+g33f460b1.d20240927", url = "https://vllm-wheels.s3.us-west-2.amazonaws.com/33f460b17a54acb3b6cc0b03f4a17876cff5eafd/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl" }
```
gives:
```
  × failed to parse project manifest
    ╭─[pixi.toml:14:8]
 13 │ [pypi-dependencies]
 14 │ vllm = {version = "==0.6.3.dev28+g33f460b1.d20240927", url = "https://vllm-wheels.s3.us-west-2.amazonaws.com/33f460b17a54acb3b6cc0b03f4a17876cff5eafd/vllm-1.0.0.dev-cp38-abi3-manylinux1_x86_64.whl" }
    ·        ────────────────────────────────────────────────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────
    ·                                                                                                        ╰── `version` cannot be used with `url`
    ╰────


```

As a workaround I currently download the wheel manually, rename it and install it from the local fs, but it would be much better not having to resort to doing so.

Thanks!
