### ISSUE TITLE
Lowercase exposed executables removed and not recreated after pixi global update

### ISSUE THREAD

**Issue by beenje** [prefix-dev/pixi#2575]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Exposed executable casing issue was fixed in 0.38.0 and that's great but I bumped into an issue when updating some env.

Given the following `.pixi/manifests/pixi-global.toml`:

```toml
version = 1

[envs.tango-test]
channels = ["conda-forge"]
dependencies = { tango-test = "*" }
exposed = { tangotest = "tangotest" }

[envs.tango-starter]
channels = ["conda-forge"]
dependencies = { tango-starter = "*" }
exposed = { starter = "starter" }
```

Running `pixi global update` after updating to pixi 0.38.0 removed the exposed executables because they didn't follow the executable original case (`TangoTest` and `Starter`).

```shell
$ pixi self-update
✔ Pixi will be updated from 0.37.0 to 0.38.0
✔ Pixi archive downloaded.
✔ Pixi archive uncompressed.
✔ Pixi has been updated to version 0.38.0.

$ pixi global update
✔ Updated environment tango-starter.
✔ Removed exposed executable starter from environment tango-starter.
✔ Updated environment tango-test.
✔ Removed exposed executable tangotest from environment tango-test.

$ pixi global list
├── tango-starter: 8.4
│   └─ exposes: Nothing
├── tango-test: 3.10
│   └─ exposes: Nothing
```

Running `pixi global install tango-starter` doesn't expose the executable.

```shell
$ pixi global install tango-starter
Global environments as specified in '/Users/benber/.pixi/manifests/pixi-global.toml'
└── tango-starter: 8.4 (already installed)
    └─ exposes: Nothing
```

I had to uninstall and install again to get the exposed executable:

```shell
$ pixi global uninstall tango-starter
✔ Removed environment tango-starter.
$ pixi global install tango-starter
Global environments as specified in '/Users/benber/.pixi/manifests/pixi-global.toml'
└── tango-starter: 8.4 (installed)
    └─ exposes: Starter
```

### Issue description

`pixi global update` removed the lowercase executable and left the environment with nothing exposed.

### Expected behavior

I'd have expected `pixi global update` to remove the lowercase executable and automatically add the proper one.

This is an edge case and not super critical. Uninstalling and re-installing works, but I wanted to raise the issue.
