### ISSUE TITLE
"No module named numpy" when trying to install eif from pypi with pixi

### ISSUE THREAD

**Issue by oulenz** [prefix-dev/pixi#2577]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
~/code> pixi init test-pixi-eif --format pyproject
✔ Created /home/oliver/code/test-pixi-eif/pyproject.toml
~/code/test-pixi-eif> cd test-pixi-eif/
~/code/test-pixi-eif> pixi add numpy
✔ Added numpy >=2.1.3,<3
~/code/test-pixi-eif> pixi add --pypi eif
  × default: error installing/updating PyPI dependencies
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to download and build `eif==2.0.2`
  ╰─▶ Build backend failed to determine requirements with `build_wheel()` (exit status: 1)
      
      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
          requires = get_requires_for_build({})
        File "/home/oliver/.cache/rattler/cache/uv-cache/builds-v0/.tmplz6UaX/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/oliver/.cache/rattler/cache/uv-cache/builds-v0/.tmplz6UaX/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/home/oliver/.cache/rattler/cache/uv-cache/builds-v0/.tmplz6UaX/lib/python3.13/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/oliver/.cache/rattler/cache/uv-cache/builds-v0/.tmplz6UaX/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 3, in <module>
          if sys.path[0] == "":
          ^^^^^^^^^^^^
      ModuleNotFoundError: No module named 'numpy'
```

The corresponding `pyproject.toml` file is:

```
[project]
authors = [{name = "foo", email = "bar"}]
description = "Add a short description here"
name = "test-pixi-eif"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = ["eif>=2.0.2,<3"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
test_pixi_eif = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.1.3,<3"
```

### Issue description

I am trying to use `pixi` for a python library, and it's running into an error when trying to install the pipy dependency `eif`. I've also tried having `eif` under `[tool.pixi.pypi-dependencies]`, and not first installing `numpy`, but that doesn't seem to make a difference.

I guess I have three questions:

* Am I doing anything wrong in how I am adding this dependency?
* If not, what is the underlying issue here?
* If this is a real issue, is there a short-term workaround for me?

### Expected behavior

What I find puzzling is that when I manually install numpy in a micromamba/conda environment, and then `pip install eif`, I don't encounter any issues. I thought that pixi is doing essentially the same, but there must be some difference somewhere.

The only thing that I can think of is that the `setup.py` file of `eif` imports `numpy` — that might be atypical.

**Comment by jjjermiah** [comment]
very likely the `setup.py` `numpy` import. It cant tell that the build for eif [requires `numpy`](https://github.com/sahandha/eif/blob/5363acde955e43b5728151443b900585c363fafe/setup.py#L43) without running `setup.py`

Have you been able to install `eif` without pixi? I just tried and there looks like theres a c++ compile error related to [this issue](https://github.com/sahandha/eif/issues/38) 


regardless, i believe the solution to this is to use the `no-build-isolation` pypi-option w/ all the build-requirements installed as pixi dependencies: 

```toml
[project]
name = "eif-with-no-build-isolation"
requires-python = ">= 3.11"
version = "0.1.0"
dependencies = [
  "eif>=2.0.2,<3",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

[tool.pixi.dependencies]
setuptools = ">=72, <=73"
numpy = "*"
cython = ">=3.0.11,<4"
wheel = ">=0.45.1,<0.46"
setuptools_scm = ">=7.1.0,<7.2.0"

[tool.pixi.pypi-options]
no-build-isolation = ["eif"]
```
