### ISSUE TITLE
`pixi global sync` should collect errors rather than returning early

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#2584]
### Problem description

Running `pixi global sync` on this `pixi-global.toml`

```toml
version = 1

[envs.test]
channels = ["https://prefix.dev/conda-forge"]
dependencies = { invalid_package = "*" }
exposed = {}

[envs.test2]
channels = ["https://prefix.dev/conda-forge"]
dependencies = { invalid_package_2 = "*" }
exposed = {}

[envs.typos]
channels = ["https://prefix.dev/conda-forge"]
dependencies = { typos = "*" }
exposed = { typos = "typos" }
```

gives the following error:

```
  × failed to solve environment
  ╰─▶ Cannot solve the request because of: No candidates were found for invalid_package *.
```

Also, `typos` is not available afterward.

As discussed with @wolfv, it would be good if:
- all errors would be collected, and
- correct environments would still be evaluated
