### ISSUE TITLE
Impossible to add a pypi git dependency in a clean environment

### ISSUE THREAD

**Issue by akhmerov** [prefix-dev/pixi#2588]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
authors = ["Anton Akhmerov"]
channels = ["conda-forge"]
description = "Can't boostrap pypi git dependency"
name = "pixi_bug"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
git = ">=2.47.1,<3"

[pypi-dependencies]
skunk = { git = "https://github.com/akhmerov/skunk.git" }
```

### Issue description

It is impossible to install a git dependency in a pixi environment without git even if git is available via pixi itself.

### Expected behavior

Pixi should be able to use git to install pypi dependencies from git sources just like it uses python.
