### ISSUE TITLE
`pixi global sync` doesn't report on removed package

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#2593]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[envs.python]
channels = ["https://prefix.dev/conda-forge"]
dependencies = { python = "*", numpy = "*"}
exposed = { python = "python" }
```

```shell
pixi global sync
pixi global edit
# remove numpy
pixi global sync
```

Output of the last command

```
✔ Environment python was already up-to-date.
```

### Issue description

If I remove a package from an environment, and run `pixi global sync` it is indeed being removed. However, it claims that the environment was already up-to-date which is not true

### Expected behavior

Something like
```
✔ Removed package numpy in environment python.
```
