### ISSUE TITLE
`pixi build` `pixi.lock` doesn't include proper version

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#2600]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

https://github.com/Quantco/polarify/pull/81

```toml
# pixi.toml
[project]
name = "polarify"
# <version not set here>
# ...
[package]
version = "0.2.0"
# ...
```

### Issue description

pixi.lock looks like this:

```yml
- conda: .
  name: polarify
  version: 0.1.0
  build: pyhbf21a9e_0
  subdir: noarch
  depends:
  - python
  input:
    hash: 4f79b562092ea284f5aee2a320868102e5a32984839c350c8f78170339fe2516
    globs:
    - pixi.toml
```

### Expected behavior

pixi.lock should look like this:

```yml
- conda: .
  name: polarify
  version: 0.2.0
  build: pyhbf21a9e_0
  subdir: noarch
  depends:
  - python
  input:
    hash: 4f79b562092ea284f5aee2a320868102e5a32984839c350c8f78170339fe2516
    globs:
    - pixi.toml
```
