### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by lambdaofgod** [prefix-dev/pixi#262]
How to install pytorch?

I've added `pytorch-cuda = "11.8"` and appropriate channels suggested from Pytorch's installation page, but when in `pixi run python` I try to `import torch` it doesn't find the module

**Comment by ruben-arts** [comment]
I was trying to recreate it locally but my internet is to slow to get pytorch installed from their channel right now. I've done it before using `conda-forge` as a channel. So maybe try that. Also always also add the `pytorch` package itself.

**Comment by ruben-arts** [comment]
I was trying to recreate it locally but my internet is to slow to get pytorch installed from their channel right now. I've done it before using `conda-forge` as a channel. So maybe try that. Also always also add the `pytorch` package itself.

**Comment by niemiaszek** [comment]
@lambdaofgod from Pytorch installation page you've got `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia`. Sounds like you installed only pytorch-cuda part. 

For me this worked in pixi.toml (you don't need to torchvision etc.):
```toml
channels = ["conda-forge", "pytorch", "nvidia"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.10.*"
pytorch = "*"
torchvision = "*"
torchaudio = "*"
pytorch-cuda = "11.8"
```
