### ISSUE TITLE
`detached-environments` broken in `0.39`

### ISSUE THREAD

**Issue by moritzwilksch** [prefix-dev/pixi#2623]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
➜  pixi-fr git:(main) ✗ pixi init
✔ Created /home/moritz/Documents/diesdas/mre/pixi-fr/pixi.toml
➜  pixi-fr git:(main) ✗ pixi config list
detached-environments = false

➜  pixi-fr git:(main) ✗ pixi config set detached-environments /tmp/ 
✅ Updated config at /home/moritz/Documents/diesdas/mre/pixi-fr/.pixi/config.toml
➜  pixi-fr git:(main) ✗ pixi config list
detached-environments = "/tmp/"
➜  pixi-fr git:(main) ✗ pixi exec -s pixi=0.39 -- pixi add python
✔ Added python >=3.13.0,<3.14
➜  pixi-fr git:(main) ✗ pixi exec -s pixi=0.39 -- pixi shell     
? The environment directory seems have to moved! Environments are non-relocatable, moving them can cause issues.

        /tmp/pixi-fr-10246024661101062041/envs/default -> /home/moritz/Documents/diesdas/mre/pixi-fr/.pixi/envs/default

This can be fixed by reinstall the environment from the lock-file in the new location.

  × The environment directory has moved from `/tmp/pixi-fr-10246024661101062041/envs/default` to `/home/moritz/Documents/diesdas/mre/
  │ pixi-fr/.pixi/envs/default`. Environments are non-relocatable, moving them can cause issues.
  help: Remove the environment directory, pixi will recreate it on the next run.

```

The created toml file:
```toml
[project]
authors = ["Moritz Wilksch <moritzwilksch@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi-fr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<3.14"
```

### Issue description

After updating to `0.39` pixi no longer respects the `detached-environment` location set in the global config. Instead, it prints a "The environment directory seems have to moved!" message and proceeds to install things into the project root. This happens both for new projects (see reproducer) as well as existing projects.

### Expected behavior

The install location from the global config should be respected.
