### ISSUE TITLE
In `pixi ==0.39.0`, pixi.toml nested dependencies tables are un-parsable without explicit top-level table declaration

### ISSUE THREAD

**Issue by cisaacstern** [prefix-dev/pixi#2640]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

This style of `pixi.toml` is parsable in `pixi <0.39.0` (note lack of explicit top-level table declaration)

```toml
[project]
name = "example"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies.curl]
version = "*"

[feature.nested.dependencies.curl]
version = "*"

```

In `pixi ==0.39.0`, however the following error is raised on parse:

```console
➜ pixi install -a
  × invalid type: string "curl", expected a borrowed string
   ╭─[pixi.toml:6:15]
 5 │ 
 6 │ [dependencies.curl]
   ·               ────
 7 │ version = "*"
   ╰────
```

And the same for the feature dependency table (if the top-level dependency table is removed):

```console
➜ pixi install -a
  × invalid type: string "curl", expected a borrowed string
    ╭─[pixi.toml:9:30]
  8 │ 
  9 │ [feature.nested.dependencies.curl]
    ·                              ────
 10 │ version = "*"
    ╰────
```

To fix this, the top-level tables (for both dependencies, and the nested feature dependencies) must be declared, e.g.

```toml
[project]
name = "example"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[dependencies]
[feature.nested.dependencies]

[dependencies.curl]
version = "*"

[feature.nested.dependencies.curl]
version = "*"

```

### Issue description

Opening as a bug because I am not sure if this is intended behavior or not, but perhaps even if it is, we can devise a more descriptive error message. Happy to help with a fix if there is some way I can be of use!

### Expected behavior

I would expect the behavior to be consisted with prior versions, in which the top-level table definition is not explicitly required. Alternatively, a more descriptive error message would be another option.
