### ISSUE TITLE
`system-requirements` can't be `target` specific.

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#2714]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
[project]
name = "test"
channels = []
platforms = ["osx-arm64", "linux-64"]

[target.linux-64.system-requirements]
cuda = "12.0"
```
Results in:
```
  × unknown field `system-requirements`, expected one of `dependencies`, `host-dependencies`, `build-dependencies`, `run-dependencies`, `pypi-
  │ dependencies`, `activation`, `tasks`
   ╭─[pixi.toml:8:28]
 7 │
 8 │ [target.linux-64.system-requirements]
   ·                  ───────────────────
 9 │ cuda = "12.0"
   ╰────
```

### Issue description

This is not implemented correctly, as it should have system requirements here: 
https://github.com/prefix-dev/pixi/blob/2e8ca9bc14c34899f02885d4cd14baaa815bf076/crates/pixi_manifest/src/target.rs#L22-L38

### Expected behavior

Being able to set system requirements per target.

**Comment by matthewfeickert** [comment]
Thanks for already finding and noting this!

**Comment by hadim** [comment]
I was about to open a new issue about exactly this.

Without this, it's only possible to have a pytorch with cuda package in a second pixi env/feature. I haven't been able to setup. single pixi env/feature that can support a non-cuda system (`osx`) but also a cuda system (`linux`).

Dealing with 2 pixi envs is ok but for this simple scenario, it would be ice to be able to do everything in a single pixi env.

Here is the pixi config that I would like to get to work:

```toml
[project]
name = "pixi_cuda"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12.0,<4"
numpy = ">=2.0.0,<3"
pandas = ">=2.2.3,<3"
pytorch = ">=2.6.0,<3.0.0"


[target.linux-64.dependencies]
cuda-version = "*"

[target.linux-64.system-requirements]
cuda = "12"

```

```bash
$ pixi list --platform linux-64 pytorch
Error: 
  × Unexpected keys, expected only 'dependencies', 'host-dependencies', 'build-dependencies', 'pypi-dependencies', 'activation', 'tasks'
    ╭─[/Users/hadim/pixi_cuda/pixi.toml:17:18]
 16 │ 
 17 │ [target.linux-64.system-requirements]
    ·                  ─────────┬─────────
    ·                           ╰── 'system-requirements' was not expected here
 18 │ cuda = "12"
    ╰────
  help: Did you mean 'host-dependencies'?
```

---

@ruben-arts do you think this is something that require an extensive refactoring or amount of work? If it isn't, then I could potentially give it a try. Let me know.

**Comment by ruben-arts** [comment]
@hadim, this should be doable, and I was also planning to get back to this at some point. But for now my focus is on getting this one in: https://github.com/prefix-dev/pixi/pull/2849

Which should fix your issue, as it checks the lockfile instead of the manifest if the environment can be run. Feel free to test the PR out. It's in review.

**Comment by hadim** [comment]
Thanks. That will probably solve it indeed. I am not in the rush so I'll wait your PR to be released.

I might still give a try to `target.linux-64.system-requirements`.

**Comment by ruben-arts** [comment]
Feel free to do so! It's a welcome change, but know the code around that is heavily changed, so expect conflicts 😉

**Comment by hadim** [comment]
I gave it a try to https://github.com/prefix-dev/pixi/pull/2849 and it still fail on this pixi file:

```toml
[project]
name = "pixi_cuda"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.12.0,<4"
numpy = ">=2.0.0,<3"
pandas = ">=2.2.3,<3"
pytorch = ">=2.6.0,<3.0.0"


[target.linux-64.dependencies]
cuda-version = "*"

[target.linux-64.system-requirements]
cuda = "12"

```

```bash
❯ pixi install    
Error: 
  × Unexpected keys, expected only 'dependencies', 'host-dependencies', 'build-dependencies', 'pypi-dependencies', 'activation', 'tasks'
    ╭─[/Users/hadim/Code/libs/pixi/test-pixi-cuda/pixi.toml:17:18]
 16 │ 
 17 │ [target.linux-64.system-requirements]
    ·                  ─────────┬─────────
    ·                           ╰── 'system-requirements' was not expected here
 18 │ cuda = "12"
    ╰────
  help: Did you mean 'host-dependencies'?
```

**Comment by uwu-420** [comment]
Do I understand correctly that this would also resolve the issue that this does not work?
```toml
[tool.pixi.project]
platforms = ["osx-64", "osx-arm64"]
# ...

[tool.pixi.system-requirements]
macos = "10.13"
```
```
$ pixi install
Error: 
  × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: python >=3.13 cannot be installed because there are no viable options:
      └─ python 3.13.0 | 3.13.0 | 3.13.0 | 3.13.0 | 3.13.0 | 3.13.0 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 | 3.13.1 |
      3.13.1 | 3.13.1 | 3.13.2 | 3.13.2 | 3.13.2 | 3.13.2 | 3.13.2 would require
         └─ __osx >=11.0, for which no candidates were found.
```
because the `macos` requirement is both for `osx-64` and `osx-arm64` which doesn't really make sense.

**Comment by hadim** [comment]
I think so since you'll be able to set `macos = "10.13"` for target `osx64` and `macos = "11.0" for target `osx-arm64`.

---

@ruben-arts: out of curiosity, are you planning a new pixi release soon? It turns out that https://github.com/prefix-dev/pixi/pull/2849 is good enough for my usecase.

**Comment by hadim** [comment]
Actually, https://github.com/prefix-dev/pixi/pull/2849 is enough to make it work on `osx` systems but fails on `linux` CI for example. Ideally I would like to allow cuda packages to be selected and installed on CI even if the machine does not have a GPU. I guess for now, the best is to use something like `CONDA_OVERRIDE_CUDA=12.0`.

**Comment by nelsyeung** [comment]
May I ask why is this not planned?

I'm hitting an issue where I have

```toml
[tool.pixi.system-requirements]
libc = {family = "glibc", version = "2.26"}
```

But for `linux-aarch64`, I don't need that requirement. I tried using `CONDA_OVERRIDE_GLIBC`, but I'm still getting:

```
Error:   × failed to solve the pypi requirements of environment 'default' for platform 'linux-aarch64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because vtk==9.6.0 has no wheels with a matching platform tag (e.g., `manylinux_2_26_aarch64`) and only vtk<=9.6.0 is available, we can conclude that vtk>=9.6.0 cannot be used.
      And because you require vtk>=9.6.0, we can conclude that your requirements are unsatisfiable.
      
      hint: Wheels are available for `vtk` (v9.6.0) on the following platforms: `manylinux_2_17_x86_64`, `manylinux_2_28_aarch64`, `manylinux2014_x86_64`, `macosx_10_10_x86_64`, `macosx_11_0_arm64`, `win_amd64`
```
