### ISSUE TITLE
Environments with different platforms fail to solve in the same solve group

### ISSUE THREAD

**Issue by borchero** [prefix-dev/pixi#2725]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
channels = ["conda-forge"]
name = "pixitest"
platforms = ["linux-64", "osx-arm64", "win-64"]

[dependencies]
numpy = "*"

[feature.feat1]
platforms = ["linux-64", "osx-arm64"]
[feature.feat1.dependencies]
kubernetes-kind = "*"

[environments]
env1 = { solve-group = "prod" }
env2 = { features = ["feat1"], solve-group = "prod" }
```

### Issue description

When trying to run a solve where

- There are >=2 environments with the same solve group AND
- A strict subset of the environments reference a feature whose `platforms` is a strict subset of the project's `platforms` AND
- At least one dependency in this feature is not available for all of the project's `platforms`

the solve fails. For the MWE above, it fails with the following message:

```
  × failed to solve the conda requirements of 'prod' 'win-64'
  ╰─▶ Cannot solve the request because of: No candidates were found for kubernetes-kind *.
```

### Expected behavior

The solve should be successful with:

- `env1` containing `numpy` for `linux-64`, `osx-arm64` and `win-64`
- `env2` containing `numpy` and `kubernetes-kind` for `linux-64` and `osx-arm64`

**Comment by ruben-arts** [comment]
Great issue report!

This sounds like a reasonable extension of the `solve-group` feature. I would like to figure out where in the design this logic gets called, as I would also have expected it to skip the solve-group logic for the `win-64` platform on env2.

**Comment by borchero** [comment]
@ruben-arts do you have some pointers on where to solve this? Happy to drive this along by getting started with a PR.

**Comment by ruben-arts** [comment]
Since you already figured out that the error depends on the lockfile I think the best guess would be to start here: https://github.com/prefix-dev/pixi/blob/110acb95b24e1550d93b7c36636d790f8dc31659/src/lock_file/outdated.rs#L288

It looks like extending those platforms is creating the current behavior. I guess the solve groups need to be split into platforms or something like that. 

Does that help already? Otherwise you know where to find us!

**Comment by maresb** [comment]
I think I've encountered the same or an extremely similar problem.

I run Linux. I want to use JAX/`jaxlib` when possible. I'd need to support Windows. Jaxlib is unavailable for Windows from conda-forge. I define lots of environments, and so I want everything to use a single solve group.

Accordingly, for a minimal reproducer I define:

```toml
[project]
name = "no-candidates-found-for-jaxlib"
platforms = ["linux-64", "win-64"]
channels = ["conda-forge"]

[feature.jax]
platforms = ["linux-64"]

[feature.jax.dependencies]
jaxlib = "*"

[environments]
default = {features = [], solve-group = "default"}
jax = {features = ["jax"], solve-group = "default"}
```

This won't solve, but I can achieve an up-to-date lockfile via the following procedure:

**Steps:**
1. Ensure `pixi.lock` doesn't exist and the cache is clean.
2. From Linux I run `pixi update`: 
   ```text
   Error:   × failed to solve the environment
     ╰─▶ Cannot solve the request because of: No candidates were found for jaxlib *.
   ```
3. Comment out the `default` environment.
4. Run `pixi update` again with success.
5. Restore the `default` environment.
6. Run `pixi update` again:
   ```text
   ✔ Lock-file was already up-to-date
   ```

Since my jax feature is restricted to `linux-64`, I would have expected this to work from a fresh start (via steps 1 and 2 alone).

This makes me wonder how tightly coupled is a pixi solve group between different platforms? For example, does a solve group attempt to enforce the same version across platforms? (Obviously it's impossible enforce the same build string across platforms, since build strings are platform dependent.) Or does a solve group permit different versions on different platforms?
