### ISSUE TITLE
Pixi doesn't seem to be isolating environments correctly

### ISSUE THREAD

**Issue by rohanaras** [prefix-dev/pixi#2747]
I'm trying to install a Pixi environment in a docker container based on the image ate `ghcr.io/prefix-dev/pixi:latest`. I have a `pyproject.toml` that looks something like

```toml
[tool.pixi.dependencies]
python = ">=3.12"

[tool.pixi.pypi-dependencies]
local-package = { path = ".", editable = true }

[tool.pixi.feature.dev.pypi-dependencies]
custom-dev-dep = { git = "ssh://git@url/custom-dev-dep.git", rev = "revision" }

[tool.pixi.environments]
default = { features = [], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
```
Of interest here is the the dependency installed from a git repo. The container in question does not have git installed—however, I believe this shouldn't matter as in the container I install the `default` environment with

```docker
RUN pixi install -e default
```

This step, however, results in this error:

```shell
 => ERROR [base build 4/5] RUN pixi install -e prod                                                      68.7s
------
 > [base build 4/5] RUN pixi install -e prod:
68.59   × failed to solve the pypi requirements of 'default' 'linux-64'
68.59   ├─▶ Failed to download and build `dsrepo-backend @ git+ssh://
68.59   │   git@url/custom-dev-dep.git@revision`
68.59   ├─▶ Git operation failed
68.59   ╰─▶ Git executable not found. Ensure that Git is installed and available.
68.59
```

I don't get this error if I comment out the `custom-dev-dep` line in the `pyproject.toml`. This seems to suggest that Pixi is trying to fetch the requirements of the `dev` environment, even when I'm not asking for it—I feel like this isn't the expected behavior?
