### ISSUE TITLE
`lock-file not up-to-date with the project` with Python package from Github.

### ISSUE THREAD

**Issue by tobiasraabe** [prefix-dev/pixi#2763]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Hi,

when installing from Github, I cannot lock my environment.

```toml
[project]
channels = ["conda-forge"]
name = "repro"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"

[pypi-dependencies]
inspect-ai = { git = "https://github.com/tobiasraabe/inspect_ai", rev = "enable-structured-output"}
```

```console
$ pixi --version
pixi 0.39.3
```

Running

```console
$ pixi install
$ pixi run --locked python
```

always leads to an `lock-file not up-to-date with the project`.

[pixi.lock](https://github.com/user-attachments/files/18231693/pixi.txt)

### Issue description

-

### Expected behavior

-
