### ISSUE TITLE
pixi fails to install psycopg[binary] on MacOS 14

### ISSUE THREAD

**Issue by bshelkhonov** [prefix-dev/pixi#2769]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init
pixi add python
pixi add --pypi "psycopg[binary]"
```

pixi.toml:
```toml
[project]
authors = ["my name"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "test_pixi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.1,<3.14"

[pypi-dependencies]
psycopg = { version = "*", extras = ["binary"] }
```

macbook m1, macos 14.6.1
pixi 0.39.4

### Issue description

pixi fails with the following output: https://gist.github.com/bshelkhonov/9c61ca91f8f3c8bb0d79dd31b2053469

### Expected behavior

uv works fine:
```shell
uv init
uv add "psycopg[binary]"
```
