### ISSUE TITLE
Incorrect environment resolution when using both Conda and PyPI dependencies

### ISSUE THREAD

**Issue by apcamargo** [prefix-dev/pixi#2772]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi init -c conda-forge -c bioconda test
$ cd test
$ pixi add bakta
$ pixi add --pypi lovis4u
$ pixi run python -c "import pyhmmer ; print(pyhmmer.__version__)"
```

```
0.1.4
```

```shell
$ cat pixi.toml
```

```toml
[project]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bakta = ">=1.10.3,<2"

[pypi-dependencies]
lovis4u = ">=0.0.13, <0.0.14"
```

### Issue description

I'm trying to create a project with both the `bakta` (in Bioconda) and `lovis4u` (in PyPI only) Python libraries. Both of them depend on `pyhmmer`: `bakta` depends on [`pyhmmer >=0.10.15`](https://github.com/bioconda/bioconda-recipes/blob/f79c3794c9c9e5562cd5e62af0a0a0252aaa3fbc/recipes/bakta/meta.yaml#L40), while `lovis4u` [doesn't have any version requirements for `pyhmmer`](https://github.com/art-egorov/ilund4u/blob/649a552f81a2b99546f0083cf80adcefb4ed3d75/setup.py#L29-L30).

When Pixi resolves the environment, it installs version 0.1.4 of `pyhmmer` (which is too old for `bakta`), even though the latest version (0.10.15) would satisfy both. If I create a project with Python 3.11 and add `lovis4u`, `pyhmmer` 0.10.15 gets installed.

Maybe this has to do with parselmouth and Bioconda? If that's the case, why did Pixi pull an old version from PyPI instead of the newest one?

### Expected behavior

Pixi should detect that a `pyhmmer` Conda package is already installed and not pull it from PyPI.

**Comment by Hofer-Julian** [comment]
I can reproduce your issue. Like you, I cannot see a reason why `pyhmmer` conda dependency would be overridden with the older one from pypi.

Maybe @tdejager can take a look when he's back from his holiday.

**Comment by apcamargo** [comment]
Thank you, @Hofer-Julian! Let me know if there's anything I could do to help with this

**Comment by apcamargo** [comment]
@baszalmstra I think that the auto-close might have made a mistake. This is a bug, not a feature request

**Comment by tdejager** [comment]
Tried this with this:

```toml
[workspace]
authors = ["Tim de Jager <tdejager89@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "2772"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
bakta = ">=1.11.4,<2"

[pypi-dependencies]
lovis4u = ">=0.1.5.1, <0.2"
```

And I get phymer:

```
pixi list pyhmmer                                                                                                                                                                                                                                                                                                                                                                                          ─╯
Package  Version  Build            Size     Kind   Source
pyhmmer  0.11.1   py311h3d978dd_2  4.2 MiB  conda  https://conda.anaconda.org/bioconda/
```

Has this been resolved?
