### ISSUE TITLE
Add `--force` flag to `pixi add` and `pixi upgrade`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#2784]
### Problem description

When adding or upgrading a package, you sometimes want to adapt other dependencies if they clash with your request.

If e.g. there's no flask version supporting Python 3.13, this will fail

```toml
# pixi.toml
[dependencies]
python = ">=3.13.0,<3.14"
````

```
pixi add flask
```

However, we could add a `--force` flag which would downgrade python

```
pixi add flask --force
```

The same use case applies to `pixi upgrade`

**Comment by notPlancha** [comment]
What should the behaviour of the downgraded dependencies be? Using that example, let's say pixi decided on using python 3.12.10; which would be more appropriate:

```toml
python = "<3.13"                 # limit based on flask
python = "*"                         # fully removing version
python = ">=3.12.10,3.13"   # limit based on flask and extend minimum version
python = ">=3.12.10,3.14"   # extend minimum version without changing the other end
```

(there might be other options I'm not seeing)
