### ISSUE TITLE
rename `[x-dependencies]` to `[package.x-dependencies]`?

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#2798]
Currently its quite confusing that some things belong to package and the other to the workspace/project. The following specification would be a way to rectify this:

```toml
[package]
name = "foobar"
version = "0.1.0" 

[package.build]
backend = { name = "pixi-build-python", version = "*" }

# Question: should channels also be part of build-backend perhaps?
channels = []

# I think this can be achieved in JSON schema if we can match on 
# `package.build.backend.name` == `pixi-build-python`
#
# Question: Is `args` a good enough name?
[tool.pixi-build-python]
noarch = true

[package.host-dependencies]
python = "3.11"
meson-py = "*"

[package.build-dependencies]
cxx-compilers = "*"

[package.run-dependencies]
foobar-ext = "*"

[package.variants]
python = []


# Workspace keys are not nested
[workspace]

[dependencies]
foobar = { source = "." }

[feature]
[environments
[pypi-options]
```

**Comment by baszalmstra** [comment]
#2731 needs to go in before this is done.

**Comment by baszalmstra** [comment]
What should we do with `target`?

```toml
[target.osx-64.host-dependencies]
package1 = { version = ">=1.2.3", build = "py34_0" }
```

Since `host-dependencies` is now:

```toml
[package.host-dependencies]
```

Should we do ?

```toml
[package.target.osx-64-host-dependencies]
```
