### ISSUE TITLE
Pixi pep508 file scheme does not support relative paths

### ISSUE THREAD

**Issue by rmorshea** [prefix-dev/pixi#2802]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Create a Python project with a dependency like

```toml
[project]
dependencies = ["my-package@file://./path/to/my-package-0.0.1-py3-none-any.whl"]
```

Running `pixi i` yields 

```
  × Unsupported pep508 requirement: 'my-package@file://./path/to/my-package-0.0.1-py3-none-any.whl'
  ╰─▶ could not convert './path/to/my-package-0.0.1-py3-none-any.whl' to a file path
```

If I convert this to an absolute, rather than relative path installation succeeds.

```toml
[project]
dependencies = ["my-package@file:///absolute/path/to/my-package-0.0.1-py3-none-any.whl"]
```

This likely is resulting from an error in [`url.to_file_path`](https://github.com/prefix-dev/pixi/blob/1f9daf50d99f0340f7dd739569897497b36f39a7/crates/pixi_manifest/src/pypi/pypi_requirement.rs#L508).

### Issue description

Pixi's method for converting pep508 file paths to requirements does not support relative paths.

### Expected behavior

Pixi should be able to install packages via relative paths. This is currently an issue with [`pip`](https://github.com/pypa/pip/issues/6658#issuecomment-562973835) but other tools have workarounds for the limitations in the pep508 spec. For example, Hatch has [contextual formatting](https://hatch.pypa.io/latest/config/dependency/#local).
