### ISSUE TITLE
Cache glob doesn't work with relative paths pointing out of the project

### ISSUE THREAD

**Issue by phcerdan** [prefix-dev/pixi#2804]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[tasks]
cmd = "mkdir -p ../folder_a && echo Hello >> ../folder_a/a.txt"
outputs = ["../folder_a/a.txt"]
```
```
pixi --version
0.39.4
```

### Issue description

Following the same example given in #1237
Not sure if expected, but  the glob doesn't work if the folder is out of the project:

```toml
[tasks]
cmd = "mkdir -p ../folder_a && echo Hello >> ../folder_a/a.txt"
outputs = ["../folder_a/a.txt"]
```

```sh
✨ Pixi task (start in cxx): mkdir -p ../folder_a && echo Hello >> ../folder_a/a.txt
 WARN No files matched the output globs for task` 'start'
 WARN Output globs: ["../folder_a/a.txt"]
```

But the folder is indeed there:
```sh
ls ../folder_a
a.txt
```

These out of source folders are specially useful for CMake projects, where the build folder is strongly recommended to not be nested with the source (project) folder.

Something odd with the glob:

These two give different results:

This works ✅ 

```toml
[tasks]
cmd = "mkdir -p folder_a && echo Hello >> folder_a/a.txt"
outputs = ["folder_a/a.txt"]
```

This doesn't ❌ 
```toml
[tasks]
cmd = "mkdir -p folder_a && echo Hello >> folder_a/a.txt"
outputs = ["./folder_a/a.txt"]
```

Changing `cwd` to the parent folder works again ✅ , so it seems a glob issue
```toml
cmd = "mkdir -p folder_a && echo Hello >> folder_a/a.txt"
cwd = ".."
outputs = ["folder_a/a.txt"]
```

### Expected behavior

I expect that the glob works with relative paths:

```toml
[tasks]
cmd = "mkdir -p ../folder_a && echo Hello >> ../folder_a/a.txt"
outputs = ["../folder_a/a.txt"]
```
