### ISSUE TITLE
Install gromacs with cuda

### ISSUE THREAD

**Issue by vsoch** [prefix-dev/pixi#2838]
I'm trying to install gromacs with cuda, specifically:

```
{
  "arch": "x86_64",
  "build": "nompi_cuda_h5cb645a_0",
  "build_number": 0,
  "depends": [
    "__cuda",
    "__glibc >=2.17,<3.0.a0",
    "_openmp_mutex >=4.5",
    "cudatoolkit >=11.8,<12",
    "fftw >=3.3.10,<4.0a0",
    "libgcc",
    "libgcc-ng >=12",
    "libhwloc 2.*",
    "libhwloc >=2.11.2,<2.11.3.0a0",
    "libstdcxx",
    "libstdcxx-ng >=12",
    "sysroot_linux-64 >=2.17"
  ],
  "license": "LGPL-2.1-or-later",
  "license_family": "LGPL",
  "name": "gromacs",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1730744822394,
  "version": "2024.4"
}
```
I tried adding the system-dependencies with cuda, and got an error about the virtual environment. I then found the build I want, the `gromacs-2024.4-mpi_openmpi_cuda_he6b8466_0.conda` here https://prefix.dev/channels/conda-forge/packages/gromacs but there doesn't seem to be a way to install it explicitly. I tried downloading the .conda package and extracting, but none of the paths are populated.

```
bash: /home/conda/feedstock_root/build_artifacts/gromacs_1730738703188/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin.SSE2/GMXRC: No such file or directory
```
Let me know what to try. It should work to specify cuda, for the system or package, in a cuda base container from nvidia. Thanks!

**Comment by vsoch** [comment]
I'm trying this in the pixi.toml:

```
gromacs =  { version = "==2024.4", build = "nompi_cuda_h5cb645a_0.conda" }
```
but it's just hanging on the install.

**Comment by ruben-arts** [comment]
I'm not sure what it would be hanging on, but that is indeed the solution. This `pixi.toml` works for me:
```toml
[project]
channels = ["https://prefix.dev/conda-forge"]
name = "gromacs"
platforms = ["linux-64"]

[system-requirements]
cuda = "12.0" # Required for the `__cuda` dependency

[dependencies]
gromacs =  { version = "==2024.4", build = "nompi_cuda_h5cb645a_0" }
```
