### ISSUE TITLE
Add the ability to set environment variables globally and per task

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#288]
### Problem description

It would be nice to be able to configure additional environment variables (such as `CARGO_HOME`).
I am thinking there should be a global environment section, and a per-task one.

E.g.

```
[env]
MYVAR = "TEST"
CARGO_HOME = "$PIXI_FOLDER/.cargo_cache"
...
```

Note that we should have env var expansion, at least for a limited set of variables.

**Comment by ruben-arts** [comment]
As we already have `[activation]` maybe we could add this as:

```toml
[activation.variables]
MYVAR = "test"
CARGO_HOME = "$PIXI_PACKAGE_ROOT/.cargo_cache"
```

This is something we most probably also want to have target specific. 

```toml
[target.osx-64.activation.variables]
METAL=on
```
