### ISSUE TITLE
`exec` doesn't run .bat files correctly on windows

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/pixi#2911]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

This package will not be executed correctly on windows.
```
- package:
      name: dummy-f
      version: 0.1.0

    build:
      script:
        - mkdir -p $PREFIX/bin
        - if: win
          then:
            - echo "@echo off" > $PREFIX/bin/dummy-f.bat
            - echo "echo dummy-f on windows" >> $PREFIX/bin/dummy-f.bat
          else:
            - echo "#!/usr/bin/env bash" > $PREFIX/bin/dummy-f
            - echo "echo dummy-f on unix" >> $PREFIX/bin/dummy-f
            - chmod +x $PREFIX/bin/dummy-f
```

### Issue description

as discovered in this PR: https://github.com/prefix-dev/pixi/pull/2908 by this test:
https://github.com/prefix-dev/pixi/pull/2908/files#diff-65678e4892996b2357f8907876fedab4ef74cf8ac1bd7c1cfbe36a69f7c8a995R13

when running `pixi exec` for a .bat file, it will complain that it cannot be executed.

This problem is not present for `pixi add` and `pixi run` or `pixi shell` so it is possible that `exec` command behave differently somehow.

### Expected behavior

`pixi exec` should execute .bat file
