### ISSUE TITLE
Use PyPI dependencies in building of non-isolated sdist

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#2921]
### Problem description

We've had a discord discussion where someone had a `pixi.toml` like:

```toml
[dependencies]
hatchling = "*"
cython = ">3.0"

[pypi-dependencies]
hatch-cython = ">=0.6.0rc0"
my-package = { path = ".", editable = true }

[pypi-options]
no-build-isolation = {"my-package"}
```

their editable package requires `hatch-cython` but this is unavailable in conda for now. So they initially tried to use `pypi-dependencies` figuring it might be available in the prefix before the build of `my-package` is invoked. Mind you this only requires a build on *install* time, at *resolve* static metadata could be used (in this case reading the `pyproject.toml`).

So, our thinking was here, it might be possible to pass to uv what to install first **sorted** esentially, and as we are re-using the prefix for building this might just work. Would need a little investigation if this is possible.
