### ISSUE TITLE
pixi build: redundancy between `dependencies` and `run-dependencies`

### ISSUE THREAD

**Issue by hadim** [prefix-dev/pixi#2944]
At https://github.com/hadim/feedrattler/pull/1, I have a few places where my package deps are redundant in `pyproject.toml`

- `project.dependencies`: pypi deps
- `tool.pixi.dependencies`: the "default" pixi feature
- `tool.pixi.package.run-dependencies`: conda deps used during package building

What do you think about an option to tell `tool.pixi.package.run-dependencies` to re-use the deps of a feature? And why not doing the same for `host-dependencies`?

```toml
[tool.pixi.package]
run-dependencies-from-feature = "default"
host-dependencies-from-feature = "dev"
```
