### ISSUE TITLE
Define and document `[package]` property inheritance from `[workspace]`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#2945]
In this simple example, both workspace and package are defined in two separate same manifest.

```toml
# /first/pixi.toml
[workspace] 
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies] 
rich_example = { path = "package/pixi.toml" }
```

```toml
# /first/package/pixi.toml
[package] 
name = "rich_example"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "*" }
```

The package is added to the workspace as path dependency, and `package.channels` is inherited from `workspace.channels`. 
Unlike with Cargo, inheritance isn't opt-in with something like `channels = { workspace = true }`.

Things get a bit more complicated when depending on a package that is already part of a workspace.
Cargo solves that by depending on the top-level manifest, rather than the manifest of the package.
In our case, this would look like this:

```toml
# /second/pixi.toml
[workspace] 
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[dependencies] 
rich_example = { path = "/first/pixi.toml" }
```

## Open questions

- Should we allow `[workspace]` in package manifests that are already part of a workspace? I could imagine that could cause a bit of confusion.
- Source dependencies can also be added to feature dependencies. Should we allow the following?

```toml
# /first/pixi.toml
[feature.build.dependencies] 
rich_example = { path = "package/pixi.toml" }
```

```toml
# /second/pixi.toml
[dependencies] 
rich_example = { path = "/first/pixi.toml",  feature="build" }
```

**Comment by baszalmstra** [comment]
> Source dependencies can also be added to feature dependencies. Should we allow the following

Features are not a thing for packages at the moment. So the above example would not work.

> Should we allow [workspace] in package manifests that are already part of a workspace? I could imagine that could cause a bit of confusion.

In cargo you can define a `workspace` in a package as well. This excludes it from the "top-level" workspace. 

We could also consider using `members` in the workspace definition to be more explicit which packages are part of the workspace and which are not. This is more similar to uv and cargo.

**Comment by Hofer-Julian** [comment]
Discussion conclusion:

- We try to follow Cargo as close as possible, but also checked out how uv differs from Cargo
- Cargo is explicit about `members` and we plan to do the same
- Cargo adds `workspace.dependencies`, we don't plan to do that at the moment, because we expect a lot of use cases to be covered by variants
- Unlike Cargo, we also want to be able to inherit workspace members
- Like Cargo
  - if you have a path dependency, you specify the path to the package
  - if you have a git or url dependency, you specify the path to the workspace. The package path will be inferred.

```toml
# pixi.toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]
members = ["packages/*"] 

[dependencies]
rich_example = { member = true } 
python_bindings = { git = "https://github.com/prefix-dev/pixi" }
```
