### ISSUE TITLE
Unable to solve dependencies for package

### ISSUE THREAD

**Issue by vidosits** [prefix-dev/pixi#2959]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
  authors = []
  channels = []
  description = ""
  name = "rasa"
  platforms = ["linux-64"]
  version = "1.0.0"

[environments]
  rasa = ["rasa"]

[feature.rasa.dependencies]
  numpy = {version = "*", channel = "conda-forge"}
  pandas = {version = "*", channel = "conda-forge"}
  tqdm = {version = "*", channel = "conda-forge"}
  huggingface_hub = {version = "*", channel = "conda-forge"}
  safetensors = {version = "*", channel = "conda-forge"}
  nltk = {version = "*", channel = "conda-forge"}
  fuzzywuzzy = {version = "*", channel = "conda-forge"}
  sqlalchemy = {version = "*", channel = "conda-forge"}
  transformers = {version = "*", channel = "conda-forge"}
  scipy = {version = "*", channel = "conda-forge"}
  python = {version = "3.10.1", channel = "conda-forge"}

[feature.rasa.pypi-dependencies]
  rasa = {version = ">=3.6.0"}

[feature.rasa]
channels = ["conda-forge"]

```

Installing with `pixi install -a`

```shell
Error:
  × failed to solve the pypi requirements of 'rasa' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because all of:
          rasa==3.6.0
          rasa>=3.6.1,<=3.6.6
      depend on scipy>=1.4.1,<1.9.0 and scipy==1.15.1, we can conclude that all of:
          rasa==3.6.0
          rasa>=3.6.1,<=3.6.6
       cannot be used.
      And because only the following versions of rasa are available:
          rasa<=3.6.0
          rasa>=3.6.1,<=3.6.21
      we can conclude that all of:
          rasa>=3.6.0,<3.6.7
          rasa>3.6.21
       cannot be used. (1)

      Because rasa>=3.6.7,<=3.6.21 depends on regex>=2020.6,<2022.11 and regex==2024.11.6, we can conclude that
      rasa>=3.6.7,<=3.6.21 cannot be used.
      And because we know from (1) that all of:
          rasa>=3.6.0,<3.6.7
          rasa>3.6.21
       cannot be used, we can conclude that rasa>=3.6.0 cannot be used.
      And because you require rasa>=3.6.0, we can conclude that your requirements are unsatisfiable.

      hint: Pre-releases are available for `rasa` in the requested range (e.g., 3.7.0b2), but pre-releases weren't enabled
      (try: `--prerelease=allow`)
```

but in rasa-s `pyproject.toml` the `scipy` version constraint is:

https://github.com/RasaHQ/rasa/blob/3.6.x/pyproject.toml#L192-L198
```toml
[[tool.poetry.dependencies.scipy]]
version = ">=1.4.1,<1.7.3"
python = "~=3.7.0"

[[tool.poetry.dependencies.scipy]]
version = ">=1.10.0,<1.11.0"
python = ">=3.8,<3.11"
```

### Issue description

Pixi is unable to solve the requirements

### Expected behavior

Pixi should be able to install the project. Since `python` is pinned to `3.10.1`, `scipy >=1.10.0,<1.11.0`  should be used

**Comment by vidosits** [comment]
Actually, on second read it seems like `regex>=2020.6,<2022.11 and regex==2024.11.6` is also a problem, but I'm not sure where `regex==2024.11.6` comes from? 

Rasa has this in their `pyproject.toml`:

https://github.com/RasaHQ/rasa/blob/3.6.x/pyproject.toml#L137

`regex = ">=2020.6,<2022.11"`

**Comment by vidosits** [comment]
I've confirmed that the `rasa-3.6.21-py3-none-any.whl` has the following dependencies in it:

```
['CacheControl (>=0.12.9,<0.13.0)',
 'PyJWT[crypto] (>=2.0.0,<3.0.0)',
 'SQLAlchemy (>=1.4.0,<1.5.0)',
 'absl-py (>=0.9,<1.5)',
 'aio-pika (>=6.7.1,<8.2.4)',
 'aiogram (<2.26)',
 'aiohttp (>=3.9.0,<3.10)',
 'apscheduler (>=3.6,<3.10)',
 'attrs (>=19.3,<22.2)',
 'boto3 (>=1.26.136,<2.0.0)',
 'certifi (>=2023.7.22)',
 'colorama (>=0.4.4,<0.5.0) ; sys_platform == "win32"',
 'colorclass (>=2.2,<2.3)',
 'coloredlogs (>=10,<16)',
 'colorhash (>=1.0.2,<1.3.0)',
 'confluent-kafka (>=1.9.2,<3.0.0)',
 'cryptography (>=41.0.7)',
 'dask (==2022.10.2) ; python_version >= "3.8" and python_version < "3.11"',
 'dask (==2022.2.0) ; python_full_version >= "3.7.0" and python_full_version < '
 '"3.8.0"',
 'dnspython (==2.3.0)',
 'fbmessenger (>=6.0.0,<6.1.0)',
 'github3.py (>=3.2.0,<3.3.0) ; extra == "gh-release-notes"',
 'google-auth (<3)',
 'jieba (>=0.39,<0.43) ; extra == "jieba" or extra == "full"',
 'jsonpickle (>=1.3,<3.1)',
 'jsonschema (>=3.2,<4.18)',
 'matplotlib (>=3.1,<3.6)',
 'mattermostwrapper (>=2.2,<2.3)',
 'networkx (>=2.4,<2.7)',
 'numpy (==1.22.3) ; sys_platform == "Windows" and '
 'platform_python_implementation != "PyPy" and python_version == "3.10"',
 'numpy (>=1.19.2,<1.22.0) ; python_full_version >= "3.7.0" and '
 'python_full_version < "3.8.0"',
 'numpy (>=1.19.2,<1.25.0) ; python_version >= "3.8" and python_version < '
 '"3.11"',
 'packaging (>=20.0,<21.0)',
 'pluggy (>=1.0.0,<2.0.0)',
 'portalocker (>=2.7.0,<3.0.0)',
 'prompt-toolkit (>=3.0,<3.0.29)',
 'protobuf (>=4.23.3,<4.23.4)',
 'psycopg2-binary (>=2.8.2,<2.10.0)',
 'pydantic (<1.10.10)',
 'pydot (>=1.4,<1.5)',
 'pykwalify (>=1.7,<1.9)',
 'pymongo[srv,tls] (>=3.8,<4.4)',
 'python-dateutil (>=2.8,<2.9)',
 'python-engineio (>=4,<6,!=5.0.0)',
 'python-socketio (>=4.4,<6)',
 'pytz (>=2019.1,<2023.0)',
 'pyyaml (>=6.0)',
 'questionary (>=1.5.1,<1.11.0)',
 'randomname (>=0.1.5,<0.2.0)',
 'rasa-sdk (>=3.6.2,<3.7.0)',
 'redis (>=4.5.3,<5.0)',
 'regex (>=2020.6,<2022.11)',
 'requests (>=2.23,<3.0)',
 'rocketchat_API (>=0.6.31,<1.31.0)',
 'ruamel.yaml (>=0.16.5,<0.17.22)',
 'safetensors (>=0.4.5,<0.5.0)',
 'sanic (>=21.12,<21.13)',
 'sanic-cors (>=2.0.0,<2.1.0)',
 'sanic-jwt (>=1.6.0,<2.0.0)',
 'sanic-routing (>=0.7.2,<0.8.0)',
 'scikit-learn (>=0.22,<1.1) ; python_full_version >= "3.7.0" and '
 'python_full_version < "3.8.0"',
 'scikit-learn (>=0.22,<1.2) ; python_version >= "3.8" and python_version < '
 '"3.11"',
 'scipy (>=1.10.0,<1.11.0) ; python_version >= "3.8" and python_version < '
 '"3.11"',
 'scipy (>=1.4.1,<1.7.3) ; python_full_version >= "3.7.0" and '
 'python_full_version < "3.8.0"',
 'sentencepiece[sentencepiece] (>=0.1.99,<0.2.0) ; extra == "transformers" or '
 'extra == "full"',
 'sentry-sdk (>=0.17.0,<1.15.0)',
 'setuptools (>=70.3.0,<70.4.0)',
 'sklearn-crfsuite (>=0.3,<0.4)',
 'skops (==0.9.0)',
 'slack-sdk (>=3.19.2,<4.0.0)',
 'spacy (>=3.1,<3.5) ; (sys_platform != "darwin" or platform_machine != '
 '"arm64") and (extra == "spacy" or extra == "full")',
 'spacy (>=3.4,<4.0) ; (sys_platform == "darwin" and platform_machine == '
 '"arm64") and (extra == "spacy" or extra == "full")',
 'structlog (>=23.1.0,<24.0.0)',
 'structlog-sentry (>=2.0.2,<3.0.0)',
 'tarsafe (>=0.0.3,<0.0.5)',
 'tensorflow (==2.12.0) ; sys_platform != "darwin" or platform_machine != '
 '"arm64"',
 'tensorflow-cpu-aws (==2.12.0) ; sys_platform == "linux" and '
 '(platform_machine == "arm64" or platform_machine == "aarch64")',
 'tensorflow-intel (==2.12.0) ; sys_platform == "win32"',
 'tensorflow-io-gcs-filesystem (==0.31) ; sys_platform == "win32"',
 'tensorflow-io-gcs-filesystem (==0.32) ; sys_platform == "darwin" and '
 'platform_machine != "arm64"',
 'tensorflow-io-gcs-filesystem (==0.32) ; sys_platform == "linux"',
 'tensorflow-macos (==2.12.0) ; sys_platform == "darwin" and platform_machine '
 '== "arm64"',
 'tensorflow-metal (==0.8.0) ; (sys_platform == "darwin" and platform_machine '
 '== "arm64") and (extra == "metal")',
 'tensorflow-text (==2.12.0) ; sys_platform != "win32" and (platform_machine '
 '!= "arm64" and platform_machine != "aarch64")',
 'tensorflow_hub (>=0.13.0,<0.14.0)',
 'terminaltables (>=3.1.0,<3.2.0)',
 'tqdm (>=4.31,<5.0)',
 'transformers (>=4.36.2,<4.37.0) ; extra == "transformers" or extra == "full"',
 'twilio (>=6.26,<8.3)',
 'typing-extensions (>=4.1.1,<5.0.0)',
 'typing-utils (>=0.1.0,<0.2.0)',
 'ujson (>=1.35,<6.0)',
 'webexteamssdk (>=1.1.1,<1.7.0)',
 'websockets (>=10.0,<11.0)',
 'wheel (>=0.38.1)']
```

The two things I see happening in the rasa output:
- the `scipy` version is resolved to be `scipy==1.15.1`, but this cannot come from this wheel file
- the `regex` package version is resolved to be `regex==2024.11.6`, but this does not come from the wheel file's dependencies

**Comment by vidosits** [comment]
Thanks! If I comment the pypi deps, like the following:

```toml
[project]
  authors = []
  channels = []
  description = ""
  name = "rasa"
  platforms = ["linux-64"]
  version = "1.0.0"

[environments]
  rasa = ["rasa"]

[feature.rasa.dependencies]
  numpy = {version = "*", channel = "conda-forge"}
  pandas = {version = "*", channel = "conda-forge"}
  tqdm = {version = "*", channel = "conda-forge"}
  huggingface_hub = {version = "*", channel = "conda-forge"}
  safetensors = {version = "*", channel = "conda-forge"}
  nltk = {version = "*", channel = "conda-forge"}
  fuzzywuzzy = {version = "*", channel = "conda-forge"}
  sqlalchemy = {version = "*", channel = "conda-forge"}
  transformers = {version = "*", channel = "conda-forge"}
  scipy = {version = "*", channel = "conda-forge"}
  python = {version = "3.10.1", channel = "conda-forge"}

[feature.rasa.pypi-dependencies]
#  rasa = {version = ">=3.6.0"}

[feature.rasa]
channels = ["conda-forge"]

```

and do `pixi list`, I get: `✘ No packages found.`

Just so that I understand correctly, the problem is that in the `feature.rasa.dependencies` (which enumerate the deps which should be installed from the conda part of the ecosystem) somehow pin the `scipy` and the `regex` packages in isolation?

So these get installed first, they resolve to be `scipy==1.15.1` and  `regex==2024.11.6` and _then_ pixi tries to install the pypi deps, which cannot be satisfied with the above?


Btw, this works for me, so it's a solution for now:

```toml
[project]
  authors = []
  channels = []
  description = ""
  name = "rasa"
  platforms = ["linux-64"]
  version = "1.0.0"

[environments]
  rasa = ["rasa"]

[feature.rasa.dependencies]
  python = {version = "3.10.1", channel = "conda-forge"}

[feature.rasa.pypi-dependencies]
  rasa = {version = ">=3.6.0"}

[feature.rasa]
channels = ["conda-forge"]
```

Thanks for your work on Pixi, it's my go-to package manager
