### ISSUE TITLE
Exact package version gives a warning

### ISSUE THREAD

**Issue by rmekdma** [prefix-dev/pixi#2964]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[dependencies]
python = "~=3.10.0"
pyarrow = "*"
pyspark = "3.1.2"
```

```bash
pixi install
```

### Issue description

This configuration gives warning
>  WARN Encountered ambiguous version specifier `3.1.2`, could be `3.1.2.*` but assuming you meant `==3.1.2`. In the future this will result in an error.

### Expected behavior

No warning
