### ISSUE TITLE
Automatic inclusion of project dependencies from pyproject.toml

### ISSUE THREAD

**Issue by akhmerov** [prefix-dev/pixi#2971]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

1. create project

    ```shell
    mkdir my_project && cd my_project && pixi init --format pyproject
    ```
2. Copy the following into `pyproject.toml`

    ```toml
    [project]
    dependencies = ["requests"]
    name = "my_project"
    requires-python = ">= 3.11"
    version = "0.1.0"
    
    [build-system]
    build-backend = "hatchling.build"
    requires = ["hatchling"]
    
    [tool.pixi.project]
    channels = ["https://prefix.dev/conda-forge"]
    platforms = ["linux-64"]
    ```
3. Run `pixi install && grep "pythonhosted" pixi.lock` to confirm that pypi dependencies are added.

### Issue description

If current project is not specified as a pixi depenency, *and* pixi uses `pyproject.toml`, the project required python version and its dependencies are nevertheless installed in the default environment.

Why this matters: I have a package whose dependencies aren't available on `osx-arm64` yet, but are available on `osx-64`. Other dependencies (some pre-commit hooks) aren't available on osx-64. I first intended to specify both platforms in the project so that I could include corresponding packages separately for the platforms for which they work. This, however, is impossible because the dependencies of the main package of `pyproject.toml` are included in the default feature automatically.

### Expected behavior

One of the two:

- https://pixi.sh/latest/advanced/pyproject_toml/ states that the package requirements, but not the package itself are included in the default feature unconditionally (right now this is not clarified)
- Package requirements are not included in the default feature unless the package itself is included.
