### ISSUE TITLE
Failed to subscribe ROS 2 topic between pixi and Docker container with Cyclone DDS

### ISSUE THREAD

**Issue by atinfinity** [prefix-dev/pixi#2979]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

# Environment

- macOS Sonoma 14.4
- pixi 0.40.2
- Docker Desktop 4.37.2

# Steps to reproduce

## Install pixi

```bash
curl -fsSL https://pixi.sh/install.sh | bash
```

## Create project

```bash
pixi init my_ros2_project -c robostack-staging -c conda-forge
cd my_ros2_project
```

## Install package

```bash
pixi add ros-humble-desktop
```

My `pixi.toml` is as follows.

```toml
[project]
authors = ["atinfinity <dandelion1124@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "my_ros2_project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"

[activation]
scripts = ["activate.sh"]
```

My `activate.sh` is as follows.

```bash
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
```

## Launch Docker container

I enabled host networking in Docker Desktop via setting.
And, I launched Docker container.

```bash
docker run --rm -it \
           --net=host \
           --ipc=host \
           ros:humble-perception \
           bash
```

I changed Cyclone DDS on Docker container.

```bash
apt update
apt install ros-humble-rmw-cyclonedds-cpp
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
```

### Issue description

I could not subscribe ROS 2 topic between pixi and Docker container(with Cyclone DDS) on same PC.
I published topic.

```bash
pixi run ros2 topic pub --rate 1 /turtle1/cmd_vel geometry_msgs/msg/Twist "{linear: {x: 2.0, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.8}}"
```

And I tried to subscribe topic. But, I could not subscribe topic between pixi and Docker container.

```bash
ros2 topic echo /turtle1/cmd_vel
```

## Supplementary information

I changed to Fast DDS. As a result, I could subscribe topic.

```bash
ros2 topic echo /turtle1/cmd_vel
linear:
  x: 2.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 1.8
```

### Expected behavior

I expected the following result between pixi and Docker container.

```bash
ros2 topic list
/parameter_events
/rosout
/turtle1/cmd_vel
```

```bash
ros2 topic echo /turtle1/cmd_vel
linear:
  x: 2.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 1.8
```
