### ISSUE TITLE
Incomplete Wheel Installation in `pixi>0.39.0`

### ISSUE THREAD

**Issue by dvnatanael** [prefix-dev/pixi#2984]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

0. Create a new project.
1. Copy the following pyproject configuration.

    ```toml
    [project]
    authors = [{name = "dvnatanael", email = "85625605+dvnatanael@users.noreply.github.com"}]
    dependencies = []
    description = "Add a short description here"
    name = "bug-report"
    requires-python = ">=3.10,<3.11"
    version = "0.1.0"
    
    [build-system]
    build-backend = "hatchling.build"
    requires = ["hatchling"]
    
    [tool.pixi.project]
    channels = ["conda-forge"]
    platforms = ["linux-64"]
    
    [tool.pixi.pypi-dependencies]
    bug_report = { path = ".", editable = true }
    mmcv-full = { url = "https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/mmcv_full-1.7.2-cp310-cp310-manylinux1_x86_64.whl" }
    ```
2. Attempt to run the following command:

    ```shell
    pixi run python -c 'import mmcv._ext'
    ```

### Issue description

Since version 0.39.1, Pixi fails to unpack the shared object `_ext.cpython-310-x86_64-linux-gnu.so` from the wheel into the package directory, and the given command raises an `ImportError`.

### Expected behavior

Pixi should extract the shared object into the `mmcv` package directory (i.e. `.pixi/envs/default/lib/python3.10/site-packages/mmcv/`).
