### ISSUE TITLE
Configuration priority seems not to be handled properly

### ISSUE THREAD

**Issue by function2-llx** [prefix-dev/pixi#2999]
### Checks

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pixi --version` output: `pixi 0.40.3`

1. Create an empty pixi project.
2. Edit the project pixi configuration at `<project root>/.pixi/config.toml	` with something like:
```toml
[mirrors]
"https://conda.anaconda.org/conda-forge" = [
    "whatever://from/project/config"
]
```
3. Edit the configuration at user home directory `$HOME/.pixi/config.toml` with something like:
```toml
change-ps1 = false

[mirrors]
"https://conda.anaconda.org/conda-forge" = [
    "whatever://global/config/at/user-home-dir"
]
```
4. Inspect the active config with `pixi config list`.

### Issue description

The results of `pixi config list` are:

```toml
change-ps1 = false

[mirrors]
"https://conda.anaconda.org/conda-forge" = ["whatever://global/config/at/user-home-dir"]
```

### Expected behavior

The `[mirrors]` section in results are expected to be what specified in the project configuration due to higher priority as specified in [doc](https://pixi.sh/v0.40.3/reference/pixi_configuration/#the-configuration-of-pixi-itself), as follows:

```toml
change-ps1 = false

[mirrors]
"https://conda.anaconda.org/conda-forge" = ["whatever://from/project/config"]
```

If commenting out the `[mirrors]` section in the configuration at user home directory, i.e., setting it to:
```toml
change-ps1 = false

# [mirrors]
# "https://conda.anaconda.org/conda-forge" = [
#     "whatever://global/config/at/user-home-dir"
# ]
```
The results of `pixi config list` will then work as expected. So I guess it may be an issue of overriding handling.
