### ISSUE TITLE
Help detecting dependencies in `pyproject.toml` that are only specified as conda-dependencies

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3001]
### Problem description

# Problem description

Let's assume the following script:
```python
# __init__.py
import numpy as np
x = np.array([1,2,3])
```
and the following `pyproject.toml`

```toml
[project]
dependencies = []
name = "pypi-test"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pypi_test = { path = ".", editable = true }

[tool.pixi.dependencies]
numpy = ">=2.2.2,<3"
```

This works fine, when used with pixi, but when you publish it on PyPI, people will not be able to use it since numpy isn't added as dependency.

# Suggested solutions

We already know which conda packages correspond to PyPI packages.
Therefore, we also know the list of packages that are missing in `project.dependencies`

We could:
- warn, but only if `pyproject.toml` is both the package and the manifest
- create `pixi lint` and add that as a lint rule
- let that handle by an external lint tool
