### ISSUE TITLE
fail to resolve polars with gpu support - pip package from non pypi index

### ISSUE THREAD

**Issue by geoHeil** [prefix-dev/pixi#3003]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

given a pyproject toml

```toml
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "x", email = "y@x.com" }]
requires-python = "~=3.12"

[tool.pixi.project]
platforms = ["linux-64"]
channels = ["conda-forge"]

[tool.pixi.environments]
foo = { features = ["foo"], solve-group = "foo" }

[tool.pixi.feature.foo.dependencies]
[tool.pixi.feature.foo.pypi-dependencies]
polars = {version=">=1.19.0", extras = ["gpu"], index = "https://pypi.nvidia.com" }

```

why does this fail as https://rapids.ai/polars-gpu-engine/ clearly shows that:

```sh
pip install polars[gpu] --extra-index-url=https://pypi.nvidia.com
```

https://pypi.nvidia.com and https://pypi.org/project/polars/1.20.0/ even list 1.20 as available for now

should work.

When using:

```
polars = {version="<1.19.0", extras = ["gpu"], index = "https://pypi.nvidia.com" }
```

the error is

```
 polars[gpu] <1.19.0 is forbidden    
 INFO solve: pubgrub::internal::core: prior cause: root ==0a0.dev0 is forbidden    
Error: 
  × failed to solve the pypi requirements of 'foo' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because only polars[gpu]>=1.19.0 is available and you require polars[gpu]<1.19.0, we can conclude that your requirements are unsatisfiable.

```

A manual approach of:

```
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "x", email = "y@x.com" }]
requires-python = "~=3.12"

[tool.pixi.project]
platforms = ["linux-64"]
channels = ["conda-forge"]

[tool.pixi.environments]
foo = { features = ["foo"], solve-group = "foo" }

[tool.pixi.feature.foo.dependencies]
pip = "*"
[tool.pixi.feature.foo.pypi-dependencies]
#polars = {version="<1.19.0", extras = ["gpu"], index = "https://pypi.nvidia.com" }
```

```
pixi shell -e foo
pip install "polars[gpu]" --extra-index-url=https://pypi.nvidia.com
```

is installing fine

## observations

- resolution is failing
- `prior cause: root ==0a0.dev0 is forbidden    ` is a really strange error message
- pixi cannot resolve; manual install is fine

### Issue description

pixi version is 0.40.3

### Expected behavior

working resolve for this package

**Comment by RaphaelMelanconAtBentley** [comment]
Well, it looks like it has to do with the version of polars you are requesting.

Your manual installation does not restrict the polars version.
Have you checked what version it installs?

**Comment by geoHeil** [comment]
good point it looks like that is taking the wrong version - and certainly an old one.

**Comment by ruben-arts** [comment]
I didn't get it to work on my machine. But note that there is also an option to use conda packages:
https://prefix.dev/channels/rapidsai

If you want to use `extra-index-urls` with pixi the configuration looks like this:
```toml
[tool.pixi.pypi-options]
extra-index-urls = ["https://pypi.nvidia.com"]
index-strategy = "unsafe-best-match" # Without this `uv` will warn about not using everything from the main index.

[tool.pixi.feature.foo.pypi-dependencies]
cudf-polars-cu12 = {version="*", index = "https://pypi.nvidia.com"}
polars = {version="*", extras = ["gpu"]}
```

**Comment by tdejager** [comment]
AFAICS polars does not exist on that index?

https://pypi.nvidia.com/polars does not seem to work.

**Comment by ruben-arts** [comment]
@tdejager correct, that's why it's an extra-index-url.

**Comment by geoHeil** [comment]
But why does:

```toml
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "x", email = "y@x.com" }]
requires-python = "~=3.12"

[tool.pixi.project]
platforms = ["linux-64"]
channels = ["conda-forge"]

[tool.pixi.pypi-options]
extra-index-urls = ["https://pypi.nvidia.com"]
index-strategy = "unsafe-best-match" # Without this `uv` will warn about not using everything from the main index.

[tool.pixi.environments]
foo = { features = ["foo"], solve-group = "foo" }

[tool.pixi.feature.foo.dependencies]
[tool.pixi.feature.foo.pypi-dependencies]
cudf-polars-cu12 = {version="*", index = "https://pypi.nvidia.com"}
polars = {version=">=1.20.0", extras = ["gpu"]}
```

fail with 

```
pixi update
Error: 
  × failed to solve the pypi requirements of 'foo' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because cudf-polars-cu12==24.10.1 depends on polars>=1.8,<1.9 and only the following versions of cudf-polars-cu12 are available:
          cudf-polars-cu12==24.10.1
          cudf-polars-cu12==24.12.0
      we can conclude that cudf-polars-cu12<24.12.0 depends on polars>=1.8,<1.9.
      And because cudf-polars-cu12==24.12.0 depends on polars>=1.11,<1.15 and only polars[gpu]<=1.20.0 is available, we can conclude that all versions of cudf-polars-cu12 and polars[gpu]>=1.20.0 are incompatible.
      And because you require cudf-polars-cu12 and polars[gpu]>=1.20.0, we can conclude that your requirements are unsatisfiable.

```

Given `polars = {version=">=1.19.0", extras = ["gpu"]}` fail with:

```
pixi update
Error: 
  × failed to solve the pypi requirements of 'foo' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because only the following versions of polars[gpu] are available:
          polars[gpu]<=1.19.0
          polars[gpu]==1.20.0
      and cudf-polars-cu12==24.10.1 depends on polars>=1.8,<1.9, we can conclude that cudf-polars-cu12==24.10.1 and polars[gpu]>=1.19.0 are incompatible.
      And because only the following versions of cudf-polars-cu12 are available:
          cudf-polars-cu12==24.10.1
          cudf-polars-cu12==24.12.0
      we can conclude that all of:
          cudf-polars-cu12<24.12.0
          cudf-polars-cu12>24.12.0
       and polars[gpu]>=1.19.0 are incompatible. (1)
      
      Because only the following versions of polars[gpu] are available:
          polars[gpu]<=1.19.0
          polars[gpu]==1.20.0
      and cudf-polars-cu12==24.12.0 depends on polars>=1.11,<1.15, we can conclude that cudf-polars-cu12==24.12.0 and polars[gpu]>=1.19.0 are incompatible.
      And because we know from (1) that all of:
          cudf-polars-cu12<24.12.0
          cudf-polars-cu12>24.12.0
       and polars[gpu]>=1.19.0 are incompatible, we can conclude that all versions of cudf-polars-cu12 and polars[gpu]>=1.19.0 are incompatible.
      And because you require cudf-polars-cu12 and polars[gpu]>=1.19.0, we can conclude that your requirements are unsatisfiable.

```

and given `polars = {version="*", extras = ["gpu"]}` fail with:

```
Error: 
  × failed to solve the pypi requirements of 'foo' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because pylibcudf-cu12==24.10.1 has no wheels with a matching Python ABI tag and only the following versions of pylibcudf-cu12 are available:
          pylibcudf-cu12<24.10.dev0
          pylibcudf-cu12==24.10.1
          pylibcudf-cu12>24.11.dev0
      we can conclude that pylibcudf-cu12>=24.10.dev0,<24.11.dev0 cannot be used.
      And because cudf-polars-cu12==24.10.1 depends on pylibcudf-cu12>=24.10.dev0,<24.11.dev0 and only the following versions of cudf-polars-cu12 are available:
          cudf-polars-cu12==24.10.1
          cudf-polars-cu12==24.12.0
      we can conclude that cudf-polars-cu12<24.12.0 cannot be used. (1)
      
      Because pylibcudf-cu12==24.12.0 has no wheels with a matching Python ABI tag and only the following versions of pylibcudf-cu12 are available:
          pylibcudf-cu12<24.12.dev0
          pylibcudf-cu12==24.12.0
      we can conclude that pylibcudf-cu12>=24.12.dev0 cannot be used.
      And because cudf-polars-cu12==24.12.0 depends on pylibcudf-cu12>=24.12.dev0, we can conclude that cudf-polars-cu12==24.12.0 cannot be used.
      And because we know from (1) that cudf-polars-cu12<24.12.0 cannot be used, we can conclude that all versions of cudf-polars-cu12 cannot be used.
      And because you require cudf-polars-cu12, we can conclude that your requirements are unsatisfiable.
      
      hint: `pylibcudf-cu12` was requested with a pre-release marker (e.g., all of:
          pylibcudf-cu12>=24.10.dev0,<24.10.1
          pylibcudf-cu12>24.10.1,<24.11.dev0
      ), but pre-releases weren't enabled (try: `--prerelease=allow`)

```

so it looks like I am not alone - as @ruben-arts also cannot get it to resolve so far. Do I understand correctly this is an upstream issue that rapids/nvidia/polars has to fix?
