### ISSUE TITLE
Windows editable install does not pass pixi env prefix in PATH

### ISSUE THREAD

**Issue by nunupeke** [prefix-dev/pixi#3005]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

See discussion [here](https://discord.com/channels/1082332781146800168/1327202947137929357) which contains a minimal example. (see attached zip for a minimal example)

[env-printer.zip](https://github.com/user-attachments/files/18537513/env-printer.zip)

### Issue description

Commands executed during the Python editable install do not see the full PATH on windows. In particular, the corresponding pixi env prefix is missing. This can lead to subsequent errors, e.g. CMake fails to find required packages in the PATH.

### Expected behavior

On Windows (just like this is the case on Linux / Mac OS), the corresponding pixi env prefix is passed in the PATH environment variable when executing editable installs.

**Comment by philippjfr** [comment]
This is quite frustrating since this is blocking the ability to specify the package you're working on as an editable pypi dependency.

**Comment by ruben-arts** [comment]
Could you share the output of a `pixi shell-hook` on the Windows machine?

**Comment by nunupeke** [comment]
Any updates on this?

One workaround is to put
```toml
[tool.pixi.target.win-64.build-dependencies]
vs2022_win-64 = "*"
```
in the `pyproject.toml`.

The disadvantage is that it fixes the CMAKE_GENERATOR to "Visual Studio *" (MSBUILD). If one wants to use Ninja instead (default on Linux and macOS), additional config options are necessary:
```toml
[tool.scikit-build]
cmake.define.CMAKE_TOOLCHAIN_FILE = "cmake/Windows.MSVC.toolchain.cmake"
cmake.define.CMAKE_GENERATOR = "Ninja"
cmake.define.CMAKE_GENERATOR_PLATFORM = ""
cmake.define.CMAKE_GENERATOR_TOOLSET = ""
cmake.define.CMAKE_BUILD_TYPE = "Release"
```
where the toolchain file (e.g. from https://github.com/MarkSchofield/WindowsToolchain) enables CMake to find the correct compiler paths.

In addition, and this is the actual workaround for the current issue in the Ninja case, one needs
```toml
[tool.pixi.target.win.activation]
env = { "CMAKE_PREFIX_PATH" = "%CONDA_PREFIX%\\Library" }
```

Note that none of this is necessary on Linux / macOS. There, everything works out of the box and it would be very helpful if this was the case on Windows as well.
