### ISSUE TITLE
Unexpected conflicting indexes

### ISSUE THREAD

**Issue by mickvangelderen** [prefix-dev/pixi#3015]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "pixi-lab"
requires-python = ">= 3.11"
version = "0.1.0"

[tool.pixi.feature.cpu.pypi-dependencies]
torch = { index = "https://download.pytorch.org/whl/cpu" }

[tool.pixi.feature.cuda.pypi-dependencies]
torch = { index = "https://download.pytorch.org/whl/cu121" }

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.environments]
# default is production
default = { features = ["cuda"], solve-group="default" }
cpu = { features = ["cpu"], solve-group="default" }

[tool.pixi.pypi-dependencies]
pixi-lab = { path = ".", editable = true }
```

```shell
$ pixi --version
pixi 0.40.3

$ pixi list --explicit --environment default
Error: 
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Requirements contain conflicting indexes for package `torch`:
      - https://download.pytorch.org/whl/cpu
      - https://download.pytorch.org/whl/cu121
```

### Issue description

When defining the same package under two different features `cpu` and `cuda` as `pypi-dependencies` with different `index-url`s, I expect to be able to use one or the other in an environment. However, dependency resolution fails if I use only one of the two features (not both).

I wanted to guarantee that `torch` and only `torch` got pulled out of one or another index. I can work around this using `pypi-options.extra-index-urls` but that does not guarantee that `torch` will not be pulled from the `pypi` index as far as I'm aware. I can't use `pypi-options.index-url` in different features either.

Am I missing something?

EDIT: Yes I am, we're using the same `solve-group`. Pixi needs to resolve all dependencies within the group and since the two environments share the same `solve-group` the `torch` package is included twice with different `index-url`s.

### Expected behavior

Dependency resolution should resolve by only using the index from the active features of the environment.
