### ISSUE TITLE
Specifying a development branch of a Conda dependency as a pypi dependency fails with a cryptic error

### ISSUE THREAD

**Issue by Yoshanuikabundi** [prefix-dev/pixi#3032]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

The following `pixi.toml`

```shell
[project]
name = "pixi-test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
scipy = "*"

[pypi-dependencies]
numpy = { git = "https://github.com/numpy/numpy.git", rev = "v2.3.0.dev0" }

```

Produces output:

```
Error:
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because there is no version of numpy==2.2.2 and you require numpy==2.2.2, we can conclude that your
      requirements are unsatisfiable.
```

Note that there is no requirement for `numpy==2.2.2` specified anywhere in the project file; neither that version nor that package is an explicit requirement. (it is a dependency of SciPy)

For a second example, see https://github.com/openforcefield/openff-pablo/pull/17

### Issue description

Thanks for Pixi! I made a very amateurish tool with a similar vibe a few years ago and I'm very glad to see someone's taking the problem more seriously than I did.

Using a pypi dependency to grab a development branch through Git for a dependency we usually get through Conda fails. The error is quite confusing, as it says I require a version of a package I have never requested. This pattern works very simply in Conda `environment.yaml` files.

We often make use of this pattern to unblock progress on a downstream package while an upstream patch is merged or reviewed. It's useful because our dependencies change rarely and are generally very flexible in terms of their precise version requirements, but each package's repo only lists its dependencies in eclectic Conda environments. Using the Conda Forge package to get dependencies and just taking the leaf package from the Git repository works so often that its easy to forget that its a bit of a hack.

### Expected behavior

The Conda environment would be solved as usual, and then the PyPi dependency installed over the top. If this is undesirable because the repository and Conda packages might have different dependencies or something, it'd be great to both have a clearer error and have some mechanism to install a branch from a Git repository for an existing Conda dependency, or some sort of "nodep"-like override for pypi dependencies that would allow them to be installed over a conda dependency. Thanks!

**Comment by ruben-arts** [comment]
Hello @Yoshanuikabundi,

I agree the error should be improved! However, we can't fix the issue as we currently want to avoid breaking environments with overwriting Conda packages with PyPI packages. 

To fix this, you should use `scipy` from `pypi` as well for now. 

We're currently working on git dependencies for conda packages, so you can just get a rebuild of NumPy through the conda packages. But that is still under development for now.

**Comment by Yoshanuikabundi** [comment]
The only problem is that the packages I usually patch in this way are not available on `pypi`. But thanks!

**Comment by tdejager** [comment]
Related to: [https://github.com/prefix-dev/pixi/issues/3405](https://github.com/prefix-dev/pixi/issues/3405)

**Comment by VeckoTheGecko** [comment]
Same error, with a bit of a different use case that I thought was worth flagging: I'm also encountering this when doing an installation from source.

Cfgrib needs Xarray, but xarray is provided via Pypi

```toml
# pixi.toml
[project]
preview = ["pixi-build"]
channels = ["conda-forge", "nodefaults"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]


[environments]
doc = { features = [
  "doc",
], solve-group = "doc" }

[dependencies]
python = "*"
numpy = "*"
pandas = "*"

git = "*" # needed for dynamic versioning

[pypi-dependencies]
xarray = { path = ".", editable = true }

[feature.doc.dependencies]
cfgrib = "*" #! What is up with cfgrib??

[package]
name = "xarray"
version = "dynamic" # dynamic versioning needs better support in pixi https://github.com/prefix-dev/pixi/issues/2923#issuecomment-2598460666 . Putting `version = "dynamic"` here for now until pixi recommends something else.

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.host-dependencies]
setuptools = "*"
setuptools_scm = "*"
```

```sh
$ pixi --version
pixi 0.54.2
```

```sh
$ pixi lock
Error:   × failed to solve the pypi requirements of environment 'doc' for platform 'win-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because there is no version of xarray==2025.9.0 and you require xarray==2025.9.0, we can conclude that your requirements are unsatisfiable.
  help: The following PyPI packages have been pinned by the conda solve, and this version may be causing a conflict:
        xarray==2025.9.0
```

> To fix this, you should use `scipy` from `pypi` as well for now.

This suggestion works :)))
