### ISSUE TITLE
Creating .pixi/.gitignore

### ISSUE THREAD

**Issue by maurosilber** [prefix-dev/pixi#3050]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
channels = ["https://repo.prefix.dev/conda-forge"]
name = "pixi-gitignore"
platforms = ["osx-arm64"]

[dependencies]
python = "*"
```

Commands that create `.pixi/.gitignore`:
- `pixi install`
- `pixi shell`

Commands that don't:
- `pixi run python`
- `pixi add --pypi typing_extensions`

where I removed `rm -r .pixi` before each command.

### Issue description

Some commands create an environment and add `.pixi/.gitignore`, while others just create the environment without adding `.pixi/.gitignore`.

### Expected behavior

Every time that `.pixi` dir is created, I expect it to include a `.pixi/.gitignore`.

I think it would be ok to not create it if `.pixi` already exist and does not include a `.pixi/.gitignore`.
