### ISSUE TITLE
Improve how variants currently work

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#3057]
### Problem description

We want to use variants for dependency inheritance, and currently its just text, and you have to use a `*` version requirement.

This needs a bit of introspection, design, and specification to implement these.

**Comment by Hofer-Julian** [comment]
Outcome of discussion with @baszalmstra and @tdejager:
We saw two points how we could improve our current way of handling variants.
Let's start with our tutorial. There we have a package called `python_bindings with the following host-dependencies:
```toml
[package.host-dependencies]
cmake = ">=3.20, <3.27"
nanobind = ">=2.4.0, <2.5.0"
python = "*"                 
```

We can specify build-variants like this:
```toml
[workspace.build-variants]
python = ["3.11.*", "3.12.*"]
```

This way, `python_bindings` will be built twice, once for Python 3.11 and once for Python 3.12 if we specify the environments like this:

```toml
[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[environments]
py311 = ["py311"]
py312 = ["py312"]
```

## First Suggestion

At the moment, "3.11.*" is just a string. We could require it to be a version specifier. That should give better error messages and make the intention clear.
We should then also rename `build-variants` to `build-constraints`.
```diff
- [workspace.build-variants]
+ [workspace.build-constraints]
python = ["3.11.*", "3.12.*"]
```

## Second Suggestion

Ideally, `build-constraints` would be optional and pixi would be able to figure out on its own which packages it needs to build. In the example above, it should just build a version of `python_bindings` for Python 3.11 for environment `py311`. @baszalmstra called this process "reverse solving" where runtime dependencies inform build requirements.
