### ISSUE TITLE
Inconsistent population of `pixi.toml` vs. `pyproject.toml` with `[pypi-config]` from `config.toml`

### ISSUE THREAD

**Issue by dev351** [prefix-dev/pixi#3062]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.
  * (I've tested with pixi 0.40.3 Linux)

### Reproducible example

The file contents shown here are referenced in the issue description below.

A `~/.pixi/config.toml` file:
```toml
[pypi-config]
index-url = "https://<private-pypi-server>/simple"
```

A generated `pixi.toml` project file:

```toml
[project]
authors = ["User <user@example.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "new-project"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://<private-pypi-server>/simple"


[tasks]

[dependencies]
```

A starting `pyproject.toml` file (generated with `flit init`):
```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "new-project-package"
authors = [{name = "_", email = "user@example.com"}]
dynamic = ["version", "description"]
```

### Issue description

This issue shows an inconsistency in auto-populating the Pixi config `[pypi-config]` options into the generated `pixi.toml` or `pyproject.toml` files when running `pixi init`.

I have a Pixi config file (`~/.pixi/config.toml`) with the following content:

```toml
[pypi-config]
index-url = "https://<private-pypi-server>/simple"
```

When I run `pixi init` in an empty directory, the `[pypi-config]` contents from `config.toml` are correctly translated and copied into the generated `pixi.toml` project file. E.g.,

```toml
[project]
authors = ["User <user@example.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "new-project"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
index-url = "https://<private-pypi-server>/simple"


[tasks]

[dependencies]
```

However, if I intend to develop a new PyPI package, I'll start with a `pyproject.toml` file in the new project directory and then run `pixi init`. 

An initial `pyproject.toml` file (generated with `flit init`) has the following contents:

```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "new-project-package"
authors = [{name = "_", email = "user@example.com"}]
dynamic = ["version", "description"]

```

Now I run `pixi init` and Pixi asks if it should extend the existing `pyproject.toml`. I select `y` to extend.

```shell
$ pixi init
A 'pyproject.toml' file already exists.
Do you want to extend it with the '[tool.pixi]' configuration? [y/N]
✔ Added package 'new-project-package' as an editable dependency.
```

Observing the newly extended contents in `pyproject.toml`, I see some added Pixi configuration; however, I am expecting to see a `[tool.pixi.pypi-options]` section added with the `index-url` entry from the `~/.pixi/config.toml` file.

The extended `pyproject.toml` file contents are now:
```toml
[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "new-project-package"
authors = [{name = "_", email = "user@example.com"}]
dynamic = ["version", "description"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
ooo = { path = ".", editable = true }

[tool.pixi.tasks]

### NO [tools.pixi.pypi-options] section was generated !??

```

### Expected behavior

The `pyproject.toml` file should be populated with a `[tool.pixi.pypi-options]` section from the `~/.pixi/config.toml` file (`[pypi-config]`)--but no such configuration is inserted automatically.
This is inconsistent behavior with generating a `pixi.toml` file exclusively.
