### ISSUE TITLE
inconsistent lockfile - again

### ISSUE THREAD

**Issue by geoHeil** [prefix-dev/pixi#3076]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

given a pixi project like 

```toml
[dependencies]
python = "~=3.11"

[environments]
dagster-webserver = { features = [
  "dagster-webserver",
  "dagster-basics",
], solve-group = "default" }

[feature.dagster-basics.pypi-dependencies]
dagster = ">=1.9.0,<1.10"

[feature.dagster-webserver.pypi-dependencies]
dagster-webserver = ">=1.9.0,<1.10"

[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [
  "baz",
]
platforms = ["linux-64", "osx-arm64"]
channels = ["conda-forge"]

```

### Issue description

and a lockfile like https://gist.github.com/geoHeil/4c304c9233f4f1165354f8419e8743b2 I face the following issue:

```bash
pixi update

pixi shell -e dagster-webserver --locked
Error: 
  × lock-file not up-to-date with the project
```

This looks a bit similar to https://github.com/prefix-dev/pixi/issues/2865 but I am on 0.40.3 already. So this particular issue should be fixed.

### Expected behavior

consistent resolution
