### ISSUE TITLE
Environments of dependency tasks installed even with run --skip-deps

### ISSUE THREAD

**Issue by akhmerov** [prefix-dev/pixi#3080]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

1. Create `pyproject.toml` with the contents below

```toml
[project]
dependencies = []
name = "aaa"
requires-python = ">= 3.11"
version = "0.1.0"

[tool.pixi.project]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]

[tool.pixi.tasks]
ww = { cmd = "w" }

[tool.pixi.feature.empty.dependencies]

[tool.pixi.feature.empty.tasks]
w = { cmd = "w", depends-on = ["ww"] }

[tool.pixi.environments]
default = { solve-group = "default" }
empty = { features = ["empty"], no-default-feature = true }
```

2. `pixi run --skip-deps w; ls .pixi/envs/default`
3. Confirm that `detault` env is installed.

### Issue description

`pixi run task` only installs environments that a task uses. If a task has other tasks that it `depends-on`, also environments of those are installed. However, this should not be the case if a task is run with `--skip-deps`.

### Expected behavior

Environments that aren't used, aren't installed. `--skip-deps` is particularly relevant in CI environments where different tasks may run in different steps, and therefore this may cause a problem.
