### ISSUE TITLE
Pixi cannot resolve pypi dependency on a mac

### ISSUE THREAD

**Issue by arun-akur8** [prefix-dev/pixi#3081]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```pyproject.toml
[project]
# If you update this file please update the requirements.txt as well
name = "***"
version = "0.1.0"
requires-python = "==3.9.*"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
numpy = "==1.26.4"
scikit-learn = "==1.5.2"

[dependency-groups]
test = ["pytest"]

```

```shell
pixi add --pypi "ddtrace==2.20.0"  

```

I get the following error:

```
Error: 
  × Unable to solve pypi dependencies for the default environment because no compatible python interpreter can be installed for the current platform
    ╭─[9:5]
  8 │ [tool.pixi.project]
  9 │ channels = ["conda-forge"]
    ·     ──────┬─────
    ·           ╰── even though the projects does include support for 'osx-arm64'
 10 │ platforms = ["linux-64"]
    ╰────
  help: Try converting your [pypi-dependencies] to conda [dependencies]

```

### Issue description

I am working a macos machine to generate a lock file for a linux environment.

A related issue seems to be this one: https://github.com/prefix-dev/pixi/issues/1750

But in my case I need to install ddtrace as part of our docker image and I need to generate a lock file for the CI in github. What are the alternatives you could suggest?

Thank you for your reply

### Expected behavior

I expect the lock file to be updated for the linux target

**Comment by ruben-arts** [comment]
This is currently a limitation in pixi, we can't lock pypi dependencies for a system that we can't install the same environment for yet. So you would need to add `osx-arm64` to the platforms.

**Comment by tdejager** [comment]
This should solve that: https://github.com/prefix-dev/pixi/pull/3084

**Comment by uwu-420** [comment]
I wonder if I run into the same issue with this. I'm on `osx-arm64`.
```toml
[project]
dependencies = []
name = "foo"
requires-python = ">=3.13"
version = "0.1.0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tool.pixi.pypi-dependencies]
foo = { path = ".", editable = true }

[tool.pixi.feature.osx-arm64]
platforms = ["osx-arm64"]
system-requirements = {macos = "11.0"}

[tool.pixi.feature.linux-64]
platforms = ["linux-64"]
system-requirements = {libc = { family = "glibc", version = "2.17" }}

[tool.pixi.environments]
default = []
osx-arm64 = ["osx-arm64"]
linux-64 = ["linux-64"]
```
```
Error:
  × Unable to solve pypi dependencies for the linux-64 environment because no compatible python interpreter can be installed for the current platform
  help: Try converting your [pypi-dependencies] to conda [dependencies]
```
This is just a minimal example. I would have actually expected to be able to define things like dependencies and system requirements for all the platforms I want to support and pixi can do the resolution for all targets no matter on which platform I'm currently on.

After having read the `Multiple machines from one project` example in https://pixi.sh/latest/features/multi_environment/#real-world-example-use-cases I thought this would already be possible. I don't see what I'm doing differently here.

**Comment by tdejager** [comment]
Not sure what this example was condensed down to but you should be able to use the `system-requirements` for all platforms at the same time, no need to gate this behind a feature. If you want to install target specific dependencies its better to use: https://pixi.sh/latest/reference/pixi_manifest/#the-target-table

**Comment by uwu-420** [comment]
My bad, it's kind of a bad example. What I initially wanted was to specify different `macos` `system-requirements` for `osx-64` and `osx-arm64` respectively which currently isn't directly possible but with the help of different features and environments. That's why I went for such a kind of example, although admittedly quite misleading, sorry about that.

**Comment by tdejager** [comment]
Okay @uwu-420 I just did a small dive, needed to remember why this was difficult to do again :)

So for a couple of releases now we have the delayed instantation of the conda prefix, so if we do not encounter anything during the PyPI solve that needs the Python interpreter we do not create and install the conda prefix this is based on. However, and this the thing we do require the conda dependencies to be both solvable and solved for the platform this is running on. 

So if you have:

```toml
[project]
# If you update this file please update the requirements.txt as well
name = "***"
version = "0.1.0"
requires-python = "==3.9.*"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
numpy = "==1.26.4"
scikit-learn = "==1.5.2"
```

And you are solving this on an `osx` machine, then pixi says, hey there is no solve available for that platform, which in this case is implictly only `python`, as that is taken from conda. And I **do** need it because I might need to create a conda prefix with python in there. The problem that in this case, we actually know we do not need it.

There are a couple of solutions here.

## (1) Simplest
Use the pypi-options `no-build = true` at which point we could relax the requirement, because we know we for sure we are not going to build anything. Downsides, are that while editables keep working any other kind of source dependencies, including git dependencies will not work, as they need to be built.

## (2) Change meaning of platforms
We could change the meaning of `platforms` that it means that it **only** locks for those platforms, but is allowed to install to solve pypi dependencies for example. This requires some re-architecture of the code. A downside would be that it is easy to create a base prefix, that is uncompatible with other platforms, like including a `linux-64` dependency or `mlx` which is osx only.

## (3) PyPI build env
Another option is what we have an issue for and that is to be able to specify a special build environment in some way: https://github.com/prefix-dev/pixi/issues/1340 This is the least ambiguous and least magical, this environment should be cross-platform in some capacity however. It's also probably the most difficult for users to understand.

**Comment by uwu-420** [comment]
@tdejager personally I'm strongly in favor of (1). So if I understood correctly, just adding this to `pyproject.toml`
```toml
[tool.pixi.pypi-options]
no-build = true
```
could in theory allow examples like yours above to work because there shouldn't be any sdists during resolution anyway and if there are we can error intentionally. Imo having editable installs keep working is the most important thing as opposed to other forms of source distributions.

So I'd argue this seems like the least invasive change that would already unblock ~80% of usecases that are affected by this. Also it doesn't really break anything because it would be opt-in with `no-build = true`. I see that pixi already shows this tip when that error occurs `help: Try converting your [pypi-dependencies] to conda [dependencies]` so in case this change is implemented I'd add an explanation for this `no-build = true` trick as another hint to the message.

**Comment by tdejager** [comment]
Yeah looking into it more, I think that if we can delay the solve to when the prefix needs to be instantiated, similar as to when we install the prefix than this could be alleviated. There is nothing in the pypi code that would prevent this afaict at this point. It would require some re-architecturing of the code, because it now assumes a solve is done for a conda env for that platform.

**Comment by gzm55** [comment]
@tdejager  we have set `no-build = true` to avoid invoking pypi source build process. But we still need to [add current platform into the platforms](https://github.com/prefix-dev/pixi/blob/v0.48.2/src/lock_file/update.rs#L1309). Can we:

1. loose this requirement when `no-build` is `true`?
1. Or if current platform is not in platforms, fallback to an `exec`-env with spec `python=*` to delay the incompatible exception to the pypi source building steps.


A test case `pixi.toml`

```toml
[workspace]
channels = ["conda-forge"]
name = "test-uv"
platforms = ["linux-64", "osx-arm64"]
[pypi-options]
no-build = true
[dependencies]
python = '*'
[pypi-dependencies]
click = '*'
```

After run `pixi lock` on a `osx-arm64 machine, `pixi.lock` is generated successfully for both two platforms. Whereas conda prefix `.pixi/envs/default` is not installed at all. So the `LazyBuildDispatch` does not perform initialization.
