### ISSUE TITLE
inconsistent lockfile v3

### ISSUE THREAD

**Issue by geoHeil** [prefix-dev/pixi#3088]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

given a `pyproject.toml` in the current main folder
```toml
[dependencies]
python = "~=3.11"
pip = ">=24.2"

[environments]

research-cpu = { features = [
  "research-basics",
], solve-group = "default" }


[feature.research-basics.dependencies]
qdrant-client = "~=1.12.0"

[feature.research-basics.pypi-dependencies]
other = { path = "./src/pipelines/other", editable = true }

[project]
name = "baz"
version = "1.0.0"
description = "bar"
authors = [
  "foo",
]
platforms = ["linux-64", "win-64", "osx-arm64"]
channels = ["conda-forge"]

```

The following lock-file is created https://gist.github.com/geoHeil/50b27ba76a17e558caa39c800bfe7952

```bash
pixi update

pixi shell -e research-cpu --locked
Error: 
  × lock-file not up-to-date with the project
```

In order to reproduce: `other = { path = "./src/pipelines/other", editable = true }`, you need to create a:

```
[tool.dagster]
module_name = "other"

[build-system]
requires = ["setuptools>=72", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "other"
version = "0.0.1"
description = "dummy code location"
authors = [
  { name = "foo", email = "bar" },

]

dependencies = ["dagster"]

[project.optional-dependencies]

dev = ["dagster-webserver", "pytest"]

[tool.setuptools.packages.find]
exclude = ["other_tests"]

```

in `./src/pipelines/other`.

### Issue description

```bash
pixi update

pixi shell -e research-cpu --locked
Error: 
  × lock-file not up-to-date with the project
```

### Expected behavior

consistent resolution

the pixi version is  0.41.1
