### ISSUE TITLE
ros2 rplidar_ros symbol not found in flat namespace '__Py_TrueStruct'

### ISSUE THREAD

**Issue by ibrahim4529** [prefix-dev/pixi#3091]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi init test_rp_lidar -c robostack-staging -c conda-forge
pixi add ros-humble-desktop cmake pkg-config make ninja colcon-common-extensions catkin_tools rosdep

cd test_rp_lidar
mkdir src

cd src
git clone -b ros2 https://github.com/Slamtec/rplidar_ros.git

# modify to patch rplidar_roscan compile on osx-arm64
```
Cmake file after patch on rplidar_ros directory

```xml
################################################################################
# Set minimum required version of cmake, project name and compile options
################################################################################
cmake_minimum_required(VERSION 3.5)
project(rplidar_ros)

if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

if(MSVC)
  add_compile_definitions(
    _USE_MATH_DEFINES
  )
endif()

set(RPLIDAR_SDK_PATH "./sdk/")

if(APPLE)
add_compile_definitions(_MACOS)
FILE(GLOB RPLIDAR_SDK_SRC
  "${RPLIDAR_SDK_PATH}/src/arch/macOS/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/dataunpacker/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/dataunpacker/unpacker/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/hal/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/*.cpp"
)
else()
FILE(GLOB RPLIDAR_SDK_SRC 
  "${RPLIDAR_SDK_PATH}/src/arch/linux/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/dataunpacker/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/dataunpacker/unpacker/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/hal/*.cpp"
  "${RPLIDAR_SDK_PATH}/src/*.cpp"
)
endif()

################################################################################
# Find ament packages and libraries for ament and system dependencies
################################################################################
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(std_srvs REQUIRED)

################################################################################
# Build
################################################################################
include_directories(
  ${RPLIDAR_SDK_PATH}/include
  ${RPLIDAR_SDK_PATH}/src
  ${Boost_INCLUDE_DIRS}
)

add_executable(rplidar_node	src/rplidar_node.cpp ${RPLIDAR_SDK_SRC})
# target_link_libraries(rplidar_node ${ament_cmake_LIBRARIES})
ament_target_dependencies(rplidar_node
  rclcpp
  std_srvs
  sensor_msgs
)

add_executable(rplidar_composition src/rplidar_node.cpp ${RPLIDAR_SDK_SRC})
ament_target_dependencies(rplidar_composition
  rclcpp
  std_srvs
  sensor_msgs
)

add_executable(rplidar_client src/rplidar_client.cpp)
ament_target_dependencies(rplidar_client
  rclcpp
  std_srvs
  sensor_msgs
)
################################################################################
# Install
################################################################################
install(DIRECTORY launch rviz
  DESTINATION share/${PROJECT_NAME}
)

install(
  TARGETS rplidar_node rplidar_composition rplidar_client
  RUNTIME DESTINATION lib/${PROJECT_NAME}
)

################################################################################
# Macro for ament package
################################################################################
ament_export_dependencies(rclcpp)
ament_export_dependencies(std_msgs)
ament_export_dependencies(sensor_msgs)
ament_export_include_directories(include)
ament_package()
```
```toml
#file pixi toml
[project]
authors = ["ibrahim hanif <ibrahim.hanif@liostech.my.id>"]
channels = ["conda-forge", "robostack-staging"]
name = "simple_ros_ws"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = {cmd = "colcon build --symlink-install", inputs=["src"]}
start = {cmd="ros2 launch rplidar_ros view_rplidar_c1_launch.py", depends-on="build"}

[dependencies]
python = "3.11.*"
ros-humble-desktop = ">=0.10.0,<0.11"
cmake = ">=3.31.5,<4"
pkg-config = ">=0.29.2,<0.30"
make = ">=4.4.1,<5"
ninja = ">=1.12.1,<2"
colcon-common-extensions = ">=0.3.0,<0.4"
catkin_tools = ">=0.9.4,<0.10"
rosdep = ">=0.25.1,<0.26"

[activation]
scripts = ["install/setup.bash"]
```
Running and rplidar_ros node crash 
[rplidar_node-1] dyld[80638]: symbol not found in flat namespace '__Py_TrueStruct'
```shell
 pixi run start
✨ Pixi task (build): colcon build --symlink-install
Starting >>> rplidar_ros
Finished <<< rplidar_ros [0.53s]

Summary: 1 package finished [0.61s]

✨ Pixi task (start): ros2 launch rplidar_ros view_rplidar_c1_launch.py
[INFO] [launch]: All log files can be found below /Users/ibrahimhanif/.ros/log/2025-02-09-06-38-04-281557-Ibrahims-Mac-mini.local-80637
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rplidar_node-1]: process started with pid [80638]
[INFO] [rviz2-2]: process started with pid [80639]
[rplidar_node-1] dyld[80638]: symbol not found in flat namespace '__Py_TrueStruct'
[ERROR] [rplidar_node-1]: process has died [pid 80638, exit code -6, cmd '/Users/ibrahimhanif/Labs/simple_ros_ws/install/rplidar_ros/lib/rplidar_ros/rplidar_node --ros-args -r __node:=rplidar_node --params-file /var/folders/55/dnnqp_v946sch1_z88_xb_l80000gn/T/launch_params_v81fr3fx'].
[rviz2-2] [INFO] [1739057884.637623538] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1739057884.638000459] [rviz2]: OpenGl version: 2.1 (GLSL 1.2)
[rviz2-2] [INFO] [1739057884.658608885] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] 2025-02-09 06:38:04.786 rviz2[80639:28213876] +[IMKClient subclass]: chose IMKClient_Modern
[rviz2-2] 2025-02-09 06:38:04.786 rviz2[80639:28213876] +[IMKInputSession subclass]: chose IMKInputSession_Modern
[INFO] [rviz2-2]: process has finished cleanly [pid 80639]
```

### Issue description

 symbol not found in flat namespace '__Py_TrueStruct'

### Expected behavior

run correctly and can comunicate with hardware and node not crash
