### ISSUE TITLE
I can not specify the correct python version with bugfix number

### ISSUE THREAD

**Issue by etienne-monier** [prefix-dev/pixi#3110]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Here is a `pyproject.toml`

```toml
[project]
authors = [{name = "Etienne Monier", email = "etienne.monier@test.com"}]
name = "pixi-py"
requires-python = "== 3.10.7"
version = "0.1.0"
dependencies = ["pydantic"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "pypi"]
platforms = ["linux-64"]

[tool.pixi.tasks]
run-local = "python scripts/run.py"

[tool.pixi.pypi-dependencies]
pixi_py = { path = ".", editable = true }

[tool.pixi.dependencies]
pygrib = ">=2.1.6,<3"

```

Run `pixi install`

### Issue description

Running `pixi install` raises

```
❯ pixi install
Error: 
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because the requested Python version (==3.10.*) does not satisfy Python==3.10.7 and pixi-py==0.1.0
      depends on Python==3.10.7, we can conclude that pixi-py==0.1.0 cannot be used.
      And because only pixi-py==0.1.0 is available and you require pixi-py, we can conclude that your
      requirements are unsatisfiable.
      
      hint: The `requires-python` value (==3.10.*) includes Python versions that are not supported by
      your dependencies (e.g., pixi-py==0.1.0 only supports ==3.10.7). Consider using a more restrictive
      `requires-python` value (like ==3.10.7).

Error: 
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because the requested Python version (==3.10.*) does not satisfy Python==3.10.7 and pixi-py==0.1.0
      depends on Python==3.10.7, we can conclude that pixi-py==0.1.0 cannot be used.
      And because only pixi-py==0.1.0 is available and you require pixi-py, we can conclude that your
      requirements are unsatisfiable.
      
      hint: The `requires-python` value (==3.10.*) includes Python versions that are not supported by
      your dependencies (e.g., pixi-py==0.1.0 only supports ==3.10.7). Consider using a more restrictive
      `requires-python` value (like ==3.10.7).
```

### Expected behavior

I expect the correct python version to be installed.
