### ISSUE TITLE
pixi 0.41.2 breaks shebang

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#3112]
```
[project]
name = "my-repo"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
docs = "cd docs && make html"

[dependencies]
make = "*"
sphinx = "*"
sphinxcontrib-apidoc = "*"
```

```
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          cache: false
          pixi-version: v0.41.2
      - name: Build docs
        run: |
          cat $(pixi run which sphinx-build)
```

```
#!.pixi/envs/default/bin/python3.13
# -*- coding: utf-8 -*-
import re
import sys

from sphinx.cmd.build import main

if __name__ == '__main__':
	sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
	sys.exit(main())
```
