### ISSUE TITLE
Robostack-humble channel not mirroring correctly

### ISSUE THREAD

**Issue by TedVanderfeen** [prefix-dev/pixi#3136]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```bash
pixi init robostack
cd robostack
```
Modify pixi.toml with the following configuration:
```toml
[project]
name = "robostack"
version = "0.1.0"
description = "Development environment for RoboStack ROS packages"
authors = ["Your Name <your.email@example.com>"]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64", "linux-aarch64"]

[target.win-64.dependencies]
#vs2022_win-64 = "*" #Uncomment if using Visual Studio 2022

[dependencies]
python = "==3.11"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"

[environments]
noetic = { features = ["noetic"] }
humble = { features = ["humble"] }
jazzy = { features = ["jazzy"] }

#noetic
[feature.noetic]
channels = ["https://prefix.dev/robostack-staging"]

[feature.noetic.dependencies]
ros-noetic-desktop = "*"
catkin_tools = "*"
rosdep = "*"

#humble
[feature.humble]
channels = ["https://prefix.dev/robostack-humble"]

[feature.humble.dependencies]
ros-humble-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"

#jazzy
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
ros-jazzy-desktop = "*"
colcon-common-extensions = "*"
rosdep = "*"
```
```bash
pixi install
pixi shell -e humble -v
```

### Issue description

I'm currently updating the documentation (https://github.com/RoboStack/robostack.github.io/pull/73) for https://github.com/RoboStack/ to include install steps for Pixi and the new robostack-(distribution) channels. But it looks like there's an issue with the `https::/prefix.dev/robostack-humble` channel. I get the following error upon invoking `pixi shell -e humble -v`. Tested on both Linux/WSL and windows to the same effect.

```bash
ted@SCYTHE-PH:~/robostack$ pixi shell -e humble -v
 INFO pixi::environment: verifying prefix location is unchanged, with prefix file: /home/ted/robostack/.pixi/envs/conda-meta/pixi_env_prefix
 INFO pixi::lock_file::update: the lock-file is up-to-date
 INFO pixi::lock_file::update: Updating prefix
    download & extract   [00:00:01] [━━━━━━━━━━━━━━━━━━━━]      0 B @ 0 B/s    pyqt-builder
    installing packages  [00:00:01] [━━━━━━━━━━━━━━━━━━━━]     1/1                                                      Error:
  × failed to fetch pyqt-builder-1.13.0-py_2.tar.bz2
  ╰─▶ HTTP status client error (404 Not Found) for url (https://conda.anaconda.org/robostack-humble/noarch/pyqt-
      builder-1.13.0-py_2.tar.bz2)
```
`ros-humble-desktop` installs fine when grabbing files from `https:://prefix.dev/robostack-staging`, and also installs correctly into a mamba environment from the conda channel `robostack-humble`.

### Expected behavior

Expect the environment to grab all dependencies without issues.
