### ISSUE TITLE
Allow "meta package" builds for pixi build

### ISSUE THREAD

**Issue by jackm97** [prefix-dev/pixi#3143]
### Problem description

Consider a workspace with multiple packages, but no specific "main" package, in contrast with the example in the documentation. One can imagine a situation where multiple teams work on different packages that are all equally important and only when are they all together do they constitute a complete product. This is the case for my current workplace.

The top-level workspace manifest might look like

```toml
[workspace]
name = "Product Packages"
platforms = ["win-64", "linux-64"]
preview = ["pixi-build"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[system-requirements]
libc = { family = "glibc", version = "2.34" }

[dependencies]
package1 = { path = "./packages/package1/pkg-spec" }
package2 = { path = "./packages/package2/pkg-spec" }
package3 = { path = "./packages/package3/pkg-spec" }
```

Now, this is great if all I want to do is install the packages and tar the env using `pixi-pack`, which will likely be a common use case for sharing reproducing environments for bugs and such. 

But we have a lot of work that can't be run locally and needs to be submitted as a job to our CI infra. We have an artifactory that or CI manifests already support, which would make using conda packages a breeze.

So it would be nice if it was possible to do `pixi build` so all the `.conda` packages are dropped in the working directory allowing for upload to the artifactory. 

I imagine this would be easiest with some sort of meta package type, where it just aggregates individual package builds. Maybe even a new backend? I'm not sure...

**Comment by jackm97** [comment]
To add, I'm thinking the manifest would look something like this:

```toml
[workspace]
name = "Product Packages"
platforms = ["win-64", "linux-64"]
preview = ["pixi-build"]
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[system-requirements]
libc = { family = "glibc", version = "2.34" }

[dependencies]
product-package = { path = "." }

[package]
name = "product-package"
version = "1.0.0"

[package.build]
backend = { name = "pixi-build-metapackage", version = "0.1.*" }

[package.run-dependencies]
package1 = { path = "./packages/package1/pkg-spec" }
package2 = { path = "./packages/package2/pkg-spec" }
package3 = { path = "./packages/package3/pkg-spec" }
```
