### ISSUE TITLE
Environment with platform not matching default is skipped.

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#3150]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "test"
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64"]

[dependencies]
python = "*"

[feature.not-win]
platforms = ["osx-arm64"]
dependencies = { pixi = "*" }

[environments]
not-win = ["not-win"]
```

Results in a `pixi.lock` that includes the `not-win` env as:
```yml
  not-win:
    channels:
    - url: https://prefix.dev/conda-forge/
    packages: {}
```

### Issue description

With `no-default-feature = true` it does work

### Expected behavior

This should have created an error as the platform is not supported by the default feature, but it's not ignored by setting `no-default-feature = true`.
