### ISSUE TITLE
Support variants for `pixi build`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3153]
We can define variants for a workspace like this:

```toml
[workspace.build-variants]
python = ["3.11.*", "3.12.*"]
```

That works fine when installing with `pixi install`, however `pixi build` only produces a single conda package.
That is the case, because we don't pass the information via the `variant_configuration` parameter:
https://github.com/prefix-dev/pixi/blob/caf2d82429939975cf2e642ee5bb3c64666359a8/src/cli/build.rs#L175
