### ISSUE TITLE
Improve error messages for missing `build` fields in `pixi.toml`

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#3158]
### Description
When there is a missing required field in `pixi.toml`, Pixi does not clearly indicate which table the missing field belongs to.

### Steps to Reproduce
1. Create a `pixi.toml` file:
   ```toml
   [project]
   channels = ["https://prefix.dev/conda-forge"]
   name = "build"
   platforms = ["osx-arm64"]
   preview = ["pixi-build"]

   [package.run-dependencies]
   python = "*"
   ```
2. Run `pixi i`
3. Observe the error:
   ```
   Error:
     × failed to parse project from /Users/rubenarts/envs/build/pixi.toml: missing field 'build' in table
   ```
4. After adding `[package.build]`, the error changes to:
   ```
   Error:
     × failed to parse project from /Users/rubenarts/envs/build/pixi.toml: missing field 'version' in table
   ```

### Expected Behavior
Pixi should specify *which* table the missing field belongs to, making debugging easier.
