### ISSUE TITLE
Improve error message when conda path dependency does not match

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#3159]
### Description
If the package name in `pixi.toml` does not match a dependency declaration, the error message is unclear and does not guide the user toward the root cause of the issue.

### Steps to Reproduce
1. Define `pixi.toml`:
   ```toml
   [package]
   name = "talker"
   version = "1.2.3"

   [dependencies]
   talker2 = { path = "src/talker2" }
   ```
2. Run:
   ```
   pixi run ros2 run talker2 talker2
   ```
3. Observe the error:
   ```
   Error:
     × failed to solve the conda requirements of 'default' 'osx-arm64'
     ╰─▶ Cannot solve the request because of: No candidates were found for talker2 *.
   ```

### Expected Behavior
The error should clearly indicate that the package name `talker2` does not match the package definition in `pixi.toml`.
