### ISSUE TITLE
Unable to install pytorch nightly

### ISSUE THREAD

**Issue by samvanstroud** [prefix-dev/pixi#3193]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
apptainer pull pixi.sif docker://ghcr.io/prefix-dev/pixi:noble-cuda-12.6.3
apptainer shell -nv pixi.sif
cd <project>
pixi install 
```

minimal `pyproject.toml`:
```toml
[project]
name = "test"
requires-python = "== 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "nodefaults"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
torch = { version = "==2.7.*", index = "https://download.pytorch.org/whl/nightly/cu124"}

[tool.pixi.system-requirements]
linux = "3.10.0"
libc = "2.39"
cuda = "12.4"

[tool.pixi.dependencies]
python = "3.11.*"
ninja = "*"

```

Output:
```
Error: 
  × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because there is no version of pytorch-triton{platform_machine == 'x86_64' and sys_platform == 'linux'}
      ==3.2.0+git0d4682f0 and torch>=2.7.0.dev20250105+cu124,<=2.7.0.dev20250124+cu124 depends on pytorch-
      triton{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.2.0+git0d4682f0, we can conclude that
      torch>=2.7.0.dev20250105+cu124,<=2.7.0.dev20250124+cu124 cannot be used.
      And because only the following versions of torch are available:
          torch<2.7.dev0
          torch==2.7.0.dev20250105+cu124
          torch==2.7.0.dev20250106+cu124
          torch==2.7.0.dev20250107+cu124
          torch==2.7.0.dev20250108+cu124
          torch==2.7.0.dev20250109+cu124
          torch==2.7.0.dev20250110+cu124
          torch==2.7.0.dev20250111+cu124
          torch==2.7.0.dev20250112+cu124
          torch==2.7.0.dev20250113+cu124
          torch==2.7.0.dev20250114+cu124
          torch==2.7.0.dev20250115+cu124
          torch==2.7.0.dev20250116+cu124
          torch==2.7.0.dev20250117+cu124
          torch==2.7.0.dev20250118+cu124
          torch==2.7.0.dev20250119+cu124
          torch==2.7.0.dev20250120+cu124
          torch==2.7.0.dev20250121+cu124
          torch==2.7.0.dev20250122+cu124
          torch==2.7.0.dev20250123+cu124
          torch==2.7.0.dev20250124+cu124
          torch==2.7.0.dev20250125+cu124
          torch==2.7.0.dev20250126+cu124
          torch==2.7.0.dev20250127+cu124
          torch==2.7.0.dev20250128+cu124
          torch==2.7.0.dev20250129+cu124
          torch==2.7.0.dev20250130+cu124
          torch==2.7.0.dev20250131+cu124
          torch==2.7.0.dev20250201+cu124
          torch==2.7.0.dev20250202+cu124
          torch==2.7.0.dev20250203+cu124
          torch==2.7.0.dev20250204+cu124
          torch==2.7.0.dev20250205+cu124
          torch==2.7.0.dev20250206+cu124
          torch==2.7.0.dev20250207+cu124
          torch==2.7.0.dev20250208+cu124
          torch==2.7.0.dev20250209+cu124
          torch==2.7.0.dev20250210+cu124
          torch==2.7.0.dev20250211+cu124
          torch==2.7.0.dev20250212+cu124
          torch==2.7.0.dev20250213+cu124
          torch==2.7.0.dev20250214+cu124
          torch==2.7.0.dev20250215+cu124
          torch==2.7.0.dev20250216+cu124
          torch==2.7.0.dev20250217+cu124
          torch==2.7.0.dev20250218+cu124
          torch==2.7.0.dev20250219+cu124
          torch==2.7.0.dev20250220+cu124
          torch==2.7.0.dev20250221+cu124
          torch==2.7.0.dev20250222+cu124
          torch==2.7.0.dev20250223+cu124
          torch==2.7.0.dev20250224+cu124
      we can conclude that torch>=2.7.dev0,<2.7.0.dev20250125+cu124 cannot be used. (1)
      
      Because there is no version of pytorch-triton{platform_machine == 'x86_64' and sys_platform == 'linux'}
      ==3.2.0+gitb2684bf3 and torch>=2.7.0.dev20250125+cu124,<=2.7.0.dev20250204+cu124 depends on pytorch-
      triton{platform_machine == 'x86_64' and sys_platform == 'linux'}==3.2.0+gitb2684bf3, we can conclude that
      torch>=2.7.0.dev20250125+cu124,<=2.7.0.dev20250204+cu124 cannot be used.
      And because we know from (1) that torch>=2.7.dev0,<2.7.0.dev20250125+cu124 cannot be used, we can conclude that
      torch>=2.7.dev0,<2.7.0.dev20250205+cu124 cannot be used. (2)
      
      Because there is no version of pytorch-triton{platform_machine == 'x86_64' and sys_platform == 'linux'}
      ==3.2.0+git4b3bb1f8 and torch>=2.7.0.dev20250205+cu124 depends on pytorch-triton{platform_machine == 'x86_64' and
      sys_platform == 'linux'}==3.2.0+git4b3bb1f8, we can conclude that torch>=2.7.0.dev20250205+cu124 cannot be used.
      And because we know from (2) that torch>=2.7.dev0,<2.7.0.dev20250205+cu124 cannot be used, we can conclude that
      torch>=2.7.dev0 cannot be used.
      And because you require torch>=2.7.dev0, we can conclude that your requirements are unsatisfiable.
      
      hint: `torch` was requested with a pre-release marker (e.g., all of:
          torch>=2.7.dev0,<2.7.0.dev20250105+cu124
          torch>2.7.0.dev20250105+cu124,<2.7.0.dev20250106+cu124
          torch>2.7.0.dev20250106+cu124,<2.7.0.dev20250107+cu124
          torch>2.7.0.dev20250107+cu124,<2.7.0.dev20250108+cu124
          torch>2.7.0.dev20250108+cu124,<2.7.0.dev20250109+cu124
          torch>2.7.0.dev20250109+cu124,<2.7.0.dev20250110+cu124
          torch>2.7.0.dev20250110+cu124,<2.7.0.dev20250111+cu124
          torch>2.7.0.dev20250111+cu124,<2.7.0.dev20250112+cu124
          torch>2.7.0.dev20250112+cu124,<2.7.0.dev20250113+cu124
          torch>2.7.0.dev20250113+cu124,<2.7.0.dev20250114+cu124
          torch>2.7.0.dev20250114+cu124,<2.7.0.dev20250115+cu124
          torch>2.7.0.dev20250115+cu124,<2.7.0.dev20250116+cu124
          torch>2.7.0.dev20250116+cu124,<2.7.0.dev20250117+cu124
          torch>2.7.0.dev20250117+cu124,<2.7.0.dev20250118+cu124
          torch>2.7.0.dev20250118+cu124,<2.7.0.dev20250119+cu124
          torch>2.7.0.dev20250119+cu124,<2.7.0.dev20250120+cu124
          torch>2.7.0.dev20250120+cu124,<2.7.0.dev20250121+cu124
          torch>2.7.0.dev20250121+cu124,<2.7.0.dev20250122+cu124
          torch>2.7.0.dev20250122+cu124,<2.7.0.dev20250123+cu124
          torch>2.7.0.dev20250123+cu124,<2.7.0.dev20250124+cu124
          torch>2.7.0.dev20250124+cu124,<2.7.0.dev20250125+cu124
          torch>2.7.0.dev20250125+cu124,<2.7.0.dev20250126+cu124
          torch>2.7.0.dev20250126+cu124,<2.7.0.dev20250127+cu124
          torch>2.7.0.dev20250127+cu124,<2.7.0.dev20250128+cu124
          torch>2.7.0.dev20250128+cu124,<2.7.0.dev20250129+cu124
          torch>2.7.0.dev20250129+cu124,<2.7.0.dev20250130+cu124
          torch>2.7.0.dev20250130+cu124,<2.7.0.dev20250131+cu124
          torch>2.7.0.dev20250131+cu124,<2.7.0.dev20250201+cu124
          torch>2.7.0.dev20250201+cu124,<2.7.0.dev20250202+cu124
          torch>2.7.0.dev20250202+cu124,<2.7.0.dev20250203+cu124
          torch>2.7.0.dev20250203+cu124,<2.7.0.dev20250204+cu124
          torch>2.7.0.dev20250204+cu124,<2.7.0.dev20250205+cu124
          torch>2.7.0.dev20250205+cu124,<2.7.0.dev20250206+cu124
          torch>2.7.0.dev20250206+cu124,<2.7.0.dev20250207+cu124
          torch>2.7.0.dev20250207+cu124,<2.7.0.dev20250208+cu124
          torch>2.7.0.dev20250208+cu124,<2.7.0.dev20250209+cu124
          torch>2.7.0.dev20250209+cu124,<2.7.0.dev20250210+cu124
          torch>2.7.0.dev20250210+cu124,<2.7.0.dev20250211+cu124
          torch>2.7.0.dev20250211+cu124,<2.7.0.dev20250212+cu124
          torch>2.7.0.dev20250212+cu124,<2.7.0.dev20250213+cu124
          torch>2.7.0.dev20250213+cu124,<2.7.0.dev20250214+cu124
          torch>2.7.0.dev20250214+cu124,<2.7.0.dev20250215+cu124
          torch>2.7.0.dev20250215+cu124,<2.7.0.dev20250216+cu124
          torch>2.7.0.dev20250216+cu124,<2.7.0.dev20250217+cu124
          torch>2.7.0.dev20250217+cu124,<2.7.0.dev20250218+cu124
          torch>2.7.0.dev20250218+cu124,<2.7.0.dev20250219+cu124
          torch>2.7.0.dev20250219+cu124,<2.7.0.dev20250220+cu124
          torch>2.7.0.dev20250220+cu124,<2.7.0.dev20250221+cu124
          torch>2.7.0.dev20250221+cu124,<2.7.0.dev20250222+cu124
          torch>2.7.0.dev20250222+cu124,<2.7.0.dev20250223+cu124
          torch>2.7.0.dev20250223+cu124,<2.7.0.dev20250224+cu124
          torch>2.7.0.dev20250224+cu124,<2.8.dev0
      ), but pre-releases weren't enabled (try: `--prerelease=allow`)
```

### Issue description

I'm trying to install pytorch nightlies using pixi with some errors about `pytorch-triton` which torch pins to a specific git reference. I that thought that pixi supported this but perhaps not transitively?

The error message also mentions ```but pre-releases weren't enabled (try: `--prerelease=allow`)``` which I think is an unhelpful hint and could be removed.

### Expected behavior

I want to be able to install the latest pytorch nightly

**Comment by ruben-arts** [comment]
Hey!

The torch nightly packages require dependencies from that index. Pixi needs to understand that it can use that index for it's dependencies. You can do that by setting the `pypi-options.extra-index-urls` e.g.:
```toml
[project]
name = "test"
requires-python = "== 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge", "nodefaults"]
platforms = ["linux-64"]


### THIS ###
[tool.pixi.pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/nightly/cu124"]
### THIS ###


[tool.pixi.pypi-dependencies]
# torch = { version = "==2.7.0.dev20250221+cu124", index = "https://download.pytorch.org/whl/nightly/cu124"}
torch = { version = "==2.7.*", index = "https://download.pytorch.org/whl/nightly/cu124"}

[tool.pixi.system-requirements]
linux = "5.10.0"
libc = "2.39"
cuda = "12.4"

[tool.pixi.dependencies]
python = "3.11.*"
ninja = "*"
```

Ps. the `--prerelease` flag tip is coming from `uv`, unfortunately.
