### ISSUE TITLE
Improve multi environment task running exprience

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#3197]
Original mention: https://github.com/prefix-dev/pixi/issues/1272#issuecomment-2678337558

Depending on a task that is in a different environment works great until you want to use an explicit environment. Because then all depended on tasks should be available in the given environment. 

For example, the `pixi run -e default install-build` will not work where `pixi run install-build` will. 
```toml
[feature.build.tasks]
build = "echo build"

[feature.test.tasks]
install-build = { cmd = "echo install-build", depends-on = ["build"] }

[feature.dev.tasks]
dev-task = "echo dev-task"

[environments]
build = { features = ["build"], no-default-feature = true }
default = { features = ["test", "dev"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" } 
```

A few ideas to solve this:
- Allow users to specify multiple environment so in the explicit case it can have a list of environments to choose from. 
- Automatically redirect to a non-explicit environment if the task can not be found. (I prefer this but it creates an issue when you then have a task in multiple environments, basically moving the issue one level deeper)
- Make the depends-on a more verbose, with one of the ideas from #1272 to allow users to specify which environment the depends on should run in.
