### ISSUE TITLE
Add `project.exclude-newer` to pixi projecct definition

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#3244]
### Problem description

I think it would be great to have the option to only include dependencies up to a certain point in time.

```toml
[project]
name = "my-project"
# ...
exclude-newer = 2023-09-01 # toml supports dates and datetimes
```

https://docs.rs/rattler_solve/1.3.11/rattler_solve/struct.SolverTask.html

rattler_solve already has the option to do so using `exclude_newer`.
