### ISSUE TITLE
Document the conda path dependencies

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#3251]
We support `recipe.yaml` and `meta.yaml` as a path dependency, but it's not documented.

e.g.
```toml
[dependencies]
package = { path = "./recipe.yml" }
```
