### ISSUE TITLE
Potential caching bug when changing solve-group

### ISSUE THREAD

**Issue by uwu-420** [prefix-dev/pixi#3269]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

- Create a fresh project with this `pyproject.toml`.
```toml
[project]
name = "pixi-test"
requires-python = ">=3.13"
version = "0.1.0"
dependencies = []

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["osx-64", "osx-arm64"]

[tool.pixi.feature.foo]
platforms = ["osx-64"]

[tool.pixi.feature.foo.dependencies]
fastapi = ">=0.115"

[tool.pixi.feature.bar]
platforms = ["osx-arm64"]

[tool.pixi.feature.bar.dependencies]
fastapi = "<0.115"

[tool.pixi.environments]
foo = {features = ["foo"], solve-group = "default"}
bar = {features = ["bar"], solve-group = "default"}
```
- Run `pixi install` which will fail as expected due to the conflicting dependency in the `default` solve-group.
- Change the solve-group of the `bar` environment to something other than `"default"` (I just chose `"other"`).
- Run `pixi install` again and it should successfully resolve everything as expected.
- Change back the solve-group of the `bar` environment to `"default"`
- Run `pixi install` again. It does not fail although it should due to the dependency conflicts in the `"default"` solve-group.

### Issue description

I think the example above shows that there are some caching issues which cause pixi to be fine with dependency conflicts that are usually caught by the solver.

### Expected behavior

The last `pixi install` should have shown the same error as the very first `pixi install`
