### ISSUE TITLE
Add constraints to limit dependency versions

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#3278]
### Problem description

It would be cool if we were able to add `constraints` in pixi.toml as well without needing to install them

```toml
[dependencies]
numpy = "*"

[constraints]
abc = "<5"
```

In this scenario, _if_ abc is added to the env, we get abc<5.

**Comment by bollwyvl** [comment]
Likely implied, but I would assume this would work for `feature`s as well. 

I've presently been doing this via dedicated full `dependency`-only features that provide refinements e.g. 

```toml
feature.run.dependencies.python = ">=3.9"
feature.run-oldest.dependencies.python = "3.9.*"
# the same for other factors
```

I guess an `feature.oldest.constraints` would allow all of those (even unrelated ones) to be stored together, and only impact the solve when needed.

Semi-related for the common case of minimum dependencies: another way to avoid extra specs that need to be kept in check fattening up `[environments.*.features]` with [`strategy`](https://github.com/conda/rattler/pull/660):

```toml
[feature.py.dependencies]
python = ">=3.9"

[feature.test.dependencies]
pytest = ">=7"

[environments]
test = {features = ["py", "test"] }
test-oldest = {features = [
  {name = "py", strategy = "lowest"},
  {name = "test", strategy = "lowest-direct"},
]}
```

This would start to get crazy with `solve-group`, but it was _already_ crazy.

As for export: I don't think `environment.yml` would be able to support this at all, as it doesn't expose an equivalent to `run_constraints` or `run_constrained`. `pip` would need a second file, though it could be specified inline with a _second_ file e.g. `-c env_platform_pip-constraints.txt`.
