### ISSUE TITLE
Pixi panics on manifest parsing with environments containing feature "default"

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3290]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

With the following manifest:

```toml
[workspace]
channels = ["conda-forge"]
name = "hello-world"
platforms = ["linux-64", "osx-arm64", "win-64"]

[environments]
test = ["default"]
```

Running the following command gives
```shell
pixi install
```

```
thread 'main2' panicked at src/workspace/environment.rs:343:18:
feature usage should have been validated upfront
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at src/main.rs:54:10:
Tokio executor failed, was there a panic?: Any { .. }
```

### Issue description

With our current setup, pixi cannot deal with environments that explicitly include the "default" feature

### Expected behavior

No panic, maybe not even an error.
