### ISSUE TITLE
"pixi add" adds unfulfillable dependency related to pre-release letter suffix

### ISSUE THREAD

**Issue by Vuenc** [prefix-dev/pixi#3317]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

With a new project `pixi.toml`:
```toml
[project]
channels = ["conda-forge"]
name = "pixi-issue-letter"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
```
running
```shell
pixi add opentelemetry-instrumentation-aiohttp-client
```

adds the unfulfillable dependency
```toml
[dependencies]
opentelemetry-instrumentation-aiohttp-client = ">=0.51b0,<0.51a1"
```

Then running `pixi install` yields
```
Error:   × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: No candidates were found for opentelemetry-instrumentation-aiohttp-client >=0.51b0,<0.51a1.
```

Changing the `<0.51a1` to `<0.51b1` lets the install go through.

### Issue description

It seems as if the handling of pre-release alphanumeric suffixes is not handled correctly by `pixi add` when computing the smallest excluded version.

### Expected behavior

The dependency 
```toml
[dependencies]
opentelemetry-instrumentation-aiohttp-client = ">=0.51b0,<0.51b1"
```
should be added.
