### ISSUE TITLE
`pixi auth login` doesn't work when no keychain is available.

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#334]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "test-auth"
version = "0.1.0"
description = "Add a short description here"
authors = ["Pavel"]
channels = ["conda-forge", "https://repo.prefix.dev/setup-pixi-test"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
test = "python -c 'print(\"Hello world!\")'"

[dependencies]
python = "3.9.*"
private-package = "*"
```

```yml
  auth-token-install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Move pixi.toml
        run: mv test/auth/* .
      - uses: prefix-dev/setup-pixi@v0.2.0
        with:
          auth-host: https://repo.prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - name: Ensure private-package is installed
        run: |
          test -f .pixi/env/conda-meta/private-package-0.0.1-0.json
```

### Issue description

On `ubuntu-latest`, there is no keychain available. `pixi auth login ...` writes the credentials to `~/.rattler/rattler_auth_store.json`. When doing `pixi install`, we get a http status code 401, though.

```
/home/runner/.pixi/bin/pixi install --manifest-path pixi.toml
  × HTTP status client error (403 Forbidden) for url (https://repo.prefix.dev/
  │ setup-pixi-test/noarch/private-package-0.0.1-0.tar.bz2)
```

### Expected behavior

The credentials should be read from `~/.rattler/rattler_auth_store.json`.

See also https://github.com/prefix-dev/setup-pixi/issues/14
