### ISSUE TITLE
Allow to specify build-backend for source code without `pixi.toml`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3348]
At the moment we have code in order to deal with source packages built by:
- conda-build
- rattler-build
- pixi-build

While `conda-build` isn't implemented, `rattler-build` works by spinning up the `pixi-build-rattler-build` backend behind the scenes. It does that by hard-coding the "conda-forge" and "https://prefix.dev/pixi-build-backends" channels, which isn't flexible nor robust.

https://github.com/prefix-dev/pixi/blob/0a04b0ca7b6c86f64848b4e31f7b57edb44eb6e5/crates/pixi_build_frontend/src/protocols/builders/rattler_build.rs#L116-L130

The motivation for direct `conda-build` and `rattler-build` support is in order to depend on 3rd party packages built on a forge like conda-forge.

I believe that it would be both simpler and powerful to add an optional `src` field to `package`.

```
[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.1.*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
src = { git = "https://github.com/conda-forge/numpy-feedstock" }
```

`src` would default to `{ path = "."}`, and therefore have the same behavior as is.

**Comment by ruben-arts** [comment]
I like the idea! I was also thinking about that lately. But since I was more on the using end I didn't want to create extra pixi.tomls or "packages" for the dependencies.

So I was thinking about making it part of the dependency spec:
```toml
[dependencies]
ros-jazzy-navigation2-msgs = { git = "https://github.com/navigation2/navigation2", build-backend = "pixi-build-ros-package"}
```

Do you think that would make sense to solve the same problem?

**Comment by baszalmstra** [comment]
Mmm yeah that seems more powerful indeed!

But you would need to create a pixi.toml for the feedstocks you want to depend on. 

E.g. you root pixi.toml would look like:

```
[dependencies]
numpy = { path = "numpy-feedstock" }
```

and you would need a pixi.toml in the `numpy-feedstock` directory with the above contents.

Vs, how it is now:

```
[dependencies]
numpy = "https://github.com/conda-forge/numpy-feedstock"
```

**Comment by nichmor** [comment]
> I like the idea! I was also thinking about that lately. But since I was more on the using end I didn't want to create extra pixi.tomls or "packages" for the dependencies.
> 
> So I was thinking about making it part of the dependency spec:
> 
> [dependencies]
> ros-jazzy-navigation2-msgs = { git = "https://github.com/navigation2/navigation2", build-backend = "pixi-build-ros-package"}
> Do you think that would make sense to solve the same problem?

could we make it as a table? for example

```
[dependencies.ros-jazzy-navigation2-msgs]
src = { git = "https://github.com/navigation2/navigation2"
build-backend = "pixi-build-ros-package 0.1.0"
channels = "...." ( optional, will inherit pixi.toml channels by default ) 
```

**Comment by Hofer-Julian** [comment]
Yeah, my suggestion is clearly more verbose. Your summary was indeed what I had in mind @baszalmstra.


I think @ruben-arts' and @nichmor's alternative might be a good, less verbose alternative. I'd be fine with going for that one instead.

Here a slightly fixed up version:

```toml
[dependencies.ros-jazzy-navigation2-msgs]
git = "https://github.com/navigation2/navigation2"
build-backend = "pixi-build-ros-package 0.1.0"
channels = "...." # ( optional, will inherit pixi.toml channels by default ) 
```
