### ISSUE TITLE
`pixi global update` unintended behavior

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#3366]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[envs.dotnet]
channels = ["conda-forge"]
dependencies = { dotnet = "*" }
exposed = {dotnet = 'dotnet\dotnet' }

```
Test with the example in pixi document.
os: windows11

### Issue description

# problem1
Create a pixi-global.toml and run `pixi global update`.

The dotnet env will be actually installed, but pixi shows `Error:   × failed to find the designated package 'dotnet' in the prefix: 'C:\Users\Glatzel\.pixi\envs\dotnet'`, and dotnet.exe will not be exposed into .pixi/bin folder.

# problem2
After problem1,
1. Run `pixi global sync` to install dotnet.exe to bin folder.
2. Run `pixi global update` again, the dotnet.exe in bin folder will be removed, and the exposed in pixi global.toml will be removed.
```toml
[envs.dotnet]
channels = ["conda-forge"]
dependencies = { dotnet = "*" }
exposed = {}
```
This problem seems only happens to those with custom exposed path.

### Expected behavior

1. If my understanding is correct, `pixi global update` could do installing environments, updating environments, exposing tools to .pixi.bin folder (same as `pixi global sync`). 
I also aware of the hidden command `pixi global upgrade`, what's the difference between them? Maybe there will be a lock file of pixi-global.toml and the update and upgrade command in global will work like pixi update and upgrade?  

2. Disable the unexpected field removal in pixi-global.toml with `pixi global update`.
