### ISSUE TITLE
`pixi global update` doesn't create shortcut

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#3400]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[envs.mss]
channels = ["https://prefix.dev/conda-forge"]
dependencies = { mss = "*" }
shortcuts = ["mss"]
```
example from pixi document

### Issue description

pixi global update doesn't create shortcut

### Expected behavior

allow `pixi global update` create shortcut like what `pixi global install do`
I will try if i could fix it.
