### ISSUE TITLE
`pixi global update` throw `Activation variables need to contain PATH`

### ISSUE THREAD

**Issue by Glatzel** [prefix-dev/pixi#3402]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[envs.mss]
channels = ["https://prefix.dev/conda-forge"]
dependencies = { mss = "*" }
shortcuts = ["mss"]
```
os: win11

### Issue description

latest main branch throw this error while tag 0.43 works fine.
I think this caused by #3384 .

### Expected behavior

fix this problem
