### ISSUE TITLE
When lock file update fails on utility command it should hint at `--no-lockfile-update`

### ISSUE THREAD

**Issue by savente93** [prefix-dev/pixi#3406]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.
(it is arguable that this is a feature request and not a bug, but since it involved a MWE I reported as such. Maintainers are free to convert it to feature request if they think that is better)

### Reproducible example

```toml
[project]
authors         = [{ name = "Sam Vente", email = "savente93@proton.me" }]
name            = "pixi-bug-report"
requires-python = ">= 3.11"
version         = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires      = ["hatchling"]

[tool.pixi.workspace]
channels  = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
pixi_bug_report = { path = ".", editable = true }
numpy           = "<2.2"

[tool.pixi.dependencies]
gdal = "*"
```

```shell
pixi tree -i numpy
```
this now outputs 
```
> pixi tree -i numpy
Error:   × Failed to update lock file                                                                                                                            
  ├─▶ failed to solve the pypi requirements of 'default' 'win-64'                                                                                                
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because you require numpy<2.2 and numpy==2.2.4, we can conclude that your requirements are unsatisfiable.
```

### Issue description

While the above behavior is technically correct, the hints for resolving it could be clearer. The toml provided is put in an intentionally unsolvable state, which I had when trying to move a different project to pixi. I then tried to use `pixi tree -i numpy` to discover which dependency was causing this dependency but this failed because the environment was unsolvable. However `pixi tree -i numpy --no-lockfile-update` runs successfully

This issue is slightly related to #3405 (they originated in the same project) but I decided to file them separately since I think they both have somewhat orthagonal use

### Expected behavior

it would be very helpful if pixi would hint at this option to guide people who don't know about it, especially on informative commands (e.g. tree, list etc.). Perhaps the error could include something like: 
```
if the command failed because of an unsolvable command, rerunning it with  `--no-lockfile-update` may resolve the issue
```
