### ISSUE TITLE
Handling of repeated dependencies via "include-group" in dependency groups (PEP 735)

### ISSUE THREAD

**Issue by jamesmyatt** [prefix-dev/pixi#3456]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pyproject.toml`:

```toml
[project]
name = "project"
version = "0"
requires-python = ">=3.9"

[dependency-groups]
run = ["packaging"]
test = [{include-group = "run"}, "pytest"]
docs = [{include-group = "run"}, "sphinx"]
dev = [{include-group = "test"}, {include-group = "docs"}, "black"]
```

Then:

```shell
>pixi init           

A 'pyproject.toml' file already exists.

A 'pyproject.toml' file already exists.
Do you want to extend it with the '[tool.pixi]' configuration? yes
Added package 'project' as an editable dependency.
Added environments 'test', 'dev', 'run', 'docs' from optional dependencies or dependency groups.
```

```shell
>pixi shell -e dev -v
 INFO pixi_manifest::discovery: Found manifest in directory: "...", continuing further.
 INFO pixi_manifest::target: Adding pypi dependency: packaging "*"
 INFO pixi_manifest::target: Adding pypi dependency: packaging "*"
 INFO pixi_manifest::target: Adding pypi dependency: pytest "*"
 INFO pixi_manifest::target: Adding pypi dependency: packaging "*"
 INFO pixi_manifest::target: Adding pypi dependency: sphinx "*"
 INFO pixi_manifest::target: Adding pypi dependency: packaging "*"
 INFO pixi_manifest::target: Adding pypi dependency: pytest "*"
Error:   × packaging is already a dependency.
```

### Issue description

PEP 735 and the [official PyPA docs](https://packaging.python.org/en/latest/specifications/dependency-groups/#dependency-groups) are clear that with dependency groups, the tool should permit repeated dependencies and attempt to satisfy all of the constraints, as pixi already does with repeated dependencies between separate pixi features within the same pixi environment.

Since pixi has no concept of dependencies between features (as far as I can see), I think that pixi treats this by expanding each dependency group independently and making a feature from it, then include each separately as an environment, which is equivalent to:

```toml
[tool.pixi.feature.run.pypi-dependencies]
packaging = "*"

[tool.pixi.feature.test.pypi-dependencies]
packaging = "*"
pytest = "*"

[tool.pixi.feature.docs.pypi-dependencies]
packaging = "*"
sphinx = "*"

[tool.pixi.feature.dev.pypi-dependencies]
packaging = "*"
pytest = "*"
packaging = "*"
sphinx = "*"
black = "*"

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
run = { features = ["run"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
```

And the repeated entry for "packaging" in "dev" causes problems (obviously).

### Expected behavior

The immediate issue is that it should combine the constraints on the repeated packages and create the environment without error, as "uv" does.

The longer-term issue, and one that needs much more discussion, is that I think that pixi should really treat this as equivalent to the following.

```toml
[tool.pixi.feature.run.pypi-dependencies]
packaging = "*"

[tool.pixi.feature.test.pypi-dependencies]
pytest = "*"

[tool.pixi.feature.docs.pypi-dependencies]
sphinx = "*"

[tool.pixi.feature.dev.pypi-dependencies]
black = "*"

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["run", "test", "docs", "dev"], solve-group = "default" }
docs = { features = ["run", "docs"], solve-group = "default" }
run = { features = ["run"], solve-group = "default" }
test = { features = ["run", "test"], solve-group = "default" }
```

since this interacts correctly with other pixi configuration, such as defining tasks, e.g.

```toml
[tool.pixi.feature.test.tasks]
test = "python -m pytest"
```

Even better would be the functionality for "include-features" to link between features.
