### ISSUE TITLE
pixi global list performance regression starting with version 0.44.0

### ISSUE THREAD

**Issue by noamgot** [prefix-dev/pixi#3476]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi global list
# now wait...
```

### Issue description

In the past, there were some slowness issues with `pixi global list` (https://github.com/prefix-dev/pixi/issues/2605).

I'm afraid the issue is back on version 0.44.0.

I downgraded to all 0.43.* versions and there it works fast enough, but in 0.44.0 it just hangs.

### Expected behavior

make it work :)

**Comment by Hofer-Julian** [comment]
I just ran it locally, and it takes relatively long (~5s), but doesn't hang.

Could you please share your `pixi-global.toml`?

**Comment by Hofer-Julian** [comment]
After running, `pixi global sync`, `pixi global list` is nearly instantaneous for me.

**Comment by noamgot** [comment]
> I just ran it locally, and it takes relatively long (~5s), but doesn't hang.
> 
> Could you please share your `pixi-global.toml`?
@Hofer-Julian here:

```toml
version = 1

[envs.graphviz]
channels = ["conda-forge"]
dependencies = { graphviz = "*" }
exposed = { acyclic = "acyclic", bcomps = "bcomps", ccomps = "ccomps", circo = "circo", cluster = "cluster", diffimg = "diffimg", dijkstra = "dijkstra", dot = "dot", dot2gxl = "dot2gxl", fdp = "fdp", gc = "gc", gml2gv = "gml2gv", gv2gml = "gv2gml", gv2gxl = "gv2gxl", gvcolor = "gvcolor", gvgen = "gvgen", gvmap = "gvmap", ".graphviz-post-link" = ".graphviz-post-link", dot_builtins = "dot_builtins", edgepaint = "edgepaint", graphml2gv = "graphml2gv", gvpack = "gvpack", gvpr = "gvpr", gxl2dot = "gxl2dot", gxl2gv = "gxl2gv", mm2gv = "mm2gv", neato = "neato", nop = "nop", osage = "osage", prune = "prune", sccmap = "sccmap", sfdp = "sfdp", tred = "tred", twopi = "twopi", patchwork = "patchwork", unflatten = "unflatten" }

[envs.conda-pack]
channels = ["conda-forge"]
dependencies = { conda-pack = "*" }
exposed = { conda-pack = "conda-pack" }

[envs.exiftool]
channels = ["conda-forge"]
dependencies = { exiftool = "*" }
exposed = { exiftool = "exiftool" }

[envs.python]
channels = ["conda-forge"]
dependencies = { python = "*" }
exposed = { idle3 = "idle3", "idle3.13" = "idle3.13", pydoc = "pydoc", pydoc3 = "pydoc3", python = "python", python3 = "python3", "pydoc3.13" = "pydoc3.13", python3-config = "python3-config", "python3.1" = "python3.1", "python3.13" = "python3.13", "python3.13-config" = "python3.13-config" }

[envs.eza]
channels = ["conda-forge"]
dependencies = { eza = "*" }
exposed = { eza = "eza" }

[envs.bat]
channels = ["conda-forge"]
dependencies = { bat = "*" }
exposed = { bat = "bat" }

[envs.rattler-build]
channels = ["conda-forge"]
dependencies = { rattler-build = "*" }
exposed = { rattler-build = "rattler-build" }

[envs.s5cmd]
channels = ["conda-forge"]
dependencies = { s5cmd = "*" }
exposed = { s5cmd = "s5cmd" }

[envs.pixi-pack]
channels = ["conda-forge"]
dependencies = { pixi-pack = "*" }
exposed = { pixi-pack = "pixi-pack" }

[envs.gh]
channels = ["conda-forge"]
dependencies = { gh = "*" }
exposed = { gh = "gh" }

[envs.btop]
channels = ["conda-forge"]
dependencies = { btop = "*" }
exposed = { btop = "btop" }

[envs.conda-lock]
channels = ["conda-forge"]
dependencies = { conda-lock = "*" }
exposed = { conda-lock = "conda-lock" }

[envs.conda-build]
channels = ["conda-forge"]
dependencies = { conda-build = "*" }
exposed = { conda-build = "conda-build", conda-convert = "conda-convert", conda-debug = "conda-debug", conda-develop = "conda-develop", conda-inspect = "conda-inspect", conda-metapackage = "conda-metapackage", conda-render = "conda-render", conda-skeleton = "conda-skeleton" }

[envs.conda-recipe-manager]
channels = ["conda-forge"]
dependencies = { conda-recipe-manager = "*" }
exposed = { conda-recipe-manager = "conda-recipe-manager", crm = "crm" }

[envs.conda-smithy]
channels = ["conda-forge"]
dependencies = { conda-smithy = "*" }
exposed = { feedstocks = "feedstocks", conda-smithy = "conda-smithy" }


[envs.starship]
channels = ["conda-forge"]
dependencies = { starship = "*" }
exposed = { starship = "starship" }

[envs.direnv]
channels = ["conda-forge"]
dependencies = { direnv = "*" }
exposed = { direnv = "direnv" }

[envs.data-science]
channels = ["conda-forge"]
dependencies = { jupyter = "*", numpy = "*", pandas = "*", matplotlib = "*", ipython = "*", cloudpathlib-s3 = "*" , fsspec = "*", s3fs = "*" }
exposed = { jupyter = "jupyter", ipython = "ipython" }
```
I'm syncing now, will update here if it's solved...
