### ISSUE TITLE
Environment variable not correctly set when using `[activation]` table

### ISSUE THREAD

**Issue by EugenePlanteurCS** [prefix-dev/pixi#3491]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
channels = ["conda-forge", "eugeneplanteur"]
name = "gdal_in_pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gdal = "==3.9.3"
otb = { version = "=10.0.0", channel = "eugeneplanteur" }

[activation]
#scripts = ["setup_env.sh"]
env = { GDAL_DRIVER_PATH = "$CONDA_PREFIX/lib/gdalplugins" }
```

### Issue description

Hello! I'm having an issue when setting an environment variable when activating a pixi environment. I provided a minimal example: I'm installing `gdal` (from conda-forge) and `otb` from my own channel. For the context, this is a package that I built (using `rattler-build`). 

When using `gdal`, the environment variable `GDAL_DRIVER_PATH` is used to access drivers. If I only install `gdal`, the variable is automatically set when running `pixi shell` for example. But when installing otb alongside it, the variable sets itself to `disable`. There is probably something I can do when building the package, but as a quick workaround I tried using the `[activation]` table, but I noticed an inconsistency (?). If I use `env = { GDAL_DRIVER_PATH = "$CONDA_PREFIX/lib/gdalplugins" }`, the variable is set to `disable` when entering the environment:

```bash
$ pixi shell
(gdal_in_pixi)$ echo $GDAL_DRIVER_PATH
disable
```

But, if I create a bash script (setup_env.sh) which exports this variable:

```bash
export GDAL_DRIVER_PATH="$CONDA_PREFIX/lib/gdalplugins"
```

And use `scripts = ["setup_env.sh"]` in my `pixi.toml` instead, the variable is correctly set. Any idea why exporting the variable with a bash script correctly sets the variable, but using the `env = ...` doesn't ? 

### Expected behavior

The `GDAL_DRIVER_PATH` variable should be set to `$CONDA_PREFIX/lib/gdalplugins` when using `env = { GDAL_DRIVER_PATH = "$CONDA_PREFIX/lib/gdalplugins" }`.
