### ISSUE TITLE
Validate task args

### ISSUE THREAD

**Issue by bollwyvl** [prefix-dev/pixi#3535]
### Problem description

per https://github.com/prefix-dev/pixi/issues/3533#issuecomment-2783696643:

I would love if `args` also had a richer model to help projects write maintainable, self-documenting tasks:

```toml
[tasks.foo-one--]
cmd = "echo built {{ bar }} > bar/{{ bar }}.txt"
args = [
  { "arg" = "bar", default = "baz", description = "the foo to bar", enum=["baz", "boo"], regex="(baz|boo)" }
]
```

These would be lovely to see in a `pixi task help foo`, and give good feedback:

```bash
$> pixi r foo-one-- --bar poo

`foo-one--` argument `--bar` (the foo to bar) to was `poo`, but should be:
- one of `baz`, `boo`
- match the pattern `(baz|boo)`

Use `pixi task help foo-one--` to learn more.
```
