### ISSUE TITLE
task args: allow passing args to `depends-on`

### ISSUE THREAD

**Issue by lucascolley** [prefix-dev/pixi#3538]
### Problem description

Closely related to gh-3533.

To echo @bollwyvl's issues, super excited about task args! It looks like there is a missing piece for my use-case, though, trying to enable customisable parallelism. Relevant section of my `pixi.toml`:

```toml
[feature.build.tasks.build-only]
# just build without configure
cmd = ["cmake", "--build", "build", "-j{{ parallel }}"]
cwd = "."
args = [{ arg = "parallel", default = "2" }]
...
[feature.tests.tasks]
# build for tests
build-tests.depends-on = [
  "configure-tests",
  { "task" = "build-only", "args" = ["{{ parallel }}"] },
]
build-tests.args = [{ arg = "parallel", default = "2" }]
# just run tests
tests-only.cmd = ["ctest", "--output-on-failure", "--test-dir", "build/tests", "-j{{ parallel }}"]
tests-only.cwd = "."
tests-only.args = [{ arg = "parallel", default = "2" }]
# build and run tests
tests.cwd = "."
tests.depends-on = [
  "clone-xsref",
  { "task" = "build-tests", "args" = ["{{ parallel }}"] },
  { "task" = "tests-only", args = ["{{ parallel }}"] },
]
tests.args = [{ arg = "parallel", default = "2" }]
```

This fails for two reasons. In the first place, there are errors like

```
Error:   × Unexpected keys, expected only 'cmd', 'depends-on', 'description'
    ╭─[/Users/lucascolley/programming/xsf/pixi.toml:74:13]
 73 │ ]
 74 │ build-tests.args = [{ arg = "parallel", default = "2" }]
    ·             ──┬─
    ·               ╰── 'args' was not expected here
 75 │ # just run tests
    ╰────
```

which can be remedied by specifying a 'dummy' command `":"`. But this is just a symptom of the wider problem:

```
xsf on 🎋 task-args [🔨] via △ took 3s 
❯ pixi run build-tests
✨ Pixi task (configure-tests in dev): cmake -DBUILD_TESTS=ON "-S ." "-B build"
-- Arrow version: 19.0.1
-- Found the Arrow shared library: /Users/lucascolley/programming/xsf/./.pixi/envs/dev/lib/libarrow.1900.1.0.dylib
-- Found the Arrow import library: ARROW_IMPORT_LIB-NOTFOUND
-- Found the Arrow static library: 
-- Parquet version: 19.0.1
-- Found the Parquet shared library: /Users/lucascolley/programming/xsf/./.pixi/envs/dev/lib/libparquet.1900.1.0.dylib
-- Found the Parquet import library: PARQUET_IMPORT_LIB-NOTFOUND
-- Found the Parquet static library: 
-- Configuring done (0.8s)
-- Generating done (1.0s)
-- Build files have been written to: /Users/lucascolley/programming/xsf/./build

✨ Pixi task (build-only in dev): cmake --build build "-j{{ parallel }}"
Error:   × The task failed to parse
  ├─▶ Failed to replace argument placeholders. Task: 'cmake --build build "-j{{ parallel }}" '
  ╰─▶ unresolved argument placeholders found
```

So the enhancement request is to enable arg templating in `depends-on`, not just `cmd`.

**Comment by phreed** [comment]
Is there a reason the `minijinja` capability was not included in the `task` field?
```toml
[tasks.build]
args = [
    { arg = "pkg", default = "dummy" },
    { arg = "tgt_platform", default = "linux-64" }
]
cmd = [ ... ]

[tasks.build-force]
args = [
    { arg = "pkg", default = "dummy" },
    { arg = "tgt_platform", default = "linux-64" }
]
cmd = [ ... ]

[tasks.publish]
args = [
    { arg = "pkg", default = "dummy" },
]
cmd = [ ... ]

[task.for-each]
args = [
  { arg = "the_task", default = "build"},
  { arg = "tgt_platform", default = "linux-64"}
]
depends-on = [
  { task = "{{ the_task }}", args = ["foo", "{{ tgt_platform }}"],
  ...
]

[tasks.build-all]
depends-on = [ { task = "for-each", args = ["build"] } ]

[tasks.publish-all]
depends-on = [ { task = "for-each", args = ["publish"] } ]
```
This does not work because  in the for-each task: `depends-on` -> list -> `task` value, does not do the minijinja thing.,
I thought this might get included in this issue.

This would give pixi higher-order-task the ability (making functions/tasks first-order) .
https://en.wikipedia.org/wiki/Higher-order_function
