### ISSUE TITLE
Allow setting environments in "fat" depends-on

### ISSUE THREAD

**Issue by bollwyvl** [prefix-dev/pixi#3539]
> Edit: changed to focus on multiple environments, and re-opened per https://github.com/prefix-dev/pixi/pull/3501#issuecomment-2785534843

### Problem description

To continue #3533, #3535, #3536:

One of the remaining pieces for handling big environment matrices (#1272) is explicitly knowing in which environment a task should run, started on #3501. While this breaks the "`feature`s don't know about `environments`" model, the up-side is much more comfortable access to scalable excursions in different environments, a la `tox`. 

Going a step further, `environment` could be an array, such that adding another task+environment excursion costs, at the very least, a comma, two quotes, and the name of the env instead of full duplication of the (increasingly complex) dependency description.

```toml
[tasks.foo-one--]
args = [{ "arg" = "bar" }]
cmd = "echo built {{ bar }} in $PIXI_ENVIRONMENT_NAME > bar/{{ bar }}-$PIXI_ENVIRONMENT_NAME.txt"
inputs = ["foo/{{ bar }}/"]
outputs = ["bar/{{ bar }}-$PIXI_ENVIRONMENT_NAME.txt"]

[tasks.foo-all]
depends-on = [
  { task = "foo-one--", args = ["baz"], environment = ["x", "y"] },
  # instead of: 
  #   { task = "foo-one--", "args" = ["baz"], environment = "y" },
  #   { task = "foo-one--", "args" = ["baz"], environment = "x" },
  { task = "foo-one--", args = ["boo"], environment = ["x", "z"] },
  # instead of:
  #  { task = "foo-one--", args = ["boo"], environment = "x" },
  #  { task = "foo-one--", args = ["boo"], environment = "z" },
]

[feature]
d-x.dependencies.foo = "1"
d-y.dependencies.foo = "2"
d-z.dependencies.foo = "3"

[environments]
x = ["d-x"]
y = ["d-y"]
z = ["d-z"]
```

All of the above [_can_ be done](https://github.com/prefix-dev/pixi/issues/1272#issuecomment-2124863626), even without `args`, but requires defining everything a couple of extra, typo-prone times.
