### ISSUE TITLE
DYLD_LIBRARY_PATH can't be set in pixi.toml?

### ISSUE THREAD

**Issue by photex** [prefix-dev/pixi#3542]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
channels = ["conda-forge"]
name = "dyld_test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]

[activation.env]
DYLD_LIBRARY_PATH="$CONDA_PREFIX/lib"
LD_LIBRARY_PATH="$CONDA_PREFIX/lib"
```

```shell
chipc@Chips-MacBook-Pro dyld_test % pixi shell

(dyld_test) chipc@Chips-MacBook-Pro dyld_test % printenv | grep LD
OLDPWD=/Users/chipc/workspaces/dyld_test
LD_LIBRARY_PATH=/Users/chipc/workspaces/dyld_test/.pixi/envs/default/lib
```

### Issue description

It would be ideal if the pixi environment could help the Macos dynamic linker find things I'm linking with.

### Expected behavior

I'd expect any variable to be assignable. I don't know if this is a pixi issue or just the default macos zsh setup that prevents this from being set.
