### ISSUE TITLE
Include conda (or conda-lock) environment file(s) dynamically in manifest

### ISSUE THREAD

**Issue by jamesmyatt** [prefix-dev/pixi#3556]
### Problem description

`pixi init --from environment.yml` enables you to _convert_ an existing conda (or conda-lock) environment file into a `pixi.toml` file. However, this implies a one-time conversion from conda to pixi.

It would be nice to be able to import an environment yml file into a pixi manifest dynamically, so that a user can choose to use pixi in place of conda to manage their local environments on a project that uses conda environment yml files.

For example, in `pixi.toml`:

```toml
[project]
include = {conda-env="environment.yml"}

[feature.dev]
include = {conda-env="dev-environment.yml"}

[environments]
default = { features = ["dev"] }
```
