### ISSUE TITLE
Subdir in match spec is ignored

### ISSUE THREAD

**Issue by jonashaag** [prefix-dev/pixi#356]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
pixi add conda-forge/osx-arm64::clickhouse-connect
```

### Issue description

```
pixi add conda-forge/osx-arm64::clickhouse-connect
```

will install the package from `noarch`:

```
- name: clickhouse-connect
  version: 0.6.14
  manager: conda
  platform: osx-arm64
  dependencies:
    certifi: '*'
    importlib_metadata: '*'
    lz4: '*'
    python: '>=3.7'
    pytz: '*'
    urllib3: '>=1.26'
    zstandard: '*'
  url: https://conda.anaconda.org/conda-forge/noarch/clickhouse-connect-0.6.14-pyhd8ed1ab_0.conda
```

### Expected behavior

Should install from osx-arm64 or fail if not found
