### ISSUE TITLE
Platform change in pixi.toml not taken into account when solving

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#3568]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

There is a slight bug where platforms from an existing pixi.lock are somehow picked up, even if the platform is already removed from the `pixi.toml`.

For example, first:

```toml
[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
name = "solvf"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[target.linux-64.dependencies]
numpy = "2.*"
```

Will generate an appropriate lockfile.

Then exchange numpy for a version that does not exist (e.g. `4.*`) AND remove `linux-64`.

```toml
[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
name = "solvf"
platforms = ["osx-arm64"] # , "linux-64"]
version = "0.1.0"

[target.linux-64.dependencies]
numpy = "4.*"
```

### Issue description

Now we first get a warning about `linux-64` not being part of the platforms, but also a solver error about `numpy 4` not existing.
For some reason, it seems that pixi tries to resolve for platforms in the lockfile even though it's not necessary anymore.

![Image](https://github.com/user-attachments/assets/972ed853-a23d-4bc4-a61f-b47c61b7bd07)

### Expected behavior

Remove linux-64 and do not attempt to solve for it.
