### ISSUE TITLE
Missing libglib-2.0.0.dylib, libgobject-2.0.0.dylib, libgio-2.0.0.dylib, and libaravis-0.8.0.dylib When Using GI Repository Modules Outside Pixi on macOS

### ISSUE THREAD

**Issue by leila-ayad** [prefix-dev/pixi#3577]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

First I install gobject-introspection and aravis with brew. I do this because there is no pixi build available for aravis, and gobject-introspection is an aravis dependency. 

```shell
brew install gobject-introspection
brew install aravis

```

Then I try to install my other dependencies with pixi install. Here is `pixi.toml`
```toml
[project]
authors = ["Leila <leila.alhemali@gmail.com>"]
channels = ["conda-forge"]
description = "USB3 version of the laser server"
name = "laser-server-ft-aravis"
platforms = ["osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
libjpeg-turbo = ">=3.0.0,<4"
libusb = ">=1.0.27,<2"
libpng = ">=1.6.44,<2"
llvm-openmp = ">=19.1.0,<20"
python = "3.9.*"
pillow = ">=10.4.0,<11"
numpy = ">=2.0.2,<3"
scikit-image = ">=0.24.0,<0.25"

[pypi-dependencies]
pygobject = ">=3.50.0, <4"


### Issue description

Hi there 👋

I’m encountering a shared library error when trying to use gi.repository modules (specifically Aravis) from a Python project running inside a Pixi-managed environment on macOS.

I'm not installing Aravis or gobject-introspection via Pixi — Aravis doesn’t have a Pixi build, and gobject-introspection is a dependency of Aravis. Until recently, this setup worked fine. But now I'm seeing the following errors: 

```bash
GLib-GIRepository-WARNING **: Failed to load shared library 'libgobject-2.0.0.dylib'...
GLib-GIRepository-WARNING **: Failed to load shared library 'libglib-2.0.0.dylib'...

gi._error.GError: gi-invoke-error-quark: Could not locate g_option_error_quark: dlopen(libglib-2.0.0.dylib, 0x0009): tried: ...
```

It looks like the dynamic libraries aren’t being found by the environment. Some of the attempted paths include:

`/System/Volumes/Preboot/Cryptexes/OSlibglib-2.0.0.dylib`

`.pixi/envs/default/lib/libglib-2.0.0.dylib`

`/usr/lib/libglib-2.0.0.dylib`

This same code used to run fine. I'm on macOS, and haven’t tested this setup on Linux yet.

###Temporary Solution

I was able to resolve the issue by manually creating symlinks to the necessary dynamic libraries:

```bash
ln -s /opt/homebrew/lib/libglib-2.0.0.dylib .pixi/envs/default/lib/
ln -s /opt/homebrew/lib/libgobject-2.0.0.dylib .pixi/envs/default/lib/
ln -s /opt/homebrew/lib/libgio-2.0.0.dylib .pixi/envs/default/lib/
ln -s /opt/homebrew/lib/libaravis-0.8.0.dylib .pixi/envs/default/lib/
```

This works, but it feels a bit brittle, and I wanted to check if there's a more idiomatic solution using Pixi's environment configuration.

Thanks again for the amazing work on Pixi — happy to provide more info if needed!

— Leila

### Expected behavior

Pixi should automatically detect and use the necessary `.dylib` files (such as `libgobject-2.0.0.dylib`, `libglib-2.0.0.dylib`, `libgio-2.0.0.dylib`, and `libaravis-0.8.0.dylib`) when installed via Homebrew. This would allow Pixi to function without requiring manual intervention (e.g., creating symlinks) for the required shared libraries. Pixi should be able to find these libraries in their default Homebrew installation locations or use the appropriate environment paths for them.
