### ISSUE TITLE
DYLD_LIBRARY_PATH should be updated with pixi path

### ISSUE THREAD

**Issue by zhuoqiang** [prefix-dev/pixi#3584]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

build some binary in mac os that depends on python using pixi and then run the binary

```shell
pixi add python
pixi r make
pixi r some-binary-depends-on-python
```

it will output error:

```shell
dyld[97647]: Library not loaded: @rpath/libpython3.12.dylib
```

### Issue description

update the env manually could fix the issue

```toml
[project]
channels = ["conda-forge"]
name = "abc"
platforms = ["osx-arm64"]

[dependencies]
python = "==3.12.10"

[tasks]
xmake = {cmd="xmake", env={DYLD_LIBRARY_PATH="$PIXI_PROJECT_ROOT/.pixi/envs/default/lib:$DYLD_LIBRARY_PATH"}}
```

### Expected behavior

pixi run command should setup `DYLD_LIBRARY_PATH` prepended with `$PIXI_PROJECT_ROOT/.pixi/envs/default/lib` automatically, just as PATH env variable
