### ISSUE TITLE
`pixi auth` struggles

### ISSUE THREAD

**Issue by MartinJepsen** [prefix-dev/pixi#3585]
I was originally going to put this as a comment on #2177, but I think it might be it's own issue. Not sure if bug, feature request or if I missed something in the docs.

At my workplace, we have a private conda channel on Artifactory which uses basic HTTP (user + password) auth.

I can connect to the channel with

```
https://majp%40ramboll.com:********@artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools
```

by putting it in `pyproject.toml` under `[tool.pixi.workspace.channels]`, like so:

```toml
# pyproject.toml
[tool.pixi.workspace]
channels = [
    "conda-forge",
    "https://majp%40ramboll.com:********@artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools",
]
```

This has the following drawbacks:

* The credentials are part of the version control history (git) for anyone to see
* I could put them in a `.gitignore`'d config file, but that would require me to do the same for all projects, of which I have many (10-15 projects).

As a solution, I thought I'd try to use [mirrors](https://pixi.sh/dev/reference/pixi_configuration/#mirror-configuration) to redirect requests for `artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools` to the basic auth form of the channel URL.

According to the docs:

> The implementation will look for the mirror key (a URL) in the mirrors section of the configuration file and replace the original URL with the mirror URL.

So as I understand it, pixi will simply recognize that I'm trying to send a request to that channel and replace the URL. Here's my attempt of (ab)using this to store my credentials in a single place:

```toml
# pyproject.toml
[tool.pixi.workspace]
channels = [
    "conda-forge",
    "https://artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools",
]
```

```toml
# ~/.pixi/config.toml
default-channels = [
    "conda-forge",
    "https://artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools",
]

[mirrors]
"https://conda.anaconda.org/conda-forge" = ["https://prefix.dev/conda-forge"]
# Redirect to use the URL that includes my credentials
"https://artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools" = [
    "https://majp%40ramboll.com:********@artifactory.ramboll.com/artifactory/api/conda/renopexconda-pytools"
]
```

However, this causes a 401 Not authorized, regardless of whether I try to install something global or project-specific.

Note also that in [#2177](https://github.com/prefix-dev/pixi/issues/2177#issuecomment-2392872040), I highlighted that using another credential store (keyring or rattler-build creds) doesn't work.
