### ISSUE TITLE
Building PyPI packages fails with native-tls: (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by mgorny** [prefix-dev/pixi#3587]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
name = "test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "*"

[pypi-dependencies]
build = { git = "https://github.com/mgorny/build", branch = "variant-deps" }

[tasks]
test = ""
```

```console
$ pixi run test
Error:   × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ Failed to download and build `build @ git+https://github.com/mgorny/build@variant-deps`
  ├─▶ Failed to resolve requirements from `build-system.requires`
  ├─▶ No solution found when resolving: `flit-core>=3.8`
  ├─▶ Failed to fetch: `https://pypi.org/simple/flit-core/`
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://pypi.org/simple/flit-core/)
  ├─▶ client error (Connect)
  ├─▶ error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../openssl-3.5.0/ssl/statem/
  │   statem_clnt.c:2106: (unable to get local issuer certificate)
  ╰─▶ error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../openssl-3.5.0/ssl/statem/
      statem_clnt.c:2106:
```

### Issue description

pixi 0.45.0 seems unable to build a PyPI dependency when it is built with `native-tls` feature <del>(I haven't tested `rustls`)</del>. My guess is that it does not use system certificate store correctly somehow. I've tested with OpenSSL 3.5.0 and 3.3.3 (rebuilding pixi after reinstalling OpenSSL).

The problem doesn't seem to affect installing packages from Conda-forge. Other tools using OpenSSL, such as `wget` or Python, have no problem accessing `https://pypi.org/simple/flit-core/`.

### Expected behavior

Working TLS.
