### ISSUE TITLE
tox-pixi similiar to tox-conda

### ISSUE THREAD

**Issue by ReimarBauer** [prefix-dev/pixi#3641]
### Problem description

Are there any plans to integrate something like this with Pixi?
https://github.com/tox-dev/tox-conda

I’d like to use all available Python versions in isolation within our test bench to confirm we have true compatibility. Or is there a better way to approach this?

**Comment by bollwyvl** [comment]
A couple of approaches already work for this, provided a project is willing to do a couple enumerations.

Parametrized [depends-on](https://pixi.sh/latest/workspace/advanced_tasks/#passing-arguments-to-dependent-tasks) are _basically_ up to this already, at worst requiring three novel lines per `{env x task}` excursion, with the lovely side-effect of the cross-platform versions of everything captured in the lockfile:

```toml
[tasks]
test = {cmd = "pytest", inputs = ["tests"]}
test-all = {depends-on = [
  {task="test", environment="py39"}, 
  {task="test", environment="py313"},
]}

[feature]
test.dependencies.pytest = "*"
py39.dependencies.python = "3.9.*"
py313.dependencies.python = "3.13.*"

[environments]
py39 = ["test", "py39"]
py313 = ["test", "py313"]
```

This would halt on the _first_ failing env, which might not be desirable, and would require some trickery to get _run all of the tests, and summarize the fails_.

For _libraries_, getting the _`pip-or-conda` roulette_ of `tox` feature with some `pixi`-in-`pixi` might actually be worth capturing as a test:

```toml
[tasks]
test-roulette = """
  rm -rf .pixi/ pixi.lock 
  && pixi lock
  && git diff pixi.lock 
  && pixi run test-all
"""
```

Some proposed syntax would make this slightly more terse to get to "single command with no extra lines or runtime re-work":

- #3533 (already under way on #3638) 
  - would make it easier to use file-based "receipts" in `outputs`
- #3539 would save a few duplicated lines
  ```toml
  depends-on = [{task="test", environment=["py39", "py313"]}]
  ```
