### ISSUE TITLE
pixi build - pointing to recipe.yaml always rebuilds

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#3682]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

When pointing to a folder that contains a recipe.yaml everything is fine because the lockfile says:

```
      - conda: ./recipe
...
- conda: ./recipe/recipe.yaml
  name: with-variants
  version: 0.1.0
  build: py310hd06803d_0
  subdir: osx-arm64
  depends:
  - python_abi 3.10.* *_cp310
  input:
    hash: '0000000000000000000000000000000000000000000000000000000000000000'
    globs:
    - recipe.yaml
```

However, when pointing to a `recipe.yaml` _directly_ then the lockfile will say:

```
      - conda: ./recipe/recipe.yaml <- note the extra `recipe.yaml` here!
...
    globs:
    - recipe.yaml
```

Which will cause it to always rebuild. Maybe the `globs` in this case should say `../recipe.yaml`? Or maybe we should find that if it's a file, we resolve to the parent directory?

### Issue description

Pixi rebuilds the recipe every time.

### Expected behavior

Not rebuild everytime.
