### ISSUE TITLE
pixi build - variants + recipe.yaml gives an error: Error: expected the build backend to return a single built package but it returned 2

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#3683]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "build-recipe"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[workspace.build-variants]
python = ["3.10.*", "3.11.*"]

[dependencies]
with-variants = { path = "./recipe" }
python = "3.10.*"
```

And 

```yaml
package:
  name: with-variants
  version: 0.1.0

requirements:
  host:
    - python
```

### Issue description

Error:   × expected the build backend to return a single built package but it returned 2

This should not be the case - we should only build the `python 3.10` package in this case and not error like this.

### Expected behavior

Build only a single package and not complain / error.
