### ISSUE TITLE
Editable dep on poetry pyproject.toml with editable dep succeeds once, then crashes after

### ISSUE THREAD

**Issue by gene-maniro** [prefix-dev/pixi#3687]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Both `__init__.py` files are empty.
```
~/delme$ tree
.
├── foo
│   ├── pyproject.toml
│   └── src
│       └── foo
│           └── __init__.py
├── my-dep
│   ├── pyproject.toml
│   └── src
│       └── my_dep
│           └── __init__.py
├── pixi.lock
└── pixi.toml

7 directories, 6 files
```

`pixi.toml`
```
[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "delme"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-dependencies]
my-dep = { path = "./my-dep", editable = true }

[dependencies]
python = ">=3.13.3,<3.14"
```

`my-dep` `pyproject.toml`
```
[tool.poetry]
name = "my-dep"
version = "0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
foo = { path = "../foo", develop = true }
```

`foo` `pyproject.toml`
```
[tool.poetry]
name = "foo"
version = "0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Issue description

See https://discord.com/channels/1082332781146800168/1365025446374281298/1365025446374281298 @Hofer-Julian 

After the first, successful run of any pixi command, all subsequent pixi commands fail with:
```shell
pixi run python

thread 'main2' panicked at crates/pixi_uv_conversions/src/requirements.rs:246:30:
cannot get extension: MissingExtensionPath("/home/gene/delme/foo", Dist)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at src/main.rs:49:10:
Tokio executor failed, was there a panic?: Any { .. }
```

### Expected behavior

Subsequent pixi commands succeed, just like the first.

**Comment by Hofer-Julian** [comment]
I was able to reproduce this on my machine.
First command works, all subsequent fail.

Here is the git repo: https://github.com/Hofer-Julian/editable-poetry

**Comment by gene-maniro** [comment]
Manually changing this section in `pixi.lock` from:
```
- pypi: ./my-dep
  name: my-dep
  version: 0.1.0
  sha256: de9ac4b45d87b172a6eea5047b386de22ed079ce456178a38250ceaf5fb81a26
  requires_dist:
  - foo @ file:///home/gene/delme/foo
  editable: true
```

to (removing the `file` version spec)

```
- pypi: ./my-dep
  name: my-dep
  version: 0.1.0
  sha256: de9ac4b45d87b172a6eea5047b386de22ed079ce456178a38250ceaf5fb81a26
  requires_dist:
  - foo
  editable: true
```

lets pixi commands work again
