### ISSUE TITLE
Target specific build/host/run dependencies for packages

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#3706]
### Problem description

While converting `pixi` to build itself as a package, I'm unable to do this due to requiring different packages when building for different platforms. 

I'm expecting something like the target specific tables, e.g.:
```toml
[package.target.linux-64.host-dependencies]
compilers = "*"

[package.target.win.build-dependencies]
vs2017_win-64 = ">=19.16.27033"
```
