### ISSUE TITLE
ssh passphrase prompt not showing when installing ssh dependency

### ISSUE THREAD

**Issue by Ehab-Ibrahim** [prefix-dev/pixi#3709]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

pyproject:
```toml
# pyproject.toml
[project]
name = "foo"
# Add a dependency using SSH URL
dependencies = [
  "pytest @ git+ssh://git@github.com:pytest-dev/pytest.git",
]
```

Bash:
```shell
# Using a git SSH key with a passphrase
# Make sure the SSH key is not added to your ssh-agent
pixi install
```

### Issue description

Currently, I use an ssh key with a passphrase for Github. When installing a dependency using `ssh`, the prompt to enter a passphrase is not shown, and the environment installation appears to be stuck:

![Image](https://github.com/user-attachments/assets/778f96c5-7dfc-4eb5-aa33-81213f973733)

However, if at this point I enter my passphrase and press "Enter", then the environment installation resumes.

### Expected behavior

It would be helpful to show a prompt that a passphrase is needed when running into this case:

![Image](https://github.com/user-attachments/assets/ba28b1eb-e086-45b8-88fb-bc7186e5763e)
