### ISSUE TITLE
Not running depends-on task in different environment

### ISSUE THREAD

**Issue by maurosilber** [prefix-dev/pixi#3715]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]
requires-pixi = ">=0.45"

[environments]
python = ["python"]
rust = ["rust"]

[feature.rust.tasks.build]
cmd = "echo Building"

[feature.python.tasks]
depends-on = [{ task = "build", environment = "rust" }]
hello = "echo Hello"
```

```sh
❯ pixi run hello 
✨ Pixi task (hello in python): echo Hello
Hello
```

### Issue description

It is not running the `depends-on` task from the other environment.

Also, it triggers a panic if I remove the inline table and write:

```toml
[feature.python.tasks]
depends-on = ["build"]
hello = "echo Hello"
```

```sh
thread 'main2' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/toml-span-0.4.1/src/value.rs:40:27:
the value has already been taken
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at src/main.rs:49:10:
Tokio executor failed, was there a panic?: Any { .. }
```

But it runs (without running the `depends-on` task) if I write:

```toml
[feature.python.tasks]
depends-on = [{ task = "build" }]  # without environment
hello = "echo Hello"
```

```sh
❯ pixi run hello 
✨ Pixi task (hello in python): echo Hello
Hello
```

### Expected behavior

```sh
❯ pixi run hello 
✨ Pixi task (build in rust): echo Building
Building

✨ Pixi task (hello in python): echo Hello
Hello
```

**Comment by maurosilber** [comment]
Sorry, I just realized that I was mixing the ways to define a task.
```toml
[feature.python.tasks]
depends-on = ["build"]
hello = "echo Hello"
```
should have been:
```toml
[feature.python.tasks.hello]
depends-on = ["build"]
cmd = "echo Hello"
```
or:
```toml
[feature.python.tasks]
hello = "echo Hello"
```
