### ISSUE TITLE
Pixi dependency resolution is dependent on the dependencies order for some platforms

### ISSUE THREAD

**Issue by linuxrider** [prefix-dev/pixi#3727]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
channels = ["conda-forge"]
name = "envtest"
platforms = ["linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = "*"
python = "*"
```

results in unexpected python versions for `linux-64` platform:
```shell
pixi init --platform win-64 --platform linux-64 envtest
cd envtest
pixi add numpy=* python=*
```
works as expected:
```shell
pixi init --platform win-64 --platform linux-64 envtest
cd envtest
pixi add python=* numpy=* 
```

### Issue description

This `pixi.toml` resolves to python version `3.13.x` for `win-64` but to `3.12.x` for `linux-64` and `osx-64`.
Defining `python = ">=3.13"` version `3.13.x` is installed for all platforms. The dependency resolution seems to depend on the order of the dependencies but only for `linux-64` and `osx-64`.

### Expected behavior

I would expect resolution to 3.13.x for all platforms independent of the order of dependencies.
