### ISSUE TITLE
Pixi panics on wrong task schema

### ISSUE THREAD

**Issue by maurosilber** [prefix-dev/pixi#3729]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[tasks]
hello = "echo Hello"
inputs = ["pixi.toml"]
```

(note that `hello =` should be `cmd =`, and `tasks` should be `tasks.hello`)

```shell
❯ pixi run hello                                                                                 

thread 'main2' panicked at /Users/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/toml-span-0.4.1/src/value.rs:40:27:
the value has already been taken
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'main' panicked at src/main.rs:49:10:
Tokio executor failed, was there a panic?: Any { .. }
```

### Issue description

It panics when using the wrong schema for tasks.

### Expected behavior

Show a more actionable diagnostic?

I recently opened an issue (#3715)  due to misdiagnosing this.
