### ISSUE TITLE
No description added to task alias (CLI)

### ISSUE THREAD

**Issue by pya** [prefix-dev/pixi#3742]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Add two tasks (one with and one without description) and one task alias with a description:

```shell
pixi task add --description="Create a PDF" build-my-pdf "make pdf"
pixi task add  make-index "make index"
pixi task alias --description="Create PDF with index" build-full make-index build-my-pdf
```

Adds these lines to the manifest:

```toml
build-my-pdf = { cmd = "make pdf", description = "Create a PDF" }
make-index = { cmd = "make index" }
build-full = [{ task = "make-index" }, { task = "build-my-pdf" }]
```

Listing the tasks shows the task with description but the task alias has no description:

```shell
pixi task list
Tasks that can run on this machine:
-----------------------------------
build-full, build-my-pdf, make-index

 - build-my-pdf    Create a PDF
```

### Issue description

Adding a task alias with a description via the CLI echos back that the alias created with description. But the description is not added to the mainfest and not show with `pixi task list.`

### Expected behavior

The task alias should have a description that is added to the manifest and displayed with `pixi task list`.
