### ISSUE TITLE
Provide `post-task` Capability

### ISSUE THREAD

**Issue by phreed** [prefix-dev/pixi#3743]
### Problem description

I would like to see an alternative to the https://pixi.sh/latest/reference/pixi_configuration/#run-post-link-scripts behavior.
Setting this behavior on a project presents a security risk and limited capability.
I would rather have a `post-task` associated with a dependency. These tasks would be normal pixi tasks.
Such tasks could run post-link scripts included in a package (or any other script). The task should be run with an additional environment variable (e.g., PKG_DIR)  referring to the recently installed package. 

Security would be improved as it puts control of tasks under the direct control of the writer of the `pixi.toml`,
who can decide which packages can be trusted, and how much trust to allot.
The `pixi.toml` writer could decide to run the `pixi` task's script in an appropriate sandbox.
The ability to run tasks in a `sandbox` mode is (as I understand it) on the roadmap.
It currently possible to wrap the script with a sand-boxing tool like [firejail](https://github.com/netblue30/firejail) .

Here is a sample of the kind of user facing changes to the 
manifest dependencies, https://pixi.sh/latest/reference/pixi_manifest/#dependencies, and 
tasks, https://pixi.sh/latest/reference/pixi_manifest/#the-tasks-table:

```toml
[dependencies]
python = ">3.9,<=3.11"
rust = "==1.72"
pytorch-cpu = { version = "~=1.1", channel = "pytorch", post-task = "post-link" }

[feature.linux.task.post-link]
cmd = ["firejail", "post-link.sh"]
cwd = "$PKG_DIR"
```

Currently `firejail` does not have a conda package.
