### ISSUE TITLE
Task that depends on multiple parametrized tasks does not use the task cache

### ISSUE THREAD

**Issue by maurosilber** [prefix-dev/pixi#3758]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[tasks.create]
args = ["file"]
cmd = "touch {{ file }}"
outputs = ["{{ file }}"]

[tasks.single]
depends-on = [
    { task = "create", args = ["single.txt"] }
]

[tasks.multiple]
depends-on = [
    { task = "create", args = ["A.txt"] },
    { task = "create", args = ["B.txt"] }
]

[tasks.create1]
cmd = "touch 1.txt"
outputs = ["1.txt"]

[tasks.create2]
cmd = "touch 2.txt"
outputs = ["2.txt"]

[tasks.create-all]
depends-on = ["create1", "create2"]
```

Running a task that depends on multiple parametrized tasks does not use the task cache:

```shell
❯ pixi run multiple 
✨ Pixi task (create): touch A.txt

✨ Pixi task (create): touch B.txt

❯ pixi run multiple
✨ Pixi task (create): touch A.txt

✨ Pixi task (create): touch B.txt
```

If it depends on a single task, it works:

```shell
❯ pixi run single
✨ Pixi task (create): touch single.txt

❯ pixi run single
✨ Pixi task (create): touch single.txt
Task 'create' can be skipped (cache hit) 🚀
```

Or multiple non-parametrized tasks:

```shell
❯ pixi run create-all
✨ Pixi task (create1): touch 1.txt

✨ Pixi task (create2): touch 2.txt

❯ pixi run create-all
✨ Pixi task (create1): touch 1.txt
Task 'create1' can be skipped (cache hit) 🚀

✨ Pixi task (create2): touch 2.txt
Task 'create2' can be skipped (cache hit) 🚀
```

### Issue description

Running a task that depends on multiple parametrized tasks does not use the task cache.

### Expected behavior

That it uses the task cache.
