### ISSUE TITLE
Expose rattler-build's `--up-to` parameter in pixi manifests

### ISSUE THREAD

**Issue by stanmart** [prefix-dev/pixi#3765]
### Problem description

I love that the new pixi build feature allows me to simply point to conda recipes in git repos in my manifests. However, some recipes include multiple outputs (e.g., core and extras), and it would be great if I did not have to build all of them when I only need earlier ones (the later ones might take long to build, or have extra dependencies that might be problematic).

rattler-build has the `--up-to` flag which let's me do this rather nicely. Would it be possible to expose this flag also in the dependencies section of `pixi.toml`? I'm thinking of something like

```toml
[dependencies]
"my-package.core" = { git = "...", subdirectory = "conda.recipe", up-to = "my-package.core" }
```
