### ISSUE TITLE
Workspace inheritance only works if the package is defined in the same `pixi.toml`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3766]
This works as expected.
Even though, neither `package.name` nor `package.version` is defined, `pixi install` runs just fine.

```toml
[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
preview = [
    "pixi-build",
]
platforms = [
    "linux-64",
]
name = "test_build_conda_package"
version = "1.0.0"

[dependencies.test_build_conda_package]
path = "package"

[package.build.backend]
name = "pixi-build-rattler-build"
version = "0.1.*"

[package.build.configuration]
debug-dir = "/var/home/julian/Projekte/github.com/prefix-dev/pixi-1/pytest-temp/popen-gw0/test_build_conda_package0"
```

However, if I split `workspace` and `package` into two `pixi.toml`, `package.name` and `package.version` is required. My expectation was that workspace inheritance works independently of where the package is defined. Tag @baszalmstra to make sure whether that was indeed the intention
