### ISSUE TITLE
Configure used cmake compiler

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#3783]
Currently the cmake build backend always selects the \`cpp\` compiler. When we want to use CUDA we also need to add `${{ compiler("cuda") }}`. <br><br>We want to keep using a sane default ("cpp", or magic in the future) but if the user explicitly configure it, it should also be possible to overwrite this behavior:

```toml
[package.build.configuration]
compilers = ["cpp"] # If not specified this will be the default
compilers = ["cpp", "cuda"]
```
