### ISSUE TITLE
Weird behavior when using packages that overwrite each other

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#379]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "test-opt"
version = "0.1.0"
description = ""
authors = [""]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
opt-einsum = "3.0.0.*"
opt_einsum = "3.3.0.*"
```

`open .pixi/env/lib/python3.12/site-packages`

![image](https://github.com/prefix-dev/pixi/assets/29506042/c65ef919-65b2-4e38-bbca-cb2369bf95cc)

### Issue description

The `opt_einsum` directory gets written to by both `opt_einsum` and `opt-einsum` (which are two different versions).

### Expected behavior

pixi should crash here or print a warning at least.
