### ISSUE TITLE
Confusing/regressed error message: `command not found`

### ISSUE THREAD

**Issue by mfisher87** [prefix-dev/pixi#3792]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi run foo
foo: command not found

$ pixi --version
pixi 0.47.0
```

This error message occurs for me on Linux with the following `pixi.toml`:

```toml
[project]
authors = ["..."]
channels = ["conda-forge"]
name = "pixi-task-not-found"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
foo = "echo foo"

[dependencies]
```

### Issue description

The source of the error is that my platform is not specified. An error is expected. The actual message is the confusing part.

I also experienced this collaborating with Mac users when the `pixi.toml` was generated on my machine, so it only included the `linux-64` platform. Because the error message doesn't point out the actual problem, the missing platform, it can be confusing to resolve.

**In pixi 0.41.4, this message is much much much better!**

```shell
$ pixi run foo
Error: 
  × The current platform does not satisfy the minimal virtual package requirements
  ╰─▶ The project does not support 'linux-64'.
      Add it with 'pixi project platform add linux-64'.

$ pixi --version
pixi 0.41.4
```

### Expected behavior

Raise an error which clearly communicates the problem: My platform is not specified in the `pixi.toml`, and a pathway to resolve it. The pixi 0.41 behavior was perfect! :)
