### ISSUE TITLE
Allow target specific configuration for pixi build backend

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3800]
Build backends can be configured like this:

```toml
[package.build.configuration]
env = "blah"
```

It would be good to allow target specific configuration:

```toml
[package.build.configuration.target.osx-64]
env = "blah"
```

Combining multiple configurations should be done on the pixi-build-backend side
