### ISSUE TITLE
Pixi doesn't enforce that `depends-on` needs to be a list

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3814]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Create a Pixi manifest with a valid task `x` and an invalid task `y`.

```toml
[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "task-arg-test"
platforms = ["linux-64", "osx-arm64", "win-64"]

[tasks]
x = { depends-on = [{ task = "z" }] }
y = { depends-on = { task = "z" } }
```

### Issue description

If you run `pixi run x` it prints "hello" on the terminal
If you run `pixi run y` it gives no feedback. 

### Expected behavior

During manifest parsing, it should detect that `depends-on` needs to be a list and error if it isn't.
