### ISSUE TITLE
Proposal: Variables in the Manifest file

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#3835]
*Originally written by @Hofer-Julian in this [gist](https://gist.github.com/Hofer-Julian/399707042cada047074a079daa911406) but moving it here for visibility.*

# Variables in manifest

Goals:
- Avoid repeating values
- Make it easy to interact with a full tree of tasks

```toml
[vars]
profile = "--release"

[tasks.install]
cmd = "cargo install {{ profile }}"

[tasks.test]
depends-on = ["install"]
cmd = "cargo test {{ profile }}"
```

```bash
pixi run test
# Runs:
# cargo install --release
# cargo test --release

pixi run --var profile=--debug test
# Runs:
# cargo install --debug
# cargo test --debug
```

# Cross environments

```toml
[vars]
profile = "--release"

[tasks.install]
cmd = "cargo install {{ profile }}"

[feature.test.vars]
profile = "--debug"

[feature.test.tasks.test]
depends-on = ["install"]
cmd = "cargo test {{ profile }}"

[environments]
test = ["test"]
```

```bash
pixi run install
# Runs:
# cargo install --release

pixi run test
# Runs:
# cargo install --release
# cargo test --debug    

pixi run --environment test test
# Runs:
# cargo install --debug
# cargo test --debug

pixi run --var "profile=--profile" test
# Runs:
# cargo install --profile
# cargo test --profile
```

# Slightly adapted example

```toml
[vars]
profile = "--release"

[tasks.install]
cmd = "cargo install {{ profile }}"

[feature.test.vars]
profile = "--debug"

[feature.test.tasks.test]
depends-on = ["install"]
cmd = "cargo test {{ profile }}"

[environments]
test = { features= ["test"], no-default-feature = true }
```

```bash
pixi run install
# Runs:
# cargo install --release

pixi run test
# Runs:
# cargo install --release
# cargo test --debug    

pixi run --environment test test
# Task `install` doesn't exist in environment "test", so it will run in environment "default" instead.
# Runs:
# cargo install --debug
# cargo test --debug

pixi run --var "profile=--profile" test
# Runs:
# cargo install --profile
# cargo test --profile
```

# Merging vars

We need to take care when we merge vars.
The current behaviour is that, that the first feature wins:

```toml
[feature.test1.vars]
profile = "--debug"

[feature.test1.tasks]
start = "cargo test {{ profile }}"

[feature.test2.vars]
profile = "--release"

[envs]
test = ["test2", "test1"]
```
  
Running should behaves as follows:

```bash
$ pixi run start
cargo test --release
```

Keep in mind, that unless `no-default-feature=true`, the default feature is always implicitly appended:

```toml
test = ["test2", "test1", "default"]
