### ISSUE TITLE
Enable omitting certain dependencies from lockfile

### ISSUE THREAD

**Issue by jtroe** [prefix-dev/pixi#3839]
### Problem description

For my use case, I have an environment which includes the daily conda package build for my library.
```toml
[feature.daily.dependencies]
my-pkg = {version = ">=2,<3", channel = "https://my-daily-dev-build-rattler-index.com"}

[environments]
daily = { features = ["daily"] }
```

I would like to do something like this:
```toml
[feature.daily.dependencies]
my-pkg = {version = ">=2,<3", channel = "https://my-daily-dev-build-rattler-index.com", no-lock = true}

[environments]
daily = { features = ["daily"] }
```
Which should enable me to load the environment and get the latest build.

Currently, each user must run `pixi update -e daily my-pkg`, whcih then modifies the lockfile.  We aren't committing this change to the lockfile regularly, and I don't see the need to PR just this change (I could have a github action update it after the build is complete also and skip the PR, but that feels unneccesary also), I would like to omit the entry for this package from the lockfile and just take latest.

I am a newer user to pixi so if there is something sane I am missing, please let me know! Thank you!
