### ISSUE TITLE
Lock file of `multi-output` from `pixi-build-examples` is always out-of-date

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3863]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
git clone https://github.com/wolfv/pixi-build-examples.git
cd pixi-build-examples/multi-output
pixi install
pixi install
```

### Issue description

The lock file is always considered out-of-date.
That's probably a problem with depending directly on `recipe.yaml`.
This should have been fixed by https://github.com/prefix-dev/pixi-build-backends/pull/137, but I can still reproduce it with the latest `pixi-build-rattler-build` release.

### Expected behavior

Not relock all the time

**Comment by Hofer-Julian** [comment]
The reason is that the recipe outputs a package `foobar-desktop` that depends on `foobar`

```toml
[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "build-feedstock"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
foobar-desktop = { path = "./recipe" }
```

By manually adding foobar, pixi considers the lockfile up-to-date.

```toml
[workspace]
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "build-feedstock"
platforms = ["osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[dependencies]
foobar-desktop = { path = "./recipe" }
foobar = { path = "./recipe" }
```

This is the line to blame: <br><br>[https://github.com/prefix-dev/pixi/blob/942caf258fa661a0574e4d181d44022f7d113511/src/lock_file/satisfiability.rs#L1292-L1293](https://github.com/prefix-dev/pixi/blob/942caf258fa661a0574e4d181d44022f7d113511/src/lock_file/satisfiability.rs#L1292-L1293)

**Comment by baszalmstra** [comment]
If `foobar-desktop` depends on another output of the recipe (`foobar` ) then both `foobar` and `foobar-desktop` should be included in the lock-file and both should be build. <br><br>Only the outputs that are included in the lock-file (as dictated by the solve) should be build by the backend.

**Comment by Hofer-Julian** [comment]
My findings so far for this issue:<br><br>When checking satisfiability, we don't notice that `foobar` is a source dependency, which is why this code path is triggered: [https://github.com/prefix-dev/pixi/blob/942caf258fa661a0574e4d181d44022f7d113511/src/lock_file/satisfiability.rs#L1292-L1293](https://github.com/prefix-dev/pixi/blob/942caf258fa661a0574e4d181d44022f7d113511/src/lock_file/satisfiability.rs#L1292-L1293)<br><br>The reason for that is that while we correctly deduce that `foobar` is a dependency of `foobar-desktop`, it doesn't trigger that code path: [https://github.com/prefix-dev/pixi/blob/104461262e47a70cf76a9d1ff0604666c01465a3/src/lock_file/satisfiability/mod.rs#L1297](https://github.com/prefix-dev/pixi/blob/104461262e47a70cf76a9d1ff0604666c01465a3/src/lock_file/satisfiability/mod.rs#L1297)<br><br>It doesn't because the `SourceRecord` of `foobar-desktop` contains an empty `sources` dictionary, while this code expects this dictionary to contain the `{"foobar": source_spec}`.

**Comment by Hofer-Julian** [comment]
Looking at our doc example, I indeed find such an entry in the lock file:

```
- conda: .
  name: python_rich
  version: 0.1.0
  build: pyhbf21a9e_0
  subdir: noarch
  depends:
  - cpp_math
  - rich 13.9.*
  - python
  input:
    hash: 3faf7b3f59ceeac0af67d0681025dbfc847410eef0ed4649b6f03ceda554e007
    globs:
    - pixi.toml
  sources:
    cpp_math:
      path: packages/cpp_math
```

And indeed, `pixi-build-rattler-build` never returns sources: [https://github.com/prefix-dev/pixi-build-backends/blob/b816e8427da7f2aa723023e88b020350ac2d1a0c/crates/pixi-build-rattler-build/src/protocol.rs#L194](https://github.com/prefix-dev/pixi-build-backends/blob/b816e8427da7f2aa723023e88b020350ac2d1a0c/crates/pixi-build-rattler-build/src/protocol.rs#L194)<br><br>My impression is that `pixi-build-rattler-build`should return the correct sources and then this issue should be fixed
