### ISSUE TITLE
Add option to only use proxy for some domains

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#3865]
### Problem description

https://github.com/prefix-dev/pixi/pull/3320 allows you to specify a proxy and exclude some domains.
I think an option to specify a proxy _only_ for a couple of domains would also be nice.

Maybe also allow globs there?

something like

```toml
[proxy-config]
http = "http://proxy.com:8080"
https = "http://proxy.com:8080"
hosts = ["*.de"] # incompatible with `non-proxy-hosts`
```
