### ISSUE TITLE
Allow for dependency overrides

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/pixi#3890]
This comment: https://github.com/prefix-dev/pixi/issues/1417#issuecomment-2934964151 prompted me to create this issue.

For some use-cases it might make sense to override certain dependency constraints, uv does allow this but we do not expose. Guessing from the previous options we should do this on an feature level.

Something like:

```toml
[tool.pixi.pypi-options.dependency-overrides]
numpy = ">=3"
````

That overrides all constraints in that environment with that one.
