### ISSUE TITLE
Resolve-time python dependency for uv cross platform pypi resolving

### ISSUE THREAD

**Issue by gzm55** [prefix-dev/pixi#3897]
## Problem description

When cross platform resolving packages, a python dependency on **_the current platform_** is required for resolving pypi dependencies. This may block the resolving or make the `pixi.toml` hard to maintain. Can we add a temporary env on **_the current platform_** with only python dependency if `pixi` [cannot find](https://github.com/prefix-dev/pixi/blob/main/src/lock_file/update.rs#L1656) the python package. The packages in the temporary env (such as `__uv-python`)  should not be written into the `pixi.lock`.

### conda packages already works

```toml
platforms = [  "linux-64"  ]

[dependencies]
click = '*'
```

This can be locked on both linux-64 and osx-arm64.

### pypi packages do not works.

```toml
platforms = [  "linux-64"  ]

[dependencies]
python = '*'

[pypi-dependencies]
click = '*'
```

This can be locked on linux-64, but fail to lock on osx-arm64, error message:

```bash
✦ ❯ pixi lock
Error:   × Unable to solve pypi dependencies for the default environment — no compatible Python interpreter for 'osx-arm64'
  help: Try: pixi workspace platform add osx-arm64
```

We cannot add osx-arm64 platform since some pypi dependencies can only be resolved on linux-64.

### a workaround

```toml
platforms = [
  "linux-64",
  "linux-aarch64",
  "osx-arm64",
  ]

[dependencies]
python ='*'

[target.linux-64.pypi-dependencies]
click = '*'
[target.linux-aarch64.pypi-dependencies]
click = '*'
```

This can also be locked on osx-arm64. But multiple _real_ target platforms make the toml hard to maintain. Also all the resolve-time platforms have to be list in toml and locked to `pixi.lock` which are all unnecessary after resolving work.

**Comment by nichmor** [comment]
hey!

Could you please give me more details regarding this issue?
I'm on osx-arm64, I can `pixi install` this toml and produce a lockfile:
```
[workspace]
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
name = "boltons"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = '*'

[pypi-dependencies]
click = '*'
```

Do you mean that you would like to skip specifying `python` here, so it will automatically pick up the right Python?

**Comment by gzm55** [comment]
> hey!
> 
> Could you please give me more details regarding this issue? I'm on osx-arm64, I can `pixi install` this toml and produce a lockfile:
> 
> ```
> [workspace]
> authors = ["nichmor <nmorkotilo@gmail.com>"]
> channels = ["conda-forge"]
> name = "boltons"
> platforms = ["osx-arm64", "linux-64"]
> version = "0.1.0"
> 
> [tasks]
> 
> [dependencies]
> python = '*'
> 
> [pypi-dependencies]
> click = '*'
> ```
> 
> Do you mean that you would like to skip specifying `python` here, so it will automatically pick up the right Python?

hi, @nichmor this is a pixi.toml to reproduce the error on osx.

```toml
[workspace]
authors = []
channels = ["conda-forge"]
name = "test-uv"
platforms = ["linux-64"]

[dependencies]
python = '*'

[pypi-dependencies]
click = '*'
```

Error message
```bash
Error:   × Unable to solve pypi dependencies for the default environment — no compatible Python interpreter for 'osx-arm64'
  help: Try: pixi workspace platform add osx-arm64
```
