### ISSUE TITLE
could not find pixi.toml or pyproject.toml at directory even if it exists

### ISSUE THREAD

**Issue by tabedzki** [prefix-dev/pixi#3898]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
mkdir -p test_pixi
cd test_pixi
uv init
pixi a python
```

```
user@hostname:~/code/test-pixi$ uv init
Initialized project `test-pixi`
user@hostname:~/code/test-pixi$ pixi a python
Error:   × could not find pixi.toml or pyproject.toml at directory /home/user/code/test-pixi

user@hostname:~/code/test-pixi$ ls -a
.  ..  main.py  pyproject.toml  .python-version  README.md
```

`pyproject.toml`
```toml
[project]
name = "test-pixi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
```

### Issue description

Currently, when running `pixi init` with a new `pyproject.toml` that exists from `uv init`, `pixi` does not recognize the `pyproject.toml` even though it exists. I have to do `pixi init` to fix it.

### Expected behavior

user@hostname:~/code/fts-cupy-conda$ pixi a python
✔ Added python >=3.13.3,<3.14
