### ISSUE TITLE
wildcard conda deps should be compatible with transitive constraints of PyPI deps

### ISSUE THREAD

**Issue by function2-llx** [prefix-dev/pixi#3914]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Enter an empty directory, create the `pixi.toml` and `pyproject.toml` following the structure:

```tree
.
├── pixi.toml
└── pyproject.toml
```

The files content are as follows:

### pixi.toml

```toml
[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
numpy = "*"

[pypi-dependencies]
pypi-test = {path = "."}
```

### pyproject.toml

```toml
[project]
name = "pypi-test"
version = "0.1.0"

dependencies = [
    "numpy<2"
]
```

Then, execute `pixi.lock`, and pixi (version 0.48.0) will complain that the project depends on both numpy < 2 and == 2.2.6 (current latest version).

```
Error:   × failed to solve the pypi requirements of 'default' 'linux-64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because pypi-test==0.1.0 depends on numpy<2 and numpy==2.2.6, we can conclude that pypi-test==0.1.0 cannot be used.
      And because only pypi-test==0.1.0 is available and you require pypi-test, we can conclude that your requirements are unsatisfiable.
```

### Issue description

The issue can be reproduced with pixi 0.48.0 in the following situation: 

- there's a package named A listed the [dependencies] section with wildcard
- there's another package named B listed in [pypi-dependencies]
- A is configured as a dependency in B with version constraint

### Expected behavior

The version constraint should be compatible.
