### ISSUE TITLE
bug: lock file not up-to date even after fresh update (w/ cuda system dependency)

### ISSUE THREAD

**Issue by geoHeil** [prefix-dev/pixi#3915]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

- pixi 0.48

Given a pyprojet toml like

```toml
[project]
name = "foo"
version = "1.0.0"
description = "bar"
authors = [{ name = "name", email = "name@mail.com" }]
requires-python = "~= 3.13"

[tool.pixi.project]
platforms = ["linux-64", "osx-arm64"]
channels = ["conda-forge"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.environments]
dev = { features = [
  "my-location",
  "something-else"

], solve-group = "default" }
dev-gpu = { features = [
  "my-location",
  "something-gpu",
  "something-else"

], solve-group = "default" }
# ], solve-group = "dev-gpu", no-default-feature = true }
something-else = { features = [
  "something-else",
], solve-group = "default" }

[tool.pixi.feature.something-else.pypi-dependencies]
dagster-webserver = ">=1.10.0,<1.11"

[tool.pixi.feature.my-location.dependencies]
pypdf = "~=5.4.0"

[tool.pixi.feature.something-gpu]
platforms = ["linux-64", "win-64"]
system-requirements = { cuda = "12.6" }

# [tool.pixi.feature.my-location.target.linux-64.dependencies]
# flash-attn = "~=2.7.4"
```

and executing:

```bash
pixi update
pixi install -e dev --locked

# this can only install on linux -> see the platform selector
# pixi install -e dev-gpu --locked
```

> NOTICE the real environment would then install additional packages to the linux target - see the example below
> ```toml
> [tool.pixi.feature.my-location.target.linux-64.dependencies]
> flash-attn = "~=2.7.4"
> ```

### observations
I observe the following

#### on osx

```
Error:   × lock-file not up-to-date with the workspace
```

#### on linux

- the server:  It works fine
- the github actions Dockerfile - it fails just like osx (though it stil is x86)

### Issue description

- I want to mix gpu/non gpu dependencies and lock together
- I want to mix osx/linux and lock together

### Expected behavior

- I want to be able to execute the locking on either side; especially if the GPU code is so simple as in this example here
- Especially if some environment is not even included on the platform I would expect the locking to work on the platform (resolve and lock i.e. for dev vs dev-gpu)
