### ISSUE TITLE
Support multi envs

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#392]
### Problem description

I need multiple Python version environments, but I can't declare multiple versions simultaneously.

Maybe we can specify envs like

```toml
# pixi.toml

[env.py37.dependencies]
python = "3.7.*"
default = true

[env.py311.dependencies]
python = "3.11.*"
```

After exec `pixi install` will create two env dirs
- .pixi/py37
- .pixi/py311

Control the environment through the `-e/--env` option
```bash
pixi run -e py311 python
```
