### ISSUE TITLE
Private channel authentication error with local conda src package

### ISSUE THREAD

**Issue by jmayes-rx** [prefix-dev/pixi#3941]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### complete pyproject.toml
```toml
# pyproject.toml
[project]
authors = [{name = "jmayes", email = "jeremy.mayes@readyx.com"}]
dependencies = []
name = "private-repo-test"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = [
        "https://prefix.dev/pixi-build-backends",
        "https://conda.cloudsmith.io/readystate/main",
        "conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]

[tool.pixi.dependencies]
private_repo_test = { path = "." }

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "0.1.*" }
```

### example error
```shell
$ pixi add numpy
Error:   × failed to extract metadata for package 'private_repo_test'
  ├─▶   × failed to determine metadata of source dependency 'private_repo_test'
  │
  ├─▶   × could not find subdir 'noarch' in channel 'http://conda.cloudsmith.io/readystate/main/'
  │
  ╰─▶ HTTP status client error (404 Not Found) for url (https://conda.cloudsmith.io/readystate/main/noarch/repodata.json)
```

### Issue description

This issue does seem related to issues #2177 and #3585 but slightly different.

### Steps to repeat:
1. Init a project to use a pyproject.toml (this may apply to pixi.toml as well, but, I haven't tested)
2. Add a private conda channel:
```
[tool.pixi.workspace]
channels = [
        "conda-forge",
        "http://conda.cloudsmith.io/readystate/main",
]
```
4. Change the local source dependency from
```toml
[tool.pixi.pypi-dependencies]
private_repo_test = { path = ".", editable = true }
```
to a conda dependency instead
```toml
[tool.pixi.dependencies]
private_repo_test = { path = "." }
```
5. Run a pixi command which needs to resolve the env (`pixi add ...`, `pixi lock`, `pixi install`, `pixi shell`, etc)
 
Then pixi fails with http 404 error trying to get the `noarch` repo

If I leave the local source package under `pypi-dependencies` instead, then, everything works as expected.

### Expected behavior

Successful completion of whichever pixi command triggered the failure, e.g., `pixi add numpy` adds numpy to the dips, resolves the env, and installs the default env.

**Comment by ruben-arts** [comment]
Thank you for the report! This is indeed something that we should not error on. <br>In the normal pixi resolve this would have been ignored, but I guess the building side doesn't ignore this error yet.

**Comment by jmayes-rx** [comment]
Is this an expected error that should be ignored? Like in the two issues I linked to, I can access the `noarch` url via curl using http basic auth.

**Comment by baszalmstra** [comment]
Currently the build backends solve these environments instead of pixi itself. But at the time of writing only pixi itself (not the backends) has authentication information. We are working on a refactor where pixi is in control of solving environments. Then this will be an issue of the past. Ill update this issue when that change lands.

**Comment by Hofer-Julian** [comment]
Everything seems to work as expected both with the last two releases and current `main`. Will write up a test now.

**Comment by jmayes-rx** [comment]
> Everything seems to work as expected both with the last two releases and current `main`. Will write up a test now.

I still get similar error with the above `pyproject.toml` and pixi v0.49.0. 
```
$ pixi add numpy
Error:   × failed to extract metadata for package 'private_repo_test'
  ├─▶   × Failed to resolve dependencies: could not find subdir 'noarch' in channel 'https://conda.cloudsmith.io/readystate/main/'
  │
  ├─▶   × HTTP status client error (404 Not Found) for url (https://conda.cloudsmith.io/readystate/main/noarch/repodata.json.bz2)
  │
  ╰─▶   × could not find subdir 'noarch' in channel 'https://conda.cloudsmith.io/readystate/main/'
```

**Comment by Hofer-Julian** [comment]
Unfortunately, I can't test it with your exact setup.

I tried it with prefix.dev private channels, it would be really helpful if you could do the same to make sure it's not related fo cloudsmithy or your specifc  machines

**Comment by Hofer-Julian** [comment]
@jmayes-rx @wolfv and I were able to reproduce this bug on `conda.cloudsmithy.io`. We still have to figure out why it only goes wrong in the combination of `pixi build` + private channel on `cloudsmithy`.

**Comment by Hofer-Julian** [comment]
@baszalmstra and I debugged this and we were able to confirm that this problem is solved on the combination of `pixi` on the `main` branch and `pixi-build-backends` on this [PR](https://github.com/prefix-dev/pixi-build-backends/pull/241). As soon as both of them are released, this problem should be solved

**Comment by lucascolley** [comment]
@jmayes-rx this should be fixed now, can you check with latest Pixi and `pixi-build-python==0.2.*`?

**Comment by baszalmstra** [comment]
We didnt release the latest pixi-build-api-version yet, so not quite yet!

**Comment by jmayes-rx** [comment]
waiting patiently

**Comment by baszalmstra** [comment]
We released `pixi-build-api-version 1` just now which should make this issue a thing of the past.<br><br>We are maintaining a rolling distribution of the build backends on the `pixi-build-backends` channel and a stable one on `conda-forge`. For the time being you have to use the `pixi-build-backends `channel to install the build backends. You can do this with:

```toml
[package.build]
backend = { name = "pixi-build-python", version = "0.*" }
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
```

With this you can build python packages directly into conda packages (including transitive dependencies) which can be consumed by pixi itself.
