### ISSUE TITLE
pypi dependency resolution fails with `extra-index-url` index returning 403

### ISSUE THREAD

**Issue by valpesendorfer** [prefix-dev/pixi#3963]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```python
# webserver.py
#!/usr/bin/env python3
import http.server
import socketserver
from http import HTTPStatus

class Custom403Handler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # raise 403
        self.send_error(HTTPStatus.FORBIDDEN, "Access Forbidden")
        return
# Set up the server
PORT = 8000


with socketserver.TCPServer(("", PORT), Handler) as httpd:
    print(f"Server running at http://localhost:{PORT}/")
    httpd.serve_forever()
```

```toml
# pixi.toml
[workspace]
name = "test-project"
version = "0.1.0"

channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[pypi-options]
index-url = "https://pypi.org/simple"
extra-index-urls = ["http://localhost:8000/"]


[environments]
default = { solve-group = "default" }

[dependencies]
python = ">=3.10,<3.12"

[pypi-dependencies]
cowpy = "*"
```

```shell
❯ pixi -V
pixi 0.48.2

❯ pixi install
Error:   × failed to solve the pypi requirements of 'default' 'osx-arm64'
  ├─▶ failed to resolve pypi dependencies
  ╰─▶ Because cowpy was not found in the package registry and you require cowpy, we can conclude that your requirements are unsatisfiable.
      
      hint: An index URL (http://localhost:8000/) could not be queried due to a lack of valid authentication credentials (403 Forbidden).
```

### Issue description

We're using an additional pypi index which returns a 403 error if a package is requested which does not exist on the index. Packages which do exists, are normally available - no credentials are required.

Curiously, this seems to mess up the dependency resolution for pypi dependencies. My expectation would be that the "default" index (pypi) is used first and since the package exists there, it should succeed.

But, adding this index results in a failure to resolve the dependencies - even when intentionally setting `index-url = "https://pypi.org/simple"`.

I suppose this could be related to uv's [ignoring-error-codes-when-searching-across-indexes](https://docs.astral.sh/uv/concepts/indexes/#ignoring-error-codes-when-searching-across-indexes)? As far as I can see, this can't be configured yet for pixi.

To reproduce it, a simple local http server which returns 403 instead of 404 is needed.

### Expected behavior

If the webserver returns 404, the dependency resolution works as expected and the environment is installed:

```shell
❯ pixi install
✔ The default environment has been installed.
```
