### ISSUE TITLE
Inconsistent naming pypi config/options

### ISSUE THREAD

**Issue by lucharo** [prefix-dev/pixi#3978]
Hi, I've been a bit confused lately trying to get pixi to work with private pypi repositories, partly because my search engine led me to pixi 0.21.0 documentation. 

Besides that, it seems to be the case that within a project's pyproject.toml you honour `[pypi-options]`](https://pixi.sh/dev/reference/pixi_manifest/#the-pypi-options-table) to set pypi config values but in the global configs (e.g. ~/.pypi/config.toml) you honour [`[pypi-config]`](https://pixi.sh/dev/reference/pixi_configuration/#pypi-config)

I find this a bit confusing, how do these interact if at all? I'm currently facing issues with getting pixi to respect the private extra index url set in my `~/.config/pixi.toml` and this issue added to the confusion

**Comment by lucharo** [comment]
This adds to my confusion: https://pixi.sh/v0.48.2/deployment/authentication/#pypi-authentication

Do I need keyring + config.toml
Or keyring + project/pixi.toml?

Or can I simply have the token in plain text in the config?

**Comment by ruben-arts** [comment]
Your confusion makes sense we should do better at either explaining this or change the names.

**Comment by lucharo** [comment]
What I've tried so far, I'm using an ADO pypi index by the way

## global config + plain test token (fails)

**~/.pixi/config.toml:**

```toml
[pypi-config]
extra-index-urls = ["https://:PATTOKEN@pkgs.dev.azure.com/{organization}/{project}/_packaging/{feed}/pypi/simple/"]
```

## global config + keyring (fails)

from the terminal:

```sh
pixi global install keyring --with keyrings.artifacts
keyring get https://pkgs.dev.azure.com/{organization}/{project}/_packaging/{feed}/pypi/simple/ VssSessionToken
```

PS: ^ is black magic to me by the way, how does it fetch that exactly? 

**~/.pixi/config.toml**:

```toml
[pypi-config]
extra-index-urls = ["https://VssSessionToken@pkgs.dev.azure.com/{organization}/{project}/_packaging/{feed}/pypi/simple/"]
~~keyring-provider = "subprocess"~~
```

edit: actually I thought the `keyring-provider` but it turns out it isn't, I actually had to specify `--pypi-keyring-provider` in the `pixi add --pypi pandas --pypi-keyring-provider` or in the `~/.pixi/config.toml`. This would seem to go against the effort to:

> keep the manifest file as complete and reproducible as possible"
> [source (info block)](https://pixi.sh/v0.48.2/reference/pixi_configuration/#pypi-config)

references:

- https://pixi.sh/v0.48.2/deployment/authentication/#pypi-authentication
- https://github.com/jslorrma/keyrings.artifacts?tab=readme-ov-file#command-line

## local/project config + keyring (works)

**/my/project/pixi.toml**: 

```toml
[pypi-options]
extra-index-urls = ["https://VssSessionToken@pkgs.dev.azure.com/{organization}/{project}/_packaging/{feed}/pypi/simple/"]
keyring-provider = "subprocess"
```

**note here** how we are using `[pypi-options]` where as in the global config we were using `[pypi-config]`

----

my question, is all of this works/doesn't work intentional or how it's meant to work? do you not allow plain test token by default or am I missing something in the examples above? 

Coming from `pip.conf` and even `~/.config/uv/uv.toml` where they allow plain text tokens it feels off when this doesn't work by default in pixi though I appreciate the emphasis on using keyring to avoid storing credentials as plain text I think this flow will be unfamiliar to many users. 

---

Finally, a very interesting (to me) demo/gist would be how to collect all of this inside a `Dockerfile` as all this manual things that need setting up are a big friction point for folks trying to use `pixi` in corporate environments. 

--- 

*Other sources* - (to collect every point where slightly conflicting or confusing information is given on this topic):

- https://pixi.sh/v0.48.2/reference/pixi_configuration/#pypi-config
- https://pixi.sh/v0.48.2/deployment/authentication/#pypi-authentication
- https://pixi.sh/dev/reference/pixi_manifest/#the-pypi-options-table

--- 

Finally as I understand it when you refer to the "pixi manifest" you mean the `pixi.toml` right?
