### ISSUE TITLE
`pixi run` behaves weirdly when using cygwin directories

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#398]
### Reproducible example

```yml
name: CI

on:
  push

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.3.0
      - run: |
          set -x
          tmp="$(mktemp)"
          echo "print('hello world')" > "$tmp"
          pixi run python -c "$tmp"
        shell: bash
```

### Issue description

```
++ mktemp
+ tmp=/tmp/tmp.xtpMxFqTLN
+ echo 'print('\''hello world'\'')'
+ pixi run python -c /tmp/tmp.xtpMxFqTLN
  × Unexpected character.
  │   ~1/AppData/Local/Temp/tmp.xtpMxFqTLN
  │   ~

Error: Process completed with exit code 1.
```

### Expected behavior

Not sure what happens here exactly. The `/tmp/...` is probably translated somewhere to an actual windows directory which `pixi run` cannot handle(?)

See https://github.com/pavelzw/ci-test/pull/5 and https://github.com/pavelzw/ci-test/actions/runs/6587384999/job/17897567467?pr=5
