### ISSUE TITLE
Build SciPy with Pixi Build

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#3993]
We would like to test Pixi build for more complex workflows.
SciPy is one of the most interesting ones, and @lucascolley is already familiar with it, so let's start with it.

- [x] Use Pixi from current `main` (one can install it by running `pixi run install-as pixid`)
- [x] Is the SciPy setup with `pixi-build-rattler-build` still working? https://github.com/rgommers/pixi-dev-scipystack/pull/20
- [ ] Make it work with source dependencies
- [ ] Make it work with Windows
- [ ] Find out what goes well, what doesn't
   - Are incremental builds working?
   - Are error messages clear?

Mid-term vision:
- `pixi-build-meson` backend

**Comment by lucascolley** [comment]
> Is the SciPy setup with pixi-build-rattler-build still working?

After some small tweaks to the PR, `pixi build` succeeds in 4 minutes. It works as a run-dependency in the workspace.

Trying out source dependencies now.

**Comment by lucascolley** [comment]
> Are incremental builds working?

It seems not with current `main`, running `pixid build` back-to-back triggers another full 4 minute build.

**Comment by lucascolley** [comment]
> Are error messages clear?

First unclear error message:

```toml
# pixi.toml
[dependencies]
meson = { path = "meson" }
```

```yaml
# recipe/recipe.yaml
package:
  name: meson
  version: ${{ version }}
source:
  path: ../meson
```

```console
pixi-dev-scipystack/meson on 🎋 build [?] via 🧚 v0.48.2 
❯ pixid build
  0s building package: meson build completed                                                                                                                                                                Error:   × during the building of the project the following error occurred
  ├─▶ IO Error: No such file or directory (os error 2)
  ╰─▶ No such file or directory (os error 2)
```

Solved by:

```console
❯ gh repo clone meson
```

**Comment by lucascolley** [comment]
`meson` is building successfully, and seems to work well as a runtime dependency of SciPy.

> Make it work with source dependencies

What am I looking to use here? Do I need gh-3967? Adding a `path` dependency in `[package.build-dependencies]` to another `package` doesn't seem to have an effect.

**Comment by Hofer-Julian** [comment]
> It seems not with current main, running pixid build back-to-back triggers another full 4 minute build.

I double-checked with @baszalmstra and that should work with the `pixi-build-rattler-build` backend.

Can you try building:
- one package using `pixi-build-cmake`
- another package using `pixi-build-rattler-build`

Both should be big enough that the difference between hot and cold build should be noticeable.

> First unclear error message: "No such file or directory"

Do you have ideas on how to improve it? Would be mentioning which directory couldn't be found already enough?

> Make it work with source dependencies. What am I looking to use here?

You are right, we can't use recursive build dependencies yet. Only one PR to go :)

What you can try though are recursive *run* dependencies.

**Comment by lucascolley** [comment]
>> First unclear error message: "No such file or directory"
>
> Do you have ideas on how to improve it? Would be mentioning which directory couldn't be found already enough?

I will follow-up on this at https://github.com/prefix-dev/rattler-build/issues/1739

**Comment by lucascolley** [comment]
>>  It seems not with current main, running pixid build back-to-back triggers another full 4 minute build.
> 
> I double-checked with @/baszalmstra and that should work with the pixi-build-rattler-build backend.
> 
> Can you try building:
> 
> - one package using pixi-build-cmake
> - another package using pixi-build-rattler-build
> 
> Both should be big enough that the difference between hot and cold build should be noticeable.

I have now confirmed that `pixi-build-rattler-build` does take advantage of incremental builds. The timings are a little underwhelming with meson, though, not sure if there is any more we can squeeze out. Timings:
- NumPy: 82s cold -> 62s warm
- PyWavelets: 33s cold -> 10s warm
- SciPy: 5mins cold -> 5mins warm

**Comment by Hofer-Julian** [comment]
That is indeed underwhelming.

Can you please also give the timings for incremental builds *without* using pixi build for the projects?

**Comment by lucascolley** [comment]
> Can you please also give the timings for incremental builds without using pixi build for the projects?

SciPy via `spin`: 6m30s cold -> 4s warm

This is using:
- https://github.com/scipy/scipy/blob/affa219ffc58a750be0f53df269061782b5bf424/.spin/cmds.py#L62-L151
- https://github.com/scientific-python/spin/blob/fee6abe42cea118c2e4577cce5e0ca034c55748e/spin/cmds/meson.py#L312-L431

---

`pixi-build-rattler-build` calls:
1. `meson setup $SRC_DIR $SRC_DIR/builddir -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md -Dblas=blas -Dlapack=lapack -Duse-g77-abi=true --native-file=$SRC_DIR/builddir/meson-python-native-file.ini`
2. `$PREFIX/bin/ninja`

from this `build.sh`:

```sh
mkdir builddir

CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY" \
    $PYTHON -m build -w -n -x \
    -Cbuild-dir=builddir \
    -Cinstall-args=--tags=runtime,python-runtime,devel \
    -Csetup-args=-Dblas=blas \
    -Csetup-args=-Dlapack=lapack \
    -Csetup-args=-Duse-g77-abi=true

$PYTHON -m pip install dist/scipy*.whl
```

---

Cold SciPy build via `spin` calls:
1. `meson setup build --prefix=/usr -Dblas=blas -Dlapack=lapack -Duse-g77-abi=true`
2. `meson compile -j 8 -C build`
3. `meson install --only-changed -C build --destdir ../build-install --tags=runtime,python-runtime,tests,devel`

Warm SciPy build via `spin` calls:
1. `meson compile -j 8 -C build`
2. `meson install --only-changed -C build --destdir ../build-install --tags=runtime,python-runtime,tests,devel`

**Comment by lucascolley** [comment]
> What you can try though are recursive run dependencies.

This seems to not be working. The path run dependency only seems to be picked up at 1 level, not 2 levels deep. This matches the behaviour I observe at runtime.

```toml
# pixi.toml
[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
name = "scipystack"

[dependencies]
scipy = { path = "./scipy" }
```

```toml
# scipy/pixi.toml
[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
name = "scipy"

[package]
name = "scipy"
version = "1.17.0.dev0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.run-dependencies]
numpy = { path = "../numpy" }

[dependencies]
# ...
numpy = { path = "../numpy" }
# ...
```

```toml
# numpy/pixi.toml
[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]
name = "numpy"

[package]
name = "numpy"
version = "2.3.2.dev0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
```

```console
pixi-dev-scipystack/scipy on 🎋 build [🔨?⬆️ ] via 🧚 v0.48.2 
❯ pixid ls numpy
Package  Version     Build            Size  Kind   Source
numpy    2.3.2.dev0  py312h440f24a_0        conda  ../numpy

pixi-dev-scipystack on 🎋 build [🔨?⬆️ ] via 🧚 v0.48.2 
❯ pixid ls numpy
Package  Version  Build            Size     Kind   Source
numpy    2.3.0    py313h41a2e72_0  6.2 MiB  conda  https://prefix.dev/conda-forge/
```

**Comment by Hofer-Julian** [comment]
You shouldn't need a workspace in the manifests for scipy and numpy.
So they should look like that. Can you try it again with those?

```toml
[package]
name = "scipy"
version = "1.17.0.dev0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[package.run-dependencies]
numpy = { path = "../numpy" }
```

```toml
[package]
name = "numpy"
version = "2.3.2.dev0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]
```
