### ISSUE TITLE
`extra-index-urls` from `config.toml` are not passed on pixi init

### ISSUE THREAD

**Issue by nichmor** [prefix-dev/pixi#4000]
In our docs, we say that `extra-index-urls` from `config.toml` will be passed to pixi init when creating one.
https://pixi.sh/latest/reference/pixi_configuration/#pypi-config

This doesn't work right now.

Take this as config.toml example
```toml
[pypi-config]
extra-index-urls = ["http://localhost:9999/simple/"]
```

when running pixi init you will receive this

```toml
[workspace]
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
name = "pixi_init_test"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]

```

but we expect to have pypi-options table with extra-index-url
