### ISSUE TITLE
Unable add packages with extras or optional deps

### ISSUE THREAD

**Issue by gokulyc** [prefix-dev/pixi#401]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
C:\Gdrive\py_projs\pixi_dir>pixi add "typer[all]"
error: invalid value 'typer[all]' for '<SPECS>...': invalid bracket
```

### Issue description

pixi 0.6.0

Platform            : win-64
-----------------------
pixi.toml

```toml
[project]
name = "pixi_dir"
version = "0.1.0"
description = "Add a short description here"
authors = ["Gokul  <gokulyc@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
jlab = "jupyter lab --no-browser"

[dependencies]
jupyterlab = "4.0.7.*"
pandas = "2.1.1.*"
python-dotenv = "1.0.0.*"
polars = "0.19.3.*"
typer = "0.9.0.*"
rich = "13.6.0.*"
plotly = "5.17.0.*"
loguru = "0.7.2.*"
orjson = "3.9.8.*"
httpx = "0.25.0.*"
pydantic = "2.4.2.*"
fastapi = "0.103.0.*"
uvicorn = "0.23.2.*"

```

### Expected behavior

It should install packages with extras. As of now I installed single dependency only(typer).
