### ISSUE TITLE
Allow to specify `package.run-exports`

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#4021]
Similar to a [recipe.yaml](https://rattler.build/latest/reference/recipe_file/#run-exports), we want to be able to specify run-exports:

```toml
[package.run-exports.strong]
libzma = "*"

[package.run-exports.weak]
own_package = { path = "." }
```

**Comment by joshkamm** [comment]
Adding a concrete user for this. We maintain a CMake-based pixi-build package, [`slatergpu`](https://github.com/ZimmermanGroup/SlaterGPU), that is consumed by a couple of downstream pixi-build packages in our group. Each consumer's `pixi.toml` currently lists `slatergpu` twice — once under `[package.host-dependencies]` and once under `[dependencies]`.

When we want to point at a feature branch or a local checkout, we toggle both stanzas. Easy to forget one.

A downstream `pixi.toml` ends up looking like this:

```toml
[package.host-dependencies]
slatergpu = { git = "https://github.com/ZimmermanGroup/SlaterGPU", branch = "main" }
# For local development, comment the line above and uncomment:
# slatergpu = { path = "../SlaterGPU" }

[dependencies]
slatergpu = { git = "https://github.com/ZimmermanGroup/SlaterGPU", branch = "main" }
# slatergpu = { path = "../SlaterGPU" }
```

It seems like the `[package.run-exports.weak]` syntax proposed at the top of this issue would let us declare the run-export on the `slatergpu` side and drop the `[dependencies]` entry on every consumer.

P.S. Feel free to suggest if there's already a cleaner way to do our example above.
