### ISSUE TITLE
Cannot depend on specific hash of source package

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#4041]
```
# regression test that pin subpackage works with `my.package`
context:
  name: my-package
  version: 0.1.0

recipe:
  version: ${{ version }}

build:
  number: 0

outputs:
  - package:
      name: ${{ name }}
    requirements:
      host:
        - python
    build:
      noarch: generic

  - package:
      name: ${{ name }}-pinned
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage(name, exact=true) }}
```

With variants:

```
python:
  - "3.8"
  - "3.9"
  - "3.10"
```

We would expect 3 variants of `my-package-pinned` where each variant depends on a *specific* variant of `my-package` (because `${{ pin_subpackage(name, exact=true) }}`) was specified. <br><br>However, when we call `conda/outputs` all dependencies to `my-package` are replaced with:

```
{
  "name": "my-package",
  "source": {
    "Path": {
      "path": "."
    }
  }
}
```

The hash for each variant is not added, which is wrong.
