### ISSUE TITLE
Could  the `depends-on` -> list -> `{ task = "{{ a_task_name }}", ... }`  be supported?

### ISSUE THREAD

**Issue by phreed** [prefix-dev/pixi#4042]
Instead of `s: &str` could this be `s: TemplateString`? so that the `{ task = "{{ a_task_name }}", ... }` could be supported?

_Originally posted in
* https://github.com/prefix-dev/pixi/pull/3668#discussion_r2172223521_
* https://github.com/prefix-dev/pixi/issues/3538#issuecomment-3013339594

[I think the change is primarily in this section of the code](https://github.com/prefix-dev/pixi/blob/main/crates/pixi_manifest/src/task.rs#L57-L63).

Here is what it might look like in a `pixi.toml`.

```toml
[tasks.build]
args = [
    { arg = "pkg", default = "dummy" },
    { arg = "tgt_platform", default = "linux-64" }
]
cmd = [ ... ]

[tasks.build-force]
args = [
    { arg = "pkg", default = "dummy" },
    { arg = "tgt_platform", default = "linux-64" }
]
cmd = [ ... ]

[tasks.publish]
args = [
    { arg = "pkg", default = "dummy" },
]
cmd = [ ... ]

[task.for-each]
args = [
  { arg = "the_task", default = "build"},
  { arg = "tgt_platform", default = "linux-64"}
]
depends-on = [
  { task = "{{ the_task }}", args = ["foo", "{{ tgt_platform }}"],
  ...
]

[tasks.build-all]
depends-on = [ { task = "for-each", args = ["build"] } ]

[tasks.publish-all]
depends-on = [ { task = "for-each", args = ["publish"] } ]
```
