### ISSUE TITLE
Platform specific configuration

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#43]
Multi-platform packages will require the need to have platform-specific dependencies or configurations.

Cargo supports this through [the `[target]` section](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies).

### How to format them in TOML?

```toml
[dependencies]
bla = "3.1.*"
windows_specific = { version = "3.1.*", only_windows = true }
```

or cargos approach:

```toml
[dependencies]
bla = "3.1.*"

[target.'sel(win)'.dependencies]
windows_specific = "3.1"
```

I like the latter the most because its clearer that this is an exception that only applies in a certain scenario. 

### Selectors or platforms?

Cargo uses the [`cfg(..)`](https://doc.rust-lang.org/reference/conditional-compilation.html) syntax in its selectors. I think this is pretty cool because it allows you to do more complex things like selecting for two platforms or for specific architectures (arm vs x86). 

We could also simplify things a little bit and only use platform names as selectors e.g. `osx-arm64` vs `sel(osx)`. Cargo also supports specifying the target directly.

I would opt to go for the full selector experience because it provides a lot of flexibility.

### Todo

- Figure out our approach
- Implement it

**Comment by baszalmstra** [comment]
In light of the recent work on https://github.com/conda-incubator/ceps/pull/54 maybe we can adopt a similar style `if` statement.

```toml
[dependencies]
bla = { matchspec = "3.1.*", if = "win or osx" }
```

**Comment by wolfv** [comment]
I think I like this. It would only work for single dependencies, though. Should we come up with something for a list?

**Comment by baszalmstra** [comment]
Ah this method:

```toml
[dependencies]
bla = { matchspec = "3.1.*", if = "win or osx" }
```

falls apart if you would want to have different matchspecs based on the os:

```toml
[dependencies]
bla = { matchspec = "3.1.*", if = "win" }
bla = { matchspec = "4.1.*", if = "osx" }
```

The key `bla` is defined twice which is illegal.

However, using the cargo method this is possible:

```toml
[target.'if(win)'.dependencies]
bla = "3.1.*"

[target.'if(osx)'.dependencies]
bla = "4.1.*"
```

Alternatively, we could also accept minijinja syntax in the dependencies list but it makes parsing a lot harder (because we have to post-process the expressions:

```toml
[dependencies]
bla = '${{ "3.1.*" if win else "4.1.*" }}'
```

its also a bit weird with the to types of quotes..
