### ISSUE TITLE
pypi: improved error messages for sdist packages

### ISSUE THREAD

**Issue by mjlbach** [prefix-dev/pixi#530]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

The following `pixi.toml` yields an innacurate error message
```toml
[project]
name = "pixi-sdist"
version = "0.1.0"
description = "Pixi Sdist"
authors = ["Michael Lingelbach"]
channels = [ "conda-forge" ]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "~=3.10.0"

[pypi-dependencies]
pyliblzfse = "*"
```

```
❯ pixi install
 WARN pixi::project: ALPHA feature enabled!

It looks like your project contains `[pypi-dependencies]`. This feature is currently still in an ALPHA state!

You may encounter bugs or weird behavior. Please report any and all issues you encounter on our github repository:

        https://github.com/prefix-dev/pixi.

  × The following packages are incompatible
  │ |-- pyliblzfse * cannot be installed because there are no viable options:
  │     |-- pyliblzfse 0.4.1 is excluded because none of the artifacts are compatible with the Python interpreter or glibc version
  │     |-- pyliblzfse 0.4.0 is excluded because none of the artifacts are compatible with the Python interpreter or glibc version
```

### Issue description

The main issue is that `pyliblzfse` does not provide a wheel, and pixi does not support sdist.

### Expected behavior

The error message should indicate no wheel is available and pixi does not support sdist.
