### ISSUE TITLE
pypi: unrecognized .data directory: headers

### ISSUE THREAD

**Issue by mjlbach** [prefix-dev/pixi#531]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

`pixi.toml`
```toml
name = "pixi-headers"
version = "0.1.0"
description = "Pixi headers"
authors = ["Michael Lingelbach"]
channels = [ "conda-forge" ]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "~=3.10.0"

[pypi-dependencies]
av = "*"
celery = "*"
controlnet_aux = "*"
diffusers = "==0.22.3"
gevent = "*"
pillow = "==9.4.0" # Required by lang-sam
timm = "==0.6.7"
xatlas = "*"
```

### Issue description

```
❯ pixi install
 WARN pixi::project: ALPHA feature enabled!

It looks like your project contains `[pypi-dependencies]`. This feature is currently still in an ALPHA state!

You may encounter bugs or weird behavior. Please report any and all issues you encounter on our github repository:

        https://github.com/prefix-dev/pixi.

  × unrecognized .data directory: headers
```

### Expected behavior

This issue is kind of hard to reproduce, this worked on the first install but I imagine there's something weird with the structure of these packages...
