### ISSUE TITLE
Modifying task behaviour

### ISSUE THREAD

**Issue by tony-p** [prefix-dev/pixi#544]
### Problem description

What I would specifically like to do is call a predefined task, but then with an environment variable set (but not every time).

My particular example
`pixi run build` <- builds the project
`pixi run build-Werror`  <- builds the project but with the `CXXFLAGS` environment variable set for ensuring all warnings are treated as errors

So ideally rather than copying and pasting the entire build command prepended with setting the flag, it would be possible to define a task that does this. `depends_on` superficially could be used for this, but each command is run in its own shell so the environment can't be modified.

Proposals,
```toml
#  if only modifying the environment (set variable for session)
build-Werror = {depends_on="build" environment=["CXXFLAGS='-Werror'", "MY_OTHER_VAR='HELLO'"]}

# More generic run in one session
build-Werror-var = {cmd="export CXXFLAGS='-Werror'"}
build-Werror = {depends_on=["build-Werror-var" , "build"] one_session=True}
```

Or a way of doing variable definition/replacement, but I understand toml doesn't support that
