### ISSUE TITLE
pypi + conda: slow resolution for some dependency combinations (example attached)

### ISSUE THREAD

**Issue by mjlbach** [prefix-dev/pixi#559]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "boto3"
version = "0.1.0"
description = "boto3 test"
authors = ["Michael Lingelbach <m.j.lbach@gmail.com>"]
channels = [
  "conda-forge"
]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "~=3.10.0"
accelerate = "*"

[pypi-dependencies]
boto3 = "*"
open3d = "*"
timm = "*"

[system-requirements]
libc = "2.27" # Required for open3d, bump frequently
```

`pixi install`

### Issue description

The above fails to resolve after 1 minute, removing any of the dependencies solves the issue.

### Expected behavior

Might be a duplicate of #419? But this resolves fine with pypi/conda.
