### ISSUE TITLE
go-task style precondition

### ISSUE THREAD

**Issue by tarasglek** [prefix-dev/pixi#566]
### Problem description

I found a really cool UX improvement in [go-task](https://github.com/go-task/task), preconditions. This feature lets one make asserts about environment and make user-friendly errors about it.
 
There is a good example: https://github.com/terotuomala/k3s-kustomize-skaffold-k3d-example/blob/main/Taskfile.yml

Here tasks have a structured description, accept a list of assertions about environments and provide a user-friendly message if assertions are not met.

We love pixi tasks. We use it to make high-level commands for running tests, deploying infra, etc in addition to the usual managing of python deps. This would be a nice improvement. 

Rest of the go-task task features are interesting too.

**Comment by ruben-arts** [comment]
So for us that would look like the following?
```toml
[tasks.test]
precondition = { cmd="test -f needed_file.txt", msg = "File 'needed_file.txt' needs to exist"}
cmd = "python train.py -f needed_file.txt"
depends_on = "x"
```

I think this could be nice to have. Do note that if you need it right now, you could create something like that with a depends on:

```toml
[tasks]
precondition = "test -f needed_file.txt || (echo You should add the needed file && exit 1)"
start = {cmd = "python train.py needed_file.txt", depends_on = "precondition"}
```

We're open to contributions :smile:
