### ISSUE TITLE
Support label-channels (particularly important for cuda)

### ISSUE THREAD

**Issue by pablovela5620** [prefix-dev/pixi#567]
### Problem description

I often need to change different versions of cuda, for example my machine has 12.3 installed, while I need to compile things like [diff-gaussian-rasterization-w-depth](https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth/tree/cb65e4b86bc3bd8ed42174b72a62e8d3a3a71110 ) with cuda 11.6 or [tiny-cuda-nn](https://github.com/NVlabs/tiny-cuda-nn) with 11.8

as it stands I can't install different versions of cuda via pixi. Using the nvidia channel and selecting the version of cuda always defaults to 12.3

**Comment by ruben-arts** [comment]
He,

We support channel specific dependencies. This means you can define from which channel you want your [dependencies](https://pixi.sh/configuration/#the-dependencies-tables) to come. 

In this case I tested the following project and that seems to work:
```toml
[project]
name = "cuda"
channels = ["conda-forge", "nvidia/label/cuda-11.8.0"]
platforms = ["linux-64"]

[dependencies]
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
```

Hope this helps
