### ISSUE TITLE
Can't load R libraries

### ISSUE THREAD

**Issue by roaldarbol** [prefix-dev/pixi#587]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

When installing R libraries, there's an error when you try to load that library. Effectively it means that R currently cannot be used with pixi unfortunately.

Here's a `pixi.toml`:
```toml
[project]
name = "Test"
version = "0.1.0"
description = "Add a short description here"
authors = ["Mikkel Roald-Arbøl"]
channels = ["conda-forge"]
platforms = ["osx-64"]

[tasks]

[dependencies]
r = "4.3.*"
r-tidyverse = "2.0.0.*"
```

Start a shell with `pixi shell`. `which R` to make sure that it is indeed the pixi R installation being used.
Then open R with

```shell
R
```

Then once R (like `ipython`) is open, run:
```r
library(tidyverse)
```

Which returns the error:
```
Error: package or namespace load failed for ‘tidyverse’ in library.dynam(lib, package, package.lib):
 shared object ‘magrittr.dylib’ not found
```

### Issue description

I've tried with multiple packages, both with `R` but also trying to run an R script with `Rscript` - same outcome. I've frequently run R scripts from the command line, so I'm fairly sure it's a pixi issue.

### Expected behavior

I would expect pixi to detect the installed packages and simply load the library.
