### ISSUE TITLE
Support for private pip registries

### ISSUE THREAD

**Issue by vlad-ivanov-name** [prefix-dev/pixi#588]
### Problem description

Hi there!

I was wondering whether custom pip registries are supported. I tried a "naive" approach of adding a channel, but it seems channels are expected to be in conda format.

I'm particularly interested in Google Artifact Registry support -- https://cloud.google.com/artifact-registry/docs/python/store-python . One particular detail about it is that it uses `keyring` and `keyrings.google-artifactregistry-auth` packages to authenticate clients which makes the workflow quite convenient

**Comment by ruben-arts** [comment]
As of right now they are not supported, we're currently focused most on the `sdists`, after that we can work on some more small features.

**Comment by ruben-arts** [comment]
I haven't played with it yet. But you could definitely give it a try!
I would start with this function:
https://github.com/prefix-dev/pixi/blob/40200b6e432fa320d6575f3103d84ce8d4cd61d9/src/project/mod.rs#L388-L392

**Comment by ruben-arts** [comment]
We had decided that the `pypi-dependencies` are the best name as the custom registries are also called `private pypi registries` 

I haven't given it a big/long think yet, so don't be too strict on it, but just out of my head I would see two options. 
```toml
[project]
name = "foobar"
channels = ["conda-forge"]
pypi-registries = ["https://us-west1-python.pkg.dev/project-name-1234567/artifact-registry-repo-name/simple"]
```

either/or 
```toml
[pypi-dependencies]
pacakge_name = { version = "==1.2.3", pypi-registry = "https://us-west1-python.pkg.dev/project-name-1234567/artifact-registry-repo-name/simple"}

# as we also have:
[dependencies]
python = { version = "*" , channel = "custom-forge" }
```

**Comment by ruben-arts** [comment]
That would be unrelated indeed but maybe something like the `context: ` in `rattler-build` you mean: https://github.com/prefix-dev/rattler-build?tab=readme-ov-file#the-recipe-format

**Comment by zachcp** [comment]
Now that pixi is based off of UV, can we pass env variables. For example the following will work with uv and would be great to have in pixi: 

```sh
UV_INDEX_URL=https://<my_corporate_mirror>/pypi/simple uv pip sync requirements.txt 
```

**Comment by ruben-arts** [comment]
No this isn't yet possible. But we do have plans to support it, @vlad-ivanov-name made a huge effort already so we just need to find time to continue this!

**Comment by ralf-vogel** [comment]
In **Azure DevOps** you can set the `UV_EXTRA_INDEX_URL` once in your job to authorize by using the `$(System.AccessToken)`.

A pwsh script for that would be:
```powershell
# Define an array of extra index URLs
$urls = @(
    "https://MY-FEED:$env:SYSTEM_ACCESSTOKEN@pkgs.dev.azure.com/MY-ORG/_packaging/MY-FEED/pypi/simple/",
    "https://MY-OTHER-FEED%40Local:$env:SYSTEM_ACCESSTOKEN@pkgs.dev.azure.com/MY-ORG/MY-PROJECT/_packaging/MY-OTHER-FEED%40Local/pypi/simple/",
)

# Concatenate the URLs into a single string separated by a space
$urlsString = $urls -join ' '

# Set UV_EXTRA_INDEX_URL
Write-Output "##vso[task.setvariable variable=UV_EXTRA_INDEX_URL]$urlsString"
```
Of course with your *feed* and *project* names and optionally *project* or view (e.g. `Local`, `Prerelease` or `Release`).

The corresponding task can look like this:
```yaml
- pwsh: |
    # add script from above here
  displayName: Authorize uv to Python feeds
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
```
Note that you have to define the `SYSTEM_ACCESSTOKEN` as described in the [docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#systemaccesstoken).
