### ISSUE TITLE
export task command failing on windows 11

### ISSUE THREAD

**Issue by bahugo** [prefix-dev/pixi#647]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[tasks]
[project]
name = "Reproduce"
channels = ["conda-forge"]
platforms = ["win-64", ]

using_export={cmd=[
    "export FOO=bar",
]}
```

### Issue description

Hello I'm using pixi on windows 11

I'm trying to create a task to set some env variables (my final goal is to have a task for dev and another one for prod)

But when i use export in tasks cmd it fails telling me that export command was not found.

I've looked at pixi  and deno_task_shell documentations and they both mention export command.

I run it with this command using pwsh.exe
```powershell
pixi run task using_export
```
And here is the output :
```
✨ Pixi task: "export FOO=bar"
export FOO=bar: command not found
```

### Expected behavior

Not failing

**Comment by ruben-arts** [comment]
The issue is that you use a `[]` (sequence) to define a command. In the implementation we either support sequences or strings. 

We have some logic to search for commands if you use a sequence to find the the `python` command in `pixi run python start.py` for instance. 

Here are some examples of working versions:
```toml
[tasks]
working_export = "export FOO=bar"
working2_export = {cmd = "export FOO=bar"}
working3_export = {cmd = ["export", "FOO=bar"]}
not_working_export = {cmd = ["export FOO=bar"]}
```
I'll check if I can give a better error when your version is used.

**Comment by bahugo** [comment]
Thank you, it works just fine!
I don't know if it's the right place to ask this, but is it possible set a environment variable in one task and use it in another task?
example:
```toml
[tasks]
pre_task="export FOO=bar"
other_task={cmd="echo $FOO", depends_on="pre_task"}
```

**Comment by ruben-arts** [comment]
That is currently not possible. The tasks are run in separate shells. The current solution would be:

```toml
[tasks]
task = "export FOO=bar && echo $FOO"
```
If it is an environment variable you always want to have in an environment you can also put it in a `[activation.scripts]`
`setup.sh`:
```
export FOO=bar
```
`pixi.toml`
```toml
[activation]
scripts = ["setup.sh"]
```
