### ISSUE TITLE
Support `pixi add channel::lib` command

### ISSUE THREAD

**Issue by xiaoxiangmoe** [prefix-dev/pixi#671]
Having this pixi.toml
```toml
[project]
#...
channels = ["conda-forge"]

[dependencies]
python = "~=3.10"
```
Then running:

```sh
pixi add -c anaconda anaconda::nodejs
# OR
pixi add --channel anaconda anaconda::nodejs
# OR
pixi add anaconda::nodejs # We can also miss -c option here.
```
Should result in the channel specific field in the pixi.toml:
```toml
[project]
#...
channels = ["conda-forge", "anaconda"] # Note that we need to add this to the channels list

[dependencies]
python = "~=3.10"
nodejs = { version = ">=20.9.0,<20.10", channel = "anaconda" }
```

**Comment by ruben-arts** [comment]
Agreed!

Having this`pixi.toml`
```toml
[project]
...
channels = ["conda-forge"]

[dependencies]
python = "~=3.10"
```
Then running:
```
pixi add -c anaconda nodejs
# OR
pixi add --channel anaconda nodejs
```
Should result in the channel specific field in the `pixi.toml`:
```toml
[project]
...
channels = ["conda-forge", "anaconda"] # Note that we need to add this to the channels list

[dependencies]
python = "~=3.10"
nodejs = { version = ">=20.9.0,<20.10", channel = "anaconda" }
```

You'll have to write a `PrioritizedChannel` `Serializer`.

**Comment by xiaoxiangmoe** [comment]
Another idea is support
```sh
pixi add anaconda::nodejs
```

because in doc https://anaconda.org/anaconda/nodejs
it writes
```sh
conda install anaconda::nodejs
```

Also in doc https://pytorch.org/get-started/locally/
it writes
```sh
# MPS acceleration is available on MacOS 12.3+
conda install pytorch::pytorch torchvision torchaudio -c pytorch
```

Many docs for conda support form `channel::lib`. We should also support it.

use case for multiple channel:
```sh
pixi add anaconda::python conda-forge::nodejs
```

**Comment by ruben-arts** [comment]
That is a good point. We already support the de-serialization of that. It is just not serializable by pixi to be put in the toml. As we want to support it in the toml with the more verbose `{ version = "*", channel = "pytorch" }` notation.

**Comment by xiaoxiangmoe** [comment]
If we support 

```sh
conda install pytorch::pytorch torchvision torchaudio -c pytorch
pixi add pytorch::pytorch torchvision torchaudio -c pytorch
```
the `-c pytorch` should not meaning all deps are from channel pytorch. It means we should add pytorch as search channel.

See doc https://docs.conda.io/projects/conda/en/latest/commands/install.html#channel-customization

**Comment by ruben-arts** [comment]
@xiaoxiangmoe Yes that would be nice!

**Comment by ruben-arts** [comment]
@xiaoxiangmoe  Thanks! updated the python dependency as it should not touch all existing dependencies. There is logic called `strict_channel_priority` which is default in pixi. So this shouldn't break anything if someone adds another channel.

**Comment by xiaoxiangmoe** [comment]
Okay, so in the array of channels, the first channel is the default channel for all dependencies that have no "channel" field?

**Comment by ruben-arts** [comment]
No the first channel that the package name can be found in will be the only channel that package can be found in. 

```toml
[project]
channels = ["conda-forge", "pytorch", "nvidia"]

[dependencies]
rando_package = "*"
```
Steps pixi takes:
- Is the package in `conda-forge`
  -  Yes, use `conda-forge` as the only channel for this package
  - No, check next channel
- Is the package in `pytorch`
  -  Yes, use `pytorch` as the only channel for this package
  - No, check next channel
 - Is the package in `nvidia`
   -  Yes, use `nvidia` as the only channel for this package
   - No, throw error that it can't find `rando_package` in any channel

**Comment by xiaoxiangmoe** [comment]
@ruben-arts There strategy may have bug.

For example:
* In first day, rando_package can be found 1.3.0 in pytorch
* In next day, someone upload rando_package@1.2.0 to conda-forge

Then the second user install it or update it will break.

**Comment by ruben-arts** [comment]
I think we should have the extra case of:
```
pixi add anaconda::nodejs
```
resulting in:
```toml
[project]
channels = ["conda-forge"] # No search channel added

[dependencies]
python = "~=3.10"
nodejs = { channel = "anaconda", version = "x.x.x" }
```
Which would also avoid that issue. 

I'm just afraid of the amount how possibly unnecessarily verbose this would become.
With the `nvidia` case there are just a really small amount of packages that could be duplicates. And changing your whole dependency set might not be a good UX.

**Comment by xiaoxiangmoe** [comment]
Let me summarize, only when there is no dependency in the previous channel, but this dependency exists in the later channel, and in the future, the previous channel updates the dependency with the same name, will it break.

---

Here is a example of current behaviour:

```toml
[project]
channels = ["anaconda"]

[dependencies]
```

run 

```sh
pixi project channel add pytorch
pixi add faiss-cpu
```

Then it will be

```toml
[project]
channels = ["anaconda", "pytorch"]

[dependencies]
faiss-cpu = ">=1.7.4,<1.8"
```

faiss-cpu is match the second channel. There is a risk that the first channel will add this dependency in the future.


----

If we change behaviour to this:

```toml
[project]
channels = ["anaconda"]

[dependencies]
```

run 

```sh
pixi project channel add pytorch
pixi add faiss-cpu
```

If it turns out:

```toml
[project]
channels = ["anaconda", "pytorch"]

[dependencies]
faiss-cpu = { "channel" = "pytorch", "version": ">=1.7.4,<1.8"} # The faiss-cpu match not first channel, so in add deps, we should add explict channel field
```

This logic will keep all new added deps
* if deps is in first channel now, then it can have no channel field. When search it in old package-channel-judgment-logic, we can sure that it can found in first channel in the future.
* if deps is not in first channel now, then if we add dep by cli command `pixi add`, it can have explict channel field. When search it in old package-channel-judgment-logic, we can sure that it can found in the same channel in the future.
* For most user, there only be one `conda-forge` channel in channels field. if they add deps, it behaves the same as before.
* Using the old package-channel-judgment-logic will not destroy all the old `pixi.lock` and old`pixi.toml` files.

**Comment by xiaoxiangmoe** [comment]
@ruben-arts I have a question, what does the channels field mean? Which commands will be affected by changing the channels field?

**Comment by ruben-arts** [comment]
> What does the channels field mean? Which commands will be affected by changing the channels field?

`channels` in the `[project]` table are the channels that the repodata will be requested for in prepeperation for the solve step, needed to generate the lockfile. 

This gets called by `pixi run` `pixi install` `pixi shell` `pixi add` `pixi remove`. (All commands that act on the created environment.

**Comment by xiaoxiangmoe** [comment]
@ruben-arts in your example

```
pixi add anaconda::nodejs
```

```toml
[project]
channels = ["conda-forge"] # No search channel added

[dependencies]
python = "~=3.10"
nodejs = { channel = "anaconda", version = "x.x.x" }
```

Is this meaning: the complete channel calculation logic of various commands will become like this —— `[...project.channels, ...new Set(dependencies.map(x => x.channel).filter(x => x !== undefined)]`

**Comment by ruben-arts** [comment]
Yes this logic is non existent at the moment.
That's why my first suggestion also stated that we need to add the channel to the `channels = []` but in a voice call @wolfv rightfully pointed out that that might not be what the user wants as it gets added to the full search set.

**Comment by xiaoxiangmoe** [comment]
https://github.com/prefix-dev/pixi/issues/671#issuecomment-1894885049

I don't think this method will break existing behavior, cause trouble to most people, or leave hidden dangers in the future.

What do you think? Can we achieve it?

**Comment by ruben-arts** [comment]
So you would add the channel to the requirement if from the solve step the channel is not the first channel?

**Comment by xiaoxiangmoe** [comment]
There are two types of things that need to be discussed separately. Let me give two specific examples.

* `pixi add` will add a dependency in `dependencies` list, which may include channel field or not.
* When the project does not have a lockfile, `pixi install` will need to use package-channel-judgment-logic to determine which channel the dependencies belong to.

I want to change `pixi add` logic, but keep the package-channel-judgment-logic the same as before.

**Comment by ruben-arts** [comment]
@xiaoxiangmoe I think I understand your idea, could you confirm this example of what happens when a user has the following setup:
Initial toml:
```toml
[project]
channels = ["nvidia", "conda-forge"]

[dependencies]
```
Then runs `pixi add python` 

-----
The logic right now would silently get the `python` package from `conda-forge` while the toml would look like:
```toml
[project]
channels = ["nvidia", "conda-forge"]

[dependencies]
python = ">=3.12.0,<3.13"
```

But your proposal creates:
```toml
[project]
channels = ["nvidia", "conda-forge"]

[dependencies]
python = {channel = "conda-forge", version = ">=3.12.0,<3.13"}
```

To prevent future changes to the environment when `nvidia` start shipping `python` themselves. (hypothetically)
