### ISSUE TITLE
task belonging to a single feature is currently ignored

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#733]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "my-project"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
# postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.11"
pip = "*"
polars = ">=0.14.24,<0.21"

[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.test.dependencies]
hatchling = "*"
[feature.test.tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[environments]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
```

### Issue description

```
❯ pixi run -e py311 postinstall
postinstall: command not found
```

### Expected behavior

```
 ❯ pixi run -e py311 postinstall
✨ Pixi task: pip install --no-build-isolation --no-deps --disable-pip-version-check -e .

# and

 ❯ pixi run postinstall
In which environment do you want to run the task postinstall?
1. py311
2. py312
1.
✨ Pixi task: pip install --no-build-isolation --no-deps --disable-pip-version-check -e .
```
