### ISSUE TITLE
Autocompletion for `-e`

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#739]
### Problem description

It would be nice to have autocompletion for `pixi install/list/... -e <TAB>` which lists all available environments.

**Comment by ruben-arts** [comment]
I which we had this to! This is currently a real pain in the *ss to build as `clap` doesn't support custom auto-completion code. Adding this to the backlog of the multi env work but as not planned for near future work.

**Comment by pavelzw** [comment]
IMO, this configuration ideally should yield the following auto completions

```toml
[project]
name = "polarify"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.9"
pip = "*"
polars = ">=0.14.24,<0.21"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.build.dependencies]
hatchling = "*"
[feature.build.tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[feature.test.dependencies]
pytest = "*"
pytest-md = "*"
pytest-emoji = "*"
hypothesis = "*"
[feature.test.tasks]
test = "pytest"

[environments]
py39 = ["py39", "test", "build"]
py310 = ["py310", "test", "build"]
py311 = ["py311", "test", "build"]
py312 = ["py312", "test", "build"]
```

```bash
pixi run -e <TAB>
py39
py310
py311
py312

pixi run <TAB>
build  # py39, py310, py311, py312
test  # py39, py310, py311, py312
```
