### ISSUE TITLE
pixi run autocompletion broken with envs

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#740]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

In the polarify example #735

```shell
pixi run <TAB>
# nothing happens
```
Tested on https://github.com/prefix-dev/pixi/commit/479c06d34ab063067de174948221ac689ccec553

### Issue description

ideally, when doing `pixi run <TAB>`, we get all tasks that are available in the default env _and_ `--environment`.
When we do `pixi run --environment <TAB>` we get a list of all envs (#739)
When we do `pixi run --environment py39 <TAB>` we get a list of all available tasks in the `py39` environment

**Comment by ruben-arts** [comment]
I'm not able to reproduce, this only works in `zsh` and `bash`. Which both work on my machine.

**Comment by pavelzw** [comment]
Ah i found out what the problem is:
I don't have global tasks defined:

```toml
[project]
name = "polarify"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.9"
pip = "*"
polars = ">=0.14.24,<0.21"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[feature.build.dependencies]
hatchling = "*"
[feature.build.tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[feature.test.dependencies]
pytest = "*"
pytest-md = "*"
pytest-emoji = "*"
hypothesis = "*"
[feature.test.tasks]
test = "pytest"

[environments]
py39 = ["py39", "test", "build"]
py310 = ["py310", "test", "build"]
py311 = ["py311", "test", "build"]
py312 = ["py312", "test", "build"]
```

With this configuration, you don't get any tasks in the tab completion
