### ISSUE TITLE
Specify in tasks on which environment you depend. 

### ISSUE THREAD

**Issue by ruben-arts** [prefix-dev/pixi#750]
### Problem description

In the case of multiple machines you would like to run the same command. But pixi should figure out which environment to run. Either with some help or even automatically. 

This could be a use-case for multiple machines running the same scripts on different hardware accelerated chipsets.
`start` can't depend on these tasks as they are ambiguous so you would have to define a start per env and then select that env.  So this doesn't work, if you want `start` from `default` but `train-model` from `cuda`:
```toml
[tasks]
train-model = "python train.py"
evaluate-model = "python test.py"
start = { depends_on = ["train-model", "evaluate-model"] }

[feature.cuda.tasks]
train-model = "python train.py --cuda"
evaluate-model = "python test.py --cuda"

[feature.mlx.tasks]
train-model = "python train.py --mlx"
evaluate-model = "python test.py --mlx"
```

It would be great to have some sort of auto selection logic. Like checking which envs would be able to run on the current machine. And if that would not be enough let the user define which task it depends on.
E.g.: `task_name = { depends_on = ["cuda:train_model"] }`

**Comment by ruben-arts** [comment]
For smart selection we could do something like:
```toml
[environments.cuda]
features = ["cuda"]
[environments.cuda.default-when]
system-requirements = { cuda = "12.2" }
platforms = [ "linux-64", "win-64" ]
```
