### ISSUE TITLE
Add ability to not include host and/or build dependencies

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#770]
### Problem description

It would be nice to be able to not include host dependencies and build dependencies into the environment.

Maybe something like `pixi install --no-include-host-dependencies`

This would enable a use case where you want to have a `prod` environment without host dependencies

```toml
[dependencies]
python = ">=3.12"
pip = "*"

[tasks]
start = "uvicorn"

[host-dependencies]
hatchling = "*"

[feature.test.dependencies]
pytest = "*"

[feature.wheel.dependencies]
build = "*"
[feature.wheel.tasks]
build-wheel = "python -m build --no-isolation" # use hatchling from pixi env

[environments]
default = ["test"]
prod = []
```

in production docker container:

```bash
$ pixi run build-wheel
$ pixi install -e prod --no-include-host-dependencies
# not sure if we should still install this into the same location as if we would do with `pixi install -e prod`?
$ pixi run -e prod pip install dist/my-package.whl
$ pixi run -e prod start
```

Maybe we could also leverage `rip` to remove `pip` from the runtime dependencies and be able to install the wheel on top?

**Comment by msegado** [comment]
I might just be missing something, but couldn't this already be handled by multi-envs? Eg,

```toml
[dependencies]
python = ">=3.12"
pip = "*"

[tasks]
start = "uvicorn"

[feature.test.dependencies]
pytest = "*"

[feature.build.dependencies]
build = "*"
hatchling = "*"

[feature.build.tasks]
build-wheel = "python -m build --no-isolation" # use hatchling from pixi env

[environments]
default = ["test", "build"]
prod = []
```
