### ISSUE TITLE
Support pyproject as an alternative to pixi.toml

### ISSUE THREAD

**Issue by baszalmstra** [prefix-dev/pixi#79]
In python world it would be far from ideal to need both a `pyproject.toml` and a `pixi.toml`. Ideally `pixi` would also be able to read a `pyproject.toml` file and use that as a project file.

Some care needs to be taken in the distinction between `conda` and `pypi` packages. Since the `pyproject.toml` originally specifies `pypi` packages I think we would need to add another section for the `conda` packages. 

```toml
[tool.pixi.dependencies]
some_conda_package = "*"
```

**Comment by baszalmstra** [comment]
Related to #29

**Comment by baszalmstra** [comment]
I like that a lot!

**Comment by dhirschfeld** [comment]
> having a Pixi mapping that allows overriding specific dependencies with their conda sourced counterparts?

That would be useful where the packages have different names or there are constraints specified in the `pip` format instead of what `pixi` expects.

You could theoretically automate that by parsing and converting the `pip` constraints and using a [`pypi --> conda-forge`](https://github.com/regro/cf-graph-countyfair/blob/master/mappings/pypi/grayskull_pypi_mapping.yaml) mapping but easier, and just as effective, would be to allow the `pip` dependencies to be manually overridden as outlined above :rocket:

**Comment by majidaldo** [comment]
how about conda/pixi just serve as a 'bootstraper' (to instally python, R, julia, npm, js)  where each language can have its own way of dealing with libraries?

i used to want conda to handle all the packaging but i learned that creates constant friction.

**Comment by baszalmstra** [comment]
@majidaldo we firmly believe that the conda ecosystem provides a package management solution beyond just language-specific packages. It makes it trivial to install packages for different languages and provides packages for system dependencies. Conda is an excellent replacement for docker in a lot of ways. We believe conda packages are the way forward. 

Nonetheless, pixi can already easily be used as a boostrapper. Using a pixi project like this would bootstrap a python/poetry environment:

```toml
[project]
name = "python"
version = "0.1.0"
description = "Add a short description here"
authors = ["Bas Zalmstra <bas@prefix.dev>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
poetry = "poetry"

[dependencies]
poetry = "~=1.5.1"
```

You can do a similar thing for Rust, npm, etc. 

However, we are currently investigating ways to use pypi packages with pixi as well, stay tuned!

**Comment by shughes-uk** [comment]
Installing poetry into the environment it manages is generally sadness introducing. It tends to do things like update it's own dependencies (which causes it crash mid update)

**Comment by zen-xu** [comment]
@baszalmstra 
But installing poetry can pollute Python's environment dependencies. Is it possible to isolate such dev-dependencies?

**Comment by raceychan** [comment]
on updates on this idea?

**Comment by vsoch** [comment]
I'd like to +1 some kind of support (or conversion even) from pyproject.toml. I have a protect with a pyproject.toml, with the expectation to use poetry:

```toml
[tool.poetry]
name = "snakemake-executor-plugin-googlebatch"
version = "0.1.0"
description = ""
authors = [
    "Vanessa Sochat <sochat1@llnl.gov>",
    "Johannes Koester <johannes.koester@uni-due.de>"
]
readme = "README.md"
license = "MIT"
repository = "https://github.com/snakemake/snakemake-executor-plugin-googlebatch"
documentation = "https://snakemake.github.io/snakemake-plugin-catalog/plugins/executor/googlebatch.html"
keywords = ["snakemake", "plugin", "executor", "cloud", "google-batch"]

[tool.poetry.dependencies]
python = "^3.11"
google-cloud-batch = "^0.17.1"
requests = "^2.31.0"
google-api-core = "^2.12.0"
google-cloud-storage = "^2.12.0"
snakemake-interface-common = "^1.14.0"
snakemake-interface-executor-plugins = "^8.1.1"
jinja2 = "^3.1.2"
google-cloud-logging = "^3.8.0"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
flake8 = "^6.1.0"
coverage = "^7.3.1"
pytest = "^7.4.2"
snakemake = {git = "https://github.com/snakemake/snakemake.git", branch="main"}
snakemake-storage-plugin-s3 = "^0.2.7"

[tool.coverage.run]
omit = [".*", "*/site-packages/*", "Snakefile"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
For one reason or another, it tries to resolve dependencies forever on one of my machines. I'm trying out replacing it with pixi, and (in practice) I'm doing a lot of:

```bash
$ pixi add --pypi google-cloud-logging
 WARN pixi::project: ALPHA feature enabled!
```

I'm not sure conversion needs to be a core feature, because there will be oodles of different formats (and likely impossible to support them all). But Perhaps a small library that is even separate, or a web interface to handle it?

Also a suggestion for the new docs - maybe default to dark mode with yellow to match the current site? The white/yellow is a bit jarring for someone like myself that lives in a bat cave. :bat: 

If you like the mkdocs look but want sphinx, I like https://github.com/jbms/sphinx-immaterial. It comes with light/dark modes out of the box (with the choice to choose a default) and the yellow / marigold on dark looks pretty nice :) 
![image](https://github.com/prefix-dev/pixi/assets/814322/a0c11116-1268-41ac-8bce-b3839d03087a)


And final question - is the expected workflow for developing a python package to do:

 - pixi add pip    # add pip to your environment
 - pixi shell         # shell in
 - pip install -e . # local development install

Or is there a pixi add command that says "install this local path in development mode"?

OK I think that's all the questions I have - thanks muchly!
