### ISSUE TITLE
failed to post process the environment (unclobbering)

### ISSUE THREAD

**Issue by YYYasin19** [prefix-dev/pixi#794]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example
I am on macOS and I want to add a package 

```shell
pixi install # this is okay
pixi add <pretty much any package>
```

for the following `pixi.toml` project
```toml
[project]
name = "project"
version = "0.1.0"
authors = ["Yasin Tatar <ytatar9@googlemail.com>"]
channels = ["conda-forge"]
platforms = ["linux-aarch64", "osx-arm64"]

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
thefuzz = ">=0.22.1,<0.23"
coverage = ">=7.4.1,<7.5"
httpx = ">=0.26.0,<0.27"
pymongo = ">=4.6.1,<4.7"
fastapi = ">=0.103.0,<0.104"
transformers = ">=4.17.0,<4.18"
openai = "<=1.0"
pyexcel-xls = ">=0.6.2,<0.7"
python-dotenv = ">=1.0.1,<1.1"
xmltodict = ">=0.13.0,<0.14"
chromadb = ">=0.4.22,<0.5"
pyexcel = ">=0.7.0,<0.8"
openpyxl = ">=3.1.2,<3.2"
pytesseract = ">=0.3.13,<0.4"
pytest = ">=8.0.0,<8.1"
python-jose = ">=3.3.0,<3.4"
python = "3.11.*"
mongomock = ">=4.0.0,<4.1"
easyocr = ">=1.7.1,<1.8"
pydantic = ">=2.6.1,<2.7"
pyexcel-xlsx = ">=0.6.0,<0.7"
python-multipart = ">=0.0.7,<0.1"
uvicorn = ">=0.27.0.post1,<0.27.1"
pandas = "2.*"
ipython = ">=8.21.0,<8.22"
pdf2image = "1.16.*"
```

### Issue description

When I do a fresh `pixi install` with the `.toml` it works, but when I try to add another package (e.g. `tesseract` but seems to be with every package) it fails with an OS error

The resulting output is
```bash
> pixi add tesseract
  ✔ downloading          [00:00:01] Done!
  ✔ linking              [00:00:01] Done!                                                                                      × failed to post process the environment (unclobbering)
  ╰─▶ No such file or directory (os error 2)
```
One of my dependencies seems to leave the pixi env in a broken state.

### Expected behavior

Add the package to the pixi project.
