### ISSUE TITLE
Error: Could not consume all of the output of the current ZipFile

### ISSUE THREAD

**Issue by humphd** [prefix-dev/pixi#799]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
✨ Pixi task (default): pip install -r requirements.txt
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/zip-0.6.6/src/read.rs:1008:25:
Could not consume all of the output of the current ZipFile: Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Error { kind: Reset(StreamId(85), INTERNAL_ERROR, Remote) }) } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: The operation was canceled.
```

### Issue description

In our CI, we've seen Pixi die like this a few times. @ruben-arts encouraged me to file if I saw it happen again.

### Expected behavior

I'd expect a Pixi error vs. a Rust panic.

**Comment by tdejager** [comment]
Would it be possible to post your `pixi.toml` :)?

**Comment by moritzwilksch** [comment]
had the same issue pop up in our CI yesterday, @pavelzw and I just suspected a flaky download.

<details>
<summary> pixi.toml </summary>

```toml
[project]
name = "name"
description = "desc"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = ">=3.11"
polars = ">=0.19.9"
rich = "*"
scikit-learn = "*"
pandas = "*"
pyarrow = "*"

[host-dependencies]
pip = "*"
setuptools = ">=61"
setuptools-scm = "*"
[feature.docs.dependencies]
make = "*"
numpydoc = "*"
sphinx = "*"
sphinxcontrib-apidoc = "*"
sphinx_rtd_theme = "*"
sphinx-book-theme = ">=1.0"
myst-parser = "*"
[feature.docs.tasks]
docs = "cd docs && make html"

[feature.test.dependencies]
pytest = ">=6,<8"
pytest-cov = "*"
pytest-md = "*"
pytest-emoji = "*"
pytest-lazy-fixture = "*"
mypy = ">=1.8,<1.9"
[feature.test.tasks]
test = "pytest"
mypy = "mypy ."

[feature.lint.dependencies]
pre-commit = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

[environments]
default = ["test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
docs = ["docs"]
lint = ["lint"]
```

</details>
