### ISSUE TITLE
Do not insert env var `CONDA_PREFIX` when run env command

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#827]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```shell
$ pixi --version
0.14.0

```

```toml
[project]
name = "awesome"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.15"

[dependencies]

[feature.py37.dep]
python = "3.7.*"

[feature.dev.dependencies]
poetry = "1.6.1"
python = "3.11.*"

[environments]
dev = ["dev"]
py37 = ["py37"]
```

### Issue description

If the environment variable CONDA_DEFAULT_ENV is found, Python dependencies will be installed under that conda environment (`dev` env).

https://github.com/python-poetry/poetry/blob/cff4d7d51c9ac0f9a8b9ac91652b6dc20e63e203/src/poetry/utils/env/env_manager.py#L292

### Expected behavior

when I activate env `py37`, and run `pixi run -e dev poetry install`, the poetry should install dependencies in env `py37`

**Comment by zen-xu** [comment]
I have found a workaround.

```bash
pixi run -e dev CONDA_PREFIX="" poetry install
```

**Comment by zen-xu** [comment]
I have found a workaround.

```toml
[project]
name = "awesome"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.15"

[dependencies]

[feature.py37.dep]
python = "3.7.*"

[feature.py37.tasks]
poetry = "pixi run -e dev CONDA_PREFIX=$CONDA_PREFIX poetry"

[feature.dev.dependencies]
poetry = "1.6.1"
python = "3.11.*"

[environments]
dev = ["dev"]
py37 = ["py37"]
```

```bash
pixi shell -e py37
pixi run poetry add click
```
