### ISSUE TITLE
Interactive environment selection should be for all

### ISSUE THREAD

**Issue by deltamarnix** [prefix-dev/pixi#840]
### Problem description

Given this example. When I do: `pixi run moon`, I receive the question if I want to run the command in `default`, `one`, or `two`. When I choose, the `depends_on` tasks don't imply the same environment, so I have to select for both `hello` and `world` where to run it, while `moon` is executed in the default environment. It feels like some automatic environment dependency should be implemented.

```toml
[project]
name = "pixitest"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]
hello = { cmd = "echo Hello" }
world = { cmd = "echo World", depends_on = ["hello"]}
moon = { cmd = "echo Moon", depends_on = ["world"]}

[environments]
one = []
two = []
```

An output could be:

```
pixi run moon
Pixi task (two): echo Hello
Hello

Pixi task (one): echo World
World

Pixi task (default): echo Moon
Moon
```

**Comment by ruben-arts** [comment]
Hee @deltamarnix 

Would you mind sharing your real world example? This is implemented as you can depend on tasks from different environments. If we for the decision to all we would not be able to do it the other way around where you would want a different env for different tasks.

**Comment by deltamarnix** [comment]
In my real world scenario, I have a custom `install` step that consists of multiple tasks that are carried out. For example, performing a local `pip install -e .` into the python environment, and installing `pre-commit` hooks like so:

```toml
install = { depends_on = ["install-hydromt", "install-pre-commit"] }
install-hydromt = "pip install --no-deps --editable ."
install-pre-commit = "pre-commit install"
```
