### ISSUE TITLE
`pixi init --import` generates incorrect prefix

### ISSUE THREAD

**Issue by pavelzw** [prefix-dev/pixi#847]
```yml
# environment.yml
name: pixi-bug
channels:
  - conda-forge
  - nodefaults
dependencies:
  - jinja2
  - micromamba
  - python
```

```bash
❯ pixi init --import environment.yml
✔ Initialized project in /private/tmp/pixibug/.
❯ cat .pixi/envs/default/prefix
.pixi/envs/default
❯ pixi shell
  × the project location seems to be change from `.pixi/envs/default` to `/private/tmp/pixibug/.pixi/envs/default`, this is not
  │ allowed.
  │ Please remove the `.pixi` folder and run again
```
