### ISSUE TITLE
`pixi run` should prioritize calling command rather than task

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#850]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```bash
$ pixi --version
pixi 0.14.0
```

```toml
[project]
name = "playground"
version = "0.1.0"
description = "Add a short description here"
authors = ["ZhengYu, Xu <zen-xu@outlook.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
pre-commit = "pixi run -e dev pre-commit"

[dependencies]

[feature.py38.dependencies]
python = "3.8.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.dev.dependencies]
pre-commit = "*"

[environments]
default = ["py311"]
py38 = ["py38"]
py311 = ["py311"]
dev = ["dev"]
```

```shell
$ pixi shell
$ pixi run pre-commit
✨ Pixi task (default): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
✨ Pixi task (dev): pixi run -e dev pre-commit
...
```

### Issue description

I installed some Python tools in the `dev` environment and exported these commands in `tasks` for use in other environments, but pixi triggers recursive calls.

### Expected behavior

`pixi run` should prioritize calling command rather than task

**Comment by zen-xu** [comment]
Or provide some mechanism to distinguish between commands and tasks.

```toml
[tasks]
# @<cmd> is a command rather than a task
pre-commit = "pixi run -e dev @pre-commit"
```
