### ISSUE TITLE
`pixi run start` says "command not found" but it's only the platform that's missing

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/pixi#874]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "test"
version = "0.1.0"
description = "Add a short description here"
authors = []
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "echo hello"
```

Now execute on a platform that is not `linux-64` (e.g. `osx-arm64`)
```shell
pixi run start
```

### Issue description

This prints:

`start: command not found`

It would be better if it prints "osx-arm64 not supported" or not in platforms or something like that.

### Expected behavior

Print a more helpful error message.
