### ISSUE TITLE
`pixi init --import` cannot deal with pip dependencies yet

### ISSUE THREAD

**Issue by Hofer-Julian** [prefix-dev/pixi#877]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```yml
# environment.yml
name: test
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
      - pyoptflow
```

```shell
nu ❯ pixi init --import environment.yml
  × pip is already added.
```

### Issue description

The import functionality gets confused since the `pip` key is there twice.

### Expected behavior

Ideally, the importer could handle the pip dependencies.
Alternatively, it could just ignore them, but still add the conda dependencies.
