### ISSUE TITLE
Default environment not automatically selected for tasks with explicit `cmd` & `depends_on`

### ISSUE THREAD

**Issue by Wumpf** [prefix-dev/pixi#919]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[environments]
cpp = ["cpp"]

[tasks]
# ...
py-build = "maturin develop --manifest-path rerun_py/Cargo.toml --extras=tests"
py-test = { cmd = "python -m pytest -vv rerun_py/tests/unit", depends_on = [
  "py-build",
] }
# ...

[feature.cpp.tasks]
# ...
```

### Issue description

The first task runs simply with `pixi run py-build` and off it goes. The second one prompts me if I wouldn't want to run in the cpp environment which is also defined in the config:
``` pixi run py-test
? The task 'py-build' (depended on by 'py-test') can be run in multiple environments.

Please select an environment to run the task in: ›
❯ default
  cpp
```

### Expected behavior

All tasks under `tasks` use the default environment without prompting (or there's a straight forward explicit way to have tasks be assigned to the default environment)
