### ISSUE TITLE
PyPI transitive dependency missing from default environment

### ISSUE THREAD

**Issue by renan-r-santos** [prefix-dev/pixi#924]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

```toml
[project]
name = "bug_test"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "=3.11"

[pypi-dependencies]
matplotlib = "~=3.8"

[feature.dev.dependencies]
moto = "=5.0"

[environments]
default = { features = [], solve-group = "bug_test" }
dev = { features = ["dev"], solve-group = "bug_test" }
```

```shell
$ pixi install
$ pixi run python -c 'import matplotlib'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workspaces/software/.pixi/envs/default/lib/python3.11/site-packages/matplotlib/__init__.py", line 157, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging
```

### Issue description

Both `moto` and `matplotlib` depend on `packaging` but in the lock file, it is added to the `dev` environment only. The workaround is to explicitly add `packaging` to the `default` environment in `pixi.toml`.
This was tested using `main` branch of pixi.

### Expected behavior

My intention is for the `dev` environment to be a superset of `default` one. Am I using `solve-group` in the wrong way or is this an actual bug?
