### ISSUE TITLE
Enable the quiet parameter in task configurations

### ISSUE THREAD

**Issue by zen-xu** [prefix-dev/pixi#934]
### Problem description

For certain dependency tasks, I do not wish them to be printed out.

**Comment by zen-xu** [comment]
Perhaps a silent option could be provided.

```toml
[task]
task1 = { cmd = "echo hello", slient = true }
task2 = { cmd = "echo world", depends_on = ["task1"] }
```
