### ISSUE TITLE
Allow passing arguments to the `depends_on` task

### ISSUE THREAD

**Issue by mjkanji** [prefix-dev/pixi#957]
### Problem description

I have the following tasks:

```toml
dbt_run = { cmd = "dbt run" }
diff_dbt = { cmd = "data-diff --dbt", depends_on = ["dbt_run"] }
```

The problem I have is that I'd like to do:

```shell
pixi run diff_dbt --select my_model
```

and have it run

```
dbt run --select my_model
data-diff --dbt --select my_model
```

There doesn't currently seem to be a way to pass the arguments back to the `depends_on` task as well.

I suppose an alternative would be to remove the dependency but how would I pass the argument to both commands?

```toml
diff_dbt = { cmd = "dbt run --select $1 && data-diff --dbt --select $1" }
```

Perhaps #502 can make this alternative possible?

**Comment by ruben-arts** [comment]
He @mjkanji This is indeed something we have heard before, we don't really have a good example. Do you know a tool that implements something alike?

**Comment by ruben-arts** [comment]
I think this could be a cool feature, but there are still to much questions for me to come up with a UX design that will not confuse the user. I'll add the `needs-design` label so I'll take another look at it later.

**Comment by Jollywatt** [comment]
> Do you know a tool that implements something alike?

Just mentioning `just`, which is a command line runner which we might like to take inspiration from. In particular, [how recipe (task) parameters work](https://just.systems/man/en/chapter_41.html).

**Comment by ruben-arts** [comment]
This should do the trick now:

```toml
[tasks.dbt_run]
cmd = "dbt run {{ argument }}"
args = ["argument"]

[tasks.diff_dbt]
cmd = "data-diff --dbt {{ argument }}"
args = ["argument"]
depends-on = [{task = "dbt_run", args = ["{{ argument }}"]}]
```

Closing as fixed
